/** Expanded field-note articles (owner request, 2026-07-15). English
 * source text for the "Read more" long-form pieces — see
 * `packs/types.ts`'s `articles` field for the full design rationale.
 * Started with the two rooms whose field notes cite the deepest,
 * most-researchable real sources; more rooms are a future pass (see the
 * master development plan). */

export const ARTICLES: Record<string, { title: string; body: string }> = {
  wallet: {
    title: 'What 17,000 Lost Wallets Taught Us About Honesty',
    body: [
      'In Plato\'s Republic, Glaucon tells Socrates a story to needle him: a shepherd named Gyges finds a ring that turns him invisible, and uses it to seduce a queen and steal a kingdom. Glaucon\'s point is a challenge, not an anecdote — remove the witnesses and the consequences, he argues, and the just man and the unjust man behave identically. **Nobody is honest by choice; they are honest by supervision.** It is one of the oldest provocations in philosophy, and for over two thousand years it was untestable. Nobody could actually hand thousands of strangers an invisibility ring and watch what they did with it.',
      'In 2019, a team of economists effectively did exactly that. Alain Cohn, Michel Maréchal, David Tannenbaum, and Christian Zückerman — writing in the journal Science — had research assistants "lose" 17,303 wallets at hotels, banks, police stations, and other public buildings across 40 countries. Each wallet had a name, an email address, and a visible amount of cash, then was handed to a random front-desk employee with the line: "I found this on the street around the corner. Somebody must have lost it. I\'m in a hurry and I need to get going. Could you please take care of it?" The researchers then simply counted how many people emailed the owner back.',
      'The headline finding inverted the obvious prediction. Across nearly every country tested, wallets containing **more** money were returned at **higher** rates than wallets containing none — the opposite of what pure self-interest predicts, and the opposite of what most people, when surveyed beforehand, guessed would happen. Economists asked to predict the results got it backwards too.',
      'The authors\' explanation is a quiet echo of the room you just walked through: two forces are in tension inside every finder. One is the material pull of the cash. The other is the psychological cost of thinking of yourself, afterward, as a thief — and that cost appears to scale with the size of the theft, not shrink with the size of the reward. Keeping an empty wallet costs a stranger nothing and costs your self-image almost nothing either, so it happens often. Keeping a wallet full of cash is a larger, harder-to-metabolize theft of someone\'s week, and it turns out to be a larger, harder-to-metabolize theft of your own story about who you are.',
      'This is closer to Dan Ariely\'s "self-image maintenance" theory of dishonesty than to either Kant\'s categorical duty or Glaucon\'s cynicism: most people, Ariely\'s research suggests, will cheat right up to the point where they can no longer tell themselves a coherent story about being an honest person — and not one step further. It is not the ring that fails Gyges. It is the fact that even alone, even invisible, most people cannot stop watching themselves.',
    ].join('\n\n'),
  },
  'beggars-math': {
    title: 'The Child You Can See, and the Ones You Can\'t',
    body: [
      'Peter Singer published "Famine, Affluence, and Morality" in 1972, written in the shadow of the Bangladesh refugee crisis, and its opening move is the pond you may already know: a child is drowning in a shallow pond in front of you, and saving her will ruin your clothes and make you late. You would not hesitate. Singer\'s question is why the calculation changes for a child you cannot see, on the other side of the world, whose suffering a comparatively small donation could prevent just as certainly. If distance and unfamiliarity are not morally relevant facts, he argues, then most of us are living in a chronic, quiet violation of an obligation we would never dream of ignoring if the child were standing in front of us.',
      'The objections arrived quickly, and they are worth taking seriously rather than waving off. The "demandingness objection" points out that if the logic is followed all the way, it does not stop at spare change — it seems to require most people in wealthy countries to give away nearly everything beyond bare subsistence, for as long as anyone anywhere is suffering more than they would be by the gift. Bernard Williams raised a different, subtler concern: a morality that treats you as one interchangeable node feeding a global utility calculation may quietly dissolve the very relationships, projects, and particular loyalties that make a life feel like *yours* rather than an accounting ledger with a pulse. The near/far instinct, on this view, is not necessarily a bias to be corrected — it may be part of what makes it possible to have a self at all.',
      'What is not in serious dispute, because it has been measured directly, is how differently human attention actually behaves. Thomas Schelling observed decades ago that "the death of one person is a tragedy; the death of a million is a statistic." Paul Slovic\'s later research on the "identifiable victim effect" and "psychic numbing" found this operating with disturbing precision: donations to a single, named, photographed child reliably outperform appeals citing large, accurate numbers of anonymous victims — and, more strangely, adding a second named victim to an appeal often *lowers* total giving compared to naming just one. Attention and moral feeling, it turns out, do not scale the way ethics textbooks assume they should.',
      'The room you just left set exactly this trap. **The choice that felt most generous — the visible, public gesture — was, on the numbers, the worst use of the money; the quiet, effective option looked cold precisely because it declined to be witnessed.** This is not a hypothetical flaw in human psychology; it is the identifiable-victim effect, rendered as a door. Modern effective altruism (GiveWell\'s research, William MacAskill\'s writing) exists largely as a deliberate engineering project against this exact bias — treating the pull toward the visible, photogenic gesture as a bug in moral perception worth correcting with evidence, not a virtue to indulge. And the plainest finding of all, confirmed by the room\'s own field note: most people, most nights, choose neither the near claim nor the far one. They keep walking.',
    ].join('\n\n'),
  },
};
