// LIMERENCE's shared UI-chrome translations — see cs-ui.ts's header for why
// this category exists, why it's scoped via oneDoorButtonKey('limerence'),
// and (item 21 backfill, 2026-07-15) why most entries below are reused from
// ANAMNESIS's own reviewed German translations while heartsTooltip/
// understoryName/personaAboutLabel/personaSub are fresh, pack-scoped ones.
import { registerAll } from '../../../engine/text/resolver';
import {
  oneDoorButtonKey,
  understoryNameKey,
  heartsTooltipKey,
  personaAboutLabelKey,
  personaSubKey,
  uiKey,
} from '../../../engine/text/keys';

registerAll('v2', 'de', {
  [oneDoorButtonKey('limerence')]: 'Eine Tür',
  [understoryNameKey('limerence')]: 'Die Registratur',
  [heartsTooltipKey('limerence')]:
    'Ihr Vertrauen — Ihre Fähigkeit, es noch zu geben. Ein paar besonders kostspielige Entscheidungen kosten unmittelbar eines, ebenso wie eine völlig erschöpfte Klarheit. Alle drei zu verlieren ist ein Ende, kein Scheitern.',
  [personaAboutLabelKey('limerence')]: 'Über Sie (optional — niemandem gezeigt, nur vom Portier gespürt)',
  [personaSubKey('limerence')]:
    'Rein zum Nutzen des Portiers — das ändert nichts an den Zimmern, nur daran, wie sie zu Ihnen sprechen.',
  [uiKey('aboutTitle')]: 'Bevor Sie beginnen',
  [uiKey('advanceHintClick')]: 'klicken · Leertaste',
  [uiKey('advanceHintContinue')]: 'weiter',
  [uiKey('annexHeader')]: 'Der Anbau notiert:',
  [uiKey('archiveBlurbFallback')]: 'keine weitere Beschreibung in der Akte',
  [uiKey('back')]: 'Zurück',
  [uiKey('begin')]: 'Beginnen',
  [uiKey('beginAgain')]: 'Erneut beginnen',
  [uiKey('codexSub')]: 'wodurch Sie gegangen sind — das bleibt gegangen',
  [uiKey('collected')]: 'gesammelt',
  [uiKey('confirmAgain')]: 'Zum Bestätigen erneut klicken',
  [uiKey('continue')]: 'Weiter',
  [uiKey('continueJourney')]: 'Die Reise fortsetzen',
  [uiKey('creditsEngine')]: '<b>Rendering & Audio.</b> Jedes Bild ist generierte Geometrie (Three.js), und jeder Klang wird zur Laufzeit erzeugt — keine gekauften oder heruntergeladenen Grafik- oder Audio-Assets.',
  [uiKey('creditsFonts')]: '<b>Schriftarten.</b> Inter, Spectral und Vazirmatn, über Fontsource — jeweils lizenziert unter der SIL Open Font License 1.1.',
  [uiKey('creditsIntro')]: 'Unabhängig geschrieben, entworfen und gebaut.',
  [uiKey('creditsNotices')]: 'Vollständige Lizenztexte Dritter finden Sie in THIRD_PARTY_NOTICES.md, das zusammen mit diesem Build verteilt wird.',
  [uiKey('creditsTelemetry')]: 'Nichts an Ihrem Spielverhalten wird verfolgt, irgendwohin gesendet oder mit einem Konto verknüpft — Ihr Spielstand existiert nur in diesem Browser oder dieser Installation.',
  [uiKey('creditsTitle')]: 'Mitwirkende',
  [uiKey('creditsTooling')]: '<b>Erstellt mit.</b> Three.js (MIT-Lizenz) · TypeScript · Vite · Electron (Desktop-Build) · Vitest & Playwright (Tests).',
  [uiKey('done')]: 'Fertig',
  [uiKey('doorHelp')]: 'wählen Sie einen Weg — klicken Sie eine Tür an, oder drücken Sie ihre Zahl',
  [uiKey('doorHelpSingle')]: 'dies ist der einzige Weg nach vorn — klicken Sie die Tür an, oder drücken Sie 1',
  [uiKey('doorUnseenBadge')]: 'neu',
  [uiKey('doorUnseenBadgeTooltip')]: 'Durch diese Tür sind Sie noch nie gegangen',
  [uiKey('doorsNeverOpenedHeader')]: 'Türen, die Sie nie geöffnet haben',
  [uiKey('ending')]: 'Ende',
  [uiKey('endingFieldNoteHeader')]: 'Ende · Notiz',
  [uiKey('endingsWitnessed')]: 'erblickte Enden',
  [uiKey('epiphaniesTitle')]: 'Erkenntnisse',
  [uiKey('epiphanyEarned')]: 'heute Abend vermerkt',
  [uiKey('examinedOfferBody')]: 'Ein freiwilliger Stempel in Ihrer Akte: Nach jeder bedeutsamen Entscheidung zeigt Ihnen ein stiller Beamter, wie mehrere benannte ethische Traditionen sie lesen könnten — nebeneinander, absichtlich uneinig. Nichts hier wird benotet oder bepunktet, und keine Lesart ist die „richtige“. Die Räume, Herzen und Enden, die Sie erreichen können, bleiben vollkommen unverändert. Jede Karte schließen Sie mit einem einzigen Klick. Die Vorauswahl für das nächste Mal können Sie jederzeit in den Einstellungen ändern.',
  [uiKey('examinedOfferIntro')]: 'Der Anbau legt Kommentare an. Er hat keine einzige Meinung — er hat vier.',
  [uiKey('examinedOfferTitle')]: 'Der Prüfungsanbau',
  [uiKey('exitGame')]: 'Spiel beenden',
  [uiKey('explainButton')]: 'Einfach erklären',
  [uiKey('explainLabel')]: 'In einfachen Worten',
  [uiKey('exportProfile')]: 'Profil exportieren',
  [uiKey('exportProfileButton')]: 'Herunterladen',
  [uiKey('exportProfileDesc')]: 'Lädt Ihr gesamtes Profil als Datei herunter — eine persönliche Sicherung, oder etwas, das Sie versenden können, falls Sie einmal Hilfe brauchen.',
  [uiKey('fieldNoteHeader')]: 'Notiz',
  [uiKey('fieldNotes')]: 'Notizen',
  [uiKey('fpsCap30')]: 'Bildrate: 30 fps (flüssiger auf schwächeren Grafikkarten)',
  [uiKey('fpsCap60')]: 'Bildrate: 60 fps',
  [uiKey('guestStampsTitle')]: 'Gäste-Stempel',
  [uiKey('heartsAriaLabel')]: 'Griff auf die Wirklichkeit',
  [uiKey('hotelRegister')]: 'Das Register',
  [uiKey('howToAdvance')]: '<b>Klicken</b> Sie den Text an, oder drücken Sie die <b>Leertaste</b>, um fortzufahren',
  [uiKey('howToClick')]: '<b>Klicken</b> Sie eine Tür an, oder drücken Sie <b>1–3</b>, um Ihren Weg zu wählen',
  [uiKey('howToPause')]: '<b>Esc</b> für Pause · fahren Sie über eine Tür, um ihren Hinweis zu lesen',
  [uiKey('hudLanguageTooltip')]: 'Sprache wechseln (wirkt sich ab dem nächsten Moment aus)',
  [uiKey('importProfile')]: 'Profil importieren',
  [uiKey('importProfileButton')]: 'Importieren',
  [uiKey('importProfileDesc')]: 'Ersetzt Ihr gesamtes Profil durch die eingefügte Datei. Ihr aktueller Fortschritt wird überschrieben — exportieren Sie ihn zuerst, wenn Sie ihn behalten möchten.',
  [uiKey('importProfileError')]: 'Das sieht nicht nach einer gültigen Profildatei aus — es wurde nichts verändert.',
  [uiKey('importProfilePlaceholder')]: 'Fügen Sie hier den Inhalt einer exportierten Profildatei ein',
  [uiKey('importProfileSuccess')]: 'Importiert — wird neu geladen…',
  [uiKey('keepsakeChoiceTooltip')]: 'Ein Andenken, still ausgegeben',
  [uiKey('lastMessageBody')]: 'Sie hatten einen Satz, und das war er:',
  [uiKey('ledger')]: 'Reisetagebuch',
  [uiKey('ledgerDescents')]: 'Abstiege nach unten',
  [uiKey('ledgerEndings')]: 'Erblickte Enden',
  [uiKey('ledgerExamined')]: 'Geprüfte Durchläufe',
  [uiKey('ledgerHearts')]: 'Verlorene Herzen, insgesamt',
  [uiKey('ledgerKeepsakes')]: 'Andenken im Regal',
  [uiKey('ledgerMostWalked')]: 'Die meistbegangene Tür',
  [uiKey('ledgerRooms')]: 'Erblickte Räume',
  [uiKey('ledgerRuns')]: 'Abgeschlossene Durchläufe',
  [uiKey('menu')]: 'Menü',
  [uiKey('notYetWalked')]: 'noch nicht begangen',
  [uiKey('of')]: 'von',
  [uiKey('off')]: 'aus',
  [uiKey('on')]: 'ein',
  [uiKey('paused')]: 'Pause',
  [uiKey('pausedSub')]: 'die Räume warten — Zeit ist hier nur Zierde',
  [uiKey('persona.about1')]: 'Vorsichtig mit anderen. Weniger vorsichtig mit sich selbst.',
  [uiKey('persona.about2')]: 'Schnell zum Lachen, langsam damit, zu sagen, was wirklich geschah.',
  [uiKey('persona.about3')]: 'Immer noch hier. Das ist an den meisten Tagen der Großteil der Antwort.',
  [uiKey('persona.daniel')]: 'Sie messen zweimal. Trotzdem schneiden Sie manchmal falsch.',
  [uiKey('persona.mira')]: 'Ihnen fielen Dinge auf, bevor jemand Sie darum bat.',
  [uiKey('persona.sara')]: 'Sie bleiben bis zum Ende der Dinge. Das taten Sie schon immer.',
  [uiKey('persona.tomas')]: 'Sie verzeihen langsam, aber vollständig, sobald Sie es tun.',
  [uiKey('personaFreeTextPlaceholder')]: 'Oder schreiben Sie kurz Ihr eigenes…',
  [uiKey('personaNameLabel')]: 'Name',
  [uiKey('personaNamePlaceholder')]: 'Ihr Name (oder wie man Sie hier nennen soll)',
  [uiKey('personaSkip')]: 'Überspringen — nennt mich Reisende(r)',
  [uiKey('personaTitle')]: 'Wer sind Sie, heute Nacht?',
  [uiKey('pivotalChoicesHeader')]: 'was Sie gewählt haben',
  [uiKey('recapHeader')]: 'Wodurch Sie gegangen sind',
  [uiKey('recoveryBody')]: 'Irgendetwas im Getriebe hat das Gleichgewicht verloren. Ihre Akte ist sicher — nichts, was Sie hier getan haben, ist verloren.',
  [uiKey('recoveryReturn')]: 'Zurück zum Titelbildschirm',
  [uiKey('recoveryTitle')]: 'Das Gerät flackert',
  [uiKey('registerDoorsWalked')]: 'durchschrittene Türen',
  [uiKey('registerSub')]: 'die Gestalt dieses Ortes — ob Sie ihn schon durchschritten haben oder nicht',
  [uiKey('rememberedTag')]: 'erinnert',
  [uiKey('renderScalePerformance')]: 'Rendering-Auflösung: Leistung',
  [uiKey('renderScaleSharp')]: 'Rendering-Auflösung: Scharf',
  [uiKey('renderScaleStandard')]: 'Rendering-Auflösung: Standard',
  [uiKey('rereadBack')]: 'Zurück — den vorherigen Abschnitt noch einmal lesen',
  [uiKey('rereadJumpTo')]: 'Abschnitt {n} noch einmal lesen',
  [uiKey('rereadScene')]: '⟲ die Szene noch einmal lesen',
  [uiKey('resetProgress')]: 'Gesamten Fortschritt zurücksetzen',
  [uiKey('resetProgressDesc')]: 'Löscht alles — Notizen, Enden, Einstellungen, Ihren aktuellen Durchlauf — zurück zum allerersten Anfang.',
  [uiKey('resetRun')]: 'Aktuellen Durchlauf zurücksetzen',
  [uiKey('resetRunDesc')]: 'Bricht Ihre laufende Reise ab. Notizen, Enden und Einstellungen bleiben erhalten.',
  [uiKey('resetRunDone')]: 'Durchlauf zurückgesetzt',
  [uiKey('restoredFromBackup')]: 'Ihr letzter Speicherstand konnte nicht geladen werden — aus der vorherigen Sicherung wiederhergestellt. Es sollte nichts fehlen.',
  [uiKey('resume')]: 'Fortsetzen',
  [uiKey('saveAndExit')]: 'Speichern und zum Titelbildschirm zurückkehren',
  [uiKey('saveFailed')]: 'Ihr Fortschritt konnte nicht gespeichert werden — der Speicherplatz ist möglicherweise voll.',
  [uiKey('savedToast')]: 'Gespeichert',
  [uiKey('senderYou')]: 'Absender: Sie',
  [uiKey('settingDynamicScenery')]: 'Dynamische Umgebung (experimentell)',
  [uiKey('settingDynamicSceneryDesc')]: 'Räume färben Licht und Nebel dezent nach ihrer Stimmung.',
  [uiKey('settingExaminedPath')]: 'Der geprüfte Pfad — zu Beginn jedes neuen Durchlaufs angeboten',
  [uiKey('settingExaminedPathDesc')]: 'Ändert nur die Vorauswahl beim Start eines neuen Durchlaufs — Sie werden stets erneut gefragt, und die Wahl für diesen Durchlauf bleibt unberührt.',
  [uiKey('settingFpsCap')]: 'Bildratenbegrenzung',
  [uiKey('settingFpsCapDesc')]: 'Niedriger spart spürbar Grafikleistung — dies ist ein Nebel-und-Text-Spiel, kein Actiontitel.',
  [uiKey('settingFullscreen')]: 'Vollbild',
  [uiKey('settingFullscreenDesc')]: 'Füllt den gesamten Bildschirm — lässt sich auch mit der Taste F umschalten.',
  [uiKey('settingHighContrast')]: 'Text mit hohem Kontrast',
  [uiKey('settingHighContrastDesc')]: 'Hellere Textfarbe für leichteres Lesen.',
  [uiKey('settingLanguage')]: 'Sprache',
  [uiKey('settingLanguageDesc')]: 'Wirkt sich sofort aus, überall im Spiel.',
  [uiKey('settingLightMode')]: 'Heller Modus',
  [uiKey('settingLightModeDesc')]: 'Dasselbe Hotel im Morgenlicht — dieselben Zimmer, nur sanfter.',
  [uiKey('settingMusic')]: 'Hintergrundmusik',
  [uiKey('settingMusicDesc')]: 'Eine leise, sich wandelnde Klangkulisse, die sich mit jedem Akt verändert.',
  [uiKey('settingMusicVolume')]: 'Musiklautstärke',
  [uiKey('settingNarration')]: 'Vertonung',
  [uiKey('settingNarrationDesc')]: 'Gesprochene Zeilen, wo aufgenommen.',
  [uiKey('settingNarrationVolume')]: 'Vertonungslautstärke',
  [uiKey('settingQuality')]: 'Hohe visuelle Qualität',
  [uiKey('settingQualityDesc')]: 'Glüh- und Kantenglättungseffekte; erfordert eine stärkere Grafikkarte. Wirkt sich erst beim nächsten Start aus.',
  [uiKey('settingReducedMotion')]: 'Reduzierte Bewegung',
  [uiKey('settingReducedMotionDesc')]: 'Verkürzt Kamerabewegungen und weiche Übergänge auf nahezu sofort — schonender bei Bewegungsempfindlichkeit.',
  [uiKey('settingRenderScale')]: 'Rendering-Auflösung',
  [uiKey('settingRenderScaleDesc')]: 'Niedriger = flüssiger auf schwächeren Grafikkarten, ein etwas weicheres Bild. Scharf nutzt die volle Bildschirmauflösung.',
  [uiKey('settingSfx')]: 'Klangeffekte',
  [uiKey('settingSfxDesc')]: 'Türgeräusche, Seitenumblättern und die kleinen Klänge des Wählens.',
  [uiKey('settingSfxVolume')]: 'Effektlautstärke',
  [uiKey('settingTextVersion')]: 'Textversion',
  [uiKey('settingTextVersionDesc')]: 'v1 ist die ursprüngliche Stimme, als wählbare Sicherung erhalten; v2 ist die aktuelle Überarbeitung.',
  [uiKey('settingTypewriter')]: 'Schreibmaschinen-Text',
  [uiKey('settingTypewriterDesc')]: 'Der Text erscheint Buchstabe für Buchstabe, als würde ihn Ihnen jemand erzählen.',
  [uiKey('settingUiZoom')]: 'Oberflächengröße',
  [uiKey('settingUiZoomDesc')]: 'Vergrößert oder verkleinert Menüs und Text nach Belieben — die 3D-Szene bleibt scharf.',
  [uiKey('settings')]: 'Einstellungen',
  [uiKey('settingsFooter')]: 'Qualitätsänderungen wirken sich erst beim nächsten Start aus · alles andere sofort',
  [uiKey('settingsSectionAudio')]: 'Ton',
  [uiKey('settingsSectionData')]: 'Daten',
  [uiKey('settingsSectionDisplay')]: 'Anzeige',
  [uiKey('settingsSectionText')]: 'Text & Sprache',
  [uiKey('shelfTitle')]: 'Das Regal',
  [uiKey('statHearts')]: 'bewahrte Herzen',
  [uiKey('statLucidity')]: 'Klarheit',
  [uiKey('statNewNotes')]: 'neue Notizen',
  [uiKey('takeExaminedPath')]: 'Den geprüften Pfad wählen',
  [uiKey('title')]: 'Titelbildschirm',
  [uiKey('titleTagline')]: 'eine Reise durch die Räume · jede Tür ist eine Frage · der Weg zurück führt hindurch',
  [uiKey('travelerLabel')]: 'Reisende(r)',
  [uiKey('travellerFallback')]: 'Reisende(r)',
  [uiKey('versionV1')]: 'Stimme: v1 (ursprünglich)',
  [uiKey('versionV2')]: 'Stimme: v2 (neu)',
  [uiKey('vestibuleButton')]: 'The Vestibule — Spiel wählen',
  [uiKey('walkAgain')]: 'Erneut gehen — die Räume ordnen sich für niemanden um, aber Sie haben sich verändert',
  [uiKey('walkPlainly')]: 'Den einfachen Weg gehen',
  [uiKey('whoAreYou')]: 'Wer sind Sie?',
});
