// LIMERENCE's shared UI-chrome translations — see cs-ui.ts's header for why
// this category exists, why it's scoped via oneDoorButtonKey('limerence'),
// and (item 21 backfill, 2026-07-15) why most entries below are reused from
// ANAMNESIS's own reviewed Farsi translations while heartsTooltip/
// understoryName/personaAboutLabel/personaSub are fresh, pack-scoped ones.
import { registerAll } from '../../../engine/text/resolver';
import {
  oneDoorButtonKey,
  understoryNameKey,
  heartsTooltipKey,
  personaAboutLabelKey,
  personaSubKey,
  uiKey,
} from '../../../engine/text/keys';

registerAll('v2', 'fa', {
  [oneDoorButtonKey('limerence')]: 'یک در',
  [understoryNameKey('limerence')]: 'بایگانی',
  [heartsTooltipKey('limerence')]:
    'اعتماد شما — ظرفیت‌تان برای بازهم آن را دادن. چند انتخاب پرهزینه مستقیماً یکی از آن را می‌گیرند، همان‌طور که تمام‌شدنِ کاملِ وضوح هم همین‌طور است. از دست دادنِ هر سه، یک پایان است، نه یک صفحه‌ی شکست.',
  [personaAboutLabelKey('limerence')]: 'درباره‌ی شما (اختیاری — به هیچ‌کس نشان داده نمی‌شود، فقط دربان آن را حس می‌کند)',
  [personaSubKey('limerence')]: 'صرفاً برای خودِ دربان — چیزی در اتاق‌ها تغییر نمی‌کند، فقط نحوه‌ی صحبتشان با شما.',
  [uiKey('aboutTitle')]: 'پیش از آغاز',
  [uiKey('advanceHintClick')]: 'کلیک · فاصله',
  [uiKey('advanceHintContinue')]: 'ادامه',
  [uiKey('annexHeader')]: 'ضمیمه ثبت می‌کند:',
  [uiKey('archiveBlurbFallback')]: 'در پرونده توضیح بیشتری ثبت نشده',
  [uiKey('back')]: 'بازگشت',
  [uiKey('begin')]: 'آغاز',
  [uiKey('beginAgain')]: 'دوباره آغاز کنید',
  [uiKey('codexSub')]: 'آنچه از آن گذشته‌اید — گذشته باقی می‌ماند',
  [uiKey('collected')]: 'جمع‌آوری‌شده',
  [uiKey('confirmAgain')]: 'برای تأیید دوباره کلیک کنید',
  [uiKey('continue')]: 'ادامه',
  [uiKey('continueJourney')]: 'ادامه‌ی سفر',
  [uiKey('creditsEngine')]: '<b>رندر و صدا.</b> هر عنصر تصویری هندسه‌ای تولیدشده است (Three.js) و هر صدا در زمان اجرا تولید می‌شود — بدون هیچ دارایی هنری یا صوتی خریداری‌شده یا دانلودشده.',
  [uiKey('creditsFonts')]: '<b>قلم‌ها.</b> Inter، Spectral و Vazirmatn، از طریق Fontsource — هرکدام تحت مجوز SIL Open Font License 1.1.',
  [uiKey('creditsIntro')]: 'نوشته‌شده، طراحی‌شده و ساخته‌شده به‌طور مستقل.',
  [uiKey('creditsNotices')]: 'متن کامل مجوزهای شخص‌ثالث در فایل THIRD_PARTY_NOTICES.md، همراه با این نسخه توزیع شده است.',
  [uiKey('creditsTelemetry')]: 'هیچ‌چیز از نحوه‌ی بازی شما ردیابی، ارسال، یا به حسابی متصل نمی‌شود — ذخیره‌ی شما فقط در همین مرورگر یا همین نصب وجود دارد.',
  [uiKey('creditsTitle')]: 'دست‌اندرکاران',
  [uiKey('creditsTooling')]: '<b>ساخته‌شده با.</b> Three.js (مجوز MIT) · TypeScript · Vite · Electron (نسخه‌ی دسکتاپ) · Vitest و Playwright (آزمایش).',
  [uiKey('done')]: 'انجام شد',
  [uiKey('doorHelp')]: 'مسیری را انتخاب کنید — روی دری کلیک کنید، یا شماره‌اش را بزنید',
  [uiKey('doorHelpSingle')]: 'این تنها راه پیش رو است — روی در کلیک کنید، یا عدد ۱ را بزنید',
  [uiKey('doorUnseenBadge')]: 'جدید',
  [uiKey('doorUnseenBadgeTooltip')]: 'هرگز از این در نگذشته‌اید',
  [uiKey('doorsNeverOpenedHeader')]: 'دری که هرگز نگشودید',
  [uiKey('ending')]: 'پایان',
  [uiKey('endingFieldNoteHeader')]: 'پایان · یادداشت',
  [uiKey('endingsWitnessed')]: 'پایان‌های دیده‌شده',
  [uiKey('epiphaniesTitle')]: 'بصیرت‌ها',
  [uiKey('epiphanyEarned')]: 'امشب ثبت شد',
  [uiKey('examinedOfferBody')]: 'مهری اختیاری روی پرونده‌ی ورودی شما: پس از هر انتخاب مهم، یک کارمند آرام نشان می‌دهد چند سنت اخلاقیِ نام‌برده ممکن است آن را چگونه بخوانند — کنار هم، عمداً ناهم‌رأی. اینجا هیچ‌چیز نمره یا امتیاز نمی‌گیرد و هیچ خوانشی «درست» نیست. اتاق‌ها، قلب‌ها، و پایان‌هایی که می‌توانید به آن‌ها برسید کاملاً بدون تغییرند. هر کارت با یک کلیک بسته می‌شود. می‌توانید بعداً در تنظیمات، پیش‌فرض دفعه‌ی بعد را تغییر دهید.',
  [uiKey('examinedOfferIntro')]: 'ضمیمه تفسیر بایگانی می‌کند. نظری ندارد — چهار نظر دارد.',
  [uiKey('examinedOfferTitle')]: 'ضمیمه‌ی بررسی',
  [uiKey('exitGame')]: 'خروج از بازی',
  [uiKey('explainButton')]: 'به‌زبان ساده توضیح بده',
  [uiKey('explainLabel')]: 'به‌زبان ساده',
  [uiKey('exportProfile')]: 'برون‌بردنِ پروفایل',
  [uiKey('exportProfileButton')]: 'دانلود',
  [uiKey('exportProfileDesc')]: 'کل پروفایل شما را به‌عنوان یک فایل دانلود می‌کند — نسخه‌ی پشتیبانِ شخصی، یا چیزی برای ارسال در صورت نیاز به کمک.',
  [uiKey('fieldNoteHeader')]: 'یادداشت',
  [uiKey('fieldNotes')]: 'یادداشت‌ها',
  [uiKey('fpsCap30')]: 'نرخ فریم: ۳۰ فریم بر ثانیه (روان‌تر روی کارت‌های گرافیک ضعیف‌تر)',
  [uiKey('fpsCap60')]: 'نرخ فریم: ۶۰ فریم بر ثانیه',
  [uiKey('guestStampsTitle')]: 'مهرهای مهمان',
  [uiKey('heartsAriaLabel')]: 'چنگ به واقعیت',
  [uiKey('hotelRegister')]: 'دفتر ثبت',
  [uiKey('howToAdvance')]: '<b>کلیک</b> روی متن، یا فشردن <b>فاصله</b>، برای ادامه',
  [uiKey('howToClick')]: '<b>کلیک</b> روی دری، یا فشردن <b>۱ تا ۳</b>، برای انتخاب مسیر',
  [uiKey('howToPause')]: '<b>Esc</b> برای توقف · با نگه‌داشتن نشانگر روی در، راهنمای آن را بخوانید',
  [uiKey('hudLanguageTooltip')]: 'تغییر زبان (از لحظه‌ی بعدی اعمال می‌شود)',
  [uiKey('importProfile')]: 'درون‌ریزیِ پروفایل',
  [uiKey('importProfileButton')]: 'درون‌ریزی',
  [uiKey('importProfileDesc')]: 'کل پروفایل شما را با فایلِ چسبانده‌شده جایگزین می‌کند. پیشرفتِ فعلیِ شما بازنویسی می‌شود — اگر می‌خواهید نگهش دارید، اول آن را برون‌ببرید.',
  [uiKey('importProfileError')]: 'این شبیه فایلِ پروفایلِ معتبر نیست — چیزی تغییر نکرد.',
  [uiKey('importProfilePlaceholder')]: 'محتوای فایلِ برون‌بردهِ پروفایل را اینجا بچسبانید',
  [uiKey('importProfileSuccess')]: 'درون‌ریزی شد — در حال بارگذاریِ دوباره…',
  [uiKey('keepsakeChoiceTooltip')]: 'یادگاری، آرام خرج‌شده',
  [uiKey('lastMessageBody')]: 'یک جمله داشتید، و این همان بود:',
  [uiKey('ledger')]: 'دفترِ مسافر',
  [uiKey('ledgerDescents')]: 'نزول‌ها به پایین',
  [uiKey('ledgerEndings')]: 'پایان‌های دیده‌شده',
  [uiKey('ledgerExamined')]: 'سفرهای بررسی‌شده',
  [uiKey('ledgerHearts')]: 'قلب‌های ازدست‌رفته، در کل',
  [uiKey('ledgerKeepsakes')]: 'یادگارهای روی قفسه',
  [uiKey('ledgerMostWalked')]: 'پرتردَدترین در',
  [uiKey('ledgerRooms')]: 'اتاق‌های دیده‌شده',
  [uiKey('ledgerRuns')]: 'سفرهای کامل‌شده',
  [uiKey('menu')]: 'منو',
  [uiKey('notYetWalked')]: 'هنوز طی‌نشده',
  [uiKey('of')]: 'از',
  [uiKey('off')]: 'خاموش',
  [uiKey('on')]: 'روشن',
  [uiKey('paused')]: 'توقف',
  [uiKey('pausedSub')]: 'اتاق‌ها منتظر می‌مانند — زمان اینجا فقط تزئین است',
  [uiKey('persona.about1')]: 'با دیگران محتاط. با خودتان کمتر.',
  [uiKey('persona.about2')]: 'زود می‌خندید، دیر می‌گویید واقعاً چه اتفاقی افتاده.',
  [uiKey('persona.about3')]: 'هنوز اینجایید. بیشترِ روزها، همین بیشترِ پاسخ است.',
  [uiKey('persona.daniel')]: 'دوبار اندازه می‌گیرید. باز هم گاهی اشتباه می‌برید.',
  [uiKey('persona.mira')]: 'پیش از آنکه کسی از شما بخواهد، متوجه‌ی چیزها می‌شدید.',
  [uiKey('persona.sara')]: 'تا پایانِ هر چیزی می‌مانید. همیشه همین‌طور بوده‌اید.',
  [uiKey('persona.tomas')]: 'دیر می‌بخشید، اما وقتی می‌بخشید، کامل می‌بخشید.',
  [uiKey('personaFreeTextPlaceholder')]: 'یا خودتان بنویسید، کوتاه…',
  [uiKey('personaNameLabel')]: 'نام',
  [uiKey('personaNamePlaceholder')]: 'نام شما (یا آنچه اینجا با آن صدایتان می‌زنند)',
  [uiKey('personaSkip')]: 'رد شدن — مرا مسافر صدا کنید',
  [uiKey('personaTitle')]: 'امشب، شما کیستید؟',
  [uiKey('pivotalChoicesHeader')]: 'آنچه انتخاب کردید',
  [uiKey('recapHeader')]: 'آنچه از آن گذشتید',
  [uiKey('recoveryBody')]: 'چیزی در چرخ‌دنده‌ها تعادلش را از دست داد. پرونده‌ی شما امن است — هیچ‌چیز از آنچه اینجا انجام داده‌اید از دست نرفته.',
  [uiKey('recoveryReturn')]: 'بازگشت به صفحه‌ی عنوان',
  [uiKey('recoveryTitle')]: 'مرکز سوسو می‌زند',
  [uiKey('registerDoorsWalked')]: 'دری که پیموده‌اید',
  [uiKey('registerSub')]: 'شکل این مکان، چه در آن قدم زده باشید و چه نه',
  [uiKey('rememberedTag')]: 'به‌یادمانده',
  [uiKey('renderScalePerformance')]: 'وضوح رندر: عملکرد',
  [uiKey('renderScaleSharp')]: 'وضوح رندر: واضح',
  [uiKey('renderScaleStandard')]: 'وضوح رندر: استاندارد',
  [uiKey('rereadBack')]: 'بازگشت — بازخوانی بخش قبلی',
  [uiKey('rereadJumpTo')]: 'بازخوانی بخش {n}',
  [uiKey('rereadScene')]: '⟲ بازخوانی صحنه',
  [uiKey('resetProgress')]: 'بازنشانی کامل پیشرفت',
  [uiKey('resetProgressDesc')]: 'همه‌چیز را پاک می‌کند — یادداشت‌ها، پایان‌ها، تنظیمات، بازی جاری شما — و به نقطه‌ی آغاز بازمی‌گردد.',
  [uiKey('resetRun')]: 'بازنشانی بازی جاری',
  [uiKey('resetRunDesc')]: 'سفر نیمه‌کاره‌ی شما را رها می‌کند. یادداشت‌ها، پایان‌ها و تنظیمات حفظ می‌شوند.',
  [uiKey('resetRunDone')]: 'بازی بازنشانی شد',
  [uiKey('restoredFromBackup')]: 'بارگذاریِ آخرین ذخیره با مشکل مواجه شد — از نسخه‌ی پیشین بازیابی شد. چیزی نباید از دست رفته باشد.',
  [uiKey('resume')]: 'ادامه',
  [uiKey('saveAndExit')]: 'ذخیره و بازگشت به صفحه‌ی عنوان',
  [uiKey('saveFailed')]: 'پیشرفت شما ذخیره نشد — ممکن است فضای ذخیره‌سازی پر باشد.',
  [uiKey('savedToast')]: 'ذخیره شد',
  [uiKey('senderYou')]: 'فرستنده: شما',
  [uiKey('settingDynamicScenery')]: 'محیط پویا (آزمایشی)',
  [uiKey('settingDynamicSceneryDesc')]: 'اتاق‌ها نور و مه را به‌آرامی متناسب با حال‌وهوایشان رنگ می‌کنند.',
  [uiKey('settingExaminedPath')]: 'مسیر بررسی‌شده — در آغاز هر بازی تازه پیشنهاد می‌شود',
  [uiKey('settingExaminedPathDesc')]: 'فقط چیزی را تغییر می‌دهد که در آغاز یک بازی تازه از پیش انتخاب شده — همیشه دوباره از شما پرسیده می‌شود و انتخاب این بازی دست‌نخورده می‌ماند.',
  [uiKey('settingFpsCap')]: 'محدودیت نرخ فریم',
  [uiKey('settingFpsCapDesc')]: 'مقدار کمتر به‌طور محسوسی توان گرافیکی کمتری مصرف می‌کند — این بازی مه و متن است، نه یک بازی اکشن.',
  [uiKey('settingFullscreen')]: 'تمام‌صفحه',
  [uiKey('settingFullscreenDesc')]: 'تمام صفحه را پر می‌کند — با کلید F هم قابل تغییر است.',
  [uiKey('settingHighContrast')]: 'کنتراست بالای متن',
  [uiKey('settingHighContrastDesc')]: 'رنگ روشن‌تر متن برای خواندن آسان‌تر.',
  [uiKey('settingLanguage')]: 'زبان',
  [uiKey('settingLanguageDesc')]: 'بلافاصله، در همه‌جای بازی اعمال می‌شود.',
  [uiKey('settingLightMode')]: 'حالت روشن',
  [uiKey('settingLightModeDesc')]: 'همان هتل در نور صبح — همان اتاق‌ها، با رنگ‌مایه‌ای ملایم‌تر.',
  [uiKey('settingMusic')]: 'موسیقی پس‌زمینه',
  [uiKey('settingMusicDesc')]: 'فضایی آرام و درحال‌تغییر که با هر پرده عوض می‌شود.',
  [uiKey('settingMusicVolume')]: 'میزان صدای موسیقی',
  [uiKey('settingNarration')]: 'روایت گفتاری',
  [uiKey('settingNarrationDesc')]: 'خطوط گفتاری، در جاهایی که ضبط شده‌اند.',
  [uiKey('settingNarrationVolume')]: 'میزان صدای روایت',
  [uiKey('settingQuality')]: 'کیفیت تصویری بالا',
  [uiKey('settingQualityDesc')]: 'جلوه‌های درخشش و صاف‌سازی؛ به کارت گرافیک قوی‌تری نیاز دارد. با بارگذاری بعدی اعمال می‌شود.',
  [uiKey('settingReducedMotion')]: 'کاهش حرکت',
  [uiKey('settingReducedMotionDesc')]: 'حرکت دوربین و انیمیشن‌های نرم را تقریباً آنی می‌کند — برای حساسیت به حرکت مناسب‌تر است.',
  [uiKey('settingRenderScale')]: 'وضوح رندر',
  [uiKey('settingRenderScaleDesc')]: 'کمتر = روان‌تر روی کارت‌های گرافیک ضعیف‌تر، تصویری کمی نرم‌تر. حالت واضح از وضوح کامل صفحه‌ی شما استفاده می‌کند.',
  [uiKey('settingSfx')]: 'جلوه‌های صوتی',
  [uiKey('settingSfxDesc')]: 'صدای درها، ورق‌خوردن صفحه، و صداهای کوچک انتخاب.',
  [uiKey('settingSfxVolume')]: 'میزان صدای جلوه‌ها',
  [uiKey('settingTextVersion')]: 'نسخه‌ی متن',
  [uiKey('settingTextVersionDesc')]: 'نسخه‌ی ۱ لحن اصلی است که به‌عنوان نسخه‌ی پشتیبان نگه داشته شده؛ نسخه‌ی ۲ بازنویسی کنونی است.',
  [uiKey('settingTypewriter')]: 'نمایش تدریجی متن',
  [uiKey('settingTypewriterDesc')]: 'متن حرف‌به‌حرف ظاهر می‌شود، مثل روایت‌شدن یک داستان.',
  [uiKey('settingUiZoom')]: 'اندازه‌ی رابط کاربری',
  [uiKey('settingUiZoomDesc')]: 'منوها و متن را به دلخواه شما بزرگ یا کوچک می‌کند — صحنه‌ی سه‌بعدی همچنان واضح می‌ماند.',
  [uiKey('settings')]: 'تنظیمات',
  [uiKey('settingsFooter')]: 'تغییر کیفیت در بارگذاری بعدی اعمال می‌شود · زبان و نسخه‌ی متن بلافاصله اعمال می‌شوند',
  [uiKey('settingsSectionAudio')]: 'صدا',
  [uiKey('settingsSectionData')]: 'داده‌ها',
  [uiKey('settingsSectionDisplay')]: 'نمایش',
  [uiKey('settingsSectionText')]: 'متن و زبان',
  [uiKey('shelfTitle')]: 'قفسه',
  [uiKey('statHearts')]: 'قلب‌های باقی‌مانده',
  [uiKey('statLucidity')]: 'هوشیاری',
  [uiKey('statNewNotes')]: 'یادداشت‌های جدید',
  [uiKey('takeExaminedPath')]: 'انتخاب مسیر بررسی‌شده',
  [uiKey('title')]: 'صفحه‌ی عنوان',
  [uiKey('titleTagline')]: 'سفری میان اتاق‌ها · هر در یک پرسش است · راه بازگشت از میان آن‌هاست',
  [uiKey('travelerLabel')]: 'مسافر',
  [uiKey('travellerFallback')]: 'مسافر',
  [uiKey('versionV1')]: 'لحن: نسخه‌ی ۱ (اصلی)',
  [uiKey('versionV2')]: 'لحن: نسخه‌ی ۲ (جدید)',
  [uiKey('vestibuleButton')]: 'The Vestibule — انتخاب بازی',
  [uiKey('walkAgain')]: 'دوباره طی کنید — اتاق‌ها برای هیچ‌کس دوباره نمی‌چینند، اما شما تغییر کرده‌اید',
  [uiKey('walkPlainly')]: 'راه رفتن ساده',
  [uiKey('whoAreYou')]: 'شما کیستید؟',
});
