// LIMERENCE's shared UI-chrome translations — see cs-ui.ts's header for why
// this category exists, why it's scoped via oneDoorButtonKey('limerence'),
// and (item 21 backfill, 2026-07-15) why most entries below are reused from
// ANAMNESIS's own reviewed French translations while heartsTooltip/
// understoryName/personaAboutLabel/personaSub are fresh, pack-scoped ones.
import { registerAll } from '../../../engine/text/resolver';
import {
  oneDoorButtonKey,
  understoryNameKey,
  heartsTooltipKey,
  personaAboutLabelKey,
  personaSubKey,
  uiKey,
} from '../../../engine/text/keys';

registerAll('v2', 'fr', {
  [oneDoorButtonKey('limerence')]: 'Une porte',
  [understoryNameKey('limerence')]: 'Le Registre',
  [heartsTooltipKey('limerence')]:
    'Votre confiance — votre capacité à encore l’accorder. Quelques choix particulièrement coûteux en coûtent une directement, tout comme une lucidité entièrement épuisée. Perdre les trois est une fin, pas un échec.',
  [personaAboutLabelKey('limerence')]: 'À propos de vous (facultatif — montré à personne, seulement ressenti par le Portier)',
  [personaSubKey('limerence')]:
    'Uniquement à l’usage du Portier — cela ne change rien aux chambres, seulement la façon dont elles vous parlent.',
  [uiKey('aboutTitle')]: 'Avant de commencer',
  [uiKey('advanceHintClick')]: 'cliquer · espace',
  [uiKey('advanceHintContinue')]: 'continuer',
  [uiKey('annexHeader')]: 'L’annexe consigne :',
  [uiKey('archiveBlurbFallback')]: 'aucune autre description au dossier',
  [uiKey('back')]: 'Retour',
  [uiKey('begin')]: 'Commencer',
  [uiKey('beginAgain')]: 'Recommencer',
  [uiKey('codexSub')]: 'ce que vous avez traversé — cela reste traversé',
  [uiKey('collected')]: 'recueillies',
  [uiKey('confirmAgain')]: 'Cliquez à nouveau pour confirmer',
  [uiKey('continue')]: 'Continuer',
  [uiKey('continueJourney')]: 'Poursuivre le voyage',
  [uiKey('creditsEngine')]: '<b>Rendu et audio.</b> Chaque visuel est une géométrie générée (Three.js), et chaque son est généré en temps réel — aucun élément graphique ou sonore acheté ou téléchargé.',
  [uiKey('creditsFonts')]: '<b>Polices.</b> Inter, Spectral et Vazirmatn, via Fontsource — chacune sous licence SIL Open Font License 1.1.',
  [uiKey('creditsIntro')]: 'Écrit, conçu et construit de manière indépendante.',
  [uiKey('creditsNotices')]: 'Les textes complets des licences tierces se trouvent dans THIRD_PARTY_NOTICES.md, distribué avec cette version.',
  [uiKey('creditsTelemetry')]: 'Rien de votre façon de jouer n’est suivi, envoyé où que ce soit, ni lié à un compte — votre sauvegarde n’existe que dans ce navigateur ou cette installation.',
  [uiKey('creditsTitle')]: 'Crédits',
  [uiKey('creditsTooling')]: '<b>Construit avec.</b> Three.js (licence MIT) · TypeScript · Vite · Electron (version bureau) · Vitest et Playwright (tests).',
  [uiKey('done')]: 'Terminé',
  [uiKey('doorHelp')]: 'choisissez un chemin — cliquez une porte, ou appuyez sur son chiffre',
  [uiKey('doorHelpSingle')]: 'c’est l’unique chemin possible — cliquez la porte, ou appuyez sur 1',
  [uiKey('doorUnseenBadge')]: 'nouveau',
  [uiKey('doorUnseenBadgeTooltip')]: 'Vous n’avez jamais franchi cette porte',
  [uiKey('doorsNeverOpenedHeader')]: 'les portes que vous n’avez jamais ouvertes',
  [uiKey('ending')]: 'Fin',
  [uiKey('endingFieldNoteHeader')]: 'Fin · Note',
  [uiKey('endingsWitnessed')]: 'fins contemplées',
  [uiKey('epiphaniesTitle')]: 'Révélations',
  [uiKey('epiphanyEarned')]: 'consignée ce soir',
  [uiKey('examinedOfferBody')]: 'Un tampon facultatif sur votre dossier : après chaque choix important, un greffier silencieux vous montre comment plusieurs traditions éthiques nommées pourraient le lire — côte à côte, délibérément en désaccord. Rien ici n’est noté ni évalué, et aucune lecture n’est la « bonne ». Les pièces, les cœurs et les fins que vous pouvez atteindre restent parfaitement identiques. Chaque carte se referme d’un seul clic. Vous pouvez changer à tout moment, dans les réglages, la présélection pour la prochaine fois.',
  [uiKey('examinedOfferIntro')]: 'L’annexe consigne des commentaires. Elle n’a pas un seul avis — elle en a quatre.',
  [uiKey('examinedOfferTitle')]: 'L’Annexe d’examen',
  [uiKey('exitGame')]: 'Quitter le jeu',
  [uiKey('explainButton')]: 'Expliquer simplement',
  [uiKey('explainLabel')]: 'En mots simples',
  [uiKey('exportProfile')]: 'Exporter le profil',
  [uiKey('exportProfileButton')]: 'Télécharger',
  [uiKey('exportProfileDesc')]: 'Télécharge tout votre profil sous forme de fichier — une sauvegarde personnelle, ou de quoi envoyer si vous avez un jour besoin d’aide.',
  [uiKey('fieldNoteHeader')]: 'Note',
  [uiKey('fieldNotes')]: 'Notes',
  [uiKey('fpsCap30')]: 'Fréquence d’images : 30 im/s (plus fluide sur les cartes graphiques modestes)',
  [uiKey('fpsCap60')]: 'Fréquence d’images : 60 im/s',
  [uiKey('guestStampsTitle')]: 'Tampons du registre',
  [uiKey('heartsAriaLabel')]: 'prise sur la réalité',
  [uiKey('hotelRegister')]: 'Le registre',
  [uiKey('howToAdvance')]: '<b>Cliquez</b> sur le texte, ou appuyez sur <b>Espace</b>, pour continuer',
  [uiKey('howToClick')]: '<b>Cliquez</b> sur une porte, ou appuyez sur <b>1–3</b>, pour choisir votre chemin',
  [uiKey('howToPause')]: '<b>Échap</b> pour mettre en pause · survolez une porte pour lire son indice',
  [uiKey('hudLanguageTooltip')]: 'Changer de langue (s’applique dès le prochain instant)',
  [uiKey('importProfile')]: 'Importer un profil',
  [uiKey('importProfileButton')]: 'Importer',
  [uiKey('importProfileDesc')]: 'Remplace tout votre profil par le fichier collé. Votre progression actuelle sera écrasée — exportez-la d’abord si vous voulez la garder.',
  [uiKey('importProfileError')]: 'Cela ne ressemble pas à un fichier de profil valide — rien n’a changé.',
  [uiKey('importProfilePlaceholder')]: 'Collez ici le contenu d’un fichier de profil exporté',
  [uiKey('importProfileSuccess')]: 'Importé — rechargement en cours…',
  [uiKey('keepsakeChoiceTooltip')]: 'Un souvenir, discrètement dépensé',
  [uiKey('lastMessageBody')]: 'Vous aviez une phrase, et la voici :',
  [uiKey('ledger')]: 'Le carnet du voyageur',
  [uiKey('ledgerDescents')]: 'Descentes en contrebas',
  [uiKey('ledgerEndings')]: 'Fins contemplées',
  [uiKey('ledgerExamined')]: 'Parties examinées',
  [uiKey('ledgerHearts')]: 'Cœurs perdus, au total',
  [uiKey('ledgerKeepsakes')]: 'Souvenirs sur l’étagère',
  [uiKey('ledgerMostWalked')]: 'La porte la plus empruntée',
  [uiKey('ledgerRooms')]: 'Pièces contemplées',
  [uiKey('ledgerRuns')]: 'Voyages accomplis',
  [uiKey('menu')]: 'Menu',
  [uiKey('notYetWalked')]: 'pas encore franchie',
  [uiKey('of')]: 'sur',
  [uiKey('off')]: 'désactivé',
  [uiKey('on')]: 'activé',
  [uiKey('paused')]: 'Pause',
  [uiKey('pausedSub')]: 'les pièces attendront — ici, le temps n’est qu’un décor',
  [uiKey('persona.about1')]: 'Attentif aux autres. Moins attentif à soi-même.',
  [uiKey('persona.about2')]: 'Prompt à rire, lent à dire ce qui s’est vraiment passé.',
  [uiKey('persona.about3')]: 'Encore là. La plupart du temps, c’est là l’essentiel de la réponse.',
  [uiKey('persona.daniel')]: 'Vous mesurez deux fois. Il vous arrive encore de mal couper.',
  [uiKey('persona.mira')]: 'Vous remarquiez les choses avant même qu’on vous le demande.',
  [uiKey('persona.sara')]: 'Vous restez jusqu’à la fin des choses. Cela a toujours été ainsi.',
  [uiKey('persona.tomas')]: 'Vous pardonnez lentement, mais complètement, une fois que vous le faites.',
  [uiKey('personaFreeTextPlaceholder')]: 'Ou écrivez le vôtre, brièvement…',
  [uiKey('personaNameLabel')]: 'Nom',
  [uiKey('personaNamePlaceholder')]: 'Votre nom (ou comment on vous appelle ici)',
  [uiKey('personaSkip')]: 'Passer — appelez-moi voyageur',
  [uiKey('personaTitle')]: 'Qui êtes-vous, ce soir ?',
  [uiKey('pivotalChoicesHeader')]: 'ce que vous avez choisi',
  [uiKey('recapHeader')]: 'Ce que vous avez traversé',
  [uiKey('recoveryBody')]: 'Quelque chose dans les rouages a perdu l’équilibre. Votre dossier est en sécurité — rien de ce que vous avez fait ici n’est perdu.',
  [uiKey('recoveryReturn')]: 'Retour à l’écran-titre',
  [uiKey('recoveryTitle')]: 'L’installation a vacillé',
  [uiKey('registerDoorsWalked')]: 'portes franchies',
  [uiKey('registerSub')]: 'la forme de ce lieu, que vous l’ayez déjà parcouru ou non',
  [uiKey('rememberedTag')]: 'souvenir',
  [uiKey('renderScalePerformance')]: 'Résolution de rendu : Performance',
  [uiKey('renderScaleSharp')]: 'Résolution de rendu : Nette',
  [uiKey('renderScaleStandard')]: 'Résolution de rendu : Standard',
  [uiKey('rereadBack')]: 'Retour — relire le passage précédent',
  [uiKey('rereadJumpTo')]: 'Relire le passage {n}',
  [uiKey('rereadScene')]: '⟲ relire la scène',
  [uiKey('resetProgress')]: 'Réinitialiser toute la progression',
  [uiKey('resetProgressDesc')]: 'Efface tout — notes, fins, réglages, votre partie en cours — retour au tout début.',
  [uiKey('resetRun')]: 'Réinitialiser la partie en cours',
  [uiKey('resetRunDesc')]: 'Abandonne votre voyage en cours. Les notes, les fins et les réglages sont conservés.',
  [uiKey('resetRunDone')]: 'Partie réinitialisée',
  [uiKey('restoredFromBackup')]: 'Votre dernière sauvegarde n’a pas pu être chargée — restaurée depuis la sauvegarde précédente. Rien ne devrait manquer.',
  [uiKey('resume')]: 'Reprendre',
  [uiKey('saveAndExit')]: 'Enregistrer et revenir à l’écran-titre',
  [uiKey('saveFailed')]: 'Votre progression n’a pas pu être enregistrée — l’espace de stockage est peut-être plein.',
  [uiKey('savedToast')]: 'Enregistré',
  [uiKey('senderYou')]: 'expéditeur : vous',
  [uiKey('settingDynamicScenery')]: 'Décor dynamique (expérimental)',
  [uiKey('settingDynamicSceneryDesc')]: 'Les pièces teintent subtilement la lumière et la brume selon leur humeur.',
  [uiKey('settingExaminedPath')]: 'Le chemin examiné — proposé au début de chaque nouvelle partie',
  [uiKey('settingExaminedPathDesc')]: 'Ne change que la présélection au début d’une nouvelle partie — on vous le demandera toujours à nouveau, et le choix de cette partie reste inchangé.',
  [uiKey('settingFpsCap')]: 'Limite de fréquence d’images',
  [uiKey('settingFpsCapDesc')]: 'Une valeur plus basse économise nettement la puissance graphique — ce jeu est fait de brume et de texte, pas d’action.',
  [uiKey('settingFullscreen')]: 'Plein écran',
  [uiKey('settingFullscreenDesc')]: 'Remplit tout l’écran — se bascule aussi avec la touche F.',
  [uiKey('settingHighContrast')]: 'Texte à contraste élevé',
  [uiKey('settingHighContrastDesc')]: 'Couleur de texte plus claire pour une lecture plus facile.',
  [uiKey('settingLanguage')]: 'Langue',
  [uiKey('settingLanguageDesc')]: 'S’applique immédiatement, partout dans le jeu.',
  [uiKey('settingLightMode')]: 'Mode clair',
  [uiKey('settingLightModeDesc')]: 'Le même hôtel au petit matin — les mêmes chambres, une lumière plus douce.',
  [uiKey('settingMusic')]: 'Musique de fond',
  [uiKey('settingMusicDesc')]: 'Une ambiance calme et changeante, qui évolue à chaque acte.',
  [uiKey('settingMusicVolume')]: 'Volume de la musique',
  [uiKey('settingNarration')]: 'Narration',
  [uiKey('settingNarrationDesc')]: 'Répliques parlées, là où elles ont été enregistrées.',
  [uiKey('settingNarrationVolume')]: 'Volume de la narration',
  [uiKey('settingQuality')]: 'Qualité visuelle élevée',
  [uiKey('settingQualityDesc')]: 'Effets de lueur et de lissage ; nécessite une carte graphique plus puissante. S’applique au prochain lancement.',
  [uiKey('settingReducedMotion')]: 'Mouvement réduit',
  [uiKey('settingReducedMotionDesc')]: 'Réduit les mouvements de caméra et les transitions à un instantané quasi immédiat — plus doux pour la sensibilité au mouvement.',
  [uiKey('settingRenderScale')]: 'Résolution de rendu',
  [uiKey('settingRenderScaleDesc')]: 'Plus bas = plus fluide sur les cartes graphiques modestes, une image un peu plus douce. Nette utilise la pleine résolution de votre écran.',
  [uiKey('settingSfx')]: 'Effets sonores',
  [uiKey('settingSfxDesc')]: 'Bruits de portes, de pages qu’on tourne, et les petits sons du choix.',
  [uiKey('settingSfxVolume')]: 'Volume des effets',
  [uiKey('settingTextVersion')]: 'Version du texte',
  [uiKey('settingTextVersionDesc')]: 'v1 est la voix d’origine, conservée comme sauvegarde optionnelle ; v2 est la réécriture actuelle.',
  [uiKey('settingTypewriter')]: 'Texte façon machine à écrire',
  [uiKey('settingTypewriterDesc')]: 'Le texte apparaît lettre par lettre, comme si on vous racontait une histoire.',
  [uiKey('settingUiZoom')]: 'Taille de l’interface',
  [uiKey('settingUiZoomDesc')]: 'Agrandit ou réduit les menus et le texte à votre convenance — la scène 3D reste nette.',
  [uiKey('settings')]: 'Réglages',
  [uiKey('settingsFooter')]: 'les changements de qualité s’appliquent au prochain lancement · le reste, immédiatement',
  [uiKey('settingsSectionAudio')]: 'Son',
  [uiKey('settingsSectionData')]: 'Données',
  [uiKey('settingsSectionDisplay')]: 'Affichage',
  [uiKey('settingsSectionText')]: 'Texte et langue',
  [uiKey('shelfTitle')]: 'L’étagère',
  [uiKey('statHearts')]: 'cœurs préservés',
  [uiKey('statLucidity')]: 'lucidité',
  [uiKey('statNewNotes')]: 'nouvelles notes',
  [uiKey('takeExaminedPath')]: 'Prendre le chemin examiné',
  [uiKey('title')]: 'Écran-titre',
  [uiKey('titleTagline')]: 'un voyage à travers les pièces · chaque porte est une question · le chemin du retour passe par elles',
  [uiKey('travelerLabel')]: 'Voyageur',
  [uiKey('travellerFallback')]: 'voyageur',
  [uiKey('versionV1')]: 'Voix : v1 (originale)',
  [uiKey('versionV2')]: 'Voix : v2 (nouvelle)',
  [uiKey('vestibuleButton')]: 'The Vestibule — choisir un jeu',
  [uiKey('walkAgain')]: 'Refaire le chemin — les pièces ne se réarrangent pour personne, mais vous avez changé',
  [uiKey('walkPlainly')]: 'Suivre le chemin ordinaire',
  [uiKey('whoAreYou')]: 'Qui êtes-vous ?',
});
