/** Expanded field-note articles (owner request, 2026-07-15) — LIMERENCE's
 * English source text. See `packs/types.ts`'s `articles` field and
 * `content/articles.ts`'s header for the full design rationale; the same
 * "start with the richest citation trails, translate carefully, expand
 * later" scoping applies here. */

export const LIMERENCE_ARTICLES: Record<string, { title: string; body: string }> = {
  'the-read-receipt': {
    title: 'Why the Same Silence Means Different Things to Different People',
    body: [
      'John Bowlby began attachment theory from an unglamorous, evolutionary premise: a human infant that stays close to a caregiver survives more reliably than one that wanders, so natural selection built proximity-seeking directly into the nervous system, alongside something Bowlby called an "internal working model" — a running, mostly unconscious expectation about whether reaching out gets met. That expectation, he argued, does not stay in the nursery. It becomes the lens a person reaches for, decades later, whenever someone they love goes quiet.',
      'Mary Ainsworth turned this into an actual experiment in the 1970s, the "Strange Situation": a caregiver and infant enter an unfamiliar room, the caregiver briefly leaves, a stranger enters, and researchers behind one-way glass record exactly how the infant handles the separation and, more tellingly, the reunion. From those recorded reunions came three now-famous patterns — **secure** (distressed by the leaving, comforted by the return), **anxious** (distressed and not easily comforted, as if the return itself is not fully trusted), and **avoidant** (showing little visible distress at all, having apparently learned that visible need does not reliably get met).',
      'The leap that matters for the room you just left came in 1987, when Cindy Hazan and Phillip Shaver asked adults to read three short paragraphs describing different approaches to closeness in romantic relationships, and simply pick the one that felt most like them. The distribution of adult answers tracked the infant distribution closely enough to convince a skeptical field that Bowlby and Ainsworth had described something that does not end at age three — it becomes, in Hazan and Shaver\'s own phrase, "the same weather system, indoors now." A 2011 refinement by Kim Bartholomew and Leonard Horowitz split "avoidant" further, into a dismissive form ("I don\'t need this") and a fearful form ("I want this and I am certain it will hurt me") — because the simpler model could not tell those two very different silences apart.',
      'Here is the specific mechanism that matters for a 1 a.m. unanswered message: anxious attachment is not merely "worrying more." It is a measurable hypervigilance to partner-availability cues, in which an ambiguous signal — a delay, a shorter-than-usual reply, a read receipt with no follow-up — is processed less like neutral information and more like a threat alarm. That alarm reliably produces protest behavior (checking, re-reading, double-texting) which, in a cruel loop the research keeps finding, often produces exactly the distance it was trying to prevent.',
      'None of this is a life sentence. Mary Main and Ruth Goldwyn\'s later longitudinal work identified what they called **"earned security"** — adults who test as securely attached despite a documented history of inconsistent or frightening early caregiving, almost always because something later in life, usually a steady relationship that survived a few honestly-discussed hard nights, taught the nervous system a different answer to the old question. **The feeling that arrives at 1 a.m. is real. The story it is telling you about why she hasn\'t answered is a first draft — and first drafts can be revised.**',
    ].join('\n\n'),
  },
  'the-best-friends-girl': {
    title: 'The Scientist Who Named the Thing You\'re Feeling',
    body: [
      'In 1979, the psychologist Dorothy Tennov published Love and Limerence: The Experience of Being in Love, built from structured interviews with roughly five hundred people about a state she deliberately gave a clinical, unmoralized name to — not "love," which she felt was too broad and too flattering, and not "infatuation" or "crush," which she felt were too dismissive of something people experienced as genuinely consuming. She wanted a word with no verdict built into it, just a description.',
      'Tennov\'s interviews mapped a remarkably consistent symptom cluster: intrusive, involuntary thinking about the limerent object that resists being willed away; an acute, specific longing for reciprocation rather than generalized affection; and — the finding that tends to surprise people most — **intensification under uncertainty and adversity, rather than dissolution.** Ambiguity does not starve limerence. It feeds it, because an unresolved signal leaves room for the mind to fill the gap with hope, and hope, unlike certainty, can run for a very long time on very little fuel. Left untended, Tennov found the state typically ran its full arc — onset, "crystallization," and eventual decay — somewhere between eighteen months and three years.',
      'Decades later, neuroscience found physical machinery to go with Tennov\'s interview data. Helen Fisher\'s fMRI research in the early 2000s scanned people who reported being intensely, newly in love and found activation concentrated in dopamine-rich reward circuitry — the ventral tegmental area, the caudate nucleus — patterns that overlap substantially with what shows up in scans of substance craving. This does not mean limerence *is* addiction in a clinical sense, but it does mean "I physically cannot stop thinking about them" turns out to be measurably closer to literal truth than to figure of speech.',
      'Jeffry Simpson, and separately David Schmitt and David Buss in their large 2001 cross-cultural study of mate-poaching, looked at exactly the triangle this room places you inside — studied from all three corners at once: the person doing the wanting, the person already partnered, and the partner who does not yet know. The finding that should sit with you longest is that real, measurable costs land on **all three** parties, largely independent of how the situation eventually resolves. There is no version of this triangle where only one person is exposed.',
      'The line worth carrying out of this room is the one Tennov\'s own data eventually forced, cleanly, between two things people tend to fuse together: **the state and the conduct.** The feeling that arrives uninvited, chemically real and involuntary, is not a moral event. What you do with a friend\'s girlfriend while feeling it is the only part anyone — including you, later — gets to judge you for.',
    ].join('\n\n'),
  },
};
