import type { Room } from '../../../engine/schema';
import { theFrontDesk } from './prologue';
import {
  theReadReceipt,
  theScreenshot,
  thePassword,
  theParty,
  theForward,
  theBestFriendsGirl,
  theSummerEnds,
  theRumor,
} from './act1';
import {
  theDistance,
  theHallPass,
  theRebound,
  theUnicorn,
  justFriends,
  theEx,
  theConfession,
  theOtherSideOfTheDoor,
  theScoreboard,
} from './act2';
import {
  theColleague,
  theMetamour,
  theVeto,
  theDrift,
  theSecondAccount,
  theDiscovery,
  theWeddingEve,
  theTherapist,
  theUsualSuite,
  theUsualRoom,
} from './act3';
import {
  theKitchenTable,
  theUnsent,
  theMorningDesk,
} from './placeholders';

export const limerenceRooms: Room[] = [
  theFrontDesk,
  theReadReceipt,
  theScreenshot,
  thePassword,
  theParty,
  theForward,
  theBestFriendsGirl,
  theSummerEnds,
  theRumor,
  theDistance,
  theHallPass,
  theRebound,
  theUnicorn,
  justFriends,
  theEx,
  theConfession,
  theOtherSideOfTheDoor,
  theScoreboard,
  theColleague,
  theMetamour,
  theVeto,
  theDrift,
  theSecondAccount,
  theDiscovery,
  theWeddingEve,
  theTherapist,
  theUsualSuite,
  theUsualRoom,
  theKitchenTable,
  theUnsent,
  theMorningDesk,
];
