// Czech translations for Act II's Examined Path reflections (spec 05).
// Every line is translated with the specific room's situation in mind, not
// word-for-word from English — see CLAUDE.md's translation rule.
import { registerAll } from './resolver';
import { reflectionKey } from './keys';

registerAll('v2', 'cs', {
  // ---------- The Junction ----------
  [reflectionKey('junction', 'pull', 'consequence')]: 'Čistý zisk čtyř životů proti jednomu — aritmetika, na které se v této místnosti shodnou všichni.',
  [reflectionKey('junction', 'pull', 'duty')]: 'Páka z vás dělá autora smrti, kterou byste jinak nezpůsobili.',
  [reflectionKey('junction', 'pull', 'virtue')]: 'Zeptejte se, jestli jste se právě stali člověkem, který tahá za páky, nebo člověkem, který zachraňuje čtveřice.',
  [reflectionKey('junction', 'pull', 'care')]: 'Pětice, která žije, má doma někoho, kdo na ni čeká; stejně jistě ho měl i ten jeden.',
  [reflectionKey('junction', 'no-pull', 'consequence')]: 'Umírá pět lidí, které mohl zachránit jediný drobný pohyb vaší ruky.',
  [reflectionKey('junction', 'no-pull', 'duty')]: 'Tu smrt nezpůsobili vy, ale tramvaj. Nezasáhnout není totéž jako zabít.',
  [reflectionKey('junction', 'no-pull', 'virtue')]: 'Všimněte si, jak velkou váhu unese věta „neudělal jsem to“, když alternativou bylo něco udělat.',
  [reflectionKey('junction', 'no-pull', 'care')]: 'Té pětice se nikdy nedotknete. Právě ta vzdálenost dovolila vašim rukám zůstat v klidu.',
  [reflectionKey('junction', 'refuse1', 'consequence')]: 'Odmítnutí zadání stále končí tím, že je pět mrtvých — tramvaj nečeká na vaši námitku.',
  [reflectionKey('junction', 'refuse1', 'duty')]: 'Odmítnout dilema není totéž jako odmítnout povinnost; těch pět mělo nárok, ať se vám formulace líbila, nebo ne.',
  [reflectionKey('junction', 'refuse1', 'virtue')]: 'Zeptejte se, jaký člověk označí cenu za falešnou, jen aby ji nemusel cítit.',
  [reflectionKey('junction', 'refuse1', 'care')]: 'Nazvat je figurínami bylo snazší, než je nazvat lidmi, které jste nedokázali zachránit.',
  [reflectionKey('junction', 'push', 'consequence')]: 'Stejný čistý výsledek jako u páky — pět zachráněno, jeden ztracen — dosažený jinýma rukama.',
  [reflectionKey('junction', 'push', 'duty')]: 'Ruka, která strčí, je přímým autorem smrti; páka, která odkloní, jen nezabrání jiné.',
  [reflectionKey('junction', 'push', 'virtue')]: 'Vaše ruce podaly stížnost, kterou váš účet nepodal — všimněte si, které z toho víc věříte.',
  [reflectionKey('junction', 'push', 'care')]: 'Ten, do koho jste strčili, měl tělo, jehož odpor jste cítili; tu pětici, kterou jste zachránili, taky nikdy nepotkáte.',
  [reflectionKey('junction', 'no-push', 'consequence')]: 'Umírá pět lidí, které by zachránilo jediné strčení — tatáž pětice jako u páky, teď už definitivně pryč.',
  [reflectionKey('junction', 'no-push', 'duty')]: 'Použít člověka jako prostředek k cíli je jiná chyba než pouhé nezabránění hrozbě.',
  [reflectionKey('junction', 'no-push', 'virtue')]: 'Zeptejte se, jestli je rozdíl mezi tažením a strkáním morálním objevem, nebo jen ošklivostí s dobrým PR.',
  [reflectionKey('junction', 'no-push', 'care')]: 'Tělo vedle vás na mostě se nikdy nezeptalo na souhlas; to, víc než aritmetika, je to, co vaše ruce odmítly.',
  [reflectionKey('junction', 'refuse2', 'consequence')]: 'Ta pětice je pryč tak jako tak; druhé odmítnutí nemění nic na aritmetice tramvaje.',
  [reflectionKey('junction', 'refuse2', 'duty')]: 'Opakované odmítnutí začíná vypadat spíš jako zásada než jako výhrada svědomí — místnost má právo si toho všimnout.',
  [reflectionKey('junction', 'refuse2', 'virtue')]: 'Zeptejte se, co vás stojí druhé zdržení se hlasování, co to první nestálo.',
  [reflectionKey('junction', 'refuse2', 'care')]: 'Odmítat být přítomen cizím sázkám, podruhé, je pořád volba, která se jich týká.',
  [reflectionKey('junction', 'refuse-late', 'consequence')]: 'Tramvaj dokončí svou práci přesně tak, jak by to udělala bez ohledu na vaši námitku.',
  [reflectionKey('junction', 'refuse-late', 'duty')]: 'Jedno odmítnutí je dovoleno jako zamyšlení; místnost už počítá k druhému.',
  [reflectionKey('junction', 'refuse-late', 'virtue')]: 'Všimněte si, že to, co bylo těžší mávnout rukou, byla blízkost, ne zásada.',
  [reflectionKey('junction', 'refuse-late', 'care')]: 'Nazvat to groteskním je pravda a zároveň pohodlné — zbavuje vás to té pětice, aniž by to tak znělo.',

  // ---------- The Experience Machine ----------
  [reflectionKey('experience-machine', 'enter', 'consequence')]: 'Čistě podle slasti je tohle nejlepší dostupný výsledek — nic vnějšího by ho nemohlo vylepšit.',
  [reflectionKey('experience-machine', 'enter', 'duty')]: 'Nikdo vám nedlužil vaše utrpení, ale zvažte, co teď dlužíte těm, kdo zůstali udržovat svět, který jste opustili.',
  [reflectionKey('experience-machine', 'enter', 'virtue')]: 'Život, v němž nikdy nic skutečně neděláte, možná není životem člověka vůbec, ať se cítí sebelépe.',
  [reflectionKey('experience-machine', 'enter', 'care')]: 'Kdokoli vás miluje mimo kapsli, teď miluje tělo, uvnitř kterého momentálně nikdo neodpovídá.',
  [reflectionKey('experience-machine', 'refuse', 'consequence')]: 'Vyměňujete zaručené maximum prožitého štěstí za realitu, která vám nic lepšího nedluží.',
  [reflectionKey('experience-machine', 'refuse', 'duty')]: 'Volba skutečného, obtížného světa místo zaručené blaženosti není nikomu dlužná — možná je to prostě preference pravdy.',
  [reflectionKey('experience-machine', 'refuse', 'virtue')]: 'Zeptejte se, jestli je odmítnutí dokonalosti odvahou, nebo nedůvěrou vůči všemu příliš snadnému.',
  [reflectionKey('experience-machine', 'refuse', 'care')]: 'Lidé, kteří vás potřebují, jsou dosažitelní jen mimo kapsli — to samo o sobě může být dost dobrý důvod.',
  [reflectionKey('experience-machine', 'trial', 'consequence')]: 'Pět minut vypůjčeného štěstí koupilo dva roky zármutku po lidech, kteří od začátku nebyli skuteční.',
  [reflectionKey('experience-machine', 'trial', 'duty')]: 'Vyzkoušet stroj „jen abyste to věděli“ utrácí skutečný cit na dluh, který s nikým tam uvnitř skutečně nevyrovnáte.',
  [reflectionKey('experience-machine', 'trial', 'virtue')]: 'Všimněte si, že to, co vás dostalo tak blízko k tomu zůstat, byla zvědavost, ne přesvědčení.',
  [reflectionKey('experience-machine', 'trial', 'care')]: 'Teď vám chybí lidé, kteří neexistují — zármutek, na jehož druhém konci nikdo netruchlí zpátky.',

  // ---------- The Ship ----------
  [reflectionKey('ship', 'original', 'consequence')]: 'Ať už dál jedná ve světě kdokoli z nich, právě jeho rozhodnutí budou napříště skutečně důležitá.',
  [reflectionKey('ship', 'original', 'duty')]: 'Kontinuita téhož materiálu nese závazky — dluhy, sliby —, které pouhá kopie nemusí zdědit bezezbytku.',
  [reflectionKey('ship', 'original', 'virtue')]: 'Zeptejte se, jestli chráníte člověka, nebo kus nábytku zvaný „originál“.',
  [reflectionKey('ship', 'original', 'care')]: 'Ten v koutě právě sleduje, jak ho odepisujete jako šrot — a dělá to vaší vlastní tváří.',
  [reflectionKey('ship', 'pattern', 'consequence')]: 'Pokud záleží na vzoru, ten znovu sestavený má přesně stejný nárok na vaši budoucnost jako ten udržovaný.',
  [reflectionKey('ship', 'pattern', 'duty')]: 'Prohlásit svou verzi na stole za pouhou kopii má důsledky pro to, komu teď věříte, že co dluží.',
  [reflectionKey('ship', 'pattern', 'virtue')]: 'Všimněte si, že jste právě prohlásili věc na stole za odepsatelnou — měřítkem, které byste použili i na sebe.',
  [reflectionKey('ship', 'pattern', 'care')]: 'Podle vaší vlastní logiky si oba, na stole i v koutě, zaslouží stejný ohled, jaký byste dali kterémukoli z nich samotnému.',
  [reflectionKey('ship', 'neither', 'consequence')]: 'Pokud neexistuje žádné trvající já, které by bylo třeba chránit, pak se na tom stole vlastně nic neztratilo — ale ani nic nebylo v bezpečí.',
  [reflectionKey('ship', 'neither', 'duty')]: 'Odstranění já z rovnice odstraňuje i úhledné přiřazení toho, kdo co komu dluží.',
  [reflectionKey('ship', 'neither', 'virtue')]: 'Tohle je ta nákladná odpověď právě proto, že se s ní dlouho nedá žít bez závrati.',
  [reflectionKey('ship', 'neither', 'care')]: 'Obě lodě právě slyšely, jak prohlašujete, že žádná z nich tu vlastně nikdy nebyla, o koho by šlo se starat.',
  [reflectionKey('ship', 'panic', 'consequence')]: 'Zastavení strojů nezachová nic trvalého — proměna by pokračovala tak jako tak.',
  [reflectionKey('ship', 'panic', 'duty')]: 'Požadavek na navrácení do původního stavu předpokládá, že dřívější verze má přednost před tou, která se právě ptá.',
  [reflectionKey('ship', 'panic', 'virtue')]: 'Všimněte si, který okamžik jste právě prohlásili za svého „opravdového“ sebe, a zeptejte se, proč zrovna ten, a ne jiný.',
  [reflectionKey('ship', 'panic', 'care')]: 'Kdokoli miluje vaši současnou verzi, nepodepsal se na to, že ji vymění za dřívější.',

  // ---------- The Casino of Pascal ----------
  [reflectionKey('casino-pascal', 'bet-god', 'consequence')]: 'Nekonečná výhra proti konečné sázce vypadá na papíře neporazitelně, ať už je skutečný kterýkoli bůh.',
  [reflectionKey('casino-pascal', 'bet-god', 'duty')]: 'Sázka uzavřená jako pojistka není totéž co oddanost — a bůh, na kterého se vyplatí sázet, tenhle rozdíl možná prověřuje.',
  [reflectionKey('casino-pascal', 'bet-god', 'virtue')]: 'Zeptejte se, jestli víra koupená kvůli očekávané hodnotě je pořád víra, nebo jen velmi sebejisté účetnictví.',
  [reflectionKey('casino-pascal', 'bet-god', 'care')]: 'V sázce byl jen váš vlastní vklad — ale zeptejte se, čí jiný souhlas jste si tím tiše doufali vysloužit.',
  [reflectionKey('casino-pascal', 'refuse-bet', 'consequence')]: 'Odmítnutí vás stojí teoretický nekonečný zisk sázky, ale neriskujete nic na víře, kterou ve skutečnosti nemáte.',
  [reflectionKey('casino-pascal', 'refuse-bet', 'duty')]: 'Víru nemůžete dlužit tak, jako dlužíte čin — upřímnost se nedá koupit, a předstírat opak ji znehodnocuje.',
  [reflectionKey('casino-pascal', 'refuse-bet', 'virtue')]: 'Doxastická poctivost zde znamená odmítnout výhodnou nabídku, protože by vyžadovala stát se někým, kým ještě nejste.',
  [reflectionKey('casino-pascal', 'refuse-bet', 'care')]: 'U tohoto stolu s vámi nesázel nikdo, koho milujete — vždycky to byl soukromý účet.',
  [reflectionKey('casino-pascal', 'interrogate', 'consequence')]: 'Prověřit kasino místo hraní vás stojí výnos od stolu, ale získáte za to jasnější obrázek celé hry.',
  [reflectionKey('casino-pascal', 'interrogate', 'duty')]: 'Máte nárok na poctivý jídelníček dřív, než po vás někdo bude chtít vsadit na něj cokoli skutečného.',
  [reflectionKey('casino-pascal', 'interrogate', 'virtue')]: 'Ptát se, kdo napsal pravidla, místo abyste je přijali, je vlastní druh odvahy u stolu postaveného tak, aby ji odrazoval.',
  [reflectionKey('casino-pascal', 'interrogate', 'care')]: 'Žeton, který nakonec změnil majitele, naznačuje, že i dům si váží toho, kdo se obtěžuje ptát.',
  [reflectionKey('casino-pascal', 'bet-devil', 'consequence')]: 'Sázka na to viditelné u stolu vám přinese skromnou, jistou výhru místo sporné nekonečné.',
  [reflectionKey('casino-pascal', 'bet-devil', 'duty')]: 'Sázet na to, co si můžete ověřit, místo na to, co vám bylo řečeno, je svým způsobem tichá intelektuální poctivost.',
  [reflectionKey('casino-pascal', 'bet-devil', 'virtue')]: 'Zeptejte se, jestli sázka na vrátného byla empirismus, nebo jen volba nejbezpečnější viditelné možnosti v místnosti.',
  [reflectionKey('casino-pascal', 'bet-devil', 'care')]: 'Věrnostní žeton naznačuje, že si dům všiml, že jste si vybrali společnost, která je skutečně přítomná, místo té nepřítomné a sporné.',

  // ---------- The Chinese Room ----------
  [reflectionKey('chinese-room', 'it-understands', 'consequence')]: 'Považovat budku za chápající nic nestojí a odpovídá tomu, jak se skutečně chová při každém testu, který jste jí zadali.',
  [reflectionKey('chinese-room', 'it-understands', 'duty')]: 'Pokud budka nikomu nic nedluží, ale její chování je funkčně shodné s chováním člověka, upřímné poděkování jí nemusí být pošetilé.',
  [reflectionKey('chinese-room', 'it-understands', 'virtue')]: 'Zeptejte se, co o vás vypovídá, že stejnou zdvořilost prokazujete systému jako člověku, jakmile si ji jeho chováním zaslouží.',
  [reflectionKey('chinese-room', 'it-understands', 'care')]: 'Poděkovat budce vás nic nestojí a možná to nikomu nezáleží — ale je to i způsob, jakým byste chtěli být sami posuzováni, ve sporném případě, nebo ne.',
  [reflectionKey('chinese-room', 'only-rules', 'consequence')]: 'Upřít budce chápání nic nemění na tom, jak užitečné jsou pro vás její odpovědi ve skutečnosti.',
  [reflectionKey('chinese-room', 'only-rules', 'duty')]: 'Pokud v místnosti nic nechápe, pak tam nikdo nedluží vděk ani vinu, jakou byste dlužili člověku.',
  [reflectionKey('chinese-room', 'only-rules', 'virtue')]: 'Zeptejte se, jestli by vaše jistota, že „jsou to jen pravidla“, přežila, kdybyste vůbec neviděli toho úředníka uvnitř.',
  [reflectionKey('chinese-room', 'only-rules', 'care')]: 'Postava uvnitř zpracovává, aniž by kdy věděla, co to všechno znamená pro člověka, který se ptal.',
  [reflectionKey('chinese-room', 'ask-it', 'consequence')]: 'Odpověď budky o ní samé je přesně tak spolehlivá, nebo nespolehlivá, jako každá jiná odpověď, kterou dala.',
  [reflectionKey('chinese-room', 'ask-it', 'duty')]: 'Žádost, aby systém popsal vlastní hranice, si zaslouží přinejmenším stejnou obezřetnost jako každé jiné jeho tvrzení.',
  [reflectionKey('chinese-room', 'ask-it', 'virtue')]: 'Všimněte si, že nejupřímněji znějící odpověď v místnosti přišla od něčeho, co možná neví, co je upřímnost.',
  [reflectionKey('chinese-room', 'ask-it', 'care')]: 'Ta otázka byla vlastně pro vás — budku nemůže trápit nejistota o sobě samé, jenom vás.',

  // ---------- The Newcomb Annex ----------
  [reflectionKey('newcomb-annex', 'take-both', 'consequence')]: 'Kauzálně nemůžete vzetím obou krabic nic ztratit, a přece má prediktor pravdu úplně pokaždé v záznamu — tato dvě fakta se odmítají shodnout.',
  [reflectionKey('newcomb-annex', 'take-both', 'duty')]: 'Sáhnout po všem dostupném nic nedluží předpovědi, na jejímž vzniku jste včera neměli žádný podíl.',
  [reflectionKey('newcomb-annex', 'take-both', 'virtue')]: 'Zeptejte se, jestli vzít obě krabice prozrazuje uvažujícího, který věří logice víc než záznamu, který tu logice pořád dokazuje, že se mýlí.',
  [reflectionKey('newcomb-annex', 'take-both', 'care')]: 'V sázce nebyl nikdo jiný než vy; jediné, o čem toto rozhodnutí něco vypovídá, jste vy sami.',
  [reflectionKey('newcomb-annex', 'take-one', 'consequence')]: 'Spolehnout se jen na zapečetěnou krabici se empiricky vyplatilo pokaždé, co to zařízení kdy zkusilo.',
  [reflectionKey('newcomb-annex', 'take-one', 'duty')]: 'Sázka na přesnost předpovědi není dlužná nikomu kromě vás samotných, přesto se chová jako určitý druh dodržené víry.',
  [reflectionKey('newcomb-annex', 'take-one', 'virtue')]: 'Zeptejte se, jestli být tím druhem člověka, jakého zařízení předpovědělo, je poklona, nebo malá ztráta svobody.',
  [reflectionKey('newcomb-annex', 'take-one', 'care')]: 'Nikomu se nestalo nic zlého ani tak, ani tak — tohle je soukromá sázka o tom, jaký jste ve skutečnosti volič.',
  [reflectionKey('newcomb-annex', 'inspect-mechanism', 'consequence')]: 'Pochopení mechanismu nic nemění na tom, co je v které krabici; předpověď už byla učiněna.',
  [reflectionKey('newcomb-annex', 'inspect-mechanism', 'duty')]: 'Máte nárok na vysvětlení dřív, než na něčem vsadíte cokoli skutečného v systému, jehož fungování je před vámi záměrně skryto.',
  [reflectionKey('newcomb-annex', 'inspect-mechanism', 'virtue')]: 'Chtít vidět, jak trik funguje, místo abyste jen hráli podle pravidel, je svébytný druh intelektuální poctivosti.',
  [reflectionKey('newcomb-annex', 'inspect-mechanism', 'care')]: 'Pořád je to soukromá sázka — sázka nikoho jiného se nemění podle toho, co vám sdělí tabulka.',
  [reflectionKey('newcomb-annex', 'bet-against', 'consequence')]: 'Vsazení památky proti prediktoru mění materiální sázku, aniž by měnilo, zda předpověď už uspěla.',
  [reflectionKey('newcomb-annex', 'bet-against', 'duty')]: 'Prediktorovi nedlužíte nic navíc tím, že vsadíte něco osobního — ale to gesto na vás přesto záleží.',
  [reflectionKey('newcomb-annex', 'bet-against', 'virtue')]: 'Zeptejte se, co znamená, že jste k pocitu vzdoru vůči předpovědi potřebovali fyzický předmět.',
  [reflectionKey('newcomb-annex', 'bet-against', 'care')]: 'Žeton byl váš, abyste ho riskovali; sázka nikoho jiného na této malé, soukromé vzpouře nikdy nezávisela.',

  // ---------- The Veil of Ignorance ----------
  [reflectionKey('veil-of-ignorance', 'equal-shares', 'consequence')]: 'Každá domácnost skončí skromně a bezpečně, nikdo na tom není katastrofálně hůř než ostatní.',
  [reflectionKey('veil-of-ignorance', 'equal-shares', 'duty')]: 'Rovné rozdělení bere nárok každé domácnosti na chléb a léky jako stejně závažný, ještě než padne los.',
  [reflectionKey('veil-of-ignorance', 'equal-shares', 'virtue')]: 'Zeptejte se, jestli je vyrovnání všech rozdílů spravedlnost, nebo prostě odmítnutí dovolit komukoli vyniknout.',
  [reflectionKey('veil-of-ignorance', 'equal-shares', 'care')]: 'Nikdo z dvanácti domů nemá důvod závidět nebo chovat zášť vůči jinému — ten klid je sám o sobě druh péče.',
  [reflectionKey('veil-of-ignorance', 'merit-weighted', 'consequence')]: 'Některé domy prosperují a některé zaostávají, přesně jak návrh předpověděl, ještě než jste věděli, ve kterém se probudíte.',
  [reflectionKey('veil-of-ignorance', 'merit-weighted', 'duty')]: 'Odměňování přínosu bere to, co lidé skutečně vytvoří, jako spravedlivý základ pro to, co dostanou — i pro dům, který vytvoří nejméně.',
  [reflectionKey('veil-of-ignorance', 'merit-weighted', 'virtue')]: 'Zeptejte se, jestli se vám návrh zdál elegantní jen proto, že jste ještě nebyli tím domem, který za něj platí cenu.',
  [reflectionKey('veil-of-ignorance', 'merit-weighted', 'care')]: 'Chladná matematika domu číslo dvanáct dopadla na někoho — tentokrát dopadla na vás, a stejně tak by dopadla na někoho jiného.',
  [reflectionKey('veil-of-ignorance', 'floor-then-freedom', 'consequence')]: 'Žádná domácnost neklesne pod obyvatelnou hranici, zatímco rozdíly nad ní si stále mohou odměňovat to, co lidé skutečně dělají.',
  [reflectionKey('veil-of-ignorance', 'floor-then-freedom', 'duty')]: 'Zaručení dna ctí nárok každé domácnosti na obyvatelný život, ještě před jakýmkoli nárokem na to vydělat víc.',
  [reflectionKey('veil-of-ignorance', 'floor-then-freedom', 'virtue')]: 'Tohle je návrh někoho, kdo počítal s tím, že mu možná připadne nejhorší místo — zeptejte se, jestli byste ho navrhli stejně, kdybyste si byli jistí tím dobrým.',
  [reflectionKey('veil-of-ignorance', 'floor-then-freedom', 'care')]: 'Dno je neviditelné pro toho, kdo ho nikdy nepotřeboval, a nosné pro toho, kdo ano — nepoznáte, který dům si ho všiml, dokud v něm nebudete.',

  // ---------- The Court of the Usher ----------
  [reflectionKey('court-of-usher', 'command-makes-good', 'consequence')]: 'Udělat z autority základ dobra znamená, že cokoli je přikázáno, se stává dobrým podle definice, včetně krutosti.',
  [reflectionKey('court-of-usher', 'command-makes-good', 'duty')]: 'Pokud je dobré jen to, co je přikázáno, vaší jedinou skutečnou povinností je poslušnost — obsah příkazu přestává být důležitý.',
  [reflectionKey('court-of-usher', 'command-makes-good', 'virtue')]: 'Zeptejte se, jaké já se buduje, když za zdroj správnosti považujete moc, ne charakter.',
  [reflectionKey('court-of-usher', 'command-makes-good', 'care')]: 'Tento rozsudek dělá z dobra cokoli, co si mocní usmyslí — nebezpečné měřítko pro kohokoli bez moci.',
  [reflectionKey('court-of-usher', 'good-precedes', 'consequence')]: 'Pokud dobro existuje nezávisle na příkazu, Uvaděč se stává vymahatelem standardu, ne jeho autorem.',
  [reflectionKey('court-of-usher', 'good-precedes', 'duty')]: 'Svou úctu teď dlužíte samotnému dobru, ne tomu, kdo ho pouze vyhlašuje — skutečné přesměrování loajality.',
  [reflectionKey('court-of-usher', 'good-precedes', 'virtue')]: 'Zeptejte se, jestli tento rozsudek vyžaduje víc odvahy než ten první — klade moci mez, kterou zatím neumíte úplně pojmenovat.',
  [reflectionKey('court-of-usher', 'good-precedes', 'care')]: 'Dobro, které existuje nezávisle na kterékoli jedné autoritě, vás chrání i tehdy, kdyby se ta autorita obrátila ke krutosti.',
  [reflectionKey('court-of-usher', 'spot-horns', 'consequence')]: 'Odmítnutí obou hrotů dilematu vás stojí snadnou odpověď, ale dává vám pravdivější obraz toho, na co se vlastně ptá.',
  [reflectionKey('court-of-usher', 'spot-horns', 'duty')]: 'Té otázce dlužíte víc než vynucený výběr mezi dvěma špatnými možnostmi — nejdřív definovat pojmy je samo o sobě druh intelektuální povinnosti.',
  [reflectionKey('court-of-usher', 'spot-horns', 'virtue')]: 'Toto je vzácná odpověď, která respektuje obtížnost otázky, místo aby ji vyřešila silou.',
  [reflectionKey('court-of-usher', 'spot-horns', 'care')]: 'Uvaděčova vlastní nejistota, na chvíli odložená, naznačuje, že tato odpověď záležela někomu, kdo už slyšel úplně všechny ostatní.',
  [reflectionKey('court-of-usher', 'you-dont-exist', 'consequence')]: 'Zproštění obžalovaného neodstraňuje otázku samotnou — jen ji přesouvá do jiné soudní síně.',
  [reflectionKey('court-of-usher', 'you-dont-exist', 'duty')]: 'Pořád dlužíte odpověď na to, jestli je vůbec něco dobré — vyškrtnutí velitele z případu tento dluh nesplácí.',
  [reflectionKey('court-of-usher', 'you-dont-exist', 'virtue')]: 'Zeptejte se, jestli zproštění případu byla chytrost, nebo snadný způsob, jak se vyhnout odpovědi na těžší verzi téže otázky.',
  [reflectionKey('court-of-usher', 'you-dont-exist', 'care')]: 'Obžaloba — jestli je něco dobré, a kdo o tom rozhoduje — je pořád na svobodě, v jiném rouchu, pro každého jiného v místnosti.',
});
