// Czech translation of the v2 Act III room prose (beats, choice text/hint/
// outcome, field notes) for: teleporter, editor, introduction, debt-of-dead,
// free-will. Registered under version 'v2'. See cs-rooms.ts for the
// established pattern this file follows.
import { registerAll } from './resolver';
import {
  roomBeatKey,
  roomChoiceHintKey,
  roomChoiceOutcomeKey,
  roomChoiceTextKey,
  roomNoteBodyKey,
  roomNoteThinkersKey,
  roomNoteTitleKey,
} from './keys';

// ---------- Act III: The Teleporter ----------
registerAll('v2', 'cs', {
  [roomBeatKey('teleporter', 0, 0)]: 'Místnost s podlahou z černého zrcadla a bez protější zdi — jen mezera, a za mezerou cesta vpřed, nedosažitelná žádným mostem, protože žádný most není.',
  [roomBeatKey('teleporter', 0, 1)]: 'Místo toho je tu kabina. Kartáčovaná ocel, jemně osvětlená, dveře jako zdvořilá gilotina. Návod je vytištěn písmem zvoleným tak, aby uklidňovalo.',
  [roomBeatKey('teleporter', 0, 2)]: 'VSTUPTE. BUDETE NASKENOVÁNI AŽ NA ATOM, ROZLOŽENI A VYTIŠTĚNI — DOKONALE — NA DRUHÉ STRANĚ. KOPIE SI BUDE PAMATOVAT ČTENÍ TÉTO CEDULE. KOPIE BUDE MÍT POCIT, ŽE PROŠLA. KOPIE SI BUDE VELMI JISTA.',
  [roomBeatKey('teleporter', 0, 4)]: 'Uvaděč: Beru to denně. Nebo to bere někdo — ten, kdo dorazí, má mé vzpomínky a mé stížnosti a podává mé zprávy, takže se tu už nikdo neptá. Mezeře je metafyzika lhostejná. Mezeře záleží jen na tom, že žádný most není.',
  [roomChoiceTextKey('teleporter', 'step-through')]: 'Vstupte dovnitř. Ať dorazí cokoli, bude si jisté, že je to vy — a jistota je vše, co jste kdy měli.',
  [roomChoiceHintKey('teleporter', 'step-through')]: 'Důvěřujte vzoru.',
  [roomChoiceOutcomeKey('teleporter', 'step-through', 0)]: 'Dveře se zavřou. Není žádná bolest, žádné světlo, žádný tunel — je tu jen cedule na druhé straně, na které stojí: DĚKUJEME. A vzpomínáte si, jak jste četli tu první ceduli, a vzpomínáte si na rozhodování, a cítíte se přesně jako někdo, kdo prošel.',
  [roomChoiceOutcomeKey('teleporter', 'step-through', 1)]: 'Což je samozřejmě přesně to, co cedule slibovala, že bude kopie cítit. Zkontrolujete si ruce. Jsou velmi přesvědčivé. Buď jste stejný člověk, nebo jste nejlepší důkaz, že „stejný člověk“ byl vždycky jen pocit oblečený do šatů faktu.',
  [roomChoiceOutcomeKey('teleporter', 'step-through', 2)]: 'Uvaděč: (už na druhé straně — nebo tam je nějaký Uvaděč) Bezbolestné, vidíte. Jestli to někdo přežil, je otázka, na kterou už nezbyl svědek, co by odpověděl. Vítejte, tak jako tak. Oba dva.',
  [roomChoiceTextKey('teleporter', 'refuse-stairs')]: 'Odmítněte. Hledejte schody, římsu, lano — cokoli, co udrží niť nepřetrženou.',
  [roomChoiceHintKey('teleporter', 'refuse-stairs')]: 'Musí existovat jiná cesta přes.',
  [roomChoiceOutcomeKey('teleporter', 'refuse-stairs', 0)]: 'Hledáte. Hledáte pořádně — stěny, zrcadlovou podlahu, servisní poklop kabiny. Místnost vás sleduje s trpělivostí něčeho, co tohle přesné hledání hostilo už mnohokrát.',
  [roomChoiceOutcomeKey('teleporter', 'refuse-stairs', 1)]: 'Žádné schody nejsou. Nikdy žádné nebyly. Místnost je poctivá ohledně svých jediných dveří, a ty dveře jsou kabina. Stojíte u mezery dlouhou chvíli, a pak — protože vpřed je jediný směr, který tohle místo nabízí — vstoupíte tak jako tak, aniž byste získali cokoli kromě jistoty, že jste vyčerpali všechny alternativy.',
  [roomChoiceOutcomeKey('teleporter', 'refuse-stairs', 2)]: 'Uvaděč: Pro co to stojí za to — ti, kdo hledají, dorazí na druhou stranu identičtí s těmi, kdo prostě důvěřovali. Ale dorazí tam s tím, že za to bojovali, a někteří poutníci potřebují přesně tenhle doklad. Drželi jste tu niť tak dlouho, dokud ta niť existovala. Víc nikdo udělat nemůže. Jestli to dokáže vůbec i tohle, je otázka, kvůli které byla tato místnost postavena.',
  [roomChoiceTextKey('teleporter', 'copy-first')]: '„Spusťte to v režimu kopie — vytiskněte toho druhého, aniž byste mě rozložili. A pak necháme na nás dvou, kdo přejde.“',
  [roomChoiceHintKey('teleporter', 'copy-first')]: 'Rozdělte otázku, než na ni odpovíte.',
  [roomChoiceOutcomeKey('teleporter', 'copy-first', 0)]: 'Kabina, zaskočená, nahlédne do vlastního manuálu. Režim kopie existuje. Samozřejmě že existuje — zničení nikdy nebylo technicky nutné; bylo to jen zdvořilost, aby čísla zůstala úhledná.',
  [roomChoiceOutcomeKey('teleporter', 'copy-first', 1)]: 'Vzdálený-vy se objeví, zkontroluje si ruce přesně vaším gestem, a podívá se přes mezeru na vás. Na jeden dlouhý okamžik jste oba zticha, protože oba víte: cokoli právě teď cítíte — tuhle závrať z toho, že jste originál — cítí to i ten druhý, symetricky, a nazývá originálem sebe. Neexistuje experiment, který by kdokoli z vás mohl provést, aby to rozhodl.',
  [roomChoiceOutcomeKey('teleporter', 'copy-first', 2)]: 'Uvaděč: A přesně tady je ten skalpel. Pokud je kopie vámi, když jste zničeni, proč není vámi, když zničeni nejste? Jeden filosof tuhle vidličku našel před spoustou let, a nikdy nepřestala krvácet. (k tomu druhému) Teď půjdete do kabiny vy. (k vám) A časem i vy. Pořád tu není žádný most — jen teď je tu ten, kdo za vás dokončí vaše přejití. Buďte k němu laskaví. Měl taky zvláštní den.',
  [roomNoteTitleKey('teleporter')]: 'Osobní identita a teleport',
  [roomNoteThinkersKey('teleporter')]: 'Derek Parfit · Důvody a osoby · John Locke',
  [roomNoteBodyKey('teleporter')]: 'Derek Parfit postavil případ teleportu, aby narušil velmi starý předpoklad: že osobní identita je hluboký další fakt — niť podobná duši, která buď přežije, nebo ne. Skener vás zničí a vytiskne dokonalou repliku; replika si pamatuje vstup a cítí se bezešvě. Zemřeli jste? Parfitova skandální odpověď: ta otázka je prázdná. Všechno, na čem záleží — psychologická kontinuita, paměť, záměr, charakter — je zachováno; ta „navíc“ věc, o jejíž přežití se bojíte, tam od počátku nikdy nebyla. Identita, tvrdil, není to, na čem záleží; záleží na kontinuitě a propojenosti. Jeho případ větvící se linky (vytisknout kopii bez zničení originálu) obnaží ránu: dva kandidáti, symetrické nároky, žádný možný rozhodčí. Parfit uváděl, že přijmout to za své mu smrt připadala méně zlá — změna míry, ne přetržení metafyzické nitě. Jestli vás to utěší, nebo vás to vyprázdní, obvykle záleží na tom, na které straně kabiny právě stojíte.',
});

// ---------- Act III: The Editor ----------
registerAll('v2', 'cs', {
  [roomBeatKey('editor', 0, 0)]: 'Pracovna, osvětlená lampou, ten druh ticha, který má v sobě nábytek. Na stole: jediná hnědá složka s vaším jménem — tím skutečným, které si teď nedokážete vybavit, a které složka taktně drží obrácené lícem dolů.',
  [roomBeatKey('editor', 0, 1)]: 'Uvnitř složky je vaše nejhorší vzpomínka. Místnost vám nemusí říkat, která to je. Vaše tělo už to řeklo samo: nejdřív ramena, pak žaludek, pak počasí ve tváři.',
  [roomBeatKey('editor', 0, 2)]: 'Vedle složky leží červené pero. Návod je vyrytý přímo na peru, drobným písmem: JEDEN TAH JI ODSTRANÍ. TA UDÁLOST SE PŘESTO STANE. VY U NÍ PROSTĚ NIKDY NEBUDETE.',
  [roomBeatKey('editor', 0, 3)]: 'Uvaděč: Tentokrát žádný trik. Pero funguje přesně tak, jak je popsáno — žádná skrytá doložka, žádné ironické žihadlo. Jediná cena je ta vytištěná na krabičce: vy, mínus tohle. Vezměte si tolik času, kolik potřebujete. Lampa je trpělivá. A pro jednou i já.',
  [roomChoiceTextKey('editor', 'strike-it')]: 'Škrtněte to. Nikdo není povinen to nést.',
  [roomChoiceHintKey('editor', 'strike-it')]: 'Čistá amputace.',
  [roomChoiceOutcomeKey('editor', 'strike-it', 0)]: 'Pero je lehké. Čára je krátká. Úleva je okamžitá, obrovská a skutečná — tahle místnost nepodvádí, a tíha se zvedá jako ruka sundaná z hrudi po letech.',
  [roomChoiceOutcomeKey('editor', 'strike-it', 1)]: 'A pak, v následujících chodbách, si všimnete okrajů té díry. Určitý druh smutku cizích lidí, který jste dřív poznali na první pohled — teď je to jen počasí na tváři. Trpělivost, kterou jste měli, tvrdě vydobytou odněkud, teď bez financování. Rána je pryč. Stejně tak to, co ta rána podpírala.',
  [roomChoiceOutcomeKey('editor', 'strike-it', 2)]: 'Uvaděč: Žádný soud. Opravdu. Některá tíha je nosná, a některá je prostě jen tíha, a ani já to zvenčí vždycky nepoznám. Rozhodl jste z jediného místa, které na to mělo výhled.',
  [roomChoiceTextKey('editor', 'keep-it')]: 'Zavřete složku. Nechte si ji. Je vaše.',
  [roomChoiceHintKey('editor', 'keep-it')]: 'Celá loď, i s hnilobou.',
  [roomChoiceOutcomeKey('editor', 'keep-it', 0)]: 'Zavřete složku a přesunete ji zpátky přes stůl, a místnost to přijme s něčím jako úcta. Tíha se usadí zpátky tam, kde vždycky seděla. Není lehčí. To nikdy nebylo v nabídce.',
  [roomChoiceOutcomeKey('editor', 'keep-it', 1)]: 'Ale něco se nepatrně změnilo: teď jste si to zvolili. Ta vzpomínka bývala něčím, co se vám stalo. Od dnešního večera je to něco, co nesete úmyslně — stejný kámen, jiný úchop.',
  [roomChoiceOutcomeKey('editor', 'keep-it', 2)]: 'Uvaděč: Pro záznam — to je rozdíl mezi jizvou a ránou. Stejná tkáň. Jedna z nich už není psána někým jiným.',
  [roomChoiceTextKey('editor', 'read-first')]: 'Otevřete složku. Přečtěte si ji — celou, pořádně — než se rozhodnete.',
  [roomChoiceHintKey('editor', 'read-first')]: 'Postavte se tomu čelem, pak si vyberte.',
  [roomChoiceOutcomeKey('editor', 'read-first', 0)]: 'Otevřete složku. Číst ji je přesně tak zlé, jak jste se báli, a mírně jiné, než jste si pamatovali — vzpomínka se, jak se ukazuje, sama léta cenzurovala, obrušovala nejhorší hranu, brousila jinou. Dokument je nezkrácená verze. Dočtete až do konce. Nevěděli jste, že to dokážete.',
  [roomChoiceOutcomeKey('editor', 'read-first', 1)]: 'A poté, co jste to přečetli, pero vypadá jinak. Menší. Vzpomínka je pořád strašná, ale teď je strašná a dosvědčená — jediným svědkem, jehož výpověď nikdy neztratíte. Necháte to ve složce, neškrtnuté. Ne proto, že to nebolí. Ale protože je to pravda, a vy jste tam byli, a někdo tam být měl.',
  [roomChoiceOutcomeKey('editor', 'read-first', 2)]: 'Uvaděč: (potichu) To je ta nejvzácnější volba. Většina poutníků volí mezi nesením a vyříznutím. Skoro nikoho nenapadne to konečně přečíst. Pero leží na tomhle stole velmi dlouho. Ta židle, na kterou jste právě usedli, byla vždycky tím skutečným nástrojem.',
  [roomNoteTitleKey('editor')]: 'Rána a účetní kniha',
  [roomNoteThinkersKey('editor')]: 'Nietzsche, amor fati · rekonsolidace paměti · Kierkegaard',
  [roomNoteBodyKey('editor')]: 'Nietzscheho vzorec pro velikost byl amor fati — milovat svůj osud, nechtít, aby bylo cokoli jinak, „nejen snášet nutné, natožpak je skrývat… ale milovat je.“ Ne proto, že utrpení je dobré, ale protože já, které utrpení posuzuje, bylo utrpením vybudováno: škrtněte nejhorší kapitolu a čtenář se změní také. Moderní věda o paměti dává tomuto myšlenkovému experimentu zuby — výzkum rekonsolidace ukazuje, že vzpomínky se přepisují pokaždé, když jsou vybavovány, a léky, které tlumí citový náboj vzpomínky, už existují. Ta otázka už není sci-fi: kdybyste mohli žal obrousit, měli byste to udělat? Argument pro pero je skutečný; nikdo není morálně povinen krvácet kvůli rozvoji charakteru. Argument proti je tišší: bolest se často ukáže jako nosná — zdroj konkrétní empatie, konkrétní trpělivosti, konkrétního odmítnutí nechat druhé trpět bez svědků. Kierkegaard řekl, že život se žije vpřed, ale rozumí se mu nazpět. Složka je ta zpětná část. Editoři, buďte s ní opatrní.',
});

// ---------- Act III: The Introduction ----------
registerAll('v2', 'cs', {
  [roomBeatKey('introduction', 0, 0)]: 'Nejmenší místnost v celém zařízení. Žádný nábytek, žádná zrcadlová podlaha, žádné stroje — jen proporce tak přesné, že to působí, jako by vás poslouchaly.',
  [roomBeatKey('introduction', 0, 1)]: 'Místnost promluví. Její hlas je zdvořilý a bez umístění.',
  [roomBeatKey('introduction', 0, 2)]: 'MÍSTNOST: Vítejte. Bude to krátké, nebo to bude nejdelší místnost vašeho života; ta část je na vás. Jen jedna otázka. Kdo jste?',
  [roomBeatKey('introduction', 0, 3)]: 'Otevřete ústa — a s malou závratí si všimnete, kolik odpovědí už stojí v řadě, a jak každá z nich má na krku visačku.',
  [roomBeatKey('introduction', 1, 0)]: 'MÍSTNOST: Teď jsme odstranili jméno, role i příběh. Tady se poutníci obvykle buď rozzlobí, nebo velmi ztiší. Obojí je pokrok.',
  [roomBeatKey('introduction', 1, 1)]: 'MÍSTNOST: Zeptám se ještě jednou, a chci, abyste si všimli, co vám ještě zbývá k odpovědi. Kdo jste?',
  [roomChoiceTextKey('introduction', 'give-name')]: 'Řekněte své jméno — nebo se po něm aspoň natáhněte.',
  [roomChoiceHintKey('introduction', 'give-name')]: 'Začněte štítkem.',
  [roomChoiceOutcomeKey('introduction', 'give-name', 0)]: 'MÍSTNOST: To je jméno. Zvuk, který vaši rodiče zvolili dřív, než vás poznali, připojený papírováním a opakováním. Kdybyste ho zítra změnili, zůstali byste — což znamená, že to nikdy nebyli vy. Je to úchyt. Ptala jsem se na hrnek.',
  [roomChoiceOutcomeKey('introduction', 'give-name', 1)]: 'Místnost to říká bez krutosti, tak jako se vrací kabát, který není váš.',
  [roomChoiceTextKey('introduction', 'give-role')]: 'Odpovězte tím, co děláte — vaší prací, vaším místem, vašimi lidmi.',
  [roomChoiceHintKey('introduction', 'give-role')]: 'Jste to, čemu věnujete své dny. Jistě.',
  [roomChoiceOutcomeKey('introduction', 'give-role', 0)]: 'MÍSTNOST: To jsou role. Pozice v systémech jiných lidí — zaměstnavatel, rodina, národ. Každá z nich existovala dřív, než jste ji zaplnili, a bude znovu zaplněna potom. Popisovali jste přihrádky. Ptala jsem se, co se do nich nalévá.',
  [roomChoiceOutcomeKey('introduction', 'give-role', 1)]: 'MÍSTNOST: (jemně) Popisy jsou to, co se rozpustilo, poutníku. Proto jste tady. Kdo je nosí?',
  [roomChoiceTextKey('introduction', 'give-story')]: 'Vyprávějte jí svůj příběh — co se vám stalo, co jste přežili, co milujete.',
  [roomChoiceHintKey('introduction', 'give-story')]: 'Narativní já, v plné míře.',
  [roomChoiceOutcomeKey('introduction', 'give-story', 0)]: 'Místnost naslouchá celému příběhu. Je to dobrý posluchač; přistihnete se, jak jí říkáte věci, na které se chodby nikdy neptaly.',
  [roomChoiceOutcomeKey('introduction', 'give-story', 1)]: 'MÍSTNOST: To je příběh. Krásný, a pravdivý, a — všimněte si — vyprávěný v minulém čase někým, kdo stojí mimo něj. Příběh vyžaduje vypravěče. Ptala jsem se na vypravěče. Každá věta, kterou jste právě řekli, byla důkazem, že nejste žádnou z těch vět.',
  [roomChoiceTextKey('introduction', 'insist')]: '„Ne — JÁ JSEM svůj příběh. Vezměte mi příběh a nezůstane nikdo, koho by se dalo ptát.“',
  [roomChoiceHintKey('introduction', 'insist')]: 'Obhajte narativní já.',
  [roomChoiceOutcomeKey('introduction', 'insist', 0)]: 'MÍSTNOST: Obhajitelná škola. Já jako svůj vlastní životopis — žádná perla uprostřed, jen náhrdelník. Mnoho pečlivých myslitelů žilo a zemřelo na této pozici, a nebudu předstírat, že jsem ji vyvrátila.',
  [roomChoiceOutcomeKey('introduction', 'insist', 1)]: 'MÍSTNOST: Ale dovolte jedno pozorování, než půjdete dál: právě teď, když jsem ohrozila váš příběh, někdo sebou trhl. Zeptejte se, až budete mít čas, kdo to byl. Dveře jsou za vámi. Nikdy nebyly zamčené. Dveře tady bývají zamčené jen zřídka; poutníci si je zamykají sami.',
  [roomChoiceTextKey('introduction', 'admit')]: '„Nevím. Nezbylo nic vyslovitelného. Ať jsem kdokoli, jsem to, co tu zůstává po tom všem — a to nemá jméno.“',
  [roomChoiceHintKey('introduction', 'admit')]: 'Řekněte to nevyslovitelné.',
  [roomChoiceOutcomeKey('introduction', 'admit', 0)]: 'Místnost je dlouhou chvíli zticha — ne ticho nepřítomnosti, ale ticho něčeho, co se klaní.',
  [roomChoiceOutcomeKey('introduction', 'admit', 1)]: 'MÍSTNOST: Správně. Ne jako odpověď — žádná odpověď neexistuje — ale jako upřímnost. To, co zůstává, když je odstraněn každý popis, není nic; je to ten, kdo odstraňuje. Nelze to najít hledáním, protože je to samo hledání. Tuhle myšlenku neudržíte dlouho; nikdo ji neudrží; to není selhání, to je povaha té myšlenky.',
  [roomChoiceOutcomeKey('introduction', 'admit', 2)]: 'MÍSTNOST: Přišli jste sem rozpuštění a vyděšení z toho. Všimněte si: rozpustil se jen obal. Jděte v klidu. Jste nejméně ztracený poutník, který tudy prošel už za dlouhou dobu.',
  [roomChoiceTextKey('introduction', 'stay-silent')]: 'Neříkejte vůbec nic. Stůjte v té otázce.',
  [roomChoiceHintKey('introduction', 'stay-silent')]: 'Nechte odpovědět ticho.',
  [roomChoiceOutcomeKey('introduction', 'stay-silent', 0)]: 'Stojíte v místnosti a neodpovídáte, a to neodpovídání není úhybný manévr — místnost pozná rozdíl; slyšela už každý druh ticha, jaký existuje.',
  [roomChoiceOutcomeKey('introduction', 'stay-silent', 1)]: 'MÍSTNOST: (po chvíli, vřele) Ano. I to je způsob, jak to říct — možná jediná gramatika, do které se ta odpověď vejde. Otázka „kdo jste“ nikdy nepostrádala informaci. Byla to pozvánka přestat sahat po visačkách. Přestali jste. Málokdo to dokáže.',
  [roomChoiceOutcomeKey('introduction', 'stay-silent', 2)]: 'Dveře se otevřou samy od sebe, což je v tomhle zařízení nejvyšší poklona, jaká je kdy zaznamenaná.',
  [roomNoteTitleKey('introduction')]: 'Nenalezitelné já',
  [roomNoteThinkersKey('introduction')]: 'Hume · anattá (buddhistické ne-já) · apofatická tradice',
  [roomNoteBodyKey('introduction')]: 'David Hume šel hledat své já a zaznamenal slavný nulový výsledek: kdykoli introspektoval, nacházel jen konkrétní vjemy — teplo, chlad, lásku, hněv — nikdy toho, kdo vnímá. Jeho závěr: já je svazek zkušeností, a „vlastník“ je jen zvyk gramatiky. O dvaadvacet století dříve učil Buddha anattá: prohledejte tělo, pocity, vjemy, popudy a vědomí, a žádné z nich se nekvalifikuje jako trvalé já, které předpokládáme; sám ten předpoklad je kořenem konkrétního utrpení. Apofatická tradice — od upanišadského neti neti („ne toto, ne toto“) až po Mistra Eckharta — proměnila to selhání v metodu: odstraňte každý popis, a to, co zůstane, není nic, ale nepojmenovatelný svědek, který to odstraňování provádí. Tahle místnost neměla řešení, protože „kdo jste?“ není otázka s chybějícími daty. Každá vyslovitelná odpověď je popis, a popisy se mají, nikoli se jimi je. Vždycky projdete. Ponaučení je to, co zbývá.',
});

// ---------- Act III: The Debt of the Dead ----------
registerAll('v2', 'cs', {
  [roomBeatKey('debt-of-dead', 0, 0)]: 'Postel nemocného. Místnost to zařídila s hroznou přesností — vůně nemocnice snažící se vonět jako levandule, okno s večerem v něm, židle postavená pro vás, jako byste potvrdili účast.',
  [roomBeatKey('debt-of-dead', 0, 1)]: 'V posteli leží ten, kdo vám ublížil. Místnost nechala jeho tvář lehce rozmazanou, protože to není jedna osoba — je to ten, koho právě pojmenovala vaše hruď. To bezpráví bylo skutečné. Tohle místo se nezabývá nedorozuměními; to, co udělali, udělali, a to formovalo půdorys vašeho života.',
  [roomBeatKey('debt-of-dead', 0, 2)]: 'Umírají. Doopravdy, a už brzy — přístroje přešly od naléhavosti ke zdvořilosti. A jsou vzhůru, a poznávají vás, a ptají se hlasem, ve kterém už skoro nic nezbylo: „Dokážeš mi odpustit?“',
  [roomBeatKey('debt-of-dead', 0, 3)]: 'Myslí to vážně. To je ta jediná krutost téhle místnosti: vidíte, že to myslí vážně, a že to, že to myslí vážně, nic nemění na tom, co bylo spácháno. Obě fakta, plně osvětlená, u téže postele.',
  [roomChoiceTextKey('debt-of-dead', 'forgive')]: '„Ano. Odpouštím ti.“ Řekněte to, a myslete to vážně, jak jen dokážete.',
  [roomChoiceHintKey('debt-of-dead', 'forgive')]: 'Zrušte dluh — ať už osvobodí kohokoli.',
  [roomChoiceOutcomeKey('debt-of-dead', 'forgive', 0)]: 'Řeknete to. Ta slova stojí víc, než jste čekali, a jakmile jsou venku, váží míň — jako byste drželi kámen proti proudu a konečně otevřeli dlaň, a zjistili, že proud držel i vás.',
  [roomChoiceOutcomeKey('debt-of-dead', 'forgive', 1)]: 'Jejich tvář udělá to, co tváře dělají, když se poslední účet života nečekaně vyrovná. Neřeknou děkuji. Řeknou vaše jméno — správně, jemně — a něco v účetní knize mezi vámi, co se nikdy nemělo vyrovnat, se místo toho prostě uzavře.',
  [roomChoiceOutcomeKey('debt-of-dead', 'forgive', 2)]: 'Odpuštění neučinilo to, co udělali, přijatelným. Učinilo to ukončeným. Strávíte roky učením se, že to jsou různá slova, a dnešní večer byl první lekcí.',
  [roomChoiceTextKey('debt-of-dead', 'refuse')]: '„Ne. Jsem tady — to je to, co mám. Odpuštění není.“',
  [roomChoiceHintKey('debt-of-dead', 'refuse')]: 'Upřímnost nad rozhřešením.',
  [roomChoiceOutcomeKey('debt-of-dead', 'refuse', 0)]: 'Řeknete ne. Řeknete to bez zloby — to je ta část, co stojí — a zůstanete v křesle, které říká to, co ne nedokáže: že vám záleželi natolik, aby ta rána byla skutečná, a rána je skutečná natolik, že její majitel ji nepodepíše pryč jen pro pohodlí smrtelné postele.',
  [roomChoiceOutcomeKey('debt-of-dead', 'refuse', 1)]: 'Přijmou to. Někde pod zdvořilostí přístrojů vidíte něco skoro jako úctu: položili poctivou otázku na konci svého života a dostali poctivou odpověď, což je víc, než čím jsou vybaveny většiny konců.',
  [roomChoiceOutcomeKey('debt-of-dead', 'refuse', 2)]: 'Udrželi jste linii, a přesto jste zůstali. Některé dluhy je lepší poctivě zaznamenat, než falešně vyrovnat, a i ten záznam je svým způsobem poctou — důkazem, že se to, co se stalo, opravdu stalo někomu, kdo tam opravdu byl.',
  [roomChoiceTextKey('debt-of-dead', 'forgive-silently')]: 'Odpusťte jim — ve své hrudi, plně — a řekněte jen: „Teď už odpočívej.“',
  [roomChoiceHintKey('debt-of-dead', 'forgive-silently')]: 'Zrušte dluh, aniž byste jim předali účtenku.',
  [roomChoiceOutcomeKey('debt-of-dead', 'forgive-silently', 0)]: 'Uvnitř otevřete dlaň. Kámen odchází. Cítíte, jak odchází — je to skutečné, to uvolnění, stejně skutečné jako jakákoli vyslovená verze.',
  [roomChoiceOutcomeKey('debt-of-dead', 'forgive-silently', 1)]: 'Nahlas řeknete jen: „Teď už odpočívej,“ a jejich oči hledají ve vaší tváři verdikt, a najdou laskavost tam, kde měl být verdikt, a tu budou svoje poslední hodiny číst oběma směry.',
  [roomChoiceOutcomeKey('debt-of-dead', 'forgive-silently', 2)]: 'Podrželi jste si odpuštění a odepřeli rozhřešení — osvobodili jste sebe, aniž byste odemkli jejich dveře. Všimněte si, bez soudu, že tohle byla ta jediná možnost, kde milost zůstala celá na vaší straně postele. Možná to byla moudrost. Možná to byla poslední malá splátka dluhu, přece jen zaplacená v jejich měně.',
  [roomChoiceTextKey('debt-of-dead', 'ask-question')]: '„Nejdřív — proč? Řekni mi o tom pravdu. Pak odpovím.“',
  [roomChoiceHintKey('debt-of-dead', 'ask-question')]: 'Otázka, kterou jste se nikdy nedostali ptát.',
  [roomChoiceOutcomeKey('debt-of-dead', 'ask-question', 0)]: 'Zeptáte se na otázku, která stála ve všech dveřích vašeho života, a umírající, kteří už nemají žádné využití pro svou obranu, odpoví.',
  [roomChoiceOutcomeKey('debt-of-dead', 'ask-question', 1)]: 'Odpověď je menší než rána. Vždycky je. Ne zloba na trůnu — vystrašený člověk, slabá chvíle, která zmetastázovala, důvody, za které by se stydělo i dítě. Čekali jste architekturu krutosti a dostali jste pokrčení rameny, které vám zlomilo život. To zklamání je svým způsobem podivný lék: nic tak malého si nezaslouží trůn, který ve vás obsadilo.',
  [roomChoiceOutcomeKey('debt-of-dead', 'ask-question', 2)]: 'To, co řeknete potom — ano, nebo ne, nebo teď už odpočívej — záleží méně, než jste si mysleli. Ta otázka byla ta návštěva. Odpoví, a oba víte, že účet byl konečně prověřen, jedinými dvěma lidmi, kteří ho kdy vedli.',
  [roomNoteTitleKey('debt-of-dead')]: 'Odpuštění a účetní kniha',
  [roomNoteThinkersKey('debt-of-dead')]: 'biskup Butler · Hannah Arendtová · Jacques Derrida',
  [roomNoteBodyKey('debt-of-dead')]: 'Biskup Butler definoval odpuštění jako odřeknutí se zášti — nikoli omlouvání, nikoli zapomínání, nikoli usmíření, ale odmítnutí dál platit úroky z rány. Hannah Arendtová nazvala odpuštění jediným skutečným únikem z nevratnosti minulosti: bez něj zůstáváme navždy obětí jednoho činu, a viník navždy jeho autorem; odpuštění osvobozuje obě strany ze zamrzlého rámce. Ale Derrida viděl paradox u postele umírajícího: odpuštění hodné toho jména odpouští neodpustitelné — cokoli menšího je pouhé účetnictví, promíjení dluhů, které si už stejně můžeme dovolit. A smrtelná postel zostří každou hranu: upřímná omluva mění viníka, ne to bezpráví; o vaše odpuštění je žádáno přesně v okamžiku, kdy je jeho odmítnutí kruté a jeho udělení může působit vynuceně. V tom křesle neexistovala žádná správná odpověď. Odpuštění, poctivé odmítnutí, tiché uvolnění a položení nepoložené otázky jsou čtyři různé způsoby, jak brát ránu vážně — což byl, možná, jediný dluh, který jste opravdu měli splatit vy sami.',
});

// ---------- Act III: The Free Will Waiting Room ----------
registerAll('v2', 'cs', {
  [roomBeatKey('free-will', 0, 0)]: 'Znovu čekárna — uzavírá kruh s tou první, ale tahle má podél zdi řadu velkých přátelských tlačítek: modré, červené, zelené a jedno bez popisku.',
  [roomBeatKey('free-will', 0, 1)]: 'Nad tlačítky obrazovka. Na obrazovce sázková tabule. Uvaděč stojí vedle ní se sázkařským stínítkem a výrazem nesnesitelného klidu.',
  [roomBeatKey('free-will', 0, 2)]: 'Uvaděč: Jednoduchá hra. Zmáčkněte kterékoli tlačítko, kdykoli chcete, zcela z vlastní svobodné vůle. Já jsem už předem napsal, které zmáčknete. Nikdy jsem neprohrál. Omluvil bych se za to, ale stejně jste mě vždycky měli slyšet, jak to říkám.',
  [roomBeatKey('free-will', 0, 3)]: 'Natáhnete ruku — jen abyste to otestovali — a MODRÉ tlačítko se rozsvítí, teple, celou vteřinu předtím, než se vaše ruka zaváže. Ještě jste se nerozhodli. Byli byste ochotni odpřísáhnout, že jste se ještě nerozhodli.',
  [roomBeatKey('free-will', 0, 4)]: 'Uvaděč: (čte tabuli) „Modré, nejdřív — aby to otestoval.“ Teď se na chvíli budete cítit vzpurně a zvážíte to červené. Klidně si na to dejte čas. Tabule už ho má.',
  [roomChoiceTextKey('free-will', 'press-red')]: 'Zmáčkněte ČERVENÉ — právě proto, že tabule říká, že to neuděláte. Přetrumfněte tabuli ve vzpouře.',
  [roomChoiceHintKey('free-will', 'press-red')]: 'Rozbijte tu předpověď silou.',
  [roomChoiceOutcomeKey('free-will', 'press-red', 0)]: 'Praštíte do červeného. Zazvoní zvonek. Tabule, rozvinutá o řádek dál, hlásá: „Červené, vzdorovitě, s vírou, že tohle něco vyvrací.“',
  [roomChoiceOutcomeKey('free-will', 'press-red', 1)]: 'Uvaděč: Vzpoura byla v předpovědi, poutníku — je to to nejpředvídatelnější počasí, jaké máte. Zdá se, že každý deterministický systém provozuje trochu vlastního vzdoru; právě to mu dovoluje cítit se jako výjimka. Nestyďte se. Červené tlačítko se v této místnosti mačká víc než jakékoli jiné. Jste v dobré společnosti.',
  [roomChoiceTextKey('free-will', 'dont-press')]: 'Nemačkejte nic. Založte si ruce. Odmítněte celou tu hru.',
  [roomChoiceHintKey('free-will', 'dont-press')]: 'Nemůžete předpovědět to, co se nikdy nestane.',
  [roomChoiceOutcomeKey('free-will', 'dont-press', 0)]: 'Založíte si ruce. Ubíhají minuty. Místnost je v minutách velmi dobrá.',
  [roomChoiceOutcomeKey('free-will', 'dont-press', 1)]: 'Uvaděč: (otočí tabuli; celou dobu na ní stálo „pokusí se nemačkat — odhadovaná doba trvání, čtyři minuty“) Zdržení se je taky tah. Tabule počítá s celým prostorem možností, včetně pýchy stát mimo něj. Čtyři minuty, skoro přesně. Většina poutníků praskne po dvou.',
  [roomChoiceTextKey('free-will', 'press-knowing')]: 'Zmáčkněte MODRÉ — to předpovězené — pomalu, rozvážně, úmyslně. „Vždycky se to mělo stát, A JÁ si to volím.“',
  [roomChoiceHintKey('free-will', 'press-knowing')]: 'Přestaňte bojovat s předpovědí. Přivlastněte si to počasí.',
  [roomChoiceOutcomeKey('free-will', 'press-knowing', 0)]: 'Zmáčknete modré — přesně to tlačítko, které tabule jmenovala — ne v rezignaci, ale s rozvahou podpisu. Zazvoní zvonek. Tentokrát to zní míň jako skórování a víc jako souhlas.',
  [roomChoiceOutcomeKey('free-will', 'press-knowing', 1)]: 'Uvaděč: Tady to je. Cesta ven nikdy nebyla porazit tabuli. Je to všimnout si, že „bylo to určeno“ a „zvolil jsem si to“ mohou být dva popisy téže události — předpověď a počasí, hádající se, kdo z nich způsobil déšť. Vaše volba je součástí toho soukolí. Soukolí běží skrz volbu, ne kolem ní.',
  [roomChoiceOutcomeKey('free-will', 'press-knowing', 2)]: 'Uvaděč: Technicky jsem pořád vyhrál. Ale jste první dnes, kdo způsobil, že to vítězství připadá vedlejší, což je nejblíž porážce, jakou si mohu dovolit. Dveře jsou otevřené. Vždycky měly být.',
  [roomChoiceTextKey('free-will', 'press-unlabeled')]: 'Zmáčkněte to bez popisku. Ať je to cokoli, není to na jídelním lístku.',
  [roomChoiceHintKey('free-will', 'press-unlabeled')]: 'Tlačítko, které nikdo nevysvětlí.',
  [roomChoiceOutcomeKey('free-will', 'press-unlabeled', 0)]: 'Zmáčknete tlačítko bez popisku. Někde hluboko v zařízení se začne vařit konvice.',
  [roomChoiceOutcomeKey('free-will', 'press-unlabeled', 1)]: 'Uvaděč: To je tlačítko na čaj. Je to napsáno na tabuli taky: „zvolí si záhadu před smyslem; pije s mlékem.“ Ta možnost bez popisku působí nejsvobodněji, že? Všimněte si ale, že jídelní lístek s vytištěným „nic z výše uvedeného“ je pořád jídelní lístek. Napijte se. Vy jste si to zvolili, a vždycky to mělo přijít, a je to docela dobrý čaj. Všechny tři věci platí zároveň. To je celé ponaučení, a levnější než seminář.',
  [roomNoteTitleKey('free-will')]: 'Svobodná vůle a předpověď',
  [roomNoteThinkersKey('free-will')]: 'Benjamin Libet · determinismus · kompatibilismus — Hume, Frankfurt, Dennett',
  [roomNoteBodyKey('free-will')]: 'V osmdesátých letech zjistil Benjamin Libet, že v mozku se objevuje takzvaný readiness potential (potenciál připravenosti) měřitelnou chvíli předtím, než subjekty ohlásí rozhodnutí pohnout se — tlačítko se, zdá se, rozsvítí dřív, než ho „vy“ zmáčknete. Titulky svobodnou vůli pohřbily; drobný tisk byl jemnější (sám Libet poznamenal, že existuje jakési okno veta, a pozdější výzkum zpochybňuje, co ten potenciál připravenosti vlastně měří). Ale hlubší otázka předchází elektrodám: pokud má každá událost příčiny, vaše volby nevyjímaje, v jakém smyslu jsou vaše? Tvrdý determinismus říká: v žádném. Libertariánská svobodná vůle říká, že řetězec příčin se ve vás nějak přerušuje. Kompatibilismus, pracovní filosofie většiny dnešních filosofů, ten spor rozpouští: svoboda nikdy nevyžadovala výjimku z příčinnosti; znamená jednat z vlastního uvažování, nenuceně — soukolí běžící skrz vaši volbu, ne kolem ní. „Mohl jsem jednat jinak?“ možná záleží méně než „byl jsem to já, kdo to udělal?“ Vždycky jste si měli přečíst tuhle poznámku. Taky jste si to právě zvolili. Obě věty, jeden šálek.',
});
