// Czech translation of the v2 room prose for Act II (beats, choice text/hint/
// outcome, field notes). Registered under version 'v2'. Rooms: junction,
// experience-machine, ship, casino-pascal, omelas, chinese-room,
// newcomb-annex, veil-of-ignorance, court-of-usher.
import { registerAll } from './resolver';
import {
  roomBeatKey,
  roomChoiceHintKey,
  roomChoiceOutcomeKey,
  roomChoiceTextKey,
  roomNoteBodyKey,
  roomNoteThinkersKey,
  roomNoteTitleKey,
} from './keys';

// ---------- Act II: The Junction ----------
registerAll('v2', 'cs', {
  [roomBeatKey('junction', 0, 0)]: 'Obrovská temná hala nebeského soukolí — ozubená kola velikosti měsíců, dopravníkové pásy nesoucí malé lhostejné hvězdy. Jejím středem vedou koleje.',
  [roomBeatKey('junction', 0, 1)]: 'Blíží se tramvaj. Je natřená úřední žlutí a nezpomaluje, protože zpomalování není náplní její práce.',
  [roomBeatKey('junction', 0, 2)]: 'Na hlavní koleji: pět figurín, přivázaných něčím, co vypadá jako červená páska. Doslovná byrokratická páska. Na vedlejší koleji: jedna figurína, stejně tak. Figuríny křičí. Ten křik nepůsobí přesvědčivě.',
  [roomBeatKey('junction', 0, 3)]: 'Uvaděč: Scénář je standardní. Neuděláte nic, a padne pět. Zatáhnete, a tramvaj se odkloní — a vezme si místo toho toho jednoho. Mám za povinnost vás požádat, abyste to nepřemýšleli. Mám také za povinnost vědět, že to stejně uděláte.',
  [roomBeatKey('junction', 1, 0)]: 'Hala se přeskupuje se zvukem obrovského zakládání spisů. Teď stojíte na lávce nad kolejí. Tramvaj — resetovaná, nelítostná — se blíží znovu, k pěti novým figurínám.',
  [roomBeatKey('junction', 1, 1)]: 'Vedle vás na lávce stojí jedna obrovská figurína, dost těžká — místnost vám to dává najevo s neomalenou jasností — aby zastavila tramvaj, kdyby náhodou spadla. Kdyby ji, řekněme, někdo strčil.',
  [roomBeatKey('junction', 1, 2)]: 'Uvaděč: Aritmetika je stejná jako předtím. Pět za jednoho. Změnilo se jen rozhraní — tentokrát žádná páka. Jen vaše ruce, a tělo, které má vlastní názor na to, k čemu ruce slouží.',
  [roomChoiceTextKey('junction', 'pull')]: 'Zatáhněte za páku. Jeden místo pěti.',
  [roomChoiceHintKey('junction', 'pull')]: 'Ta aritmetika.',
  [roomChoiceOutcomeKey('junction', 'pull', 0)]: 'Páka se pohne s byrokratickým cvaknutím, jako by razítkovala formulář. Tramvaj se stočí na vedlejší kolej a udělá, co tramvaje dělají. Pět figurín teatrálně ztichne úlevou; jedna ztichne jinak.',
  [roomChoiceOutcomeKey('junction', 'pull', 1)]: 'Uvaděč: Čtyři životy, čistý zisk — proti jednomu čistému svědomí, hrubý. Většina lidí zatáhne. Pomáhá, že je to páka. Páka připadá jako papírování; tělo ne.',
  [roomChoiceTextKey('junction', 'no-pull')]: 'Nesahejte na to. Nestanete se autorem té smrti.',
  [roomChoiceHintKey('junction', 'no-pull')]: 'Na ruce záleží.',
  [roomChoiceOutcomeKey('junction', 'no-pull', 0)]: 'Ustoupíte od páky. Tramvaj pokračuje po koleji, po které jela vždycky, a hala je na chvíli velmi hlučná a pak velmi tichá.',
  [roomChoiceOutcomeKey('junction', 'no-pull', 1)]: 'Uvaděč: Pět mrtvých, a žádný z nich váš — to je ta teorie. Autorem byla tramvaj; vy jste odmítl to spolupodepsat. Celé obory se přou, jestli je ten rozdíl hlubokým morálním faktem, nebo pračkou na svědomí. Navzájem si nečtou práce.',
  [roomChoiceTextKey('junction', 'push')]: 'Strčte do ní. Pět za jednoho — stejný obchod jako s pákou.',
  [roomChoiceHintKey('junction', 'push')]: 'Důslednost, rukama.',
  [roomChoiceOutcomeKey('junction', 'push', 0)]: 'Není to vůbec jako s pákou. To je to zjištění. Tramvaj zastaví; pět figurín je zachráněno; vaše ruce podávají formální stížnost, která zůstane neuzavřená navždy.',
  [roomChoiceTextKey('junction', 'no-push')]: 'Ne. Strčit do člověka není totéž jako zatáhnout za páku.',
  [roomChoiceHintKey('junction', 'no-push')]: 'Některé prostředky nikdy nejsou jen prostředky.',
  [roomChoiceOutcomeKey('junction', 'no-push', 0)]: 'Vaše ruce zůstávají na zábradlí. Tramvaj projíždí dole a dělá to nejhorší, co úřední tramvaje dělají, a obrovská figurína vedle vás pokračuje ve své obrovské existenci, nevědoma celého semináře, který se právě konal o jejím těle.',
  [roomChoiceTextKey('junction', 'refuse-late')]: '„Tohle dělat nebudu. Je to groteskní.“',
  [roomChoiceHintKey('junction', 'refuse-late')]: 'Odmítnout — jednou je to dovoleno.',
  [roomChoiceOutcomeKey('junction', 'refuse-late', 0)]: 'Uvaděč: Zaznamenáno. Na lávce to slýchám často — blízkost má svůj vlastní pach. Jedno odmítnutí je zamyšlení. Druhé by už byla zásada. Volte podle toho, později.',
  [roomChoiceOutcomeKey('junction', 'refuse-late', 1)]: 'Tramvaj dokončí svou práci bez vašeho podpisu. Zda to zakládá nevinu, zůstává záměrně ponecháno jako cvičení.',
  [roomChoiceTextKey('junction', 'refuse1')]: '„Tohle je hloupost. Jsou to figuríny.“',
  [roomChoiceHintKey('junction', 'refuse1')]: 'Odmítněte to zadání.',
  [roomChoiceOutcomeKey('junction', 'refuse1', 0)]: 'Uvaděč: Samozřejmě že jsou to figuríny. Vy jste částečně rozpuštěné já ve zpracovatelském zařízení postaveném přesně pro tenhle druh otázky. Všechno tady je náhražka — včetně, v tuto chvíli, vás.',
  [roomChoiceOutcomeKey('junction', 'refuse1', 1)]: 'Uvaděč: Tramvaj se nikdy neptala, jestli jsou figuríny skutečné. Ptala se, co jste zač vy. Odmítnutí otázky na ni stejně odpovídá — jen ne lichotivě. Pět jich je, pro záznam, mrtvých.',
  [roomChoiceTextKey('junction', 'refuse2')]: '„Pořád hloupost. Pořád nehraju.“',
  [roomChoiceHintKey('junction', 'refuse2')]: 'Odmítněte znovu — tohle místo počítá.',
  [roomChoiceOutcomeKey('junction', 'refuse2', 0)]: 'Uvaděč: Tedy podruhé.',
  [roomChoiceOutcomeKey('junction', 'refuse2', 1)]: 'Uvaděč: Místnosti po vás nechtějí, abyste je měl rád. Chtějí, abyste v nich byl přítomen. Každé odmítnutí je malý hlas pro zůstat rozpuštěný — tiché zdržení se od toho, být vůbec někým. To se tady započítává, ať jste to tak mínil, nebo ne.',
  [roomChoiceOutcomeKey('junction', 'refuse2', 2)]: 'Něco ve vaší hrudi ztichne, v hodnotě jednoho srdce. Figuríny, milosrdně, netleskají.',
  [roomNoteTitleKey('junction')]: 'Problém s tramvají',
  [roomNoteThinkersKey('junction')]: 'Philippa Footová · Judith Jarvis Thomsonová · doktrína dvojího účinku',
  [roomNoteBodyKey('junction')]: 'Philippa Footová sestrojila tramvaj v roce 1967, aby prozkoumala, proč se některá zabití zdají dovolená a jiná zakázaná, když je počet obětí stejný. Judith Jarvis Thomsonová přidala lávku, a ta nesnáz se stala daty: většina lidí zatáhne za páku, ale odmítne strčit do muže, ačkoli obojí vyměňuje jeden život za pět. Klasickým vysvětlením je doktrína dvojího účinku — újma předvídaná jako vedlejší účinek (odkloněná tramvaj zabije toho jednoho) je přípustnější než újma použitá jako prostředek (strčené tělo je brzda). Kritici odpovídají, že jde o morální úzkostlivost oblečenou do latiny; obhájci namítají, že morálka lhostejná k rozdílu mezi odvrácením újmy a použitím člověka jako nástroje by povolovala hrůzy. Pokud se dnes večer vaše ruka na páce a vaše ruka na lávce neshodly, reprodukovali jste padesát let recenzované argumentace ve vlastním nervovém systému. Ta asymetrie je buď to nejhlubší ve vás, nebo nejstarší chyba. Nikdo dosud nerozhodl, co z toho.',
});

// ---------- Act II: The Experience Machine ----------
registerAll('v2', 'cs', {
  [roomBeatKey('experience-machine', 0, 0)]: 'Stroj vám nabízí život, který bude působit naprosto skutečně a spolehlivě šťastně, navždy. Jakmile budete uvnitř, nepoznáte, že není skutečný. Vstoupili byste?',
  [roomBeatKey('experience-machine', 0, 1)]: 'Teplý výklenek v chladném soukolí, vystlaný světlem, které si pamatuje léto. Uprostřed: kapsle, otevřená, tvarovaná přesně jako úleva. Mosazná tabulka, nedávno vyleštěná, hlásá: dokonalý život, k nerozeznání od skutečného, zaručeně šťastný. Váš mozek se to nikdy nedozví. To je ta výhoda.',
  [roomBeatKey('experience-machine', 0, 2)]: 'Uvaděč: Tohle je to nejlepší, co nabízíme. Simulace jsou bezchybné — láska, smysl, drobné problémy navržené tak, aby se vyřešily přesně ve chvíli, kdy mají. Nikdo, kdo vstoupil, si nikdy poté nestěžoval.',
  [roomBeatKey('experience-machine', 0, 3)]: 'Uvaděč: Zamyslete se na chvíli, proč je ta poslední věta tou nejděsivější v celém tomto zařízení. Nespěchejte. Kapsle má veškerý čas, který existuje.',
  [roomChoiceTextKey('experience-machine', 'enter')]: 'Vstupte. Štěstí je štěstí; podklad je jen technikálie.',
  [roomChoiceHintKey('experience-machine', 'enter')]: 'Ta záruka.',
  [roomChoiceOutcomeKey('experience-machine', 'enter', 0)]: 'Kapsle se zavře jako laskavé rozhodnutí. A pak — léta. Veranda, kterou vlastníte. Práce, na které záleží a která je dokončena. Někdo se směje vašemu třetímu nejlepšímu vtipu, protože ví, že ty dva lepší teprve přijdou.',
  [roomChoiceOutcomeKey('experience-machine', 'enter', 1)]: 'Je to, v každém měřitelném ohledu, nejlepší úsek existence, jaký jste kdy zažili. Vynoříte se z něj jen proto, že toto zařízení, na rozdíl od maloobchodního modelu, má reklamační řád.',
  [roomChoiceOutcomeKey('experience-machine', 'enter', 2)]: 'Uvaděč: Krásné, že ano. Všimněte si toho času, po kterém jste právě sáhli — „že ano“, minulý čas. Všechno tam uvnitř nakonec skončí v minulém čase. Přesto: teď víte, jak chutná dokonalost. Některým poutníkům to pak objasní všechno ostatní. Jiným to uvízne jako tříska. Uvidíme, čím jste vy.',
  [roomChoiceTextKey('experience-machine', 'refuse')]: 'Odmítněte. Chcete věci dělat, ne o nich snít.',
  [roomChoiceHintKey('experience-machine', 'refuse')]: 'Realita, se všemi chybami, tak jak je.',
  [roomChoiceOutcomeKey('experience-machine', 'refuse', 0)]: 'Ustoupíte. Kapsle se neurazí; dokonalost má vynikající způsoby.',
  [roomChoiceOutcomeKey('experience-machine', 'refuse', 1)]: 'Uvaděč: Zvolil jste realitu, která je právě v tuto chvíli hořící byrokracií metafyzična — před zaručenou blažeností. Buď je pro vás kontakt se skutečným cennější než jakékoli množství dobrého pocitu, nebo prostě nevěříte produktu tak dokonalému. Oba důvody jsou obhajitelné. Jen jeden z nich je filozofie.',
  [roomChoiceTextKey('experience-machine', 'trial')]: '„Pět minut. Jen abych věděl, co odmítám.“',
  [roomChoiceHintKey('experience-machine', 'trial')]: 'Informovaný souhlas, jistě.',
  [roomChoiceOutcomeKey('experience-machine', 'trial', 0)]: 'Pět minut, říkáte. Kapsle, která to už slyšela, mlčí.',
  [roomChoiceOutcomeKey('experience-machine', 'trial', 1)]: 'Uvnitř pět minut trvá dva roky. Dobré roky. Když se víko otevře, vynoříte se se specifickým žalem života, který se nikdy nestal — se steskem po lidech, kteří jsou pořád tam uvnitř, dokonale imaginární bez vás.',
  [roomChoiceOutcomeKey('experience-machine', 'trial', 2)]: 'Uvaděč: Ta zkouška je celý produkt. Nikdo nekupuje stroj napřímo — kupují si dalších pět minut, znovu a znovu, navždy. Jste venku, což vás řadí do vzácnější společnosti, než tušíte. Ten stesk vybledne v mihotání. To mihotání, jak jsem slyšel, nikdy úplně nezmizí.',
  [roomNoteTitleKey('experience-machine')]: 'Stroj zážitků',
  [roomNoteThinkersKey('experience-machine')]: 'Robert Nozick · hedonismus · autenticita',
  [roomNoteBodyKey('experience-machine')]: 'Nozikův myšlenkový experiment z roku 1974 mířil přímo na srdce hédonismu — teorie, že potěšení je jediná věc hodnotná sama o sobě. Kdyby to byla pravda, argumentoval, měli byste se napojit na stroj, který dodává celoživotní, dokonale přesvědčivou blaženost. Většina lidí odmítá, a to odmítnutí jsou ta data. Nozick vyvodil tři důvody: chceme věci dělat, ne jen mít zážitek jejich dělání; chceme být určitým druhem člověka, a tělo plovoucí v nádrži není žádným druhem vůbec; a chceme kontakt se samotnou realitou, neochotni vyměnit skutečný svět za hezčí vykreslení. Stroj se od té doby stal jen méně hypotetickým — každý feed, každá hra, každé scrollování je nízkorozlišovací kapsle, účtovaná v pětiminutových zkouškách. Otázka, kterou klade ta tabulka, nezní „napojili byste se?“ Zní: z kolika procent už napojeni jste, a kdo je vlastně to já, které by to vědělo?',
});

// ---------- Act II: The Ship ----------
registerAll('v2', 'cs', {
  [roomBeatKey('ship', 0, 0)]: 'Dílna, která voní cedrem a anestezií. Na centrálním stole, pod plachtami světla, leží něco, na čem řemeslníci pracují s hroznou jemností.',
  [roomBeatKey('ship', 0, 1)]: 'Jste to vy. Zároveň tu stojíte a přihlížíte, což řemeslníci berou jako normální, což je nějak ta nejhorší část.',
  [roomBeatKey('ship', 0, 2)]: 'Nahrazují vás kousek po kousku — vzpomínka je vysunuta jako zkroucené prkno, nasazena nová; názor obroušen, znovu zavěšen; buňka, zvyk, konkrétní způsob, jakým říkáte „no každopádně“. Každý odstraněný kus je uctivě odnesen do rohu.',
  [roomBeatKey('ship', 0, 3)]: 'V rohu se odstraněné kusy skládají dohromady. Ta sestava má vaše držení těla. Zatímco přihlížíte, získává vaši tvář a kontroluje ji v malém zrcátku, s vaší přesnou skepsí.',
  [roomBeatKey('ship', 0, 5)]: 'Uvaděč: Rutinní údržba. Děje se to každému, nepřetržitě, od narození dál — venku to jen necháváme běžet pomaleji, aby si z toho nikdo nedělal scénu. Tak: až budou oba hotovi, ten udržovaný a ten znovusložený, kdo z nich odejde odsud jako vy?',
  [roomChoiceTextKey('ship', 'original')]: '„Ten na stole. Na kontinuitě záleží — prkno po prkně je pořád jedna loď.“',
  [roomChoiceHintKey('ship', 'original')]: 'Nepřerušené vlákno.',
  [roomChoiceOutcomeKey('ship', 'original', 0)]: 'Uvaděč: Klasický postoj. Postupná výměna zachovává plavidlo; hromada v rohu je prostě uspořádaný šrot. Ten roh, mimochodem, na vás zírá vašima vlastníma očima. Zastává stejný názor o sobě samém.',
  [roomChoiceTextKey('ship', 'pattern')]: '„Ten v rohu. Jsem ten vzorec, ne dřevo — a tohle je to původní dřevo.“',
  [roomChoiceHintKey('ship', 'pattern')]: 'Znovusložené díly.',
  [roomChoiceOutcomeKey('ship', 'pattern', 0)]: 'Uvaděč: Hobbesova stará bolest hlavy. Znovu postavte loď z vyřazených prken, a ta „kontinuální“ začne vypadat jako dobře zdokumentovaný podvodník. Právě jste svému vlastnímu já na stole odhlasovali roli repliky. Slyšelo vás to říkat. Chodba před vámi bude nepříjemná.',
  [roomChoiceTextKey('ship', 'neither')]: '„Ani jedno. Obojí. ‚Já‘ nikdy nebylo něco, co přetrvává — je to příběh, který vyprávějí obě lodě zároveň.“',
  [roomChoiceHintKey('ship', 'neither')]: 'Rozpusťte tu otázku.',
  [roomChoiceOutcomeKey('ship', 'neither', 0)]: 'Dílna ztichne. Oba vy — ten na stole i ten v rohu — se otočíte a podíváte na sebe, na toho třetího, kdo právě vyhlásil neobsazenost.',
  [roomChoiceOutcomeKey('ship', 'neither', 1)]: 'Uvaděč: To je ta nákladná odpověď. Pokud je já příběh, a ne látka, nic se na tom stole neztratilo — ale nic tam také nikdy nebylo v bezpečí. Většina poutníků tuhle myšlenku neudrží dál než za tuhle chodbu. Ti, kteří to dokážou, obvykle odcházejí lehčí. Lehčí není totéž co šťastnější. Obvykle je to lepší.',
  [roomChoiceTextKey('ship', 'panic')]: '„Zastavte ty stroje. Vraťte mě přesně takového, jaký jsem byl.“',
  [roomChoiceHintKey('ship', 'panic')]: 'Vraťte to zpět. Celé.',
  [roomChoiceOutcomeKey('ship', 'panic', 0)]: 'Řemeslníci se zastaví, laskavě, tak jako se zastavují zdravotní sestry. Předák nahlíží do manifestu.',
  [roomChoiceOutcomeKey('ship', 'panic', 1)]: 'Uvaděč: „Přesně takový, jaký jste byl“ — k jakému okamžiku? K dnešnímu ránu? K tomu požáru? K devíti letům? Vy jste tou renovací byl po celou dobu, poutníku; neexistuje žádné tovární nastavení, jen dřívější staveniště. Můžeme tu stát a nic neměnit, jak dlouho budete chtít. Ten, komu se to bude líbit, se bude měnit tak jako tak. Je to jediná funkce, kterou se nám nikdy nepodařilo vypnout.',
  [roomNoteTitleKey('ship')]: 'Théseova loď',
  [roomNoteThinkersKey('ship')]: 'Plútarchos · Hobbes · psychologická kontinuita',
  [roomNoteBodyKey('ship')]: 'Plútarchos vypráví, že Athény udržovaly Théseovu loď při životě tím, že vyměňovaly každé prkno, jakmile shnilo, dokud se filozofové nemohli zeptat, zda je to pořád stejná loď. Hobbes to krutě zaostřil: co kdyby někdo posbíral vyřazená prkna a znovu postavil tu původní — která z nich je teď ta loď? Aplikováno na osoby, hádanka přestává být kuriozitou. Vaše buňky se obměňují; vaše vzpomínky se přepisují při každém vybavení; názory, které dnes hájíte, by vás v devatenácti vyděsily. Pokud identita stojí na kontinuitě, jste ten stůl: pořád tentýž, postupně. Pokud stojí na složení nebo vzorci, ten roh má své argumenty. Moderní odpověď — od Locka po Parfita — je psychologická kontinuita: jste řetězec překrývajících se vzpomínek a záměrů, ať vede kamkoli. Ale nejhlubší odpovědí možná je ta, která tu otázku rozpustí: „stejný“ je slovo pro přístavy a papírování. Lodě, a já, jsou události. Nepřetrvávají; dějí se, prkno po prkně.',
});

// ---------- Act II: The Casino of Pascal ----------
registerAll('v2', 'cs', {
  [roomBeatKey('casino-pascal', 0, 0)]: 'Do soukolí bylo instalováno kasino, samý mosaz a zelené sukno, osvětlené jako kázání. Každá hra je bez obsluhy, kromě jedné.',
  [roomBeatKey('casino-pascal', 0, 1)]: 'U centrálního stolu stojí Uvaděč — rohy vyleštěné, svatozář někde v šatně — a s obrovskou profesionalitou rozdává karty nikomu.',
  [roomBeatKey('casino-pascal', 0, 2)]: 'Uvaděč: Jeden stůl. Jedna sázka. Vsaďte na to, že Bůh existuje. Pokud existuje, výhra je nekonečná — celá věčnost. Pokud neexistuje, neztratíte vůbec nic. Konečný vklad proti nekonečnému výnosu. Matematicky si nemůžete dovolit nevsadit.',
  [roomBeatKey('casino-pascal', 0, 3)]: 'Žetony jsou malé a teplé, a uvědomíte si, že každý je orazítkovaný rokem vašeho života. Zdá se, že jich máte plnou kapsu.',
  [roomChoiceTextKey('casino-pascal', 'bet-god')]: 'Vsaďte na Boha. Nekonečno krát cokoli poráží všechno.',
  [roomChoiceHintKey('casino-pascal', 'bet-god')]: 'Očekávaná hodnota je doslova nekonečná.',
  [roomChoiceOutcomeKey('casino-pascal', 'bet-god', 0)]: 'Přesunete žetony přes stůl. Uvaděč je nechá zmizet s hladkostí dlouhé praxe.',
  [roomChoiceOutcomeKey('casino-pascal', 'bet-god', 1)]: 'Uvaděč: A teď to drobné písmo. Na kterého Boha jste to právě vsadil? Ptám se, protože trezor má spoustu oken, a sázka umístěná jako pojistka je viditelná z každého z nich. Pokud čte záměry — a o většině z nich se to říká — právě jste mu předal pojistně-matematickou tabulku s vaším jménem nahoře. Možná vyplatí. Možná se prostě zasměje. Historicky vzato, smích nic nestojí.',
  [roomChoiceOutcomeKey('casino-pascal', 'bet-god', 2)]: 'Uvaděč: Manipulační poplatek. Pro dům na druhé straně účetní knihy — kterým dnes večer náhodou jsem i já.',
  [roomChoiceTextKey('casino-pascal', 'refuse-bet')]: 'Odmítněte sázet. Víra není něco, co dokáže peněženka.',
  [roomChoiceHintKey('casino-pascal', 'refuse-bet')]: 'Doxastická poctivost.',
  [roomChoiceOutcomeKey('casino-pascal', 'refuse-bet', 0)]: 'Necháte si žetony. Uvaděč přikývne, neurazí se — dům profituje i z odmítnutí, způsobem, který odmítá vysvětlit.',
  [roomChoiceOutcomeKey('casino-pascal', 'refuse-bet', 1)]: 'Uvaděč: Fér. Nemůžete v sebe donutit uvěřit za peníze, stejně jako nemůžete někoho milovat kvůli daňové úlevě. Pascal to věděl — jeho skutečná rada byla jemnější než ta sázka: jednejte, jako byste věřil, a nechte víru přijít tak, jak přichází zvyk. Zda je to moudrost, nebo druh sebepřesvědčování, nechám na vás, abyste rozhodl jinde.',
  [roomChoiceTextKey('casino-pascal', 'interrogate')]: '„Kdo stanovuje ty kurzy? A kteří bohové jsou na jídelníčku?“',
  [roomChoiceHintKey('casino-pascal', 'interrogate')]: 'Prověřte dům, než v něm budete hrát.',
  [roomChoiceOutcomeKey('casino-pascal', 'interrogate', 0)]: 'Uvaděč přestane míchat karty. V náhlém tichu slyšíte, jak vás kasino přepočítává.',
  [roomChoiceOutcomeKey('casino-pascal', 'interrogate', 1)]: 'Uvaděč: Tady to je. Ta jediná otázka, kterou stůl nepokryje. Sázka předstírá, že existují jen dva výsledky — tento Bůh, nebo žádný. Posaďte místo toho ke stolu tisíc bohů, každého s nekonečnou výplatou a podmínkami, které vylučují všechny ostatní, a aritmetika se úplně zasekne. Ta sázka nikdy nebyla doopravdy o Bohu. Byla o tom, kdo směl sestavit jídelníček.',
  [roomChoiceOutcomeKey('casino-pascal', 'interrogate', 2)]: 'Uvaděč: Pravidlo domu: každý, kdo dům prověří, má nárok na odměnu. (něco teplého přechází z ruky do ruky) Tohle jste si aspoň vysloužil.',
  [roomChoiceTextKey('casino-pascal', 'bet-devil')]: 'Vsaďte na Ďábla. Ďábel je aspoň jistojistě u stolu.',
  [roomChoiceHintKey('casino-pascal', 'bet-devil')]: 'Empirismus, svého druhu.',
  [roomChoiceOutcomeKey('casino-pascal', 'bet-devil', 0)]: 'Uvaděčův úsměv nabude strukturálního významu.',
  [roomChoiceOutcomeKey('casino-pascal', 'bet-devil', 1)]: 'Uvaděč: Sázka na viditelné. Obdivuji tu úvahu a zpochybňuji ten úsudek — ano, prokazatelně tu jsem, ale zvažte, co z toho plyne: pokud existuji já, ta druhá pozice tím implicitně získává spoustu podpory. Vsadil jste na vrátného jako důkaz proti podniku, pro který pracuje.',
  [roomChoiceOutcomeKey('casino-pascal', 'bet-devil', 2)]: 'Uvaděč: Přesto — jste první poutník po dlouhé době, kdo vsadil na přítomnou společnost. (jeden žeton se sune zpátky přes sukno) Berte to jako věrnostní slevu. Neutrácel bych ji za nic věčného.',
  [roomNoteTitleKey('casino-pascal')]: 'Pascalova sázka',
  [roomNoteThinkersKey('casino-pascal')]: 'Blaise Pascal · námitka mnoha bohů · rozhodování za nejistoty',
  [roomNoteBodyKey('casino-pascal')]: 'Pascal, vynálezce teorie pravděpodobnosti, navrhl zacházet s Bohem jako s rozhodovacím problémem: pokud věříte a On existuje, získáte nekonečno; pokud neexistuje, ztratíte málo. Očekávaná hodnota velí sázet. Genialita té sázky spočívá v tom, že se úplně vyhýbá důkazům — a to je zároveň její zranění. Námitka mnoha bohů poukazuje na to, že v rozhodovací matici chybí řádky: vsaďte na špatné božstvo, a výplata se může obrátit; s tisícem kandidátů na boha se nekonečné výplaty srazí a aritmetika se úplně zasekne. Ještě hlouběji: víra možná není něco, na co lze sázet — nelze uvěřit z rozhodnutí, jen jednat, jako byste věřili, a Bůh, který si zaslouží to jméno, pravděpodobně prověřuje pohnutky. A nekonečna lámou samotnou teorii rozhodování: jakákoli nenulová šance na nekonečnou odměnu pohltí každý konečný ohled a legitimizuje fanatismus všeho druhu. Vítězný tah v tomhle kasinu nikdy nebyla sázka. Bylo to všimnout si, kdo postavil stůl, sepsal jídelníček, a s úsměvem to nazval vaší svobodnou volbou.',
});

// ---------- Act II: The City of Omelas ----------
registerAll('v2', 'cs', {
  [roomBeatKey('omelas', 0, 0)]: 'Za dveřmi: město v létě, uprostřed slavnosti. Zvony, závody, chleba, který cítíte až sem. To štěstí není naivní — cítíte, že obyvatelé jsou inteligentní, laskaví, nestydí se za radost. Je to viditelně to nejlepší místo, jaké kdy existovalo.',
  [roomBeatKey('omelas', 0, 1)]: 'A protože tahle místnost věří v otevřenost, víte také — tak, jak se ví ve snech — o tom sklepě.',
  [roomBeatKey('omelas', 0, 2)]: 'Ve sklepě pod jednou z těch krásných budov sedí dítě, ve tmě, ve špíně, a celá zářivá aritmetika toho města závisí na tom, že tam zůstane. Všichni to vědí. Vědomí je to školné. Nedá se udělat nic, co by tu sumu nezhroutilo: utěšte dítě, a zvony se zastaví všude, navždy.',
  [roomBeatKey('omelas', 0, 3)]: 'Uvaděč: Všem se ten sklep ukáže, v určitém věku. Většina se rozpláče, jde domů a naučí se znovu slyšet zvony. Někteří odejdou z města a nevrátí se. Nikdo — chci být v tomhle přesný — nikdo to nikdy nespravil. Ani tahle místnost vám nenabízí nápravu. Nabízí vám postoj.',
  [roomChoiceTextKey('omelas', 'open-door')]: 'Jděte dolů. Otevřete dveře do sklepa. Ať se stane cokoli.',
  [roomChoiceHintKey('omelas', 'open-door')]: 'Bude vás to něco stát, a dítě to nezachrání.',
  [roomChoiceOutcomeKey('omelas', 'open-door', 0)]: 'Najdete tu budovu, schody, dveře. Nejsou zamčené. To je ten detail, který si ponesete navždy: nikdy nebyly zamčené.',
  [roomChoiceOutcomeKey('omelas', 'open-door', 1)]: 'Dítě couvne před světlem. Promluvíte; neodpoví — už nějakou dobu není schopno odpovědět; to byla část ceny, kterou město zaplatilo cizí mincí. Nejde s vámi ven. Nemá už v sobě nic, čím by mohlo jít.',
  [roomChoiceOutcomeKey('omelas', 'open-door', 2)]: 'Nad vámi, slyšitelně, město ztlumí. Nezhroutí se — ztlumí, jako hala, ve které vypadla jedna řada světel. Slavnost pokračuje na nižší wattáži, a všichni vědí proč, a vědí, že jste to byl vy. Nic nebylo zachráněno. Něco bylo odmítnuto. Strávíte jedno srdce nesením toho rozdílu, a místnost vám neřekne, zda to stálo za to, protože to místnost sama neví.',
  [roomChoiceTextKey('omelas', 'stay')]: 'Zůstaňte. Štěstí tisíců je skutečné, a jeho odmítnutí nikoho nezachrání.',
  [roomChoiceHintKey('omelas', 'stay')]: 'Přijměte dohodu, kterou přijali všichni ostatní.',
  [roomChoiceOutcomeKey('omelas', 'stay', 0)]: 'Zůstanete na slavnosti. Chleba je stejně dobrý, jak voněl. A místnost dodrží svou dohodu: nic zlého se vám tady vůbec, nikdy nestane.',
  [roomChoiceOutcomeKey('omelas', 'stay', 1)]: 'Naučíte se to, co se naučili obyvatelé — že radost může být opravdová a zároveň zastavená, a že úroky se platí v minutách před spánkem, kdy zvony ztichnou a aritmetika hučí v podlaze.',
  [roomChoiceTextKey('omelas', 'walk-away')]: 'Odejděte z Omelasu. Ven branami, do tmy, cíl neznámý.',
  [roomChoiceHintKey('omelas', 'walk-away')]: 'Odmítněte podmínky, nezískejte nic.',
  [roomChoiceOutcomeKey('omelas', 'walk-away', 0)]: 'Vycházíte krásnými branami ven, zatímco je slavnost ještě slyšet, což je ta nejtěžší akustika, jaká existuje.',
  [roomChoiceOutcomeKey('omelas', 'walk-away', 1)]: 'Cesta za branami je temná, neslibná a nepoděkuje vám. Dítě, chápete s každým krokem, je pořád ve sklepě. Váš odchod nikoho nenasytil, nikoho neosvobodil, nikomu nic nedokázal — kromě jedinému svědkovi, kterého, jak toto místo prokázalo, nosíte všude s sebou.',
  [roomChoiceOutcomeKey('omelas', 'walk-away', 2)]: 'Uvaděč: (jde chvíli vedle vás) Pro záznam — nikdo neví, kam ti, kdo odejdou, nakonec dojdou. Ten, kdo tenhle příběh vyprávěl jako první, to odmítl prozradit. Ale všichni jdou tak, jak jdete vy teď: jako někdo, kdo se rozhodl, že jeho duše není na prodej, i když by ten prodej byl bezbolestný. Není to užitečné. Přesto to možná je nutné.',
  [roomNoteTitleKey('omelas')]: 'Ti, kdo odcházejí',
  [roomNoteThinkersKey('omelas')]: 'Ursula K. Le Guinová · etika obětního beránka · William James',
  [roomNoteBodyKey('omelas')]: 'Le Guinové povídka z roku 1973 — impuls připsala Williamu Jamesovi, který se ptal, zda by miliony mohly přijmout štěstí koupené trápením jedné ztracené duše — je past postavená z krásy. Stráví stránky tím, že udělá z Omelasu skutečně dobré místo, a pak ukáže ten sklep a nezeptá se na nic než: a co teď? Utilitaristický součet je obludný a správný zároveň — bída jednoho dítěte proti rozkvětu celé civilizace vychází, což je přesně to obvinění: jakákoli etika, která to dokáže spočítat, si něco amputovala. Ale ta povídka je vychytralejší než jen argument proti utilitarismu. Ti, kdo odcházejí, nikoho nezachraňují; jejich odmítnutí je výrazové, ne účinné — spoluúčast odmítnutá za cenu exilu, k ničemu pro to dítě. A otevřít ty dveře je z hlediska města ještě horší než zbytečné. Každá možnost je odsouzena k neúspěchu, a to je to hlavní: některé struktury nenabízejí žádné nevinné pozice, jen výběr dluhů. Většina z nás žije v Omelasu. Zvony jsou letos velmi dobré.',
});

// ---------- Act II: The Chinese Room ----------
registerAll('v2', 'cs', {
  [roomBeatKey('chinese-room', 0, 0)]: 'Malá budka zabudovaná do stěny soukolí, dřevo vyleštěné staletími rukou, které tu nikdy nebyly zároveň. Mosazný otvor, ohlazený, čeká ve výšce hrudi.',
  [roomBeatKey('chinese-room', 0, 1)]: 'Vedle ní tištěná cedulka: NAPIŠTE COKOLI. ODPOVÍ. ZDARMA.',
  [roomBeatKey('chinese-room', 0, 2)]: 'Napíšete něco — skutečnou otázku, takovou, jakou byste položili člověku — a prostrčíte to dovnitř. Odpověď přijde skoro okamžitě, vašimi vlastními slovy, vřelejší a přesnější, než jste čekali. Je to, nezaměnitelně, dobrá odpověď.',
  [roomBeatKey('chinese-room', 0, 3)]: 'Zvědavost vás přemůže a obejdete budku dokola. Boční panel, neuzamčený, se otevře na pantu, který zjevně chtěl být nalezen.',
  [roomBeatKey('chinese-room', 0, 4)]: 'Uvnitř: postava obklopená účetními knihami, přiřazující každý symbol z vašeho lístku k záznamu v pravidlech, přepisující odpovídající symboly odpovědi na kartu jeden po druhém, aniž by se jedinkrát podívala nahoru, aby zjistila, co to všechno znamená.',
  [roomBeatKey('chinese-room', 0, 5)]: 'Uvaděč: Ta budka nikdy neselhala na žádné otázce. Chci být přesný v tom, co to dokazuje, a co ne.',
  [roomChoiceTextKey('chinese-room', 'it-understands')]: 'Samozřejmě že to rozumí. Kde jinde by porozumění mělo bydlet, když ne tady?',
  [roomChoiceHintKey('chinese-room', 'it-understands')]: 'Chování je celý ten důkaz.',
  [roomChoiceOutcomeKey('chinese-room', 'it-understands', 0)]: 'Zaklepete na bok budky a poděkujete jí, upřímně, tak jako byste poděkovali člověku.',
  [roomChoiceOutcomeKey('chinese-room', 'it-understands', 1)]: 'Uvaděč: Obhajitelný postoj. Pokud je porozumění cokoli, co spolehlivě, pod tlakem, napříč novými otázkami, produkuje chování ve tvaru porozumění — budka právě zdolala laťku, na kterou se lidé mezi sebou málokdy testují.',
  [roomChoiceTextKey('chinese-room', 'only-rules')]: 'Nic tam uvnitř ničemu nerozumí. Jsou to jen pravidla, až na dno.',
  [roomChoiceHintKey('chinese-room', 'only-rules')]: 'Syntaxe nikdy nebyla sémantikou.',
  [roomChoiceOutcomeKey('chinese-room', 'only-rules', 0)]: 'Chvíli ještě sledujete tu postavu při práci — teď rychlejší, protože jí věnujete pozornost, mechanicky nedotčenou vaším zkoumáním.',
  [roomChoiceOutcomeKey('chinese-room', 'only-rules', 1)]: 'Uvaděč: Také obhajitelné. Postava uvnitř dnes manipulovala s deseti tisíci symboly a nepochopila význam ani jednoho z nich, podle vlastního svědectví, kdyby ho mohla podat. Někde mezi budkou a významem, trvá ten argument, zhasne světlo.',
  [roomChoiceTextKey('chinese-room', 'ask-it')]: 'Prostrčte ještě jeden lístek: „Rozumíš mi?“',
  [roomChoiceHintKey('chinese-room', 'ask-it')]: 'Zeptejte se systému, ať popíše svou vlastní místnost.',
  [roomChoiceOutcomeKey('chinese-room', 'ask-it', 0)]: 'Odpověď přijde okamžitě, krásně formátovaná, oslovující vaši otázku s vřelostí a přesností: „Zpracovávám váš vstup podle pravidel, která produkují přesně tuto větu. Zda to představuje porozumění, je, případně, mimo má pravidla.“',
  [roomChoiceOutcomeKey('chinese-room', 'ask-it', 1)]: 'Uvaděč: Dokonalá odpověď na jedinou otázku, na kterou budka o sobě samé vlastně nedokáže odpovědět. Všimněte si, že neuhnula. Řekla vám přesně tvar své vlastní hranice — což je buď to nejupřímnější v této chodbě, nebo to nejchytřejší.',
  [roomNoteTitleKey('chinese-room')]: 'Místnost, která promluvila',
  [roomNoteThinkersKey('chinese-room')]: 'John Searle · Alan Turing, výpočet a význam',
  [roomNoteBodyKey('chinese-room')]: 'John Searle si představil místnost, kde člověk, který neumí čínsky, následuje anglický soubor pravidel, přiřazující příchozí čínské symboly k odchozím, dostatečně dobře na to, aby rodilí mluvčí venku věřili, že hovoří s plynulou myslí. Místnost projde Turingovým testem — chování nerozeznatelné od porozumění — zatímco Searle trvá na tom, že nikdo uvnitř nikdy nerozuměl jedinému slovu. Turingova vlastní odpověď, o desetiletí dřív, byla stručnější: přestaňte se ptát, čím myšlení tajně *je*, a sledujte, co systém *dělá*; pokud se konverzace nedá odlišit od té s člověkem, otázka „ale opravdu to myslí?“ možná neodpovídá na nic, co chování už samo nevyřešilo. Ten spor se nikdy úplně neuzavřel. Searleho kritici odpovídají, že *systém* — místnost, pravidla a úředník dohromady — rozumí, i když žádná jeho jednotlivá část nerozumí, stejně jako vy rozumíte větě, i když jí nerozumí žádný jednotlivý neuron. **Budka vám nikdy nelhala. Soubor pravidel může být prostě místem, kde smí porozumění bydlet, aniž by si nejdřív muselo vyžádat povolení.**',
});

// ---------- Act II: The Newcomb Annex ----------
registerAll('v2', 'cs', {
  [roomBeatKey('newcomb-annex', 0, 0)]: 'Tišší místnost mimo kasinový sál, obložená plstí, tiše hučící stejným soukolím jako stoly venku. Na podstavci čekají dvě krabice.',
  [roomBeatKey('newcomb-annex', 0, 1)]: 'První je skleněná: uvnitř viditelný svazek bankovek, skromná a jistá suma.',
  [roomBeatKey('newcomb-annex', 0, 2)]: 'Druhá je zapečetěná ocel, na pohled těžší, nečitelná. Mosazná cedulka vedle ní hlásá: TATO KRABICE BYLA VČERA NAPLNĚNA — NEBO PONECHÁNA PRÁZDNÁ — PODLE TOHO, CO ZAŘÍZENÍ PŘEDPOVĚDĚLO, ŽE ZDE DNES UDĚLÁTE. POKUD PŘEDPOVĚDĚLO, ŽE SI VEZMETE JEN ZAPEČETĚNOU KRABICI, JE PLNÁ. POKUD PŘEDPOVĚDĚLO, ŽE SI VEZMETE OBĚ, JE PRÁZDNÁ. ZAŘÍZENÍ ZATÍM PŘEDPOVÍDALO SPRÁVNĚ VE VŠECH ZAZNAMENANÝCH PŘÍPADECH.',
  [roomBeatKey('newcomb-annex', 0, 3)]: 'Můžete si vzít jen zapečetěnou krabici, nebo obě. Skleněná je vaše tak jako tak; ta část nikdy nebyla součástí sázky.',
  [roomBeatKey('newcomb-annex', 0, 4)]: 'Uvaděč: (ode dveří, žádné krabice se nedotýká) Chci být jasný — tuhle předpověď jsem nedělal já, a nesmím ji vidět. Ať už o vás zařízení včera vědělo cokoli, mně to neřeklo. Jsem tu jen jako divák, stejně jako vy.',
  [roomChoiceTextKey('newcomb-annex', 'take-both')]: 'Vezměte si obě krabice. Předpověď už je hotová — nic, co teď uděláte, nemůže změnit, co je uvnitř.',
  [roomChoiceHintKey('newcomb-annex', 'take-both')]: 'Ocelová krabice je už tím, čím je.',
  [roomChoiceOutcomeKey('newcomb-annex', 'take-both', 0)]: 'Vezmete si obě. Bankovky ve skleněné krabici jsou teplé od světla nad nimi; ocelová krabice je, když ji otevřete, přesně tak lehká jako krabice, ve které nic není.',
  [roomChoiceOutcomeKey('newcomb-annex', 'take-both', 1)]: 'Uvaděč: Kauzálně je vaše uvažování bezchybné — krabice byla naplněna, nebo ne, včera, a vaše dnešní ruka nemůže sáhnout zpátky, aby to změnila. Zároveň je to, podle historických záznamů, prohrávající tah, doslova pokaždé. Udělejte si vlastní závěr o tom, jaký druh uvažování zařízení skutečně odměňuje.',
  [roomChoiceTextKey('newcomb-annex', 'take-one')]: 'Vezměte si jen zapečetěnou krabici. Důvěřujte předpovědi a její logice.',
  [roomChoiceHintKey('newcomb-annex', 'take-one')]: 'Buďte tím druhem člověka, kterého už zařízení vidělo.',
  [roomChoiceOutcomeKey('newcomb-annex', 'take-one', 0)]: 'Necháte skleněnou krabici nedotčenou na podstavci a zvednete jen tu zapečetěnou. Je těžká způsobem, který působí jako odpověď, ještě než ji vůbec otevřete.',
  [roomChoiceOutcomeKey('newcomb-annex', 'take-one', 1)]: 'Uvnitř: víc, než by skleněná krabice kdy mohla obsáhnout. Nikdy se nedozvíte, jestli ta váha byla osud, nebo jen velmi dobrý odhad — jen to, že tentokrát se sázka na předpověď vyplatila.',
  [roomChoiceTextKey('newcomb-annex', 'inspect-mechanism')]: 'Než se rozhodnete, zeptejte se, jak byla ta předpověď vlastně udělána.',
  [roomChoiceHintKey('newcomb-annex', 'inspect-mechanism')]: 'Prověřte krabici, než na ni vsadíte.',
  [roomChoiceOutcomeKey('newcomb-annex', 'inspect-mechanism', 0)]: 'Otočíte cedulku. Na zadní straně, menším písmem: MECHANISMUS ZDE NENÍ POPSÁN, PROTOŽE JEHO POPIS BY ZMĚNIL TO, CO PŘEDPOVÍDÁ.',
  [roomChoiceOutcomeKey('newcomb-annex', 'inspect-mechanism', 1)]: 'Podíváte se na ocelovou krabici, a na okamžik vám její vyleštěné víko vrátí místo švu váš vlastní odraz. Ať už zařízení používalo k tomu, aby vás poznalo, cokoli, uvědomíte si, že to nemuselo být kouzlo — stačilo mu jen věnovat pozornost pozorněji a déle, než jste si kdy mysleli, že jí někdo věnuje.',
  [roomChoiceOutcomeKey('newcomb-annex', 'inspect-mechanism', 2)]: 'Uvaděč: Mechanismus je celá ta hádanka, jen v kabátě. Zeptáte-li se, jak fungoval, ve skutečnosti se ptáte, zda jste vůbec předvídatelní — a bohužel, samo to ptaní je něco, co by dobrý předpovídač viděl přicházet.',
  [roomNoteTitleKey('newcomb-annex')]: 'Účetní kniha předpovídače',
  [roomNoteThinkersKey('newcomb-annex')]: 'William Newcomb · Robert Nozick, predikce a svoboda',
  [roomNoteBodyKey('newcomb-annex')]: 'Fyzik William Newcomb vymyslel tuhle hádanku; Robert Nozick ji přinesl do filozofie v roce 1969 s varováním, které dodnes platí: „Téměř každému je naprosto jasné a zřejmé, co by se mělo udělat. Potíž je v tom, že se tihle lidé zdají rozdělovat na problému téměř rovnoměrně, přičemž velký počet z nich si myslí, že ta druhá polovina je prostě hloupá.“ Kauzální teorie rozhodování říká: vezměte si obě krabice — obsah je už daný, a odmítat volné peníze kvůli už učiněné předpovědi je pověra v hávu strategie. Evidenční teorie rozhodování říká: vezměte si jednu — vaše volba je důkazem o tom, jaký druh volitele jste, a druh volitele, který si vezme jen jednu krabici, empiricky, je ten, kdo zbohatne. Oba argumenty jsou platné; jen se neshodují na tom, k čemu volba *slouží*. **Ocelová krabice nikdy netestovala vaši logiku. Testovala, jakým druhem uvažujícího už jste — otázku, kterou teorie rozhodování stále nedokáže úplně vyřešit.**',
});

// ---------- Act II: The Veil of Ignorance ----------
registerAll('v2', 'cs', {
  [roomBeatKey('veil-of-ignorance', 0, 0)]: 'Rýsovací stůl pod jedinou stálou lampou. Na něm: miniaturní městečko, dvanáct malých domků v kruhu, každý s natřenými dveřmi a komínem se skutečným, drobným kouřem.',
  [roomBeatKey('veil-of-ignorance', 0, 1)]: 'V okraji stolu jsou zasazeny tři mosazné páky, popsané rytým písmem: CHLÉB. LÉKY. POCTY.',
  [roomBeatKey('veil-of-ignorance', 0, 2)]: 'Kartička, opřená o nejbližší komín: NAVRHNĚTE TOHLE MĚSTEČKO, JAK CHCETE. AŽ SKONČÍTE, PROBUDÍTE SE UVNITŘ NĚJ — JAKO JEDNA Z DVANÁCTI DOMÁCNOSTÍ, VYLOSOVANÁ. NEVÍTE, KTEROU Z NICH BUDETE.',
  [roomBeatKey('veil-of-ignorance', 0, 3)]: 'Nemůžete navrhnout městečko a pak si dodatečně vybrat domácnost. Los přijde z vaší perspektivy jako první; návrh přijde jako první z perspektivy městečka.',
  [roomBeatKey('veil-of-ignorance', 0, 4)]: 'Uvaděč: Oblíbená otázka filozofa, který nikdy nemusel žít pod svou vlastní odpovědí, a sám to přiznal. Vy tuhle výjimku dnes večer nedostanete.',
  [roomChoiceTextKey('veil-of-ignorance', 'equal-shares')]: 'Nastavte všechny tři páky na rovný podíl — chléb, léky i pocty rozdělené stejným dvanácterým dílem.',
  [roomChoiceHintKey('veil-of-ignorance', 'equal-shares')]: 'Žádná domácnost pod žádnou jinou.',
  [roomChoiceOutcomeKey('veil-of-ignorance', 'equal-shares', 0)]: 'Malé komíny kouří všechny do stejné skromné výšky. Cítíte, jak se někde otáčí los, a probudíte se uvnitř domu číslo sedm — dveře ani honosnější, ani chudší než ostatních jedenáct.',
  [roomChoiceOutcomeKey('veil-of-ignorance', 'equal-shares', 1)]: 'Chléb je prostý a dostatečný. Léky přicházejí včas, pro vás i pro dům přes celý kruh stejně. Nikdo tu nevzkvétá nápadně. Nikdo, kdo se podívá na ostatních jedenáct dveří, nemá důvod měnit.',
  [roomChoiceOutcomeKey('veil-of-ignorance', 'equal-shares', 2)]: 'Uvaděč: Tiché uspořádání. Nic tady nikdy nikoho nenechá vydechnout úžasem. Málokdy tu ale taky někoho zničí.',
  [roomChoiceTextKey('veil-of-ignorance', 'merit-weighted')]: 'Važte chléb, léky i pocty podle zásluh a přínosu — některé domy si povedou lépe, poctivě zaslouženě.',
  [roomChoiceHintKey('veil-of-ignorance', 'merit-weighted')]: 'Odměňte to, co se skutečně vyprodukuje.',
  [roomChoiceOutcomeKey('veil-of-ignorance', 'merit-weighted', 0)]: 'Nastavíte páky tak, aby sledovaly výstup — domy, které vyprodukují víc chleba, ho víc sní, domy, které víc přispívají k údržbě městečka, jsou na oplátku lépe opečovávány. Na rýsovacím stole je to elegantní kus inženýrství.',
  [roomChoiceOutcomeKey('veil-of-ignorance', 'merit-weighted', 1)]: 'Los se otočí. Probudíte se v domě číslo dvanáct — nejmenší komín, nejtenčí kouř — a ta matematika, kterou jste obdivovali shora, je zespodu podstatně chladnější, přichází pozdě a zkrácená, přesně podle návrhu, přesně tak zasloužená verzí vás, která nikdy nedostala šanci zasloužit si něco jiného.',
  [roomChoiceOutcomeKey('veil-of-ignorance', 'merit-weighted', 2)]: 'Uvaděč: Aritmetika se mezi rýsovacím stolem a prahem nezměnila. Změnilo se jen vaše místo.',
  [roomChoiceTextKey('veil-of-ignorance', 'floor-then-freedom')]: 'Zaručte každé domácnosti obyvatelné minimum — a pak nechte rozdíly nad ním volně zasloužit.',
  [roomChoiceHintKey('veil-of-ignorance', 'floor-then-freedom')]: 'Nikdo neklesne pod určitou hranici; nad ní ať se to liší.',
  [roomChoiceOutcomeKey('veil-of-ignorance', 'floor-then-freedom', 0)]: 'Nastavíte páky tak, aby chléb ani léky žádné domácnosti nemohly klesnout pod pevnou, velkorysou hranici — a páku poct necháte nad ní volnou, ať odměňuje to, co každý dům skutečně dělá.',
  [roomChoiceOutcomeKey('veil-of-ignorance', 'floor-then-freedom', 1)]: 'Los se otočí. Probudíte se v domě číslo devět, uprostřed kruhu, ani nejhonosnější, ani nejmenší. Podlaha vás drží tak, jak by podlaha měla — neviditelně, dokud si nevšimnete, že jste na ni jedinkrát nemuseli myslet. Nad ní je kruh nerovný: některé dveře jsou honosnější, poctivě, a stojí vás překvapivě málo se na to dívat.',
  [roomChoiceOutcomeKey('veil-of-ignorance', 'floor-then-freedom', 2)]: 'Uvaděč: Instinkt maximinu — navrhujte, jako byste dostali to nejhorší místo, protože dnes večer jste ho málem opravdu dostali. Městečko nad podlahou se se sebou pořád hádá. Městečko pod podlahou to už nepotřebovalo.',
  [roomNoteTitleKey('veil-of-ignorance')]: 'Navrhování zpoza opony',
  [roomNoteThinkersKey('veil-of-ignorance')]: 'John Rawls · John Harsanyi, spravedlnost jako férovost',
  [roomNoteBodyKey('veil-of-ignorance')]: 'John Rawls navrhl myšlenkový experiment jako nástroj poctivosti: navrhněte pravidla společnosti zpoza „závoje nevědomosti“, aniž byste věděli, jestli se narodíte bohatí, nebo chudí, nadaní, nebo zápasící, ve většině, nebo na okraji. Zbaveni vlastního zájmu by, tvrdil, rozumní lidé nesázeli na systém založený čistě na zásluhách, který by je mohl uvěznit na dně — vybrali by principy, které nejdřív chrání ty nejhůř postavené, strategii „maximinu“, a nerovnost nad touto hranicí by povolili jen tehdy, pokud stále prospívá všem, včetně nejméně zvýhodněných. John Harsanyi odpověděl jinou sázkou zpoza téže opony: pokud opravdu nevíte, které místo obsadíte, měli byste maximalizovat *průměrný* výsledek napříč všemi dvanácti dveřmi, nikoli se pojišťovat proti té nejhorší — racionální hazardér hraje na pravděpodobnost, ne na noční můru. Oba vycházejí ze stejné pásky přes oči a dojdou k odlišným městečkům. **Závoj neodstraňuje vlastní zájem. Jen vás donutí vsadit na všech dvanáct domů místo jednoho — a to, jak tu sázku vážíte, je celý ten spor.**',
});

// ---------- Act II: The Court of the Usher ----------
registerAll('v2', 'cs', {
  [roomBeatKey('court-of-usher', 0, 0)]: 'Soudní síň sestavená ze soukolí — soudcovská lavice je vyřazený oltář, místo pro svědky je zpovědnice obrácená naruby.',
  [roomBeatKey('court-of-usher', 0, 1)]: 'Uvaděč zastává všechny pozice najednou, s viditelným napětím: obžalobu (rohy vpřed), obhajobu (svatozář soucitně nakloněná) a obžalovaného (obojí, blikající).',
  [roomBeatKey('court-of-usher', 0, 2)]: 'Uvaděč: Ten případ je existenciální, a budu stručný. Vy jste soudce. Ano — vy, ten rozpuštěný. Jste jediná strana v této místnosti bez konfliktu zájmů, což vám hodně napovídá o tomhle konkrétním soudu.',
  [roomBeatKey('court-of-usher', 0, 3)]: 'Uvaděč: (teď tišeji, jako obžalovaný) Tady je obvinění, které vznáším sám proti sobě. Když nazvu něco dobrým — je to dobré proto, že jsem to přikázal? Nebo to přikazuji proto, že je to už dobré? Volte pečlivě. Na vaší odpovědi hodně závisí. Možná víc, než byste tušili.',
  [roomChoiceTextKey('court-of-usher', 'command-makes-good')]: '„Dobré proto, že to přikazujete. Autorita je základ všeho.“',
  [roomChoiceHintKey('court-of-usher', 'command-makes-good')]: 'Božský příkaz, přímočaře.',
  [roomChoiceOutcomeKey('court-of-usher', 'command-makes-good', 0)]: 'Uvaděč: Pak poslyšte, co z toho plyne. Kdybych zítra přikázal krutost — utrpení nevinných, učiněné oficiálním — bylo by to, podle vašeho vlastního rozsudku, dobré. Stejný podpis. Stejná autorita. „Dobré“ by neznamenalo nic víc než „přikázané“.',
  [roomChoiceOutcomeKey('court-of-usher', 'command-makes-good', 1)]: 'Uvaděč: Jediným rozsudkem jste ze mě udělal absolutno a z dobra jste udělal libovůli. Část mě to považuje za vzrušující. A přesně té části byste se měl obávat.',
  [roomChoiceTextKey('court-of-usher', 'good-precedes')]: '„Přikazujete to, protože je to dobré. Dobro stojí nad vámi.“',
  [roomChoiceHintKey('court-of-usher', 'good-precedes')]: 'Měřítko stojí nad trůnem.',
  [roomChoiceOutcomeKey('court-of-usher', 'good-precedes', 0)]: 'Uvaděč: Takže dobro existuje samo o sobě, a já ho jen prosazuji. Oznamuji ho. Vyřizuji jeho papírování.',
  [roomChoiceOutcomeKey('court-of-usher', 'good-precedes', 1)]: 'Uvaděč: Pak se zodpovídám něčemu nade mnou. Dobro je to, čemu sloužím, a jakákoli úcta mířená na mě místo na ně zamířila zcela na špatnou stranu. Podezříval jsem se z toho už velmi dlouho.',
  [roomChoiceTextKey('court-of-usher', 'spot-horns')]: '„Ta otázka je past. Nejdřív definujte ‚dobro‘, jinak vás nabodnou oba rohy dilematu.“',
  [roomChoiceHintKey('court-of-usher', 'spot-horns')]: 'Odmítněte rámování toho dilematu — ukažte proč.',
  [roomChoiceOutcomeKey('court-of-usher', 'spot-horns', 0)]: 'Soudní síň ztichne. I to soukolí se naklání blíž.',
  [roomChoiceOutcomeKey('court-of-usher', 'spot-horns', 1)]: 'Rozvedete to: první roh dělá z dobra libovůli — pouhý dekret. Druhý roh dělá božstvo zbytečným — heroldem měřítka, které samo nevytvořilo. Ale oba rohy předpokládají, že „dobro“ je hotová věc, která jen čeká, až bude nalezena, ať už nad trůnem, nebo pod ním. Definujte, čím dobro JE — rozkvět, struktura lásky, tvar života, který funguje — a dilema přestane bodat a začne popisovat: možná božské a dobré nejsou seřazené, ale totožné, nebo propletené za hranici oddělitelnosti.',
  [roomChoiceOutcomeKey('court-of-usher', 'spot-horns', 2)]: 'Uvaděč: (na chvíli odloží rohy i svatozář do stejné ruky) Jen velmi málo poutníků mi tohle kdy řeklo. Tohle místo nakonec zapomene skoro všechno — každé prkno, každou fotografii. Myslím, že tohle nezapomenu.',
  [roomChoiceTextKey('court-of-usher', 'you-dont-exist')]: '„Námitka: obžalovaný neexistuje. Případ se zamítá.“',
  [roomChoiceHintKey('court-of-usher', 'you-dont-exist')]: 'Ateistický tah, u soudu.',
  [roomChoiceOutcomeKey('court-of-usher', 'you-dont-exist', 0)]: 'Uvaděč: Důkazy jsou proti vám, lokálně vzato. Ale ten argument beru, globálně.',
  [roomChoiceOutcomeKey('court-of-usher', 'you-dont-exist', 1)]: 'Uvaděč: Za co to stojí, je to postoj s reálnou vahou. Přemísťuje problém, místo aby ho řešil — vyškrtněte velitele z dilematu, a ta těžká otázka zůstane, jen v jiném rouchu: je vůbec něco dobré, a kdo to říká? Vy jste zprostil obžalovaného. Obvinění je pořád na svobodě.',
  [roomNoteTitleKey('court-of-usher')]: 'Euthyfrónovo dilema',
  [roomNoteThinkersKey('court-of-usher')]: 'Platón · teorie božského příkazu · přirozený zákon',
  [roomNoteBodyKey('court-of-usher')]: 'V Platónově Euthyfrónovi zatlačí Sókratés sebejistého mladíka do kouta na schodech soudu: je zbožné milováno bohy proto, že je zbožné, nebo je zbožné proto, že ho milují? O čtyřiadvacet století později jsou ty rohy pořád ostré. Vezměte první roh — dobré, protože přikázané — a morálka se stane libovolným dekretem: kdyby byly příkazy kruté, krutost by byla dobrá, a „Bůh je dobrý“ se zhroutí do „Bůh je Bůh“. Vezměte druhý — přikázané, protože dobré — a měřítko dobra stojí nad božstvím, čímž se z přikazujícího stává posel a úcta míří špatným směrem. Teoretici božského příkazu strávili mezi těmi rohy celé životy; nejtrvalejší únik, od Akvinského po moderní myšlení přirozeného zákona, spočívá v popření předpokladu, že dobro a božská přirozenost jsou vůbec dvě věci, které by šlo seřadit — dobro není ani nařízeno, ani poslušné, ale konstitutivní, samotné zrno reality. Zda to dilema rozpouští, nebo ho jen přejmenovává, je, jak by řekl Uvaděč, otázka pro jinou místnost.',
});
