// Czech translation of the v2 Act IV room prose (beats, choice text/hint/
// outcome, field notes) for boulder, last-message, and door-that-asks.
// Registered under version 'v2'. See cs-rooms.ts for the established pattern
// and scripts/extract-v2.ts for the canonical English source list.
import { registerAll } from '../../engine/text/resolver';
import {
  roomBeatKey,
  roomChoiceHintKey,
  roomChoiceOutcomeKey,
  roomChoiceTextKey,
  roomNoteBodyKey,
  roomNoteThinkersKey,
  roomNoteTitleKey,
} from '../../engine/text/keys';

// ---------- Act IV: The Boulder ----------
registerAll('v2', 'cs', {
  [roomBeatKey('boulder', 0, 0)]: 'Mlha řídne. Skrz ni, poprvé, něco jako svítání — obzor se skutečnou barvou. A mezi vámi a obzorem: kopec, a úkol.',
  [roomBeatKey('boulder', 0, 1)]: 'Kameny. Úhledná cedule: NASKLÁDEJTE KAMENY, ABYSTE POKRAČOVALI. Naskládáte je. Při položení posledního kamene se hromada sama rozloží — ne násilně, skoro omluvně, kameny se odkutálí zpět na svá přesná výchozí místa jako zaměstnanci vracející se z přestávky.',
  [roomBeatKey('boulder', 0, 2)]: 'Zkusíte to znovu. Stejný výsledek. Místnost je, k její cti, upřímná: druhá cedule, menší, níž, hlásá: ÚKOL NELZE DOKONČIT. ÚKOL JE TAKÉ POVINNÝ. JSME SI VĚDOMI TOHO NAPĚTÍ.',
  [roomBeatKey('boulder', 0, 3)]: 'Na jednom z kamenů sedí muž. Vypadá starobyle způsobem, který nemá nic společného s jeho tváří — pohledem někoho, kdo tu prostě byl déle, než na to existují slova. Přikývne vám, ne nevlídně, a ukáže na kopec s únavou kolegy.',
  [roomBeatKey('boulder', 0, 4)]: 'Uvaděč: (přichází s termoskou) Poznali jste našeho nejdéle sloužícího obyvatele. Zkusil všechno — inženýrství, modlitbu, hádání se. Kameny vždycky spadnou. Jediné, co se kdy komukoli podařilo změnit, je to nesení.',
  [roomChoiceTextKey('boulder', 'carry-well')]: 'Začněte znovu — bez naděje a bez zoufalství. Udělejte to nesení svým.',
  [roomChoiceHintKey('boulder', 'carry-well')]: 'Kámen je cesta.',
  [roomChoiceOutcomeKey('boulder', 'carry-well', 0)]: 'Naskládáte kameny. Neděláte to ani rychle, ani pomalu, ani v očekávání úspěchu, ani v předvádění porážky — děláte to tak, jak člověk dělá věc, která je prostě jeho věcí. A něco se posune, ne na kopci, ale v gramatice: úkol přestává být překážkou mezi vámi a svítáním a stává se místem, kde právě teď žijete.',
  [roomChoiceOutcomeKey('boulder', 'carry-well', 1)]: 'Kameny spadnou. Všimnete si, že nečekáte, aby nespadly. Začínáte znovu, a to znovu-začínání není opakující se selhání — je to rytmus, a rytmy patří bubeníkovi.',
  [roomChoiceOutcomeKey('boulder', 'carry-well', 2)]: 'Muž vstane, oprášší si ruce a udělá něco, o čem Uvaděč později řekne, že to ještě nikdy neviděl: pomůže. Dva skladatelé kamenů, jeden nemožný úkol, svítání stoupající jako držený tón. „Vidíte to,“ řekne. Není to otázka. Po jednu celou hromadu — než spadne, a spadne — je kopec nezaměnitelně šťastný.',
  [roomChoiceHintKey('boulder', 'irony')]: 'Je-li to absurdní, buďte absurdní taky.',
  [roomChoiceOutcomeKey('boulder', 'irony', 0)]: 'Začnete úkol komentovat jako přírodopisný dokument. Skládáte kameny do urážlivých tvarů. Každému kameni dáte jméno a minulost a jeden z nich vyhodíte za neposlušnost.',
  [roomChoiceOutcomeKey('boulder', 'irony', 1)]: 'Muž se zasměje — zvuk jako něco, co přestává rezavět — a Uvaděč zatleská od termosky. Kameny přesto spadnou. Ale kopec, všimnete si, přestal být těžký jedním konkrétním způsobem: nemůže ponížit někoho, kdo odmítá brát ho jako posvátný. Ironie není nejhlubší odpověď, řekne vám muž a otře si oči. „Ale provedla mě čtvrtým stoletím a nesnesu na ni jediné slovo.“',
  [roomChoiceTextKey('boulder', 'irony')]: 'Zasmějte se tomu. Skládejte kameny schválně špatně, s komentářem.',
  [roomChoiceHintKey('boulder', 'rage')]: 'Bojujte s kamenem.',
  [roomChoiceOutcomeKey('boulder', 'rage', 0)]: 'Zaútočíte na úkol. Vyvinete techniky, opory pro nohy, opravdu působivý způsob házení. Kameny spadnou. Jdete znovu. Kameny spadnou. Na chvíli je v zuřivosti čistota — kopec se stává nepřítelem, a nepřítel je aspoň společník.',
  [roomChoiceOutcomeKey('boulder', 'rage', 1)]: 'Nakonec se zastavíte, plíce v ohni, a všimnete si, že vás muž pozoruje s hlubokým porozuměním. „První rok,“ řekne tiše. „Vlastně dobrý rok.“ Zuřivost byla skutečná a zuřivost byla palivo a zuřivost nezměnila nic než vás — což, poznamená malý hlas, je jediná věc, kterou tu cokoli kdy mění.',
  [roomChoiceTextKey('boulder', 'rage')]: 'Zuřte na něj. Skládejte rychleji, tvrději — ať toho kopec lituje.',
  [roomChoiceHintKey('boulder', 'refuse-carry')]: 'Stávka. Bude vás něco stát.',
  [roomChoiceOutcomeKey('boulder', 'refuse-carry', 0)]: 'Sednete si mezi kameny a celý úkol od sebe odsunete. Není to lenost — je to postoj: některá zadání si zaslouží odmítnutí, a povinná marnost je jedním z nich.',
  [roomChoiceOutcomeKey('boulder', 'refuse-carry', 1)]: 'Místnost vás netrestá hromem. Dělá něco tišího: nic. Svítání zůstává přesně tam, kde je, nezasloužené, a hodiny vámi procházejí, a cítíte — přesně, fyzicky — jak povoluje o srdce úchopu. Ne proto, že by odmítnutí bylo špatné. Protože odmítnutí je tu hlasem pro to přestat se hýbat, a nehybnost má na tomto místě proud, a ten proud táhne jedním směrem.',
  [roomChoiceOutcomeKey('boulder', 'refuse-carry', 2)]: 'Uvaděč: (přehazuje vám kabát přes ramena) Stávka je zaznamenána. Dokonce i respektována. Ale kopec je jediná cesta, která tu je. I on tlačí. Ne proto, že by to něco znamenalo. Protože se rozhodl, že to tlačení je jeho. Pojďte. Nahoru.',
  [roomChoiceTextKey('boulder', 'refuse-carry')]: 'Odmítněte. Sedněte si. Nebudete pro nikoho předvádět nesmyslnost.',
  [roomNoteTitleKey('boulder')]: 'Sisyfos, šťastný',
  [roomNoteThinkersKey('boulder')]: 'Albert Camus · Mýtus o Sisyfovi · absurdno',
  [roomNoteBodyKey('boulder')]: 'Camus to nazval jediným vážným filosofickým problémem: nemá-li život žádný daný smysl, proč v něm pokračovat? Jeho odpověď začíná Sisyfem, odsouzeným bohy valit balvan do kopce navěky a sledovat, jak pokaždé padá zpět. Camus odmítá oba východy — sebevraždu (podlehnutí bezesmyslnosti) i to, čemu říkal filosofická sebevražda (skok do utěšujících systémů, které slibují smysl zpátky). Absurdno pro něj není vlastností světa; je to srážka mezi naší žádostí po smyslu a mlčením vesmíru — a musí se udržet živé, ne vyřešit. Skandální poslední věta — „člověk si musí představit Sisyfa šťastného“ — není optimismus. Je to tvrzení, že při cestě zpátky dolů, jasnozřivý, neutěšený a přesto pokračující, se Sisyfos stává nadřazeným svému trestu: balvan je jeho balvan, rytmus jeho vlastní. Tuto místnost nebylo možné vyhrát, protože smyslem nikdy nebyla hromada. Byla jím cesta dolů: okamžik, kdy úkol přestal být tím, co se vám děje, a začal být přesně tím, co je vaše.',
});

// ---------- Act IV: The Last Message ----------
registerAll('v2', 'cs', {
  [roomBeatKey('last-message', 0, 0)]: 'Malá pošta na okraji mlhy, svítání teď skrz její jediné okno nepochybné. Přepážka je ohlazená lokty, nespočet jich, a za ní nosí Uvaděč poštovní čepici s viditelnou hrdostí.',
  [roomBeatKey('last-message', 0, 1)]: 'Uvaděč: Poslední služby před Prahem. Jednu zprávu lze poslat zpět — do bdělého světa, komukoli. Jednu větu. Že dojde, to vám mohu zaručit; jak dorazí, to už není na mně říct. Sen, tušení, píseň, kterou si nedokážou zařadit, náhlá potřeba někomu zavolat. Médium improvizuje. Zpráva se drží.',
  [roomBeatKey('last-message', 0, 2)]: 'Uvaděč: (přesouvá k vám pero; pero je teplé) Jedna věta, poutníku. Kousky vás, které prošly těmito místnostmi, ji sepisovaly celou dobu, ať jste si toho všimli, nebo ne. Co pošlete?',
  [roomChoiceHintKey('last-message', 'dont-wait')]: 'Propusťte je, ať vás to stojí, co chce, tu doufající část vás.',
  [roomChoiceOutcomeKey('last-message', 'dont-wait', 0)]: 'Ta velkorysá věta — ta, která utrácí své poštovné na osvobození příjemce místo na jeho udržení. Napíšete ji a cítíte, jak se to puštění děje nejdřív ve vašich vlastních rukou, kde se puštění vždycky děje.',
  [roomChoiceOutcomeKey('last-message', 'dont-wait', 1)]: 'Dorazí to jako svolení: ráno, kdy smutek povolí ruční brzdu a někdo udělá věc, kterou provinile odkládal — přestaví nábytek, vydá se na cestu, zasměje se něčemu od začátku do konce. Na chvíli se budou cítit nevěrní, pak nevysvětlitelně doprovázeni. Oba pocity budou správné.',
  [roomChoiceOutcomeKey('last-message', 'dont-wait', 2)]: 'Uvaděč: (tiše) Tahle stojí odesílatele nejvíc a příjemce nejmíň. Prémiová sazba, zaplaceno v plné výši. To je věta, kterou bych poslal já, kdyby někdo — (pauza, malé přenastavení výrazu) — jeď, dopisi. Dávej pozor na mlhu.',
  [roomChoiceTextKey('last-message', 'dont-wait')]: '„Nečekej. Žij. Najdu tě tam, kde budeš.“',
  [roomChoiceHintKey('last-message', 'keep-the-notes')]: 'Pošlete zjištění, ne pocit.',
  [roomChoiceOutcomeKey('last-message', 'keep-the-notes', 0)]: 'Depeše z druhé strany té otázky — protože přesně tak jste tyhle místnosti proháněli: jako vyšetřování. A vyšetřování podávají hlášení.',
  [roomChoiceOutcomeKey('last-message', 'keep-the-notes', 1)]: 'Dorazí to jako myšlenka ve čtyři ráno, kvůli které si někdo sedne a sáhne po papíru — jeden z těch nápadů, které se zdají spíš přijaté než vymyšlené. Stráví na tom roky. Bude to dobrá práce. Byla vaše, a teď je jejich, což je způsob, jakým kdy cestovala každá myšlenka.',
  [roomChoiceOutcomeKey('last-message', 'keep-the-notes', 2)]: 'Uvaděč: Citace napříč prázdnotou. (razítkuje ji, dojat proti vlastní vůli) Jde to pomalu, ale jde to hluboko. Některé věty potřebují desetiletí, než dorazí, a pak dopadnou jako hlubinné nálože.',
  [roomChoiceTextKey('last-message', 'keep-the-notes')]: '„Skoro to všechno dává smysl. Uchovej si poznámky — většinu z toho teď dokážu dokázat.“',
  [roomChoiceHintKey('last-message', 'not-a-burden')]: 'Utraťte svou jedinou větu na cizí ránu.',
  [roomChoiceOutcomeKey('last-message', 'not-a-burden', 0)]: 'Měli jste jednu větu, a rozdali jste ji — adresovanou člověku, o kterém víte, že si opačné přesvědčení schovává tam, kde myslí, že to nikdo nevidí.',
  [roomChoiceOutcomeKey('last-message', 'not-a-burden', 1)]: 'Dorazí to jako sen, ze kterého se probudí už s pláčem, nezahanbeně, poprvé, lehčí způsobem, který nebudou zkoumat, protože zkoumání by to mohlo zlomit. Budou dělat snídani jinak. Malé věci. Kumuluje se to.',
  [roomChoiceOutcomeKey('last-message', 'not-a-burden', 2)]: 'Uvaděč: (tiše, razítkuje ji dvakrát, což není postup) Většina poutníků posílá pro sebe. Ti, kdo neposílají — jejich dopisy jsou, všiml jsem si, jediné, kterých se mlha cestou ven nedotkne.',
  [roomChoiceTextKey('last-message', 'not-a-burden')]: '„Nikdy jsi nebyl přítěží. Řekni to všem. To je celá zpráva.“',
  [roomChoiceHintKey('last-message', 'remember-yours')]: 'Pošlete pravdu o tom, co oheň stál, a co ne.',
  [roomChoiceOutcomeKey('last-message', 'remember-yours', 0)]: 'Věta odchází s dírou, kterou ukazuje — oheň vzal fotografii, důkaz, kotvu, a nechal vám tenhle jediný objev: že vzpomínka na to, kým jste byli, znamená míň než vzpomínka na to, koho jste milovali. Ta druhá přežila oheň bez ožehnutí.',
  [roomChoiceOutcomeKey('last-message', 'remember-yours', 1)]: 'Dorazí to jako chvíle před zrcadlem, kdy se někdo dotkne vlastní tváře a nevysvětlitelně pomyslí na vás — a cítí se spatřený, což je to, oč se fotografie vždycky snažily.',
  [roomChoiceOutcomeKey('last-message', 'remember-yours', 2)]: 'Uvaděč: (drží dopis chvíli, než ho orazítkuje) Ztratil jste obrázek a podržel jste si vidění. (razítko) Pro záznam, tohle je správné pořadí, jak je ztrácet. Většina to zvládne obráceně.',
  [roomChoiceTextKey('last-message', 'remember-yours')]: '„Už si nepamatuji svou tvář. Ale pamatuji si tu tvoji.“',
  [roomChoiceHintKey('last-message', 'silence')]: 'Nenapsaný dopis.',
  [roomChoiceOutcomeKey('last-message', 'silence', 0)]: 'Přesunete přes přepážku prázdný list. Uvaděč se na něj podívá, pak na vás, a pak — profesionál do posledního — ho stejně orazítkuje.',
  [roomChoiceOutcomeKey('last-message', 'silence', 1)]: 'Dorazí to jako mlčení s přítomností v sobě: odpoledne, kdy se někdo bezdůvodně zastaví ve dveřích a na čtyři nebo pět vteřin se cítí naprosto doprovázen. Nikomu to neřeknou, protože nemají co povídat. Bude to jeden z lepších okamžiků jejich roku.',
  [roomChoiceOutcomeKey('last-message', 'silence', 2)]: 'Uvaděč: Prázdné jsou nejtěžší, víte. Všechno nevyřčené pořád něco váží — je to jediný náklad se zápornými rozměry a kladnou hmotností. (zakládá ho něžně) Postarám se, aby to dorazilo jemně.',
  [roomChoiceTextKey('last-message', 'silence')]: 'Pošlete prázdný list. Některé věci se do vět nevejdou.',
  [roomChoiceHintKey('last-message', 'wait-for-me')]: 'Slib, hozený přes propast.',
  [roomChoiceOutcomeKey('last-message', 'wait-for-me', 0)]: 'Napíšete ji, a věta udělá to, co sliby dělají: zaváže odesílatele. Někde v bdělém světě se někdo uprostřed odpoledne zastaví u pocitu jako ruka na rameni a nebude vědět proč najednou postavil konvici a mrkl ke dveřím.',
  [roomChoiceOutcomeKey('last-message', 'wait-for-me', 1)]: 'Uvaděč: (razítkuje ji s velkou slavnostností) Slib. Nejstarší žánr. Jde to nejrychleji, jestli vás to zajímá — naděje má vynikající poštovné.',
  [roomChoiceTextKey('last-message', 'wait-for-me')]: '„Počkej na mě. Jsem na cestě zpátky.“',
});

// ---------- Act IV: The Door That Asks ----------
registerAll('v2', 'cs', {
  [roomBeatKey('door-that-asks', 0, 0)]: 'Zbývají jedny dveře. Nejsou velké ani zdobené — jsou přesné, tak jako byla přesná ta malá místnost — a ve výšce očí je do nich zasazená mosazná mřížka, jako u starého výtahu, nebo zpovědnice.',
  [roomBeatKey('door-that-asks', 0, 1)]: 'DVEŘE: Dobré ráno. Než otevřu, provedu krátký pohovor. Ne zkoušku — audit. Strávili jste tuto cestu odpovídáním místnostem. Ptám se na ty odpovědi.',
  [roomBeatKey('door-that-asks', 0, 4)]: 'DVEŘE: Dejte si čas s tou poslední. Je to jediná otázka, na kterou opravdu potřebuji odpověď, a týká se všech najednou. Všechno, co jste si v těchto místnostech zvolili — stojíte si za tím?',
  [roomBeatKey('door-that-asks', 1, 0)]: 'Mřížka se zasune a zavře, a dveře — poslední dveře — se rozevřou do světla, které není mlha.',
  [roomBeatKey('door-that-asks', 1, 1)]: 'Venku je ráno. Skutečné: kdesi doprava, kdesi konvice, svět zabraný do své obrovské všednosti. Cesta zpět, v přítomném čase, tři kroky odsud.',
  [roomBeatKey('door-that-asks', 1, 2)]: 'Uvaděč: (najednou vedle vás, klobouk v ruce) Konec trati. Nebo začátek jedné, podle toho, kterým směrem to čtete. Práh vás vezme zpátky — k hluku, k tvářím, k nedokončeným hádkám, ke všemu tomu. Většina poutníků ho volí. Je to dobré dveře. Udržuji je dobře.',
  [roomBeatKey('door-that-asks', 1, 3)]: 'Uvaděč: Ale nejsou to jediné dveře, které máte otevřené, a musím to říct. Můžete zůstat — místnosti vždycky potřebují správce, a já to dělám už velmi dlouho. Nebo si můžete lehnout tady u prahu a nechat to poslední rozpouštění doběhnout. Někteří poutníci si na konci vyberou to ticho. Není na mně to nazývat prohrou.',
  [roomChoiceHintKey('door-that-asks', 'changed-mind')]: 'Růst, pojmenovaný a přiznaný.',
  [roomChoiceOutcomeKey('door-that-asks', 'changed-mind', 0)]: 'Pojmenujete tu místnost. Tu konkrétní. A pojmenujete, co se změnilo — ne náladu, ale důvod: to, co pozdější místnost naučila tu dřívější.',
  [roomChoiceOutcomeKey('door-that-asks', 'changed-mind', 1)]: 'DVEŘE: (zvuk jako zámek, který se rozhoduje být pantem) To je odpověď, pro kterou tu jsem. Konzistence je úctyhodná; revize s doklady je vzácnější a lepší. Já, které nedokáže změnit názor, není stálé — je hotové, a hotové je jediná věc, kterou jste celou tuhle cestu odmítali být.',
  [roomChoiceOutcomeKey('door-that-asks', 'changed-mind', 2)]: 'DVEŘE: Pro záznam: poutník, který odchází, není ten, který přišel, a vy jste ten vzácný druh, který to zná písemně.',
  [roomChoiceTextKey('door-that-asks', 'changed-mind')]: '„Ne — ne celé. Některé odpovědi bych změnil, a dokážu vám přesně říct, co mě změnilo.“',
  [roomChoiceHintKey('door-that-asks', 'dont-remember')]: 'Poctivá mezera.',
  [roomChoiceOutcomeKey('door-that-asks', 'dont-remember', 1)]: 'DVEŘE: Velmi dobře. Pohovor končí. Co zbývá, není otázka, ale práh.',
  [roomChoiceTextKey('door-that-asks', 'dont-remember')]: '„Něco z toho si dokonce ani nepamatuji, že jsem si vybral. V tu dobu jsem se rozpouštěl.“',
  [roomChoiceHintKey('door-that-asks', 'laughing-door')]: 'Zasloužili jste si to všimnutí.',
  [roomChoiceOutcomeKey('door-that-asks', 'laughing-door', 0)]: 'Přejdete k malým obyčejným dveřím a klika se otočí dřív, než ji pořádně uchopíte, tak jako otevírá přítel z druhé strany.',
  [roomChoiceOutcomeKey('door-that-asks', 'laughing-door', 1)]: 'Uvaděč: (za vámi, a poprvé jeho hlas nemá ani auru, ani rohy) Tyhle dveře si všimne jen málokterý poutník. Otevře je ještě míň. Tak jděte. Já zhasnu.',
  [roomChoiceTextKey('door-that-asks', 'laughing-door')]: 'Ty malé dveře. Ten smích. Otevřete je.',
  [roomChoiceHintKey('door-that-asks', 'lie-down')]: 'Ten klid.',
  [roomChoiceOutcomeKey('door-that-asks', 'lie-down', 0)]: 'Lehnete si u prahu s ránem tři kroky daleko, a není to porážka — místnost to pozná, Uvaděč to pozná, i mlha to pozná. Je to volba, učiněná s otevřenýma očima, člověkem, který prošel každou místností, aby si tu volbu zasloužil.',
  [roomChoiceOutcomeKey('door-that-asks', 'lie-down', 1)]: 'Uvaděč: (sedne si vedle vás, odloží klobouk nadobro) Pak zůstanu, dokud to nebude dokonáno. Na mé směně se nikdo nerozpouští sám. (pauza) Víte, není to konec. Je to příliv. Všechno, co místnosti zaznamenaly, se vrací do moře, a moře — (jeho hlas už zní jako voda) — nikdy neztratilo jedinou věc, na které záleželo.',
  [roomChoiceTextKey('door-that-asks', 'lie-down')]: 'Lehněte si u prahu. Nechte to rozpouštění doběhnout, jemně, podle svého.',
  [roomChoiceHintKey('door-that-asks', 'remember-everything')]: 'Každá místnost, každá volba, najednou.',
  [roomChoiceOutcomeKey('door-that-asks', 'remember-everything', 0)]: 'Nevykročíte k žádným dveřím. Řeknete to místo toho, tak jako byste vyslovili fakt, ne přání, a to vyslovení je už většinou toho, co se stane.',
  [roomChoiceOutcomeKey('door-that-asks', 'remember-everything', 1)]: 'Uvaděč strne, klobouk v půli cesty k hrudi, a nedokončí ho sundat.',
  [roomChoiceTextKey('door-that-asks', 'remember-everything')]: '„Vzpomínám si na úplně všechno.“',
  [roomChoiceHintKey('door-that-asks', 'stand-by-it')]: 'Konzistence, přiznaná.',
  [roomChoiceOutcomeKey('door-that-asks', 'stand-by-it', 0)]: 'DVEŘE: Stálost. Je vzácnější, než se prodává. Většina poutníků se v okamžiku, kdy se dveře zeptají, zřekne aspoň jedné místnosti — vy jste si ponechali celý účet, včetně položek, které vás něco stály.',
  [roomChoiceOutcomeKey('door-that-asks', 'stand-by-it', 1)]: 'DVEŘE: Poznamenávám, beze zloby, že plně podepsaný účet může být integrita nebo brnění; z téhle strany mřížky jsou k nerozeznání. Poznáte to později, v nějakou neplánovanou hodinu. Vždycky se to zjistí v neplánovanou hodinu.',
  [roomChoiceTextKey('door-that-asks', 'stand-by-it')]: '„Ano. Všechno. Zvolil jsem, co jsem zvolil, a podepsal bych to znovu.“',
  [roomChoiceHintKey('door-that-asks', 'stay')]: 'Dohoda správce.',
  [roomChoiceOutcomeKey('door-that-asks', 'stay', 0)]: 'Odvrátíte se od rána — opravdu se od něj odvrátíte, což práh zaznamená čímsi jako úklonou — a nastavíte ruku pro podložku s papíry.',
  [roomChoiceOutcomeKey('door-that-asks', 'stay', 1)]: 'Uvaděč: (zatím nevytahuje podložku) Buďte si jistí. Hodiny jsou věčné, plat žádný, poutníci jsou — nu, byl jste jedním z nich. Budete sledovat každého z nich, jak čelí ohni, páce a složce, a možná jim nikdy neřeknete odpovědi, hlavně proto, že žádné nejsou.',
  [roomChoiceOutcomeKey('door-that-asks', 'stay', 2)]: 'Uvaděč: (podává vám ji, a podložka je teplá a je na ní vaše jméno — to skutečné, náhle čitelné) ...Vítejte na palubě. První lekce: aureola a rohy mají stejnou velikost. Je to záměr. Tady je záměrem všechno.',
  [roomChoiceTextKey('door-that-asks', 'stay')]: 'Zůstaňte. Vezměte si podložku. Starejte se o místnosti pro toho, kdo přijde po vás.',
  [roomChoiceHintKey('door-that-asks', 'walk-through')]: 'Návrat.',
  [roomChoiceOutcomeKey('door-that-asks', 'walk-through', 0)]: 'Vykročíte ke světlu. Práh má teplotu dveří v létě — ten půlstupňový rozdíl, který znamená venku.',
  [roomChoiceOutcomeKey('door-that-asks', 'walk-through', 1)]: 'Uvaděč: (volá za vámi) Poutníku. Ať tam venku najdete cokoli — bude to přesně tentýž svět. To nikdy nebyl ten slib. Vy jste byl tou rekonstrukcí. Pozor na mezeru.',
  [roomChoiceTextKey('door-that-asks', 'walk-through')]: 'Projděte skrz. Zpátky do rána, do hluku, do světa.',
  [roomNoteTitleKey('door-that-asks')]: 'Prozkoumaný život, prověřený',
  [roomNoteThinkersKey('door-that-asks')]: 'Sókratés · Kierkegaard · narativní identita — MacIntyre, Ricoeur',
  [roomNoteBodyKey('door-that-asks')]: 'Sókratés řekl, že neprozkoumaný život nestojí za to žít, a byla mu za to porotou, která nechtěla být zkoumána, vyměřena smrt. Tyto dveře jsou ta věta obrácená naruby: konečně zkoumání toho, kdo zkoumá. Teoretici narativní identity — MacIntyre, Ricoeur — tvrdí, že já není substance, ale příběh v neustálé revizi, a že morální otázka zní, zda dokážete stát za svým příběhem jako autor i jako postava zároveň. Všimněte si, co dveře odměnily: ne konzistenci, která může zkamenět v brnění, ale revizi s doklady — schopnost říct „změnil jsem názor, a tady je, co ho změnilo.“ Kierkegaard: život se žije dopředu a chápe zpětně; dveře jsou místem, kde se oba směry konečně setkají a porovnají si poznámky. Každá filosofie, kterou tato cesta inscenovala — tramvaj, stroj, prkna, sázka, sklep, složka — byla vždycky jednou otázkou v přestrojení: když se vám váš vlastní spis přečte nahlas, je ten podpis váš?',
});
