// Czech translations for Act IV's Examined Path reflections (spec 05).
// Every line is translated with the specific room's situation in mind, not
// word-for-word from English — see CLAUDE.md's translation rule.
import { registerAll } from './resolver';
import { reflectionKey } from './keys';

registerAll('v2', 'cs', {
  // ---------- The Last Message ----------
  [reflectionKey('last-message', 'wait-for-me', 'consequence')]: 'Slib dorazí, ať přijde jakkoli — jako tušení, pocit, náhlá potřeba dát na sporák konvici — a udělá to, co sliby dělají: zavazuje i toho, kdo ho dal.',
  [reflectionKey('last-message', 'wait-for-me', 'duty')]: 'Slib daný přes mlhu, kterou se zpátky nedá přejít, je dluh, o kterém dopředu víte, že ho nikdy nevyberete.',
  [reflectionKey('last-message', 'wait-for-me', 'virtue')]: 'Zeptejte se, jestli utratit tu jedinou větu za naději byla odvaha, nebo prostě ta věta, která se psala nejsnáz.',
  [reflectionKey('last-message', 'wait-for-me', 'care')]: 'Někde se někdo uprostřed odpoledne zarazí nad pocitem, který neumí pojmenovat — malá, skutečná tíha péče, doručená bez zpáteční adresy.',
  [reflectionKey('last-message', 'not-a-burden', 'consequence')]: 'Jedna věta, celá utracená za odlehčení cizího soukromého účtu — a dorazí přesně nastavená tak, aby uvolnila právě tohle.',
  [reflectionKey('last-message', 'not-a-burden', 'duty')]: 'Nic dalšího jste jim tou jednou větou nedlužili, a přesto jste ji celou dali dluhu, který nikdy technicky nebyl váš k vyrovnání.',
  [reflectionKey('last-message', 'not-a-burden', 'virtue')]: 'Zeptejte se, co stojí utratit své jediné odchozí slovo za ránu někoho jiného místo za vlastní rozloučení.',
  [reflectionKey('last-message', 'not-a-burden', 'care')]: 'Dorazí to jako sen, ze kterého se probudí s pláčem, konečně nezahanbeně — zpráva adresovaná úplně cizí potřebě.',
  [reflectionKey('last-message', 'keep-the-notes', 'consequence')]: 'Zjištění přežije pocit — myšlenka, která přijde ve čtyři ráno a stojí někoho jiného desítky let dokazování, že měla pravdu.',
  [reflectionKey('last-message', 'keep-the-notes', 'duty')]: 'Argumentu, který jste stavěli, dlužíte konec, a tahle věta je jediný dostupný konec — konečně podaná zpráva.',
  [reflectionKey('last-message', 'keep-the-notes', 'virtue')]: 'Zeptejte se, jestli poslat zjištění místo pocitu byla upřímnost o tom, na čem vám záleželo, nebo starý zvyk schovávat se za argument.',
  [reflectionKey('last-message', 'keep-the-notes', 'care')]: 'Kdokoli tohle dostane, stráví léta na práci, která nikdy nebyla skutečně jeho, a stane se přesně tím druhem člověka, který dělá dobro s vypůjčenými věcmi.',
  [reflectionKey('last-message', 'remember-yours', 'consequence')]: 'Věta dorazí jako poznání, ne jako informace — okamžik před zrcadlem, který nic měřitelného nemění, a přesto mění všechno pociťované.',
  [reflectionKey('last-message', 'remember-yours', 'duty')]: 'Nikomu nedlužíte vyúčtování toho, co vzal oheň — ale pojmenovat, co přežilo, je dluh splacený vám oběma zároveň.',
  [reflectionKey('last-message', 'remember-yours', 'virtue')]: 'Zeptejte se, jestli ztratit fotografii a udržet si to vidění je správné pořadí ztráty, nebo jen pořadí, které vám bylo přiděleno.',
  [reflectionKey('last-message', 'remember-yours', 'care')]: 'Někdo se dotkne vlastní tváře a bezdůvodně pomyslí na vás — a cítí se spatřen, což je přesně to, o co se fotografie vždycky snažily.',
  [reflectionKey('last-message', 'dont-wait', 'consequence')]: 'Propuštění je stojí tu jedinou větu, která je mohla požádat o čekání, výměnou za tu, co je osvobozuje skutečně žít.',
  [reflectionKey('last-message', 'dont-wait', 'duty')]: 'Dlužíte jim jejich vlastní život víc, než dlužíte sobě jejich čekání — tahle věta ten dluh splácí naplno, na váš vlastní účet.',
  [reflectionKey('last-message', 'dont-wait', 'virtue')]: 'Zeptejte se, jestli je takhle štědré pouštění láska, nebo poslední způsob, jak řídit, jak budou truchlit.',
  [reflectionKey('last-message', 'dont-wait', 'care')]: 'Dorazí to jako svolení — ráno, kdy se smutek uvolní a oni konečně udělají to, co provinile odkládali.',
  [reflectionKey('last-message', 'silence', 'consequence')]: 'I prázdná stránka dorazí jako něco — ticho s přítomností v sobě, náklad bez váhy, který přesto přistane.',
  [reflectionKey('last-message', 'silence', 'duty')]: 'Nikomu nedlužíte větu, kterou nemáte — poslat upřímné nic může splatit dluh lépe, než poslat něco nepravdivého.',
  [reflectionKey('last-message', 'silence', 'virtue')]: 'Zeptejte se, jestli zvolit ticho místo řeči byla zdrženlivost, nebo jednoduše jediná forma upřímnosti, kterou jste dnes v noci měli k dispozici.',
  [reflectionKey('last-message', 'silence', 'care')]: 'Dorazí to jako odpoledne, kdy se někdo zastaví ve dveřích a na pár vteřin se cítí úplně doprovázen — z důvodů, které nikdy nepojmenuje.',

  // ---------- The Door That Asks ----------
  [reflectionKey('door-that-asks', 'stand-by-it', 'consequence')]: 'Stát si za každou volbou nemění nic na tom, co se stalo — mění jen to, co jste teď ochotni o tom říct.',
  [reflectionKey('door-that-asks', 'stand-by-it', 'duty')]: 'Svému vlastnímu záznamu dlužíte upřímný podpis, ať stál cokoli — a právě jste podepsali všechno, včetně položek, které vás stály nejvíc.',
  [reflectionKey('door-that-asks', 'stand-by-it', 'virtue')]: 'Zeptejte se, jestli je plně podepsaná účetní kniha integrita, nebo brnění nošené tak dlouho, že přestalo být pociťováno jako volba.',
  [reflectionKey('door-that-asks', 'stand-by-it', 'care')]: 'Dveře to konstatují bez krutosti — ať to bylo pro kohokoli, podpis byl vaším, buď ho dát, nebo zadržet, a vy jste ho dali celý.',
  [reflectionKey('door-that-asks', 'changed-mind', 'consequence')]: 'Pojmenovat, co vás změnilo, nezruší tu dřívější volbu — jen přidá upřímný druhý zápis vedle prvního.',
  [reflectionKey('door-that-asks', 'changed-mind', 'duty')]: 'Dveřím, i sobě, dlužíte doklad stejně jako revizi — pojmenovat místnost, která vás změnila, je ta těžší polovina té upřímnosti.',
  [reflectionKey('door-that-asks', 'changed-mind', 'virtue')]: 'Zeptejte se, jestli je revize záznamu tady růst, nebo pohodlný způsob, jak se zbavit té verze sebe, která si vybrala hůř.',
  [reflectionKey('door-that-asks', 'changed-mind', 'care')]: 'Dveře považují já, které umí změnit názor, za živější než to, co nemůže — laskavost prokázaná tomu, kým jste byli, než jste to věděli líp.',
  [reflectionKey('door-that-asks', 'dont-remember', 'consequence')]: 'Přiznání mezery ji nevyplní — volby učiněné při rozpouštění zůstávají stejně nezasvědčené, jako byly předtím, než jste to řekli.',
  [reflectionKey('door-that-asks', 'dont-remember', 'duty')]: 'Dveřím dlužíte upřímné vyúčtování vlastního záznamu, včetně jeho děr — přiznat mezeru splácí ten dluh víc, než by splácelo předstírání.',
  [reflectionKey('door-that-asks', 'dont-remember', 'virtue')]: 'Zeptejte se, jestli je skepse dveří vůči neporušenému archivu tvrdícímu ztrátu paměti spravedlivá, nebo jestli jsou některé mezery skutečné i bez ohně, na který se dá svést.',
  [reflectionKey('door-that-asks', 'dont-remember', 'care')]: 'Ať si dveře o té výmluvě myslí cokoli, nechají ji projít — vlastní malá milost, prokázaná poutníkovi, který přinejmenším z části skutečně nebyl celý přítomen.',
  [reflectionKey('door-that-asks', 'walk-through', 'consequence')]: 'Vstup do světa se vrací do světa, který vám nikdy nesliboval, že bude jiný — jen vy jste byli tou renovací.',
  [reflectionKey('door-that-asks', 'walk-through', 'duty')]: 'Obyčejnému světu nedlužíte nic navíc za to, že jste ho opustili — projít zpátky je prostě návrat k nároku, který zůstal celou dobu otevřený.',
  [reflectionKey('door-that-asks', 'walk-through', 'virtue')]: 'Zeptejte se, jestli se tenhle průchod liší od kteréhokoli jiného prahu, který jste kdy překročili, nebo jestli se změnilo jen samotné rozhodování.',
  [reflectionKey('door-that-asks', 'walk-through', 'care')]: 'Kdokoli čeká na druhé straně mlhy, dostane vás zpátky přesně tak, jak bylo slíbeno — stejný svět, a někoho, kdo není úplně stejný člověk, jenž odešel.',
  [reflectionKey('door-that-asks', 'stay', 'consequence')]: 'Zůstat udržuje místnosti v chodu pro toho, kdo přijde příště — cena zaplacená výhradně vámi, ve prospěch poutníků, které nikdy nepotkáte.',
  [reflectionKey('door-that-asks', 'stay', 'duty')]: 'Nikdo tohle po vás nevyžadoval — deska s klipem byla nabídnuta, ne dlužena, což z jejího přijetí dělá dar, ne splněnou povinnost.',
  [reflectionKey('door-that-asks', 'stay', 'virtue')]: 'Zeptejte se, jestli je hlídačova dohoda velkorysost, nebo prostě nepřipravenost zjistit, co obyčejný svět udělá se vším, co jste se naučili.',
  [reflectionKey('door-that-asks', 'stay', 'care')]: 'Každý poutník, který přijde po vás, zdědí hlídače, který osobně prošel pákou, složkou i ohněm — péče, za kterou vám nikdy nebude vědět poděkovat.',
  [reflectionKey('door-that-asks', 'lie-down', 'consequence')]: 'Ulehnutí tady neukončí nic, co by stejně jednou neskončilo — mění jen způsob a společnost, ve které to skončí.',
  [reflectionKey('door-that-asks', 'lie-down', 'duty')]: 'Nikdo nedluží vaše pokračování — nechat rozpouštění doběhnout je volba učiněná s otevřenýma očima, tím, kdo si právo ji udělat čestně zasloužil.',
  [reflectionKey('door-that-asks', 'lie-down', 'virtue')]: 'Zeptejte se, jestli je volba klidu vzdáním se, nebo tím stejným jasnozřivým přijetím, o které vás žádala místnost s balvanem, teď v jeho největší podobě.',
  [reflectionKey('door-that-asks', 'lie-down', 'care')]: 'Uvaděč zůstane, dokud to nebude hotové, místo aby vás nechal jít samotného — malá, konkrétní milost, nabídnutá nikomu jinému právě tímhle způsobem.',
  [reflectionKey('door-that-asks', 'laughing-door', 'consequence')]: 'Otevření dveří, jejichž všimnutí jste si vysloužili, nemění nic na dvou obyčejných dveřích vedle — jen přidává možnost, kterou skoro nikdo nikdy neuvidí.',
  [reflectionKey('door-that-asks', 'laughing-door', 'duty')]: 'Tyto dveře vám nikdo nedlužil — musely být vydobyty celou cestou volbami, což z jejich otevření dělá nárok na něco skutečně vašeho.',
  [reflectionKey('door-that-asks', 'laughing-door', 'virtue')]: 'Zeptejte se, co znamená, že nejvzácnější dveře v celém zařízení jsou ty, za kterými se prostě někdo směje.',
  [reflectionKey('door-that-asks', 'laughing-door', 'care')]: 'Uvaděč zhasne světla a nic dalšího neřekne — nejjasnější znamení, že cokoli je za těmi dveřmi, nikdy nebylo na něm, aby to vysvětlil, jen aby pro to udělal místo.',
  [reflectionKey('door-that-asks', 'remember-everything', 'consequence')]: 'Vyslovit to nemění nic na světě za touto místností a mění všechno na tom, jak končí tenhle poslední rozhovor — dveře přestávají záležet ve chvíli, kdy je věta řečena.',
  [reflectionKey('door-that-asks', 'remember-everything', 'duty')]: 'Toto přiznání nikomu nedlužíte — pamatovat si všechno najednou je soukromé dovršení, ne dluh, na jehož vybrání kdokoli čekal.',
  [reflectionKey('door-that-asks', 'remember-everything', 'virtue')]: 'Zeptejte se, co znamená, že nejhlubší odpověď v celém tomto zařízení není vůbec volbou mezi dveřmi, ale odmítnutím nějaké potřebovat.',
  [reflectionKey('door-that-asks', 'remember-everything', 'care')]: 'Uvaděč strne a nedokončí gesto — poprvé nemá ta jediná postava, která odpovídá na otázku každého poutníka, co dalšího říct.',

  // ---------- The Unchosen ----------
  [reflectionKey('the-unchosen', 'enter-it', 'consequence')]: 'Cokoli tam čekalo, se už stalo, nebo nestalo, nebo ta otázka prostě propadla — vstup teď nic nemění na tom, co bylo tehdy možné.',
  [reflectionKey('the-unchosen', 'enter-it', 'duty')]: 'Té staré možnosti nedlužíte nic kromě upřímnosti konečně se podívat — pozdní vstup splácí soukromou zvědavost, ne dluh, který by kdokoli vymáhal.',
  [reflectionKey('the-unchosen', 'enter-it', 'virtue')]: 'Zeptejte se, jestli je vstup teď, když už vás nic nemůže stát, opravdovou zvědavostí, nebo jen bezpečnou zkouškou odvahy.',
  [reflectionKey('the-unchosen', 'enter-it', 'care')]: 'Nikdo v té místnosti na vás nikdy nečekal — jediný, pro koho je tahle pozdní návštěva, je ten, kdo stojí ve dveřích.',
  [reflectionKey('the-unchosen', 'close-it', 'consequence')]: 'Zavření nic nemění na tom, co bylo uvnitř — dveře se prostě vrátí k tomu, čím byly, než jste si jich všimli.',
  [reflectionKey('the-unchosen', 'close-it', 'duty')]: 'Některým dveřím nedlužíte nic kromě respektu je nechat zavřené — ne každá možnost si zaslouží druhý pohled jen proto, že je konečně nabídnuta.',
  [reflectionKey('the-unchosen', 'close-it', 'virtue')]: 'Zeptejte se, jestli zavření bylo moudrostí o tom, které dveře nikdy nebyly vaše, nebo tišší formou vyhýbání se, oblečenou jako zdrženlivost.',
  [reflectionKey('the-unchosen', 'close-it', 'care')]: 'Nikdo za těmi dveřmi nepotřeboval, abyste je otevřeli — místnost vám dovolí nechat je přesně tak nerušené, jak jste je našli.',
  [reflectionKey('the-unchosen', 'read-the-hinges', 'consequence')]: 'Naolejované panty vám říkají, že dveře byly připraveny přesně na dnešní noc — ale to nic nemění na tom, jestli jimi projdete.',
  [reflectionKey('the-unchosen', 'read-the-hinges', 'duty')]: 'Samotné nabídce dlužíte upřímnou otázku dřív, než jí dlužíte odpověď — ptát se proč teď je vlastní druh svědomitosti.',
  [reflectionKey('the-unchosen', 'read-the-hinges', 'virtue')]: 'Zeptejte se, jestli je vyslýchání dveří místo jejich prostého použití důkladnost, nebo způsob, jak odložit tu těžší volbu vstoupit, nebo odmítnout.',
  [reflectionKey('the-unchosen', 'read-the-hinges', 'care')]: 'Panty byly naolejované jen pro vás — ať už načasování zařízení znamená cokoli, ta pozornost nikdy nebyla míněna nikomu jinému.',

  // ---------- The Echo ----------
  [reflectionKey('the-echo', 'answer-it', 'consequence')]: 'Odpovědět nic nemění na tom, co už bylo řečeno — mění jen to, jestli to bylo vyslyšeno.',
  [reflectionKey('the-echo', 'answer-it', 'duty')]: 'Svému bývalému já dlužíte uznání, ne opravu — pozdravit ho je dluh rozpoznání, ne souhlasu.',
  [reflectionKey('the-echo', 'answer-it', 'virtue')]: 'Zeptejte se, jestli oslovit ten hlas místo pouhého svědčení je druh odvahy, nebo starý zvyk potřebovat poslední slovo.',
  [reflectionKey('the-echo', 'answer-it', 'care')]: 'Místnost se usadí jako zadržený dech vypuštěný dvěma lidmi místo jedním — malá milost prokázaná tomu, kým jste kdysi byli.',
  [reflectionKey('the-echo', 'sit-in-silence', 'consequence')]: 'Nechat ho domluvit nerušeně nic nemění na tom, co říká — mění jen to, jestli to tentokrát smí říct celé.',
  [reflectionKey('the-echo', 'sit-in-silence', 'duty')]: 'Svému bývalému já dlužíte vyslechnutí, které jste mu možná napoprvé nedali — ticho tu splácí dluh pozornosti, ne souhlasu.',
  [reflectionKey('the-echo', 'sit-in-silence', 'virtue')]: 'Zeptejte se, jestli je mlčení trpělivost, nebo prostě snazší než zjistit, co byste odpověděli.',
  [reflectionKey('the-echo', 'sit-in-silence', 'care')]: 'Ticho je nejúplnější věc řečená v této místnosti — forma péče, která od toho hlasu žádá jen, aby domluvil.',
  [reflectionKey('the-echo', 'take-both-chairs', 'consequence')]: 'Sednout si do obou křesel nic nemění na tom, která verze vás teď mluví — jen odstraňuje předstírání, že jich kdy bylo dvě.',
  [reflectionKey('the-echo', 'take-both-chairs', 'duty')]: 'Žádnému návštěvníkovi nedlužíte publikum, protože přiznat, že žádný nikdy nebyl, rozpouští samotnou představu dluhu mezi hostitelem a hostem.',
  [reflectionKey('the-echo', 'take-both-chairs', 'virtue')]: 'Zeptejte se, jestli je tohle nejnákladnější upřímnost v místnosti, nebo chytrý způsob, jak se vyhnout té těžší práci skutečně odpovědět tomu hlasu.',
  [reflectionKey('the-echo', 'take-both-chairs', 'care')]: 'Nikdy tu nebyl host, o kterého by se dalo pečovat — jen řada vás, vedená pod stejným jménem, a ta péče vždycky, tiše, mířila k vám samým.',
});
