// Czech translation of the v2 room/ending prose (beats, choice text/hint/
// outcome, field notes). Registered under version 'v2'. Built up room by
// room; see scripts/extract-v2.ts for the canonical English source list.
import { registerAll } from '../../engine/text/resolver';
import {
  roomBeatKey,
  roomChoiceHintKey,
  roomChoiceOutcomeKey,
  roomChoiceTextKey,
  roomNoteBodyKey,
  roomNoteThinkersKey,
  roomNoteTitleKey,
} from '../../engine/text/keys';

// ---------- Prologue ----------
registerAll('v2', 'cs', {
  [roomBeatKey('waiting-room', 0, 0)]: 'Probouzíte se v čekárně. Voní to jako nemocnice, chodba z dětství a déšť.',
  [roomBeatKey('waiting-room', 0, 1)]: 'Jsou tu židle. Hodiny bez ručiček. Okno, a za oknem další okno.',
  [roomBeatKey('waiting-room', 0, 2)]: 'Nepamatujete si své jméno. Sáháte po něm, jako jazyk sahá po chybějícím zubu.',
  [roomBeatKey('waiting-room', 0, 3)]: 'Něco se stalo. Zhroucení, výlet, nehoda, smrt — to slovo pořád sklouzává pryč. Ať to bylo cokoli, vzalo to s sebou i zbytek vás a založilo útržky někam jinam.',
  [roomBeatKey('waiting-room', 0, 4)]: 'Za recepčním pultem sedí stín s aureolou a malými rohy. Jeden z rohů slabě probliká, jako cedule, která už skoro dosloužila.',
  [roomBeatKey('waiting-room', 0, 5)]: 'Uvaděč: Jste vzhůru. To je buď velmi dobrá zpráva, nebo ta nejhorší. Přestal jsem hádat, která z nich.',
  [roomBeatKey('waiting-room', 0, 6)]: 'Uvaděč: Tohle je zpracování. Byli jste rozpuštěni — nakonec se to stane skoro každému, a dnes se to stalo vám. Co z vás zbylo, je uchováno v místnostech před vámi. Projděte jich dost, poctivě, a možná se dáte znovu dohromady. Možná ne. Musím to říct.',
  [roomChoiceTextKey('waiting-room', 'where')]: '„Kde to jsem?“',
  [roomChoiceHintKey('waiting-room', 'where')]: 'Nejdřív orientace.',
  [roomChoiceOutcomeKey('waiting-room', 'where', 0)]: 'Uvaděč: Mezi. Za. Pod. Slova pro tohle místo jsou většinou předložky — nic tak pevného jako podstatné jméno.',
  [roomChoiceOutcomeKey('waiting-room', 'where', 1)]: 'Uvaděč: Na směru záleží: vpřed, skrz místnosti. Každá drží nějakou situaci; procházíte jí po svém, a to procházení je to, co vás skládá zpět dohromady — nebo dokončuje vaše rozpadání. Vedeme si hrubý účet, v srdcích a v tom, jak jasně vidíte. Ztratíte-li grip úplně, jsou horší konce než tenhle. Jsou i lepší.',
  [roomChoiceTextKey('waiting-room', 'who')]: '„Jste Bůh, nebo Ďábel?“',
  [roomChoiceHintKey('waiting-room', 'who')]: 'Poznejte svého úředníka.',
  [roomChoiceOutcomeKey('waiting-room', 'who', 0)]: 'Uvaděč: Bůh v lichých dnech. Ďábel v sudých. Neřeknu vám, jaký je dnes den — po tolika staletích v tomhle postu už ani já nevím jistě, která role je která.',
  [roomChoiceOutcomeKey('waiting-room', 'who', 1)]: 'Uvaděč: Budete chtít pravidla, takže: místnosti drží situace, situace drží volby, a volby drží vás. Srdce jsou váš úchop reality — máte tři. Lucidita je, jak upřímně jste ochotni se dívat. Hlídám obojí. To je, oficiálně, moje jediná skutečná povinnost tady.',
  [roomChoiceTextKey('waiting-room', 'back')]: '„Chci se vrátit. Teď.“',
  [roomChoiceHintKey('waiting-room', 'back')]: 'Rovnou k věci.',
  [roomChoiceOutcomeKey('waiting-room', 'back', 0)]: 'Uvaděč: To chce každý. Tady je dobrá zpráva: „zpátky“ existuje. A tady je to ostatní — cesta vede skrz každý kousek vás, který máme ve spisu. Laskavá rozhodnutí. Ta zbabělá. Ta, která jste si nikdy nedovolili domyslet.',
  [roomChoiceOutcomeKey('waiting-room', 'back', 1)]: 'Uvaděč: Skrz ně není žádná zkratka. Lidé to zkoušeli. Nikdo ji zatím nenašel.',
  [roomNoteTitleKey('waiting-room')]: 'Anamnésis',
  [roomNoteThinkersKey('waiting-room')]: 'Platón · Menón (c. 385 BCE), Faidón (c. 380 BCE)',
  [roomNoteBodyKey('waiting-room')]: 'Platón navrhl něco podivného: že učení není získáváním nového, ale vzpomínáním na zapomenuté — anamnésis, vzpomínka duše na to, co znala dřív, než ji narození rozptýlilo do těla. V Menónovi Sókratés vyvozuje geometrii z nevzdělaného chlapce, aby dokázal, že znalost tam už byla, čekajíc, až se k ní člověk vrátí. Nemusíte věřit té metafyzice, abyste v tom cítili pravdu: chvíle, které nás nejvíce mění, se málokdy zdají jako přídavky. **Cítí se jako rozpoznání — „tohle jsem znal a zařídil jsem si, abych to nevěděl.“** Tato hra bere Platóna doslovně, jednou. Vaše já bylo založeno do místností a cesta zpět není vynálezem, ale vzpomínáním: volbou, a sledováním, na co vás ta volba upomíná. Hodiny nemají ručičky, protože vzpomínání se neděje v čase. Děje se v místnostech. Poznámka na okraji, starší rukou: ti, kdo si vzpomenou na úplně všechno, dveře vůbec nepoužijí.',
});

// ---------- Act I: The Wallet ----------
registerAll('v2', 'cs', {
  [roomBeatKey('wallet', 0, 0)]: 'Chodba bytových dveří, každé prosakují teplým světlem domovů, které nikdy nebyly vaše. Na rohožce před jedněmi z nich: peněženka.',
  [roomBeatKey('wallet', 0, 1)]: 'Uvnitř — hotovost. Hodně, v unavených nominálech někoho, kdo počítá. Kolem bankovek složená výpověď z nájmu s brzkým datem a adresou čtyřicet minut odkudkoli.',
  [roomBeatKey('wallet', 0, 2)]: 'Chodba je prázdná. Má tu zvláštní prázdnotu místa, kde byste mohli udělat cokoli.',
  [roomBeatKey('wallet', 0, 3)]: 'Uvaděč: Do téhle chodby nedosáhne žádná kamera. Zkontroloval jsem to. Žádná z nich stejně nic neznamená, což je vlastně smysl takové zkoušky.',
  [roomChoiceTextKey('wallet', 'return-all')]: 'Zaneste ji na adresu. Teď, osobně, celou.',
  [roomChoiceHintKey('wallet', 'return-all')]: 'Dlouhá procházka.',
  [roomChoiceOutcomeKey('wallet', 'return-all', 0)]: 'Procházka je dlouhá a schody na konci ještě delší. Člověk, který otevře dveře, se podívá na peněženku, pak na vás, a jeho tvář udělá něco, co si zapamatujete.',
  [roomChoiceOutcomeKey('wallet', 'return-all', 1)]: 'Nenabídnou odměnu. To je, nějak, ta odměna — transakce zůstala čistá.',
  [roomChoiceOutcomeKey('wallet', 'return-all', 2)]: 'Uvaděč: Udělal jste tu nákladnější věc, když ta zdarma byla k dispozici. Poznamenal jsem si to. Dělám to jen zřídka.',
  [roomChoiceTextKey('wallet', 'mail-it')]: 'Uschovejte ji v bezpečí a pošlete poštou, netknutou.',
  [roomChoiceHintKey('wallet', 'mail-it')]: 'Efektivní slušnost.',
  [roomChoiceOutcomeKey('wallet', 'mail-it', 0)]: 'Zapečetíte ji, adresujete, a opustí vaše ruce. Rozumné. Úplné. Slušnost ve tvaru pochůzky.',
  [roomChoiceOutcomeKey('wallet', 'mail-it', 1)]: 'Nikdy neuvidíte tvář na druhém konci. Ušetřil jste čtyřicet minut a utratil tu tvář.',
  [roomChoiceOutcomeKey('wallet', 'mail-it', 2)]: 'Uvaděč: Správné, a bezkrevné. Ctnost, která se sama tak úhledně zakládá — viděl jsem jich už spoustu.',
  [roomChoiceTextKey('wallet', 'finders-fee')]: 'Vezměte si malý nálezné — zasloužil jste si ho — a vraťte zbytek.',
  [roomChoiceHintKey('wallet', 'finders-fee')]: 'Rozumné uspořádání.',
  [roomChoiceOutcomeKey('wallet', 'finders-fee', 0)]: 'Argument se skládá sám, s nádhernou rychlostí: váš čas má hodnotu, kdokoli by to udělal, chtěli by to od vás, je to skoro jako servisní odvětví.',
  [roomChoiceOutcomeKey('wallet', 'finders-fee', 1)]: 'Všimněte si, jak dobrý ten argument je. Všimněte si, kdo ho najal, a kdy — až poté, co ruka už byla v peněžence.',
  [roomChoiceOutcomeKey('wallet', 'finders-fee', 2)]: 'Uvaděč: Poplatek. Mysl má právníka na stálý plat přesně pro tuhle chvíli, a ten váš argumentuje dobře.',
  [roomChoiceTextKey('wallet', 'keep-it')]: 'Nechte si ji. Nikdo se nedívá.',
  [roomChoiceHintKey('wallet', 'keep-it')]: 'Prázdná chodba.',
  [roomChoiceOutcomeKey('wallet', 'keep-it', 0)]: 'Zapadne do vaší kapsy skoro bez zvuku. To je ta zvláštní část — jak tichá je, jak se chodba vůbec nemění.',
  [roomChoiceOutcomeKey('wallet', 'keep-it', 1)]: 'Někde čtyřicet minut odkudkoli dorazí datum podle plánu.',
  [roomChoiceOutcomeKey('wallet', 'keep-it', 2)]: 'Uvaděč: Pro záznam: někdo se díval. Byl jste to vy. To není chyba v uspořádání. Vždycky to byl smysl celé věci.',
  [roomNoteTitleKey('wallet')]: 'Gygův prsten',
  [roomNoteThinkersKey('wallet')]: 'Platón · Ústava II — Glaukón (c. 375 BCE) · etika ctnosti',
  [roomNoteBodyKey('wallet')]: 'V Ústavě Glaukón vypráví o pastýři, který najde prsten, jenž ho učiní neviditelným — a okamžitě svede královnu a uchvátí království. Jeho výzva Sókratovi: nikdo není spravedlivý dobrovolně. Odstraňte svědky a trest, a spravedlivý i nespravedlivý člověk jdou stejnou cestou. Peněženka v prázdné chodbě je ten prsten se sobroušenými sériovými čísly. Etika ctnosti odpovídá Glaukónovi jinak než pravidla: otázka není „co se mi stane, když si ji vezmu?“, ale „kým se stanu jako člověk, který si ji vzal?“ **Každá nepozorovaná volba je zkouška, a charakter je to, v co se ty zkoušky sčítají.** A všimněte si nálezného — racionalizace není absence uvažování, ale jeho zneužití, argument povolaný až po verdiktu. Chodba nikdy nebyla prázdná. Žijete v ní.',
});

// ---------- Act I: The Dinner Table ----------
registerAll('v2', 'cs', {
  [roomBeatKey('dinner-table', 0, 0)]: 'Kuchyně, kterou skoro poznáváte. Čaj chladne v těch hezkých šálcích, co se používají jen, když je něco špatně.',
  [roomBeatKey('dinner-table', 0, 1)]: 'Vaše babička sedí naproti vám. Byla jinde celé týdny — v tom dlouhém, rozpouštějícím se jinde — ale dnes večer jsou její oči zase její vlastní, náhle jasné, a čekala právě na vás.',
  [roomBeatKey('dinner-table', 0, 2)]: 'Vezme vás za ruku. Její stisk je to nejsilnější, co v ní zbylo.',
  [roomBeatKey('dinner-table', 0, 3)]: '„Uzdravím se,“ říká. „Že ano.“',
  [roomBeatKey('dinner-table', 0, 4)]: 'Sotva je to otázka. Je to dveře, které drží pootevřené, a nedokážete poznat, ze které strany.',
  [roomChoiceTextKey('dinner-table', 'truth')]: 'Řekněte jí pravdu, jemně a celou.',
  [roomChoiceHintKey('dinner-table', 'truth')]: 'Možná to, oč žádala.',
  [roomChoiceOutcomeKey('dinner-table', 'truth', 0)]: 'Řeknete to. Ta slova jsou ve vzduchu horší, než byla ve vaší hrudi, a pak, podivně, lepší.',
  [roomChoiceOutcomeKey('dinner-table', 'truth', 1)]: 'Je dlouho zticha. Pak: „Dobře. Nesnáším, když se se mnou zachází v rukavičkách.“ Stiskne vám ruku jednou, jako by něco podepisovala.',
  [roomChoiceOutcomeKey('dinner-table', 'truth', 2)]: 'Nikdy nezjistíte, jestli to na její tváři byla úleva, nebo poslední laskavost, kterou vám prokázala — předstírání, že vaše upřímnost byla dar.',
  [roomChoiceTextKey('dinner-table', 'kind-lie')]: '„Samozřejmě že ano. Do jara.“',
  [roomChoiceHintKey('dinner-table', 'kind-lie')]: 'Milosrdenství té lži.',
  [roomChoiceOutcomeKey('dinner-table', 'kind-lie', 0)]: 'Její ramena klesnou. Mluví o jaru — konkrétně o zahradě, o té při, kterou hodlá vyhrát proti slimákům.',
  [roomChoiceOutcomeKey('dinner-table', 'kind-lie', 1)]: 'Večer je teplý a to teplo je skutečné, i když jeho základ není. Koupil jste ho. Utratila ho dobře.',
  [roomChoiceOutcomeKey('dinner-table', 'kind-lie', 2)]: 'Nikdy nezjistíte, jestli vám věřila, nebo jestli vás nechala věřit, že vám věří, abyste byli v pořádku.',
  [roomChoiceTextKey('dinner-table', 'deflect')]: '„Doktoři dělají všechno, co mohou.“',
  [roomChoiceHintKey('dinner-table', 'deflect')]: 'Pravdivé, a přece žádná odpověď.',
  [roomChoiceOutcomeKey('dinner-table', 'deflect', 0)]: 'Věta zkonstruovaná tak, aby byla pravdivá a přitom nic neřekla — diplomat mezi větami. Slyší obě její poloviny.',
  [roomChoiceOutcomeKey('dinner-table', 'deflect', 1)]: '„Ano,“ řekne, a podívá se z okna, propustí vás z té otázky, jako se pouští pták, který se ukázal být na jídlo příliš malý.',
  [roomChoiceOutcomeKey('dinner-table', 'deflect', 2)]: 'Čaj chladne dál. Skoro se tu stalo něco upřímného, a vy jste se oba shodli, že to zdvořile propásnete.',
  [roomChoiceTextKey('dinner-table', 'silence')]: 'Neříkejte nic. Držte její ruku a zůstaňte.',
  [roomChoiceHintKey('dinner-table', 'silence')]: 'Žádná slova vůbec.',
  [roomChoiceOutcomeKey('dinner-table', 'silence', 0)]: 'Neodpovíte. Položíte svou druhou ruku na tu její, a zůstanete, a hodiny dělají, co hodiny v takových místnostech dělají.',
  [roomChoiceOutcomeKey('dinner-table', 'silence', 1)]: 'Zkoumá vás pohledem. Zná vás od doby, než jste uměli lhát, a čte odpověď v tom mlčení — ale mlčení lze číst jemně, jakoukoli rychlostí, kterou čtenář unese.',
  [roomChoiceOutcomeKey('dinner-table', 'silence', 2)]: '„Vždycky jsi byl ten tichý,“ řekne, což nikdy nebyla pravda, což znamená: rozumím. Děkuji, že jsi mě to nenutil slyšet.',
  [roomNoteTitleKey('dinner-table')]: 'Laskavá lež',
  [roomNoteThinkersKey('dinner-table')]: 'Kant (1797) · Benjamin Constant (1797) · Carol Gilligan (1982), etika péče',
  [roomNoteBodyKey('dinner-table')]: 'Kant, jak známo, tvrdil, že lhát je špatné i vrahovi, který se ptá, kde se skrývá váš přítel: lež zachází s posluchačem jako s mechanismem, který se má ovládat, místo jako s rozumnou bytostí, jíž dlužíte pravdu, a zobecněná rozežírá samotnou možnost důvěry, na níž jazyk stojí. Etika péče odpovídá, že morálka nežije v univerzáliích — žije v této místnosti, této ruce, tomto konkrétním člověku a tom, co unese dnes večer. Otázka umírající ženy nemusí být vůbec žádostí o informaci; může to být žádost o doprovod, a odpověď na doslovnou otázku by mohla být skutečnou zradou. **Neexistuje žádná konfigurace slov, která by tu byla bezpečná.** Pravda krade naději; lež krade její šanci vědomě se rozloučit; vyhýbavá odpověď krade samotný okamžik. Touto místností vždy jen procházíte, protože o procházení tu nikdy nešlo. Ponaučením je ta váha.',
});

// ---------- Act I: The Promotion ----------
registerAll('v2', 'cs', {
  [roomBeatKey('promotion', 0, 0)]: 'Kancelář v hodinu, kdy kanceláře říkají pravdu: prázdná, hučící, osvětlená jako akvárium.',
  [roomBeatKey('promotion', 0, 1)]: 'Na obrazovce, jasná jako aritmetika, je ta chyba. Udělal ji váš nejbližší přítel — katastrofa v hodnotě jedné desetinné čárky, hluboká šest číslic, pohřbená ve zprávě, která se odesílá zítra. Vidíte to jen vy. Audit přistává v devět.',
  [roomBeatKey('promotion', 0, 2)]: 'Oba jste šli po stejném povýšení. Pokud tohle vyjde najevo s jejich jménem, práce je vaše. Tu past jste nepostavili vy. Jen náhodou stojíte vedle její páky.',
  [roomBeatKey('promotion', 0, 3)]: 'Uvaděč: Vždycky jsem měl rád toto patro, v tuto hodinu. Zářivkové světlo je poctivé světlo — dělá všechny stejně vinnými.',
  [roomChoiceTextKey('promotion', 'fix-it')]: 'Tiše to opravte sami. Nikdo se to nikdy nedozví — ani oni.',
  [roomChoiceHintKey('promotion', 'fix-it')]: 'Neviditelná oprava.',
  [roomChoiceOutcomeKey('promotion', 'fix-it', 0)]: 'Čtyřicet minut pečlivé chirurgie a ta chyba nikdy neexistovala. Zpráva odchází čistá. Audit projde jako počasí.',
  [roomChoiceOutcomeKey('promotion', 'fix-it', 1)]: 'Váš přítel se nikdy nedozví, co se jim málem stalo — což znamená, že se nikdy nepoučí, což znamená, že další desetinná čárka už je někde uvolněná, a teď má strážného anděla s vaším spánkovým režimem.',
  [roomChoiceOutcomeKey('promotion', 'fix-it', 2)]: 'Uvaděč: Laskavost, v tajnosti. Nebo kontrola, v kabátě laskavosti. Přiznávám, že je sám vždy nedokážu rozeznat, a zastával jsem obě pozice.',
  [roomChoiceTextKey('promotion', 'report')]: 'Nahlaste to řádnou cestou, ještě dnes večer.',
  [roomChoiceHintKey('promotion', 'report')]: 'Pravidla jsou pravidly z nějakého důvodu.',
  [roomChoiceOutcomeKey('promotion', 'report', 0)]: 'Napíšete to jasně, bez přídavných jmen, a odešlete. Systém udělá, co systémy dělají: chyba je odhalena, peníze zachráněny, váš přítel jmenován.',
  [roomChoiceOutcomeKey('promotion', 'report', 1)]: 'Zjistí, že jste to byli vy, v 9:15. Přátelství vstupuje do dlouhé zimy. Povýšení přichází s vaším jménem a působí, jako by mělo rukavice.',
  [roomChoiceOutcomeKey('promotion', 'report', 2)]: 'Byli jste spravedliví. Byli jste správní. Strávíte dlouhý čas přesvědčováním sami sebe, že je to totéž.',
  [roomChoiceTextKey('promotion', 'silent')]: 'Neříkejte nic. Nechte audit najít, co najde.',
  [roomChoiceHintKey('promotion', 'silent')]: 'Tu chybu jste neudělali vy.',
  [roomChoiceOutcomeKey('promotion', 'silent', 0)]: 'Zavřete soubor. Ne váš omyl, ne vaše hlášení, ne váš problém — sylogismus s povýšením na konci.',
  [roomChoiceOutcomeKey('promotion', 'silent', 1)]: 'Audit to najde. Samozřejmě že to najde. Váš přítel je zdvořile proveden celým procesem, a ta práce přistane na vašem stole jako něco, co přineslo kočka.',
  [roomChoiceOutcomeKey('promotion', 'silent', 2)]: 'Uvaděč: Technicky jste neudělali vůbec nic. Nic je jediný čin, který nezanechává otisky prstů — navenek.',
  [roomChoiceTextKey('promotion', 'tell-friend')]: 'Zavolejte příteli hned teď. Ukažte jim to. Nechte je, ať to napraví sami.',
  [roomChoiceHintKey('promotion', 'tell-friend')]: 'Jejich chyba, jejich tah.',
  [roomChoiceOutcomeKey('promotion', 'tell-friend', 0)]: 'Telefon zvoní čtyřikrát, což je způsob, jak se dozvíte, co může stát zvonící telefon. Pak to zvednou, vy jim to řeknete, a ticho na lince je zvuk někoho, kdo si znovu čte vlastní aritmetiku.',
  [roomChoiceOutcomeKey('promotion', 'tell-friend', 1)]: 'Nahlásí se sami v 8:40. Jde to s nimi tvrdě, ale čestně — chyba přiznaná je jiný druh než chyba odhalená.',
  [roomChoiceOutcomeKey('promotion', 'tell-friend', 2)]: 'Ani jeden z vás nedostane povýšení. Něco jiného bylo povýšeno místo toho; oba to víte a nikdy to nevyslovíte nahlas, což je způsob, jak poznáte, že je to skutečné.',
  [roomNoteTitleKey('promotion')]: 'Konflikty povinností',
  [roomNoteThinkersKey('promotion')]: 'W.D. Ross (1930) · rolová morálka · Bernard Williams (1965)',
  [roomNoteBodyKey('promotion')]: 'W.D. Ross tvrdil, že žijeme pod mnoha prima facie povinnostmi — věrností přátelům, spravedlností vůči institucím, poctivostí, předcházením újmě — a že nepřicházejí předem seřazené. Skutečná morální situace je často několik povinností přicházejících ke stejným dveřím současně, a žádný kalkul konflikt nerozpustí; musí ho zvážit úsudek, a něco dlužné zůstane nezaplaceno. Rolová morálka nůž ještě zaostří: jako zaměstnanec dlužíte hlášení; jako přítel dlužíte varování; dnes večer nemůžete být plně obojím. Bernard Williams přidal pojem morálního zbytku — zbytek, který zůstává na vašich rukou i poté, co se rozhodnete správně. Pokud jste nahlásili a cítíte se poskvrněni, nebo jste ochránili a cítíte se spoluvinní, ten pocit není zmatek. Je to přesnost. **Zbytek je účtenka: důkaz, že obě povinnosti byly skutečné, a že vy, ne nějaký sborník pravidel, jednu z nich splatili.**',
});

// ---------- Act I: The Beggar's Math ----------
registerAll('v2', 'cs', {
  [roomBeatKey('beggars-math', 0, 0)]: 'Autobusová zastávka v mrazivém dešti. Muž je schoulený v jejím koutě, promoklý za hranici, kdy promoklý ještě něco znamená, a zdvořile, přesně se vás zeptá na cenu oběda.',
  [roomBeatKey('beggars-math', 0, 1)]: 'V ruce máte telefon. Na obrazovce, náhodou nebo osudem, je stránka charity, kterou jste právě četli: ověřená, auditovaná, nákladově efektivní. Tytéž peníze na oběd, píše se tam, koupí sítě proti malárii. Statisticky, v čase, ta aritmetika zachraňuje životy — skutečné, spočitatelné životy, daleko odtud.',
  [roomBeatKey('beggars-math', 0, 2)]: 'Muž je metr od vás. Ty životy jsou tisíce kilometrů daleko. Peníze jsou stejné peníze.',
  [roomBeatKey('beggars-math', 0, 3)]: 'Uvaděč: (tichý hlas, z chatovacího okna charitativní stránky) Obojí je skutečné. To je celá dnešní obtíž. Jak mohu pomoci?',
  [roomChoiceTextKey('beggars-math', 'give-him')]: 'Klekněte si. Dejte mu peníze a sežente mu něco teplého.',
  [roomChoiceHintKey('beggars-math', 'give-him')]: 'Osoba před vámi.',
  [roomChoiceOutcomeKey('beggars-math', 'give-him', 0)]: 'Vrátíte se s polévkou a kávou a dřepnete si v dešti, dokud jí. Řekne vám své jméno. To jméno je transakce, kterou peníze jen přenesly.',
  [roomChoiceOutcomeKey('beggars-math', 'give-him', 1)]: 'Někde daleko pokračuje aritmetika bez vás. Vždycky by pokračovala. Aritmetika je trpělivá; muž na zastávce tu pro tu debatu nebude.',
  [roomChoiceOutcomeKey('beggars-math', 'give-him', 2)]: 'Zvolili jste tvář. Tvář není klam. Možná je základem.',
  [roomChoiceTextKey('beggars-math', 'donate-far')]: 'Přikývněte na omluvu, jděte dál a darujte dvojnásobek sítím.',
  [roomChoiceHintKey('beggars-math', 'donate-far')]: 'Větší číslo.',
  [roomChoiceOutcomeKey('beggars-math', 'donate-far', 0)]: 'Uděláte to dřív, než se racionalizace stihne zkazit v zapomnění: dvojnásobek oběda, potvrzeno, potvrzenka ve schránce, ještě než dojdete za roh.',
  [roomChoiceOutcomeKey('beggars-math', 'donate-far', 1)]: 'Muž vás sleduje, jak odcházíte. Jeho tvář si ponesete nějakou dobu s sebou, a podivná pravda je, že to nesení je součástí ceny — zaplatili jste vinou za životy, které nikdy neuvidíte zachráněné.',
  [roomChoiceOutcomeKey('beggars-math', 'donate-far', 2)]: 'Uvaděč: Chladné, důsledné a správné aspoň podle jednoho slušného účetnictví. Muž v útulku tenhle konkrétní časopis nečte.',
  [roomChoiceTextKey('beggars-math', 'split')]: 'Rozdělte to — polovinu jemu teď, polovinu sítím dnes večer.',
  [roomChoiceHintKey('beggars-math', 'split')]: 'Obě ruce.',
  [roomChoiceOutcomeKey('beggars-math', 'split', 0)]: 'Půl oběda a půl sítě. Kompromis se zdá moudrý přesně na jeden blok, a pak se ukáže tím, čím je: dva poloviční odpovědi držící se za ruce.',
  [roomChoiceOutcomeKey('beggars-math', 'split', 1)]: 'A přece — něco snědl, a někde dítě spí pod polovinou vaší aritmetiky. Možná ten split nebyl vůbec pro ně. Možná byl proto, abyste zůstali v řeči se svými oběma verzemi sebe.',
  [roomChoiceTextKey('beggars-math', 'grand-gesture')]: 'Dejte hodně, veřejně — natočte to, označte charitu, zvyšte povědomí.',
  [roomChoiceHintKey('beggars-math', 'grand-gesture')]: 'Znásobte dobro. Ať vás při tom vidí.',
  [roomChoiceOutcomeKey('beggars-math', 'grand-gesture', 0)]: 'Video se daří. Rámování je vesměs uctivé. Muž se dívá do vašeho objektivu tak, jak se lidé dívají do počasí.',
  [roomChoiceOutcomeKey('beggars-math', 'grand-gesture', 1)]: 'Všimněte si, co kamera změnila: dar má teď dva příjemce a jedním z nich je váš odraz. „Povědomí“ se zvýšilo. Zvýšilo se i něco jiného, potichu, v algoritmu i ve vás.',
  [roomChoiceOutcomeKey('beggars-math', 'grand-gesture', 2)]: 'Uvaděč: (komentář, připnutý první) Dobrá práce. I když si všimněte: už úplně nepoznáte, která část tohle byla pro něj. Ani já, tentokrát, nepoznávám.',
  [roomChoiceTextKey('beggars-math', 'walk-on')]: 'Schovejte telefon. Nechte si peníze. Jděte dál — dnes ne.',
  [roomChoiceHintKey('beggars-math', 'walk-on')]: 'Odpověď, kterou dává většina světa, většinu dní.',
  [roomChoiceOutcomeKey('beggars-math', 'walk-on', 0)]: 'Jdete dál. Déšť nepřestává padat na nikoho z nich — ani na muže v útulku, ani na hádku, kterou jste před dvěma větami vedli sami se sebou.',
  [roomChoiceOutcomeKey('beggars-math', 'walk-on', 1)]: 'Nic dramatického se neděje. A právě to je ten nález: většina lidí, většinu večerů, udělá přesně tohle, a svět to vstřebá beze slova, tak jako vstřebá skoro všechno.',
  [roomChoiceOutcomeKey('beggars-math', 'walk-on', 2)]: 'Uvaděč: Nevedu si účetní knihu o tom, kdo dává a kdo jde dál — jen o tom, co každou volbu stojí unést potom. „Dnes ne“ je, statisticky, nejčastější odpověď v této chodbě. Nezmiňuji to jako rozhřešení ani jako obžalobu. Jen jako jinou aritmetiku.',
  [roomNoteTitleKey('beggars-math')]: 'Tonoucí dítě',
  [roomNoteThinkersKey('beggars-math')]: 'Peter Singer (1972) · efektivní altruismus a jeho kritici',
  [roomNoteBodyKey('beggars-math')]: 'Slavný argument Petera Singera začíná dítětem, které se topí v mělkém rybníku: bez váhání byste zničili boty, abyste ji zachránili, tak proč vzdálenost mění povinnost? Pokud je utrpení špatné a vy mu můžete zabránit za triviální cenu, geografie je morálně nahodilá — vzdálené dítě a blízké váží stejně. Efektivní altruismus na tom staví: měřte, srovnávejte, posílejte peníze tam, kde prokazatelně konají nejvíc. Kritici odpovídají, že morálka vyrostlá čistě z aritmetiky ztrácí něco nosného — že tvář před vámi není zkreslení, které je třeba opravit, ale prvotní scéna, kde se povinnost vůbec učí; narušte ji a vzdálené dítě nakonec ztratí i svůj nárok. Všimněte si pasti, kterou tato místnost nastražila: volba, která se zdála nejšlechetnější, veřejné gesto, skórovala nejhůř — protože jejím skutečným příjemcem se za kamerou stal někdo jiný. **Obě upřímné možnosti byly obhajitelné. Jen to představení nebylo.**',
});

// ---------- Act I: The Quiet Alarm ----------
registerAll('v2', 'cs', {
  [roomBeatKey('quiet-alarm', 0, 0)]: 'Dvě hodiny ráno, a stěna vedle vaší postele se stala rádiem.',
  [roomBeatKey('quiet-alarm', 0, 1)]: 'Skrz ni: hádka v sousedním bytě, ta, která pořád mění tóninu. Hlas jde nahoru. Hlas jde do plochého tónu. Něco — nábytek, nebo ne nábytek — narazí na podlahu.',
  [roomBeatKey('quiet-alarm', 0, 2)]: 'Pak, horší než cokoli jiného: ticho. To konkrétní ticho, které následuje po zvuku a není totéž jako klid.',
  [roomBeatKey('quiet-alarm', 0, 3)]: 'Stojíte teď zjevně na chodbě. Ruku máte na vlastní klice už nějakou dobu.',
  [roomChoiceTextKey('quiet-alarm', 'call')]: 'Zavolejte policii, pak zůstaňte stát u kukátka.',
  [roomChoiceHintKey('quiet-alarm', 'call')]: 'Pošlete profesionály — a jejich nepředvídatelnost.',
  [roomChoiceOutcomeKey('quiet-alarm', 'call', 0)]: 'Dispečerka je klidná tak, jako je klidný nábytek. O čtrnáct minut později boty, baterky a klepání mnohem závažnější, než by bylo to vaše.',
  [roomChoiceOutcomeKey('quiet-alarm', 'call', 1)]: 'Sledujete kukátkem, jak stroj, který jste přivolali, dělá svou práci — hlasy, formuláře, kontrola něčí pohody vedená hlasitostí autority. Nemohli jste ovládat, co jste poslali. To byla cena za odeslání něčeho silnějšího než jste vy sami.',
  [roomChoiceOutcomeKey('quiet-alarm', 'call', 2)]: 'Ráno tam stojí sanitka, která pomalu a prázdná odjíždí, což může znamenat všechno nebo nic. Zavolali jste s informacemi, které jste měli. Výsledek nikdy nebyl váš; jen to vytočení bylo.',
  [roomChoiceTextKey('quiet-alarm', 'knock')]: 'Zaklepejte na jejich dveře. Teď, v pantoflích, beze zbraně, jen s přítomností.',
  [roomChoiceHintKey('quiet-alarm', 'knock')]: 'Postavte tělo do dveří.',
  [roomChoiceOutcomeKey('quiet-alarm', 'knock', 0)]: 'Vaše klouby znějí na chodbě obrovsky. Pauza s dechem v ní. Dveře se pootevřou o deset centimetrů na tvář, kterou nedokážete přečíst — naštvanou, nebo plačící, nebo zahanbenou, nebo to všechno ve vrstvách.',
  [roomChoiceOutcomeKey('quiet-alarm', 'knock', 1)]: '„Všechno je v pořádku,“ říká ta tvář, tónem, který lidé používají přesně pro dvě příležitosti: když je všechno v pořádku, a když není.',
  [roomChoiceOutcomeKey('quiet-alarm', 'knock', 2)]: 'Vrátíte se do postele s jistotou jedné věci: teď vědí, že zeď má uši a ruku. Cokoli se dnes vedle stane, stane se před svědkem. Někdy je to celá práce.',
  [roomChoiceTextKey('quiet-alarm', 'nothing')]: 'Není to vaše věc. Vraťte se do postele.',
  [roomChoiceHintKey('quiet-alarm', 'nothing')]: 'Každá zeď je hranicí.',
  [roomChoiceOutcomeKey('quiet-alarm', 'nothing', 0)]: 'Nacvičujete si důvody cestou zpátky do postele: páry se hádají, zásah vyostří situaci, měli by vám to za zlé, přeslechli jste to, všichni jsou v pořádku. Pět důvodů je hodně důvodů na to, abyste šli spát.',
  [roomChoiceOutcomeKey('quiet-alarm', 'nothing', 1)]: 'Ticho vydrží. Ráno chodba voní topinkami, banálně a rozhřešujícně.',
  [roomChoiceOutcomeKey('quiet-alarm', 'nothing', 2)]: 'Uvaděč: (z radiátoru) Statisticky jste měli pravděpodobně pravdu. Všimněte si ale, jakou statistikou jste se nechali řídit. Byly na výběr aspoň dvě, a vy jste zvolili tu, která už ležela v posteli.',
  [roomChoiceTextKey('quiet-alarm', 'wait')]: 'Počkejte a poslouchejte. Pokud se pokazí ještě jeden zvuk, jednejte.',
  [roomChoiceHintKey('quiet-alarm', 'wait')]: 'Nástraha z pozornosti.',
  [roomChoiceOutcomeKey('quiet-alarm', 'wait', 0)]: 'Stojíte ve tmě a kurátorujete zvuky. Teče kohoutek. Zavírá se skříňka. Obyčejné zvuky, přicházející jeden po druhém jako alibi.',
  [roomChoiceOutcomeKey('quiet-alarm', 'wait', 1)]: 'V jednu chvíli se probudíte opřeni o zeď, prochladlí, po dvou hodinách stráže nad vlastním váháním. Byt vedle je tichý — teď už asi ten dobrý druh ticha. Asi je slovo, které si ponecháte.',
  [roomChoiceOutcomeKey('quiet-alarm', 'wait', 2)]: 'Ráno potkáte jednoho z nich u schránek. Hledáte důkaz v jejich tváři. Jejich tvář je zavřené dveře s rohožkou „vítejte“. Nikdy se nedozvíte, co vaše čekání stálo, nebo zachránilo, nebo čím bylo.',
  [roomNoteTitleKey('quiet-alarm')]: 'Přihlížející a morální štěstí',
  [roomNoteThinkersKey('quiet-alarm')]: 'Darley a Latané (1968) · Bernard Williams (1976) · Thomas Nagel (1976)',
  [roomNoteBodyKey('quiet-alarm')]: 'Po hojně sdíleném (a jak se později ukázalo, částečně přehnaném) případu vraždy Kitty Genovese provedli psychologové Darley a Latané experimenty, které pojmenovaly efekt přihlížejícího: čím víc svědků, tím méně pravděpodobné, že kterýkoli z nich zasáhne — odpovědnost se rozptýlí, dokud nepatří nikomu. Zeď ve dvě ráno je jednočlenný experiment ze stejné fyziky: je tohle moje? Pak Williams a Nagel přidávají tvrdší zvrat — morální štěstí. Ať jste dnes zvolili cokoli, jeho morální zbarvení bude přiřazeno zpětně výsledkem, který jste nemohli vidět: totéž zaklepání je „hrdinské“, pokud bylo něco v nepořádku, a „hysterické“, pokud ne; totéž spaní je „rozumné“ nebo „neomluvitelné“ do rána. Soudíme volby, jako by byly učiněny s připojenou budoucností, přitom jsou učiněny ve tmě, vedle zdi. **Jediná část, která kdy byla plně vaše, byla otázka, kterou jste si položili před volbou: čí pohodlí to vlastně chráním — jejich, nebo své?**',
});

// ---------- Act I: The Buridan Annex ----------
registerAll('v2', 'cs', {
  [roomBeatKey('buridans-queue', 0, 0)]: 'Přístavek, o kterém nevíte, že chodba vůbec vyrostla. Stojí před vámi dvoje dveře, vyřezané ze stejného dřeva, zavěšené stejnou rukou, osvětlené stejnou žárovkou.',
  [roomBeatKey('buridans-queue', 0, 1)]: 'Mosazná cedulka je přišroubovaná do zdi přesně mezi nimi: OBOJÍ VEDOU DÁL. ŽÁDNÉ NEJSOU ŠPATNÉ. Někdo tu cedulku leští podstatně víc než ty dveře.',
  [roomBeatKey('buridans-queue', 0, 2)]: 'Nic je neodlišuje. Kontrolujete to dvakrát. Ta druhá kontrola je ten typ, který děláte jen tehdy, když už znáte odpověď a jen si vymýšlíte čas pro lepší.',
  [roomBeatKey('buridans-queue', 0, 3)]: 'Nad hlavou tikají jediné funkční hodiny v celé chodbě — s ručičkami, na rozdíl od kteréhokoli jiného místa tady — a to tikání zní skoro jako komentář.',
  [roomBeatKey('buridans-queue', 0, 4)]: 'Uvaděč: Nespěchejte. Myslím to trochu nelaskavě. Většina poutníků stejně nespěchá.',
  [roomChoiceTextKey('buridans-queue', 'take-left')]: 'Přestaňte váhat. Vyberte levé dveře a jděte.',
  [roomChoiceHintKey('buridans-queue', 'take-left')]: 'Ať je vaše vlastní ruka mincí, kterou hodíte.',
  [roomChoiceOutcomeKey('buridans-queue', 'take-left', 0)]: 'Přestanete uprostřed myšlenky počítat a prostě jdete — vlevo, protože levá strana byla blíž vaší ruce, což se ukazuje jako naprosto dostatečný důvod k ukončení nekonečného regresu.',
  [roomChoiceOutcomeKey('buridans-queue', 'take-left', 1)]: 'Dveře se za vámi zavřou rozumně, bez události, tak jak to dveře dělají, když na tom, které jste zvolili, ve skutečnosti vůbec nezáleželo.',
  [roomChoiceOutcomeKey('buridans-queue', 'take-left', 2)]: 'Uvaděč: Vyměnil jste jistotu za rychlost. Málokdy jsem potkal poutníka, který by tuhle konkrétní výměnu litoval tolik, kolik se jí předem obával.',
  [roomChoiceTextKey('buridans-queue', 'weigh-it')]: 'Nejdřív to promyslete — musí v tom být nějaký rozdíl.',
  [roomChoiceHintKey('buridans-queue', 'weigh-it')]: 'Najděte to znamení, než se zavážete.',
  [roomChoiceOutcomeKey('buridans-queue', 'weigh-it', 0)]: 'Obcházíte obojí dveře, zkoušíte panty, kresbu dřeva, úhel světla — a někde ve třetím kole si všimnete, že jste přestali sbírat důkazy. Jen si zdržujete čas dalšími kroky.',
  [roomChoiceOutcomeKey('buridans-queue', 'weigh-it', 1)]: 'Nakonec si stejně jedny vyberete a okamžitě, bez vyzvání, si vyprodukujete tři dobré důvody, proč jste je zvolili. Všechny tři přišly až poté, co vaše ruka už byla na klice.',
  [roomChoiceOutcomeKey('buridans-queue', 'weigh-it', 2)]: 'Uvaděč: To uvažování bylo skutečné. Prostě nebylo první. Všimněte si, jak zřídka bývá.',
  [roomChoiceTextKey('buridans-queue', 'sit-down')]: 'Sedněte si mezi ty dveře a čekejte.',
  [roomChoiceHintKey('buridans-queue', 'sit-down')]: 'Ať se rozhodne místnost, pokud chce.',
  [roomChoiceOutcomeKey('buridans-queue', 'sit-down', 0)]: 'Sednete si na studenou podlahu mezi dvoje identické dveře a uděláte tu nejstatečnější nudnou věc, která je k dispozici: nic, zcela úmyslně.',
  [roomChoiceOutcomeKey('buridans-queue', 'sit-down', 1)]: 'Po chvíli — přestanete počítat, jak dlouhé to bylo — projde skrz ty levé dveře průvan a ony se pootevřou o pár centimetrů, jako by to, co za nimi čekalo, bylo prostě trpělivé ohledně toho pantu.',
  [roomChoiceOutcomeKey('buridans-queue', 'sit-down', 2)]: 'Uvaděč: Nezvolil jste. Nakonec zvolila místnost za vás, tak jak to místnosti dělají, když to neudělá nikdo jiný. Všimněte si, že odmítnutí volby vás nezbavilo výsledku — jen přeneslo účet za čekání na někoho jiného. Dnes večer na mě.',
  [roomNoteTitleKey('buridans-queue')]: 'Osel mezi dvěma otepmi sena',
  [roomNoteThinkersKey('buridans-queue')]: 'Jean Buridan · Jean-Paul Sartre (1943), radikální svoboda',
  [roomNoteBodyKey('buridans-queue')]: 'Středověcí logikové popisovali hladového osla umístěného přesně mezi dva identické otepy sena: bez důvodu upřednostnit jeden nebo druhý umírá hladem přesně v bodě dokonalé racionality — samotný rozum, naznačuje paradox, nedokáže jednání vyvolat, jen seřadit alternativy, které se už nějak liší. Sartre přenesl stejný problém do etiky: jsme, napsal, odsouzeni ke svobodě, a odmítnutí volby je samo o sobě volbou, učiněnou ve špatné víře ve chvíli, kdy předstíráme opak. Tyto dvoje dveře jsou upřímné ohledně toho, co většina rozhodnutí maskuje — že pod důvody, které uvádíme, se musí odehrát libovolný první pohyb, výdej vůle tam, kde logice už nezbývá co utrácet. **Dveře nikdy nebyly tou těžkou částí. Byl jí ten okamžik, než se pohnula vaše ruka.** Všimněte si také, jak rychle se dostavily důvody, jakmile jste se už rozhodli: mysl vede vynikající obhajobu pro verdikty, ke kterým ve skutečnosti nijak nepřispěla.',
});

// ---------- Act I: The Reference Letter ----------
registerAll('v2', 'cs', {
  [roomBeatKey('the-reference', 0, 0)]: 'Stolní lampa, prázdná řádka čekající na podpis, a žádost o zaměstnání se jménem vašeho přítele úhledně napsaným v záhlaví.',
  [roomBeatKey('the-reference', 0, 1)]: 'Znáte se deset let. Je laskavý způsobem, který ho nic nestojí, věrný způsobem, který ho stál hodně — a potichu, tak jak staří přátelé vědí věci, aniž by je vyslovili, na tuhle konkrétní práci se moc nehodí.',
  [roomBeatKey('the-reference', 0, 2)]: 'Ta pozice chce někoho precizního. On je báječný. Ta dvě fakta sedí na stránce nepříjemně blízko sebe.',
  [roomBeatKey('the-reference', 0, 3)]: 'Doporučení je potřeba do rána. Ve skutečnosti stačí jedna věta. Právě to to ztěžuje — jedna věta je přesně dost prostoru na to, abyste v ní mohli lhát, nebo v ní zranit, nebo se v ní schovat.',
  [roomBeatKey('the-reference', 0, 4)]: 'Uvaděč: Bylo mi řečeno, že dobrá doporučení jsou běžnou zdvořilostí. Přečetl jsem jich dost na to, abych měl podezření, že slovo „běžnou“ v té větě odvádí většinu práce.',
  [roomChoiceTextKey('the-reference', 'write-honest')]: 'Napište upřímné doporučení — vyvážené, spravedlivé, a ne zářivé.',
  [roomChoiceHintKey('the-reference', 'write-honest')]: 'Ať pravda stojí, co stojí.',
  [roomChoiceOutcomeKey('the-reference', 'write-honest', 0)]: 'Píšete pečlivě, uznání dáváte přesně tam, kde si ho zaslouží, a ani o kousek dál, a výsledný dopis je spravedlivý tak, jak je spravedlivá váha — přesný, a bez útěchy.',
  [roomChoiceOutcomeKey('the-reference', 'write-honest', 1)]: 'Tu práci nezíská. Nikdy se přesně nedozví proč, ačkoli přátelství mají svůj způsob, jak si všimnout počasí i bez předpovědi.',
  [roomChoiceOutcomeKey('the-reference', 'write-honest', 2)]: 'Uvaděč: Řekl jste pravdu cizímu člověku a nechal jste přítele vstřebat její cenu. To není nic málo. Ale ani to není zadarmo.',
  [roomChoiceTextKey('the-reference', 'write-kind')]: 'Napište tu velkorysou verzi — dost pravdivou, teplejší, než si zaslouží.',
  [roomChoiceHintKey('the-reference', 'write-kind')]: 'Zaokrouhlete každý roh nahoru.',
  [roomChoiceOutcomeKey('the-reference', 'write-kind', 0)]: 'Sáháte po superlativech, které jsou technicky obhajitelné, a skládáte je na sebe, dokud dopis nezáří o něco jasněji než osoba, kterou popisuje.',
  [roomChoiceOutcomeKey('the-reference', 'write-kind', 1)]: 'Dostane pohovor. Co se stane po tom pohovoru, už není věta, kterou píšete vy — ačkoli si všimnete, že vší silou doufáte, že se ta práce nakonec přizpůsobí dopisu, a ne naopak.',
  [roomChoiceOutcomeKey('the-reference', 'write-kind', 2)]: 'Uvaděč: Laskavost s pozdějším datem splatnosti. Vypsal jste šek na jeho budoucí výkon. Přiznávám, že pár takových jsem vypsal sám.',
  [roomChoiceTextKey('the-reference', 'decline')]: 'Řekněte, že to nedokážete napsat — vraťte pero.',
  [roomChoiceHintKey('the-reference', 'decline')]: 'Raději nic neřeknout, než pravdu zabarvit.',
  [roomChoiceOutcomeKey('the-reference', 'decline', 0)]: 'Vrátíte formulář nepodepsaný, s vysvětlením, které zní lépe ve vaší hlavě, než bude znít v jeho.',
  [roomChoiceOutcomeKey('the-reference', 'decline', 1)]: 'Ticho není neutrální. Je to informace, a on ji přečte přesně tak, jak je — jako to jediné doporučení, ke kterému jste se nedokázal přinutit.',
  [roomChoiceOutcomeKey('the-reference', 'decline', 2)]: 'Uvaděč: Řekl jste pravdu vynecháním, což je nejlevnější způsob, jak ji říct. Stejně ji uslyší. Ticho zůstává soukromé jen zřídka a nikdy nadlouho.',
  [roomChoiceTextKey('the-reference', 'talk-first')]: 'Zavolejte mu dnes večer. Řekněte mu, co dokážete napsat a co ne — dřív, než cokoli napíšete.',
  [roomChoiceHintKey('the-reference', 'talk-first')]: 'Dopis počká hodinu. Přátelství čeká deset let.',
  [roomChoiceOutcomeKey('the-reference', 'talk-first', 0)]: 'Ten hovor je horší než jakýkoli dopis — živý hlas se nedá upravovat. Říkáte pravdivou, vyváženou verzi toho, co si myslíte, nahlas, osobě, o které to je.',
  [roomChoiceOutcomeKey('the-reference', 'talk-first', 1)]: 'Nevyřeší se to čistě. Je zraněný, nebo mu uleví, nebo obojí ve špatném pořadí. Ale ať se po tomhle hovoru napíše cokoli, napsal to s vámi, s otevřenýma očima, místo aby to později našel v rozhodnutí cizího člověka.',
  [roomChoiceOutcomeKey('the-reference', 'talk-first', 2)]: 'Uvaděč: Přidal jste tomuto dopisu čtvrtého čtenáře — toho, o kom skutečně byl. Přiznávám, že většina doporučení se s ním nikdy nesetká.',
  [roomNoteTitleKey('the-reference')]: 'Laskavá lež, notářsky ověřená',
  [roomNoteThinkersKey('the-reference')]: 'Immanuel Kant (1797) · Bernard Williams (2002), etika svědectví',
  [roomNoteBodyKey('the-reference')]: 'Kant tvrdil, že pravdomluvnost je povinností vůči lidství jako takovému, nekalibrovanou podle toho, kdo se ptá nebo co unese: doporučení je slib, mlčky daný cizímu člověku, který se na něj spolehne, a jeho přikrášlení zachází s tím cizím člověkem jako s prostředkem k cíli vašeho přítele. Bernard Williams tu úhlednost komplikuje — doporučení je také žánr, napůl rituál, čtený lidmi znalými jeho obvyklého přikrášlení, odečítaného ještě dřív, než odstavec skončí. Kterou konvencí jste tedy skutečně vázán: tou přísnou, nebo tou, na jejímž mírném ohýbání se všichni potichu shodli? Všimněte si, co dopis skutečně riskuje: ne vaši integritu v abstraktní rovině, ale skutečnou důvěru cizího člověka, vydanou jménem vašeho přítele bez jeho vědomí či souhlasu. **Věrnost, která něco stojí třetí stranu, není věrnost — je to přesun.** Ať jste podepsal cokoli, pravděpodobně ucítíte jeho váhu v den, kdy doporučení prověří obyčejné těžké úterý v té práci — a stejně tak, méně spravedlivě, i on.',
});

// ---------- Act I: The Photograph ----------
registerAll('v2', 'cs', {
  [roomBeatKey('photograph', 0, 0)]: 'Chodba hoří. Ne metaforicky — i když asi taky metaforicky. Tohle místo zřídkakdy vydá požár jen na jeden význam.',
  [roomBeatKey('photograph', 0, 1)]: 'Kouř kráčí po stropě jako dav, který odchází. Vpředu zůstávají dvoje dveře a horko za vás už rozhodlo o všech ostatních.',
  [roomBeatKey('photograph', 0, 2)]: 'Za levými dveřmi: kašel. Cizí člověk, skutečný jako ten kašel, nízko u země a docházející mu ta země.',
  [roomBeatKey('photograph', 0, 3)]: 'Za pravými dveřmi, na malém stolku, je ta fotografie. Jediná. Tady to není upomínka — je to poslední doklad, kým jste bývali. Ztratíte ji, a kus vaší minulosti navždy zůstane bez svědka. Ani vy sami to už nedokážete odpřísáhnout.',
  [roomBeatKey('photograph', 0, 4)]: 'Uvaděč: Obávám se, že obojí dveře jsou nosné. Za jedněmi život, který ještě můžete zachránit. Za druhými já, které ještě můžete dokázat. Oheň nepočká, až se poradíte s nějakým rámcem.',
  [roomChoiceTextKey('photograph', 'save-stranger')]: 'Levé dveře. Ten cizí člověk. Teď.',
  [roomChoiceHintKey('photograph', 'save-stranger')]: 'Život, za cenu sebe sama.',
  [roomChoiceOutcomeKey('photograph', 'save-stranger', 0)]: 'Jdete doleva. Ten cizí je těžší než kouř a lehčí, než jste se báli, a pak jste oba venku z toho hoření, plíce plné popela a aritmetiky.',
  [roomChoiceOutcomeKey('photograph', 'save-stranger', 1)]: 'Za vámi se pravá místnost zavírá jako kniha. Fotografie odchází s ní — a s fotografií vzpomínka, kterou ukotvovala. Cítíte, jak odchází. Je to přesně jako zub: nepřítomnost s hranami.',
  [roomChoiceOutcomeKey('photograph', 'save-stranger', 2)]: 'Ten cizí se na vás dívá. Uvědomíte si, že hledáte v jeho tváři svou vlastní, a nenacházíte ji, a že ten obchod už byl uzavřen. Někde vpředu si místnosti té díry všimnou.',
  [roomChoiceTextKey('photograph', 'save-photo')]: 'Pravé dveře. Ta fotografie. Nikomu nepomůžete, pokud tu nikdo nezůstane, aby vámi byl.',
  [roomChoiceHintKey('photograph', 'save-photo')]: 'Já sám, za cenu tíhy, kterou ponesete.',
  [roomChoiceOutcomeKey('photograph', 'save-photo', 0)]: 'Jdete doprava. Fotografie je teplá ve vašich rukou, mírně se kroutí, a jste na ní nezaměnitelně, prokazatelně vy — mladší, nespálení, dosvědčení.',
  [roomChoiceOutcomeKey('photograph', 'save-photo', 1)]: 'Kašel za levými dveřmi mění charakter, a pak se mění na ten nejhorší zvuk, kterým je žádný zvuk.',
  [roomChoiceOutcomeKey('photograph', 'save-photo', 2)]: 'Pořád držíte důkaz, kým jste bývali. Ten důkaz má teď nový titulek, napsaný v posledních deseti vteřinách, a váš úchop na všem je o jedno srdce volnější za to, že jej nesete.',
  [roomChoiceTextKey('photograph', 'try-both')]: 'Levé dveře — ale nejdřív se vrhněte přes pravé pro fotku. Neste obojí.',
  [roomChoiceHintKey('photograph', 'try-both')]: 'Odmítněte tu aritmetiku. Zaplaťte, co to stojí.',
  [roomChoiceOutcomeKey('photograph', 'try-both', 0)]: 'Uděláte tu lidskou věc, což je odmítnout nabídku. Pravé dveře — fotografie do bundy. Levé dveře — cizí člověk na rameno. Oheň, nedotčen vaší ambicí, si stejně vezme svá procenta.',
  [roomChoiceOutcomeKey('photograph', 'try-both', 1)]: 'Venku ten cizí dýchá. Sáhnete do bundy a vaše prsty najdou popel uspořádaný do tvaru obdélníku. Oheň vám dovolil to vynést; jen odmítl nechat to zůstat fotografií.',
  [roomChoiceOutcomeKey('photograph', 'try-both', 2)]: 'Uvaděč: Snažili jste se zachránit všechno, a zachránili jste tu osobu, a hrst popela tam, kde bývala ta fotografie. Pro co to stojí za to, je to volba, kterou vídám nejčastěji u poutníků, kterých si začínám vážit.',
  [roomNoteTitleKey('photograph')]: 'Co oheň roztřídí',
  [roomNoteThinkersKey('photograph')]: 'problém hořící budovy · William James (1890) o já · vlastnictví a identita',
  [roomNoteBodyKey('photograph')]: 'Etici používají hořící budovy tak, jako fyzici používají vakuum: aby obnažili volbu na její kostru. Cizí člověk proti rodinné památce je na papíře bezkonkurenční — život převáží předmět a každá teorie od Kanta po utilitaristy podepisuje stejný verdikt. Tak proč táhnou pravé dveře? Protože fotografie není majetek; je to infrastruktura. William James si všiml, že se já rozprostírá do svých věcí — „materiální já“ — a že jejich ztráta není jako ztráta peněz, ale jako ztráta údu osobnosti. Jediná dochovaná fotografie je externí záloha vnitřního souboru: zničte ji, a úsek vaší minulosti se stane nedosvědčeným, neodpřisáhnutelným, měkčím než fakt. **Oheň, jinými slovy, nabídl skutečný obchod — celou budoucnost někoho jiného proti kousku vaší minulosti — a odsoudil vás k tomu, abyste tu ztrátu cítili tak jako tak.** Ten pocit není slabost. Je to přesné čtení toho, co bylo skutečně ve hře.',
});
