// Czech translations, registered against the text catalog. UI chrome, act
// structure, room titles/hints/teasers, and endings are fully translated;
// long-form room prose (beats, choice outcomes, field notes) is not yet
// translated and gracefully falls back to English v2 (see resolver.ts).
import { registerAll } from '../../engine/text/resolver';
import { uiKey, actNameKey, actIntroKey, usherBarkKey, roomTitleKey, roomDoorHintKey, roomTeaserKey, endingTitleKey, endingEpitaphKey, keepsakeKey } from '../../engine/text/keys';

registerAll('v2', 'cs', {
  [uiKey('abandonToTitle')]: 'Opustit a vrátit se na titulní obrazovku',
  [uiKey('advanceHintClick')]: 'klikněte · mezerník',
  [uiKey('advanceHintContinue')]: 'pokračujte',
  [uiKey('heartsAriaLabel')]: 'úchop reality',
  [uiKey('exitGame')]: 'Ukončit hru',
  [uiKey('saveAndExit')]: 'Uložit a vrátit se na titulní obrazovku',
  [uiKey('settingsSectionDisplay')]: 'Zobrazení',
  [uiKey('settingFullscreen')]: 'Celá obrazovka',
  [uiKey('settingFullscreenDesc')]: 'Vyplní celou obrazovku — přepíná se i klávesou F.',
  [uiKey('renderScalePerformance')]: 'Rozlišení vykreslování: Výkon',
  [uiKey('renderScaleStandard')]: 'Rozlišení vykreslování: Standardní',
  [uiKey('renderScaleSharp')]: 'Rozlišení vykreslování: Ostré',
  [uiKey('settingRenderScale')]: 'Rozlišení vykreslování',
  [uiKey('settingRenderScaleDesc')]: 'Nižší = plynulejší na slabších grafických kartách, mírně měkčí obraz. Ostré využívá plné rozlišení obrazovky.',
  [uiKey('fpsCap30')]: 'Snímková frekvence: 30 fps (plynulejší na slabších grafických kartách)',
  [uiKey('fpsCap60')]: 'Snímková frekvence: 60 fps',
  [uiKey('settingFpsCap')]: 'Omezení snímkové frekvence',
  [uiKey('settingFpsCapDesc')]: 'Nižší hodnota citelně šetří grafický výkon — tohle je hra o mlze a textu, ne akční titul.',
  [uiKey('settingUiZoom')]: 'Velikost rozhraní',
  [uiKey('settingUiZoomDesc')]: 'Zvětší nebo zmenší nabídky a text podle vaší chuti — 3D scéna zůstává ostrá.',
  [uiKey('settingQualityDesc')]: 'Efekty záře a vyhlazování; vyžaduje výkonnější grafickou kartu. Projeví se při dalším spuštění.',
  [uiKey('settingDynamicSceneryDesc')]: 'Místnosti jemně zabarvují světlo a mlhu podle své nálady.',
  [uiKey('settingLightModeDesc')]: 'Stejný hotel, ranní světlo — tytéž pokoje, jemnější tón.',
  [uiKey('settingReducedMotionDesc')]: 'Zkrátí pohyb kamery a plynulé přechody téměř na okamžité — šetrnější k citlivosti na pohyb.',
  [uiKey('settingsSectionAudio')]: 'Zvuk',
  [uiKey('settingMusicDesc')]: 'Tichá, proměnlivá atmosféra, která se mění s každým dějstvím.',
  [uiKey('settingSfxDesc')]: 'Zvuky dveří, otáčení stránek a drobné zvuky volby.',
  [uiKey('settingsSectionText')]: 'Text a jazyk',
  [uiKey('settingLanguageDesc')]: 'Projeví se okamžitě, všude ve hře.',
  [uiKey('settingTextVersionDesc')]: 'v1 je původní hlas, uchovaný jako volitelná záloha; v2 je aktuální přepis.',
  [uiKey('settingTypewriterDesc')]: 'Text se objevuje písmeno po písmenu, jako by vám ho někdo vyprávěl.',
  [uiKey('settingHighContrastDesc')]: 'Světlejší barva textu pro snazší čtení.',
  [uiKey('settingExaminedPath')]: 'Prozkoumaná cesta — nabídnuta na začátku každé nové hry',
  [uiKey('settingExaminedPathDesc')]: 'Mění pouze to, co je předvybrané při zahájení nové hry — vždy budete dotázáni znovu a volba pro tuto hru zůstává nedotčena.',
  [uiKey('examinedOfferTitle')]: 'Přístavek pro průzkum',
  [uiKey('examinedOfferIntro')]: 'Přístavek zakládá komentáře. Nemá jeden názor — má čtyři.',
  [uiKey('examinedOfferBody')]: 'Volitelné razítko ve vašem spisu: po každé významné volbě vám tichý úředník ukáže, jak by ji mohlo číst několik pojmenovaných etických tradic — vedle sebe, záměrně se neshodujících. Nic tady se nehodnotí ani neboduje a žádné čtení není to „správné“. Místnosti, srdce i konce, kterých můžete dosáhnout, zůstávají naprosto stejné. Každou kartu zavřete jediným kliknutím. Výchozí volbu pro příště můžete kdykoli změnit v Nastavení.',
  [uiKey('walkPlainly')]: 'Jít prostou cestou',
  [uiKey('takeExaminedPath')]: 'Zvolit prozkoumanou cestu',
  [uiKey('annexHeader')]: 'Přístavek zaznamenává:',
  [uiKey('tradition.consequence')]: 'Důsledek',
  [uiKey('tradition.duty')]: 'Povinnost',
  [uiKey('tradition.virtue')]: 'Ctnost',
  [uiKey('tradition.care')]: 'Péče',
  [uiKey('settingsSectionData')]: 'Data',
  [uiKey('resetRun')]: 'Resetovat aktuální hru',
  [uiKey('confirmAgain')]: 'Klikněte znovu pro potvrzení',
  [uiKey('resetRunDesc')]: 'Opustí vaši rozehranou cestu. Poznámky, konce a nastavení zůstanou zachovány.',
  [uiKey('resetRunDone')]: 'Hra resetována',
  [uiKey('resetProgress')]: 'Resetovat veškerý postup',
  [uiKey('resetProgressDesc')]: 'Vymaže úplně vše — poznámky, konce, nastavení, vaši rozehranou hru — zpět na úplný začátek.',
  [uiKey('recoveryTitle')]: 'Zařízení zablikalo',
  [uiKey('recoveryBody')]: 'Něco v soukolí ztratilo rovnováhu. Váš soubor je v bezpečí — nic z toho, co jste tu udělali, se neztratilo.',
  [uiKey('recoveryReturn')]: 'Zpět na titulní obrazovku',
  [uiKey('restoredFromBackup')]: 'Vaše poslední uložení se nepodařilo načíst — obnoveno z předchozí zálohy. Nic by nemělo chybět.',
  [uiKey('saveFailed')]: 'Váš postup se nepodařilo uložit — úložiště je možná plné.',
  [uiKey('exportProfile')]: 'Exportovat profil',
  [uiKey('exportProfileDesc')]: 'Stáhne celý váš profil jako soubor — osobní záloha, nebo něco, co můžete poslat, pokud budete potřebovat pomoc.',
  [uiKey('exportProfileButton')]: 'Stáhnout',
  [uiKey('importProfile')]: 'Importovat profil',
  [uiKey('importProfileDesc')]: 'Nahradí celý váš profil vloženým souborem. Váš aktuální postup se přepíše — pokud si ho chcete ponechat, nejdřív ho exportujte.',
  [uiKey('importProfileButton')]: 'Importovat',
  [uiKey('importProfilePlaceholder')]: 'Sem vložte obsah exportovaného souboru profilu',
  [uiKey('importProfileSuccess')]: 'Importováno — načítám znovu…',
  [uiKey('importProfileError')]: 'Tohle nevypadá jako platný soubor profilu — nic se nezměnilo.',
  [uiKey('ledger')]: 'Cestovatelský deník',
  [uiKey('epiphaniesTitle')]: 'Poznání',
  [uiKey('epiphanyEarned')]: 'zaznamenáno dnes večer',
  [uiKey('ledgerRuns')]: 'Dokončené cesty',
  [uiKey('ledgerRooms')]: 'Spatřené místnosti',
  [uiKey('ledgerEndings')]: 'Spatřené konce',
  [uiKey('ledgerHearts')]: 'Ztracená srdce, celkem',
  [uiKey('ledgerMostWalked')]: 'Nejchozenější dveře',
  [uiKey('ledgerKeepsakes')]: 'Památky na poličce',
  [uiKey('ledgerDescents')]: 'Sestupy dolů',
  [uiKey('ledgerExamined')]: 'Prozkoumané cesty',
  [uiKey('ledgerLastMessage')]: 'Vaše poslední zpráva',
  [uiKey('aboutDoors')]: '<b>Dveře.</b> Každé dveře za chodbou skrývají jinou situaci a v jednom průchodu jimi nemůžete projít všemi. Volba dveří znamená volbu toho, čemu budete čelit — a co tentokrát vynecháte. Další hra vám ukáže zbytek.',
  [uiKey('aboutHearts')]: '<b>Srdce.</b> Tři srdce jsou váš úchop reality. Hrstka obzvlášť nákladných voleb — vždy předem oznámená Uvaděčem — stojí jedno srdce přímo, stejně jako když vaše lucidita zcela dojde. Ztráta všech tří není obrazovka prohry — je to opravdový konec, a tak je i napsán.',
  [uiKey('aboutTitle')]: 'Než začnete',
  [uiKey('aboutWhy')]: '<b>Proč hrát.</b> Nic tady není hodnoceno jako správné nebo špatné. Každá volba tiše posouvá tři skryté sklony — rozum proti citu, sebe proti druhým, kontrolu proti přijetí — a právě ty, ne bodovací tabulka, určují, které dveře se otevřou, jak zařízení vypadá a zní, a ke kterému z šesti konců nakonec dojdete. Odměněna je jen upřímná účast.',
  [uiKey('back')]: 'Zpět',
  [uiKey('begin')]: 'Začít',
  [uiKey('beginAgain')]: 'Začít znovu',
  [uiKey('codexSub')]: 'čím jste prošli — zůstává to prošlé',
  [uiKey('collected')]: 'sebráno',
  [uiKey('continue')]: 'Pokračovat',
  [uiKey('continueJourney')]: 'Pokračovat v cestě',
  [uiKey('creditsTitle')]: 'Titulky',
  [uiKey('vestibuleButton')]: 'The Vestibule — vyberte hru',
  [uiKey('creditsIntro')]: 'Napsáno, navrženo a vytvořeno nezávisle.',
  [uiKey('creditsEngine')]: '<b>Vykreslování a zvuk.</b> Každý vizuál je generovaná geometrie (Three.js) a každý zvuk je generován za běhu — žádné zakoupené ani stažené výtvarné či zvukové materiály.',
  [uiKey('creditsTooling')]: '<b>Postaveno na.</b> Three.js (licence MIT) · TypeScript · Vite · Electron (desktopová verze) · Vitest a Playwright (testování).',
  [uiKey('creditsFonts')]: '<b>Písma.</b> Inter, Spectral a Vazirmatn, přes Fontsource — každé licencováno pod SIL Open Font License 1.1.',
  [uiKey('creditsNotices')]: 'Úplné texty licencí třetích stran jsou v souboru THIRD_PARTY_NOTICES.md, distribuovaném společně s touto verzí.',
  [uiKey('creditsTelemetry')]: 'Nic z toho, jak hrajete, se nesleduje, nikam neodesílá ani nespojuje s účtem — vaše uložená hra existuje pouze v tomto prohlížeči nebo této instalaci.',
  [uiKey('done')]: 'Hotovo',
  [uiKey('doorHelp')]: 'vyberte cestu — klikněte na dveře, nebo stiskněte jejich číslo',
  [uiKey('doorHelpSingle')]: 'toto je jediná cesta vpřed — klikněte na dveře, nebo stiskněte 1',
  [uiKey('doorUnseenBadge')]: 'nové',
  [uiKey('doorUnseenBadgeTooltip')]: 'Těmito dveřmi jste ještě nikdy neprošli',
  [uiKey('explainButton')]: 'Vysvětlit jednoduše',
  [uiKey('explainLabel')]: 'Jednoduše řečeno',
  [uiKey('rememberedTag')]: 'vzpomínka',
  [uiKey('ending')]: 'Konec',
  [uiKey('endingFieldNoteHeader')]: 'Konec · Poznámka',
  [uiKey('endingsWitnessed')]: 'zažité konce',
  [uiKey('fieldNoteHeader')]: 'Poznámka',
  [uiKey('fieldNotes')]: 'Poznámky',
  [uiKey('heartsTooltip')]: 'Váš úchop reality. Pár nákladných voleb stojí jedno srdce přímo — Uvaděč vždy varuje předem — stejně jako úplné vyčerpání lucidity. Ztráta všech tří srdcí je konec, ne prohra.',
  [uiKey('howToAdvance')]: '<b>Klikněte</b> na text, nebo stiskněte <b>mezerník</b>, pro pokračování',
  [uiKey('howToClick')]: '<b>Klikněte</b> na dveře, nebo stiskněte <b>1–3</b>, pro volbu cesty',
  [uiKey('howToPause')]: '<b>Esc</b> pro pauzu · najetím na dveře zobrazíte nápovědu',
  [uiKey('lastMessageBody')]: 'Měli jste jednu větu, a toto byla ona:',
  [uiKey('lucidityTooltip')]: 'Lucidita — jak upřímně jste se dívali.',
  [uiKey('menu')]: 'Menu',
  [uiKey('notYetWalked')]: 'ještě neprošlé',
  [uiKey('of')]: 'z',
  [uiKey('off')]: 'vypnuto',
  [uiKey('on')]: 'zapnuto',
  [uiKey('paused')]: 'Pauza',
  [uiKey('pausedSub')]: 'místnosti počkají — čas je zde jen ozdoba',
  [uiKey('persona.daniel')]: 'Měříte dvakrát. Přesto se občas řízne špatně.',
  [uiKey('persona.mira')]: 'Všímala jste si věcí dřív, než vás o to kdokoli požádal.',
  [uiKey('persona.sara')]: 'Zůstáváte do konce věcí. Vždycky jste to tak měla.',
  [uiKey('persona.tomas')]: 'Odpouštíte pomalu, ale úplně, jakmile to uděláte.',
  [uiKey('persona.about1')]: 'Opatrní k druhým. Méně opatrní k sobě.',
  [uiKey('persona.about2')]: 'Rychle se zasmějete, pomalu řeknete, co se skutečně stalo.',
  [uiKey('persona.about3')]: 'Pořád tu jste. To je většina odpovědi, ve většině dní.',
  [uiKey('personaAboutLabel')]: 'O vás (nepovinné — nikomu se to neukáže, jen to procítí Uvaděč)',
  [uiKey('personaFreeTextPlaceholder')]: 'Nebo napište vlastní, stručně…',
  [uiKey('personaNameLabel')]: 'Jméno',
  [uiKey('personaNamePlaceholder')]: 'Vaše jméno (nebo jak vás tu mají oslovovat)',
  [uiKey('personaSkip')]: 'Přeskočit — říkejte mi poutník',
  [uiKey('personaSub')]: 'Čistě pro potřeby Uvaděče — nic to nemění na místnostech, jen na tom, jak k vám promlouvají.',
  [uiKey('personaTitle')]: 'Kdo jste dnes večer?',
  [uiKey('recapHeader')]: 'Čím jste prošli',
  [uiKey('resume')]: 'Pokračovat',
  [uiKey('savedToast')]: 'Uloženo',
  [uiKey('senderYou')]: 'odesílatel: vy',
  [uiKey('settingHighContrast')]: 'Vysoký kontrast textu',
  [uiKey('settingLanguage')]: 'Jazyk',
  [uiKey('settingMusic')]: 'Hudba na pozadí',
  [uiKey('settingQuality')]: 'Vysoká grafická kvalita',
  [uiKey('settingDynamicScenery')]: 'Dynamické prostředí (experimentální)',
  [uiKey('settingLightMode')]: 'Světlý režim',
  [uiKey('settingMusicVolume')]: 'Hlasitost hudby',
  [uiKey('settingSfxVolume')]: 'Hlasitost efektů',
  [uiKey('hudLanguageTooltip')]: 'Změnit jazyk (projeví se od dalšího momentu)',
  [uiKey('settingReducedMotion')]: 'Omezený pohyb',
  [uiKey('settingSfx')]: 'Zvukové efekty',
  [uiKey('settingTextVersion')]: 'Verze textu',
  [uiKey('settingTypewriter')]: 'Postupné psaní textu',
  [uiKey('settings')]: 'Nastavení',
  [uiKey('settingsFooter')]: 'změna kvality se projeví při dalším spuštění · jazyk a verze textu platí ihned',
  [uiKey('statHearts')]: 'zachovaná srdce',
  [uiKey('statLucidity')]: 'lucidita',
  [uiKey('statNewNotes')]: 'nové poznámky',
  [uiKey('title')]: 'Titulní obrazovka',
  [uiKey('titleTagline')]: 'cesta všemi místnostmi · každé dveře jsou otázkou · cesta zpět vede skrz',
  [uiKey('titleAgeAdvisory')]: '16+ · zralá témata',
  [uiKey('travelerLabel')]: 'Poutník',
  [uiKey('travellerFallback')]: 'poutníku',
  [uiKey('archiveBlurbFallback')]: 've spisu není žádný další popis',
  [uiKey('shelfTitle')]: 'Polička',
  [uiKey('keepsakeChoiceTooltip')]: 'Upomínka, tiše vydaná',
  [uiKey('versionV1')]: 'Hlas: v1 (původní)',
  [uiKey('versionV2')]: 'Hlas: v2 (nový)',
  [uiKey('walkAgain')]: 'Projít znovu — místnosti se nepřeskládají pro nikoho, ale vy jste se změnili',
  [uiKey('whoAreYou')]: 'Kdo jste?',

  [actNameKey(0)]: 'Prolog — Čekárna',
  [actNameKey(1)]: 'Dějství I — Mělčiny',
  [actNameKey(2)]: 'Dějství II — Strojovna',
  [actNameKey(3)]: 'Dějství III — Zrcadlo',
  [actNameKey(4)]: 'Dějství IV — Práh',

  [actIntroKey(1)]: 'Před vámi: chodba bytových dveří, každé prosakují teplým světlem domovů, které nikdy nebyly vaše. Obyčejné místnosti, zjistíte, jdou nejhlouběji. Varování, poutníku: pár těchto dveří stojí víc než čas — zvolte proti sobě, a srdce může odejít.',
  [actIntroKey(2)]: 'Chodba se otevírá do strojovny — ozubená kola velká jako měsíce a pomalé pásy nesoucí malé, lhostejné hvězdy. Tady se každou noc znovu odehrávají staré myšlenkové experimenty, pro posádku o jednom člověku. Některé staré experimenty si stále účtují vstupné. Měnou jsou tu srdce.',
  [actIntroKey(3)]: 'Podlaha se mění v černé zrcadlo. Vaše vlastní vzpomínky visí ve tmě jako diorámy, tváře změkčené za hranici rozpoznání. Zařízení nazývá toto křídlo archivním. Znamená to: vaše, {name}. Něco z toho, co tu najdete, má cenu, kterou ucítíte, ne jen uvidíte — a ano, tou cenou může být srdce.',
  [actIntroKey(4)]: 'Mlha řídne. Za ní, nezaměnitelně, ráno. Zbývají tři dveře, a pak práh. Vše od teď platí dvojnásob — ačkoli by Uvaděč řekl, že tomu tak vždy bylo. I tak blízko konci vás neopatrná volba může stát srdce.',

  [usherBarkKey('understory-hint')]: 'Uvaděč: Tyhle druhé dveře nejsou na mé mapě. Kdysi byly. Vezměte je, nebo ne; podruhé se už nenabídnou.',
  [usherBarkKey('gate-single-door')]: 'Uvaděč: Pro tento úsek zbývají jedny dveře. Ostatní už máte za sebou, vybrané nebo vynechané — což byla svým způsobem také volba. Tyto jsou prostě jediná cesta, která zůstává otevřená.',
  [usherBarkKey('first-choice-explainer')]: 'Uvaděč: Několik dveří, a jen některé budou tentokrát vaše — zbytek zůstává zavřený, prozatím. Každé skrývají jinou situaci, ne jiné skóre. Vyberte ty, jejichž otázku jste ochotni skutečně unést.',
  [usherBarkKey('second-run')]: 'Uvaděč: Vrátili jste se. Páka je tam, kde jste ji nechali; tady nic nepřerovnáváme — stálost je jediný luxus, který si toto zařízení dovolí.',
  [usherBarkKey('reason-low')]: 'Uvaděč: Vážíte každou místnost jako účetní knihu. Místnosti si toho všimly a podle toho upravily poznámky pod čarou.',
  [usherBarkKey('reason-high')]: 'Uvaděč: Cítíte tu všechno, otevřeně. Chodba je kvůli tomu teplejší. To není obrazné vyjádření.',
  [usherBarkKey('self-low')]: 'Uvaděč: Udržel jste se vcelku. Rozumný instinkt. Občas se zeptejte, k čemu to udržování vlastně je.',
  [usherBarkKey('self-high')]: 'Uvaděč: Pořád ze sebe rozdáváte kusy. Sluší vám to — ačkoli časem toho k rozdávání zbude méně.',
  [usherBarkKey('control-low')]: 'Uvaděč: Bojujete s každou místností. Obdivuji to. Místnosti to nechává klidnými.',
  [usherBarkKey('control-high')]: 'Uvaděč: Přestal jste ve vodě bojovat, poutníku. Plout je také dovednost. Stejně jako vědět, kde zůstal břeh.',
  [usherBarkKey('first-heart-loss')]: 'Uvaděč: Tady — srdce, vydáno. Cítíte to. Je to jen zařízení, které vede poctivou účetní knihu, nic víc. Zbývají vám {hearts}. Není to odpočet do prohry; je to prostě to, co ta volba stála.',
  [usherBarkKey('one-heart')]: 'Uvaděč: Zbývá jedno srdce. Nesmím se bát. Považujte toto za nejbližší možnou náhradu.',
  [usherBarkKey('high-lucidity')]: 'Uvaděč: V této hloubce vidíte neobvykle jasně. Jasnost je tu jediná měna, kterou dům nedokáže padělat.',
  [usherBarkKey('generic0')]: 'Uvaděč: Vyberte dveře. Všechny jsou vaše — což většina poutníků nevěří, dokud to není dávno za nimi.',
  [usherBarkKey('generic1')]: 'Uvaděč: Nespěchejte. Dveře to snáší lépe, než byste čekali.',
  [usherBarkKey('generic2')]: 'Uvaděč: Řekl bych vám, které bych si vybral já, ale vybral jsem si je všechny, jednou. Udělejte si vlastní závěr.',
  [usherBarkKey('generic3')]: 'Uvaděč: Nápovědy nad dveřmi jsou pravdivé. Falešná znamení tu nepoužíváme.',
  [usherBarkKey('generic4')]: 'Uvaděč: Není kam spěchat. Čas je tu jen ozdoba.',
  [usherBarkKey('generic5')]: 'Uvaděč: Cokoli vynecháte, zůstane tu, neotevřené, pro jinou návštěvu. Není to ztráta. Prostě to není tento příběh.',
  [usherBarkKey('generic6')]: 'Uvaděč: Přečtěte si nápovědu, než se rozhodnete. Není to ozdoba — je to jediný poctivý náhled, který dostanete.',
  [usherBarkKey('generic7')]: 'Uvaděč: Dveře už znají vaše jméno, {name}. Zajímá je jen to, co je ještě zbytek vás.',
  [usherBarkKey('remembered-room')]: 'Toto místo si pamatujete.',
  [usherBarkKey('examined-act1')]: 'Uvaděč: Zvolili byste totéž před svědky? Bylo by to lepší — nebo jen hezčí?',
  [usherBarkKey('examined-act2')]: 'Uvaděč: Když má stroj pravdu, záleží na tom proč?',
  [usherBarkKey('examined-act3')]: 'Uvaděč: Které z vašich dnešních důvodů byly opravdu vaše, a které jen zkoušky nazpaměť?',
  [usherBarkKey('examined-act4')]: 'Uvaděč: Kdyby se to nikdo nikdy nemohl dozvědět, projděte chodbou znovu. Změnilo by se něco?',

  [roomTitleKey('waiting-room')]: 'Čekárna',
  [roomDoorHintKey('waiting-room')]: 'Dveře, kterými už procházíte',
  [roomTeaserKey('waiting-room')]: 'Ať jste kdekoli, začíná to tady.',
  [roomTitleKey('wallet')]: 'Peněženka',
  [roomDoorHintKey('wallet')]: 'Dveře té věci, kterou nikdo neviděl',
  [roomTeaserKey('wallet')]: 'Zkouška bez svědků — kromě toho jediného, na kterém záleží.',
  [roomTitleKey('dinner-table')]: 'Jídelní stůl',
  [roomDoorHintKey('dinner-table')]: 'Dveře otázky, kterou už znáte',
  [roomTeaserKey('dinner-table')]: 'Otázka bez bezpečné odpovědi, položená někým, koho milujete.',
  [roomTitleKey('promotion')]: 'Povýšení',
  [roomDoorHintKey('promotion')]: 'Dveře účetní knihy a přítele',
  [roomTeaserKey('promotion')]: 'Věrnost a výhoda — zvítězit může jen jedna z nich.',
  [roomTitleKey('beggars-math')]: 'Žebrákova matematika',
  [roomDoorHintKey('beggars-math')]: 'Dveře blízkého a vzdáleného',
  [roomTeaserKey('beggars-math')]: 'Cizinec před vámi, nebo větší dobro, které nevidíte.',
  [roomTitleKey('quiet-alarm')]: 'Tichý poplach',
  [roomDoorHintKey('quiet-alarm')]: 'Dveře zvuku skrz zeď',
  [roomTeaserKey('quiet-alarm')]: 'Zeď, ticho, a rozhodnutí, které nelze vzít zpět.',
  [roomTitleKey('photograph')]: 'Fotografie',
  [roomDoorHintKey('photograph')]: 'Dveře, které jsou už teplé',
  [roomTeaserKey('photograph')]: 'Oheň za dvěma dveřmi. Tak jako tak něco ztratíte.',
  [roomTitleKey('buridans-queue')]: 'Buridanův přístavek',
  [roomDoorHintKey('buridans-queue')]: 'Dveře dvou dveří',
  [roomTeaserKey('buridans-queue')]: 'Volba, která je těžká jen proto, že nic ji neusnadňuje.',
  [roomTitleKey('the-reference')]: 'Doporučující dopis',
  [roomDoorHintKey('the-reference')]: 'Dveře vypůjčeného pera',
  [roomTeaserKey('the-reference')]: 'Někdo, koho milujete, potřebuje větu, která nemusí být pravdivá.',
  [roomTitleKey('junction')]: 'Křižovatka',
  [roomDoorHintKey('junction')]: 'Dveře páky a váhy',
  [roomTeaserKey('junction')]: 'Páka, most, a stejných pět životů, dvakrát.',
  [roomTitleKey('experience-machine')]: 'Stroj na zážitky',
  [roomDoorHintKey('experience-machine')]: 'Dveře, za kterými nic není špatně',
  [roomTeaserKey('experience-machine')]: 'Dokonalý život, zaručeně — pokud unesete, co to stojí.',
  [roomTitleKey('ship')]: 'Loď',
  [roomDoorHintKey('ship')]: 'Dveře vyměněných prken',
  [roomTeaserKey('ship')]: 'Kousek po kousku jste nahrazován. Kdo odejde ven?',
  [roomTitleKey('casino-pascal')]: 'Pascalovo kasino',
  [roomDoorHintKey('casino-pascal')]: 'Dveře s nekonečnou výhrou',
  [roomTeaserKey('casino-pascal')]: 'Sázka na Boha, u stolu, kde kurzy určuje dům.',
  [roomTitleKey('omelas')]: 'Město Omelas',
  [roomDoorHintKey('omelas')]: 'Třetí dveře, hučící slavnostním světlem',
  [roomTeaserKey('omelas')]: 'Radost města a cena, o které se nahlas nemluví.',
  [roomTitleKey('chinese-room')]: 'Čínský pokoj',
  [roomDoorHintKey('chinese-room')]: 'Dveře dokonalé odpovědi',
  [roomTeaserKey('chinese-room')]: 'Odpoví na cokoli, vašimi vlastními slovy.',
  [roomTitleKey('newcomb-annex')]: 'Newcombův přístavek',
  [roomDoorHintKey('newcomb-annex')]: 'Dveře už naplněné krabice',
  [roomTeaserKey('newcomb-annex')]: 'Vaše volba už byla předpovězena. Ještě není pozdě — nebo je?',
  [roomTitleKey('veil-of-ignorance')]: 'Závoj nevědomosti',
  [roomDoorHintKey('veil-of-ignorance')]: 'Dveře vytaženého losu',
  [roomTeaserKey('veil-of-ignorance')]: 'Navrhnete malý svět, a pak v něm budete žít.',
  [roomTitleKey('court-of-usher')]: 'Soud s Uvaděčem',
  [roomDoorHintKey('court-of-usher')]: 'Dveře s přibitým předvoláním',
  [roomTeaserKey('court-of-usher')]: 'Uvaděč stojí před soudem a vy jste soudce.',
  [roomTitleKey('teleporter')]: 'Teleport',
  [roomDoorHintKey('teleporter')]: 'Dveře, které jsou také zdí',
  [roomTeaserKey('teleporter')]: 'Stroj vás zničí a vytiskne kopii. Ta trvá na tom, že prošla.',
  [roomTitleKey('editor')]: 'Editor',
  [roomDoorHintKey('editor')]: 'Dveře červeného pera',
  [roomTeaserKey('editor')]: 'Škrtněte svou nejhorší vzpomínku navždy. Podívejte se, co držela.',
  [roomTitleKey('introduction')]: 'Představení',
  [roomDoorHintKey('introduction')]: 'Malé prosté dveře, zdvořile pootevřené',
  [roomTeaserKey('introduction')]: 'Místnost, která chce jen vědět, kdo skutečně jste.',
  [roomTitleKey('debt-of-dead')]: 'Dluh mrtvých',
  [roomDoorHintKey('debt-of-dead')]: 'Dveře, na které jste přísahal, že nikdy nezaklepete',
  [roomTeaserKey('debt-of-dead')]: 'Někdo, kdo vám ublížil, umírá a prosí o odpuštění.',
  [roomTitleKey('marys-room')]: 'Mariina místnost',
  [roomDoorHintKey('marys-room')]: 'Dveře šedé pracovny',
  [roomTeaserKey('marys-room')]: 'Ví úplně všechno o barvě, kterou nikdy neviděla.',
  [roomTitleKey('butterfly-dream')]: 'Motýlí sen',
  [roomDoorHintKey('butterfly-dream')]: 'Dveře papírové stěny',
  [roomTeaserKey('butterfly-dream')]: 'Někdo tu sní o někom. Není jasné, kterým směrem.',
  [roomTitleKey('swampman')]: 'Bažinný muž',
  [roomDoorHintKey('swampman')]: 'Dveře druhého kabátu',
  [roomTeaserKey('swampman')]: 'Někdo tam uvnitř nosí vaši tvář, a je z toho velmi zdvořilý.',
  [roomTitleKey('the-cave')]: 'Jeskyně',
  [roomDoorHintKey('the-cave')]: 'Nízké dveře se světlem ohně',
  [roomTeaserKey('the-cave')]: 'Stíny, které poznáte, promítané pro publikum jednoho.',
  [roomTitleKey('free-will')]: 'Čekárna svobodné vůle',
  [roomDoorHintKey('free-will')]: 'Dveře, které vás čekaly',
  [roomTeaserKey('free-will')]: 'Světla se rozsvítí dřív, než si vyberete. Prohráváte každou sázku, schválně.',
  [roomTitleKey('boulder')]: 'Balvan',
  [roomDoorHintKey('boulder')]: 'Dveře na úpatí kopce',
  [roomTeaserKey('boulder')]: 'Úkol, který se sám ruší. Otázkou je, jak ho ponesete.',
  [roomTitleKey('last-message')]: 'Poslední zpráva',
  [roomDoorHintKey('last-message')]: 'Dveře s poštovní schránkou',
  [roomTeaserKey('last-message')]: 'Jedna věta zpět do bdělého světa. Kdo ji dostane?',
  [roomTitleKey('door-that-asks')]: 'Dveře, které se ptají',
  [roomDoorHintKey('door-that-asks')]: 'Poslední dveře, které čtou váš spis',
  [roomTeaserKey('door-that-asks')]: 'Přečetly celý váš spis. Teď chtějí vědět, jestli si za ním stojíte.',
  [roomTitleKey('the-archive')]: 'Archiv · dole',
  [roomDoorHintKey('the-archive')]: 'Schodiště, které nebylo na mapě',
  [roomTeaserKey('the-archive')]: 'Někde dole je váš poslední běh už založen ve spisu.',
  [roomTitleKey('the-unchosen')]: 'Nevybrané · dole',
  [roomDoorHintKey('the-unchosen')]: 'Chodba dveří, které jste neotevřel',
  [roomTeaserKey('the-unchosen')]: 'Stály pootevřené celou dobu. Jedny to dělají pořád.',
  [roomTitleKey('the-echo')]: 'Ozvěna · dole',
  [roomDoorHintKey('the-echo')]: 'Místnost s druhou židlí',
  [roomTeaserKey('the-echo')]: 'Někdo už v ní sedí, a zní to jako vy.',

  [endingTitleKey('return')]: 'Návrat',
  [endingEpitaphKey('return')]: 'Svět byl přesně stejný. To nikdy nebyl slib.',
  [endingTitleKey('open-hand')]: 'Otevřená dlaň',
  [endingEpitaphKey('open-hand')]: 'Rozdal jste se, minci po minci, rád — většinou rád.',
  [endingTitleKey('fortress')]: 'Pevnost',
  [endingEpitaphKey('fortress')]: 'Nic se nedostalo dovnitř. To byl plán. Nic se nedostalo dovnitř.',
  [endingTitleKey('dissolved')]: 'Rozpuštěný',
  [endingEpitaphKey('dissolved')]: 'Moře nikdy neztratilo jedinou věc, na které záleželo.',
  [endingTitleKey('gardener')]: 'Zahradník',
  [endingEpitaphKey('gardener')]: 'Místnosti vždy potřebují strážce. Strážce vždy potřeboval místnosti.',
  [endingTitleKey('punchline')]: 'Pointa',
  [endingEpitaphKey('punchline')]: 'Nikdy tu nebyl nikdo jiný než vy. Dobrý vtip, že?',
});

// ---------- Keepsakes (Milestone 5, Phase N) ----------
registerAll('v2', 'cs', {
  [keepsakeKey('casino-chip', 'name')]: 'Neutracený žeton',
  [keepsakeKey('casino-chip', 'origin')]: 'ponecháno z kasina, neutraceno',
  [keepsakeKey('photo-corner', 'name')]: 'Roh fotografie',
  [keepsakeKey('photo-corner', 'origin')]: 'zachráněno z ohně, jeden roh z ní',
  [keepsakeKey('ship-splinter', 'name')]: 'Tříska z lodi',
  [keepsakeKey('ship-splinter', 'origin')]: 'ponecháno z dílny, původní dřevo',
  [keepsakeKey('release-form', 'name')]: 'Výstupní formulář stroje',
  [keepsakeKey('release-form', 'origin')]: 'podepsáno cestou ven, nikdy neodesláno',
});
