// Czech translations, registered against the text catalog. UI chrome, act
// structure, room titles/hints/teasers, and endings are fully translated;
// long-form room prose (beats, choice outcomes, field notes) is not yet
// translated and gracefully falls back to English v2 (see resolver.ts).
import { registerAll } from './resolver';
import { uiKey, actNameKey, actIntroKey, usherBarkKey, roomTitleKey, roomDoorHintKey, roomTeaserKey, endingTitleKey, endingEpitaphKey } from './keys';

registerAll('v2', 'cs', {
  [uiKey('abandonToTitle')]: 'Opustit a vrátit se na titulní obrazovku',
  [uiKey('aboutDoors')]: '<b>Dveře.</b> Každé dveře za chodbou skrývají jinou situaci a v jednom průchodu jimi nemůžete projít všemi. Volba dveří znamená volbu toho, čemu budete čelit — a co tentokrát vynecháte. Další hra vám ukáže zbytek.',
  [uiKey('aboutHearts')]: '<b>Srdce.</b> Tři srdce jsou váš úchop reality. Jedno ztratíte, když opakovaně odmítáte místnosti, když neuspějete v některé místnosti typu INSIGHT, cestou zásadovou, ale nákladnou volbou v místnostech typu DOOMED, nebo když vaše lucidita zcela dojde. Ztráta všech tří není obrazovka prohry — je to opravdový konec, a tak je i napsán.',
  [uiKey('aboutTitle')]: 'Než začnete',
  [uiKey('aboutWhy')]: '<b>Proč hrát.</b> Nic tady není hodnoceno jako správné nebo špatné. Každá volba tiše posouvá tři skryté sklony — rozum proti citu, sebe proti druhým, kontrolu proti přijetí — a právě ty, ne bodovací tabulka, určují, které dveře se otevřou, jak zařízení vypadá a zní, a ke kterému z šesti konců nakonec dojdete. Odměněna je jen upřímná účast.',
  [uiKey('back')]: 'Zpět',
  [uiKey('begin')]: 'Začít',
  [uiKey('beginAgain')]: 'Začít znovu',
  [uiKey('codexSub')]: 'čím jste prošli — zůstává to prošlé',
  [uiKey('collected')]: 'sebráno',
  [uiKey('continue')]: 'Pokračovat',
  [uiKey('continueJourney')]: 'Pokračovat v cestě',
  [uiKey('done')]: 'Hotovo',
  [uiKey('doorHelp')]: 'vyberte cestu — klikněte na dveře, nebo stiskněte jejich číslo',
  [uiKey('ending')]: 'Konec',
  [uiKey('endingFieldNoteHeader')]: 'Konec · Poznámka',
  [uiKey('endingsWitnessed')]: 'zažité konce',
  [uiKey('fieldNoteHeader')]: 'Poznámka',
  [uiKey('fieldNotes')]: 'Poznámky',
  [uiKey('heartsTooltip')]: 'Váš úchop reality. Ztrácí se opakovaným odmítáním místností, špatným zvládnutím některých místností, nebo když dojde lucidita. Ztráta všech tří srdcí je konec, ne prohra.',
  [uiKey('howToAdvance')]: '<b>Klikněte</b> na text, nebo stiskněte <b>mezerník</b>, pro pokračování',
  [uiKey('howToClick')]: '<b>Klikněte</b> na dveře, nebo stiskněte <b>1–3</b>, pro volbu cesty',
  [uiKey('howToPause')]: '<b>Esc</b> pro pauzu · najetím na dveře zobrazíte nápovědu',
  [uiKey('lastMessageBody')]: 'Měli jste jednu větu, a toto byla ona:',
  [uiKey('lucidityTooltip')]: 'Lucidita — jak upřímně jste se dívali.',
  [uiKey('menu')]: 'Menu',
  [uiKey('notYetWalked')]: 'ještě neprošlé',
  [uiKey('of')]: 'z',
  [uiKey('off')]: 'vypnuto',
  [uiKey('on')]: 'zapnuto',
  [uiKey('paused')]: 'Pauza',
  [uiKey('pausedSub')]: 'místnosti počkají — čas je zde jen ozdoba',
  [uiKey('persona.daniel')]: 'Měříte dvakrát. Přesto se občas řízne špatně.',
  [uiKey('persona.mira')]: 'Všímala jste si věcí dřív, než vás o to kdokoli požádal.',
  [uiKey('persona.sara')]: 'Zůstáváte do konce věcí. Vždycky jste to tak měla.',
  [uiKey('persona.tomas')]: 'Odpouštíte pomalu, ale úplně, jakmile to uděláte.',
  [uiKey('persona.about1')]: 'Opatrní k druhým. Méně opatrní k sobě.',
  [uiKey('persona.about2')]: 'Rychle se zasmějete, pomalu řeknete, co se skutečně stalo.',
  [uiKey('persona.about3')]: 'Pořád tu jste. To je většina odpovědi, ve většině dní.',
  [uiKey('personaAboutLabel')]: 'O vás (nepovinné — nikomu se to neukáže, jen to procítí Uvaděč)',
  [uiKey('personaFreeTextPlaceholder')]: 'Nebo napište vlastní, stručně…',
  [uiKey('personaNameLabel')]: 'Jméno',
  [uiKey('personaNamePlaceholder')]: 'Vaše jméno (nebo jak vás tu mají oslovovat)',
  [uiKey('personaSkip')]: 'Přeskočit — říkejte mi poutník',
  [uiKey('personaSub')]: 'Čistě pro potřeby Uvaděče — nic to nemění na místnostech, jen na tom, jak k vám promlouvají.',
  [uiKey('personaTitle')]: 'Kdo jste dnes večer?',
  [uiKey('recapHeader')]: 'Čím jste prošli',
  [uiKey('resume')]: 'Pokračovat',
  [uiKey('senderYou')]: 'odesílatel: vy',
  [uiKey('settingHighContrast')]: 'Vysoký kontrast textu',
  [uiKey('settingLanguage')]: 'Jazyk',
  [uiKey('settingMusic')]: 'Hudba na pozadí',
  [uiKey('settingQuality')]: 'Vysoká grafická kvalita',
  [uiKey('settingReducedMotion')]: 'Omezený pohyb',
  [uiKey('settingSfx')]: 'Zvukové efekty',
  [uiKey('settingTextVersion')]: 'Verze textu',
  [uiKey('settingTypewriter')]: 'Postupné psaní textu',
  [uiKey('settings')]: 'Nastavení',
  [uiKey('settingsFooter')]: 'změna kvality se projeví při dalším spuštění · jazyk a verze textu platí ihned',
  [uiKey('statHearts')]: 'zachovaná srdce',
  [uiKey('statLucidity')]: 'lucidita',
  [uiKey('statNewNotes')]: 'nové poznámky',
  [uiKey('title')]: 'Titulní obrazovka',
  [uiKey('titleTagline')]: 'cesta dvaceti místnostmi · každé dveře jsou otázkou · cesta zpět vede skrz',
  [uiKey('travelerLabel')]: 'Poutník',
  [uiKey('travellerFallback')]: 'poutníku',
  [uiKey('versionV1')]: 'Hlas: v1 (původní)',
  [uiKey('versionV2')]: 'Hlas: v2 (nový)',
  [uiKey('walkAgain')]: 'Projít znovu — místnosti se nepřeskládají pro nikoho, ale vy jste se změnili',
  [uiKey('whoAreYou')]: 'Kdo jste?',

  [actNameKey(0)]: 'Prolog — Čekárna',
  [actNameKey(1)]: 'Dějství I — Mělčiny',
  [actNameKey(2)]: 'Dějství II — Strojovna',
  [actNameKey(3)]: 'Dějství III — Zrcadlo',
  [actNameKey(4)]: 'Dějství IV — Práh',

  [actIntroKey(1)]: 'Před vámi: chodba bytových dveří, každé prosakují teplým světlem domovů, které nikdy nebyly vaše. Obyčejné místnosti, zjistíte, jdou nejhlouběji.',
  [actIntroKey(2)]: 'Chodba se otevírá do strojovny — ozubená kola velká jako měsíce a pomalé pásy nesoucí malé, lhostejné hvězdy. Tady se každou noc znovu odehrávají staré myšlenkové experimenty, pro posádku o jednom člověku.',
  [actIntroKey(3)]: 'Podlaha se mění v černé zrcadlo. Vaše vlastní vzpomínky visí ve tmě jako diorámy, tváře změkčené za hranici rozpoznání. Zařízení nazývá toto křídlo archivním. Znamená to: vaše.',
  [actIntroKey(4)]: 'Mlha řídne. Za ní, nezaměnitelně, ráno. Zbývají tři dveře, a pak práh. Vše od teď platí dvojnásob — ačkoli by Uvaděč řekl, že tomu tak vždy bylo.',

  [usherBarkKey('second-run')]: 'Uvaděč: Vrátili jste se. Páka je tam, kde jste ji nechali; tady nic nepřerovnáváme — stálost je jediný luxus, který si toto zařízení dovolí.',
  [usherBarkKey('reason-low')]: 'Uvaděč: Vážíte každou místnost jako účetní knihu. Místnosti si toho všimly a podle toho upravily poznámky pod čarou.',
  [usherBarkKey('reason-high')]: 'Uvaděč: Cítíte tu všechno, otevřeně. Chodba je kvůli tomu teplejší. To není obrazné vyjádření.',
  [usherBarkKey('self-low')]: 'Uvaděč: Udržel jste se vcelku. Rozumný instinkt. Občas se zeptejte, k čemu to udržování vlastně je.',
  [usherBarkKey('self-high')]: 'Uvaděč: Pořád ze sebe rozdáváte kusy. Sluší vám to — ačkoli časem toho k rozdávání zbude méně.',
  [usherBarkKey('control-low')]: 'Uvaděč: Bojujete s každou místností. Obdivuji to. Místnosti to nechává klidnými.',
  [usherBarkKey('control-high')]: 'Uvaděč: Přestal jste ve vodě bojovat, poutníku. Plout je také dovednost. Stejně jako vědět, kde zůstal břeh.',
  [usherBarkKey('one-heart')]: 'Uvaděč: Zbývá jedno srdce. Nesmím se bát. Považujte toto za nejbližší možnou náhradu.',
  [usherBarkKey('high-lucidity')]: 'Uvaděč: V této hloubce vidíte neobvykle jasně. Jasnost je tu jediná měna, kterou dům nedokáže padělat.',
  [usherBarkKey('generic0')]: 'Uvaděč: Vyberte dveře. Všechny jsou vaše — což většina poutníků nevěří, dokud to není dávno za nimi.',
  [usherBarkKey('generic1')]: 'Uvaděč: Nespěchejte. Dveře to snáší lépe, než byste čekali.',
  [usherBarkKey('generic2')]: 'Uvaděč: Řekl bych vám, které bych si vybral já, ale vybral jsem si je všechny, jednou. Udělejte si vlastní závěr.',
  [usherBarkKey('generic3')]: 'Uvaděč: Nápovědy nad dveřmi jsou pravdivé. Falešná znamení tu nepoužíváme.',
  [usherBarkKey('generic4')]: 'Uvaděč: Není kam spěchat. Čas je tu jen ozdoba.',

  [roomTitleKey('waiting-room')]: 'Čekárna',
  [roomDoorHintKey('waiting-room')]: 'Dveře, kterými už procházíte',
  [roomTeaserKey('waiting-room')]: 'Ať jste kdekoli, začíná to tady.',
  [roomTitleKey('wallet')]: 'Peněženka',
  [roomDoorHintKey('wallet')]: 'Dveře té věci, kterou nikdo neviděl',
  [roomTeaserKey('wallet')]: 'Zkouška bez svědků — kromě toho jediného, na kterém záleží.',
  [roomTitleKey('dinner-table')]: 'Jídelní stůl',
  [roomDoorHintKey('dinner-table')]: 'Dveře otázky, kterou už znáte',
  [roomTeaserKey('dinner-table')]: 'Otázka bez bezpečné odpovědi, položená někým, koho milujete.',
  [roomTitleKey('promotion')]: 'Povýšení',
  [roomDoorHintKey('promotion')]: 'Dveře účetní knihy a přítele',
  [roomTeaserKey('promotion')]: 'Věrnost a výhoda — zvítězit může jen jedna z nich.',
  [roomTitleKey('beggars-math')]: 'Žebrákova matematika',
  [roomDoorHintKey('beggars-math')]: 'Dveře blízkého a vzdáleného',
  [roomTeaserKey('beggars-math')]: 'Cizinec před vámi, nebo větší dobro, které nevidíte.',
  [roomTitleKey('quiet-alarm')]: 'Tichý poplach',
  [roomDoorHintKey('quiet-alarm')]: 'Dveře zvuku skrz zeď',
  [roomTeaserKey('quiet-alarm')]: 'Zeď, ticho, a rozhodnutí, které nelze vzít zpět.',
  [roomTitleKey('photograph')]: 'Fotografie',
  [roomDoorHintKey('photograph')]: 'Dveře, které jsou už teplé',
  [roomTeaserKey('photograph')]: 'Oheň za dvěma dveřmi. Tak jako tak něco ztratíte.',
  [roomTitleKey('junction')]: 'Křižovatka',
  [roomDoorHintKey('junction')]: 'Dveře páky a váhy',
  [roomTeaserKey('junction')]: 'Páka, most, a stejných pět životů, dvakrát.',
  [roomTitleKey('experience-machine')]: 'Stroj na zážitky',
  [roomDoorHintKey('experience-machine')]: 'Dveře, za kterými nic není špatně',
  [roomTeaserKey('experience-machine')]: 'Dokonalý život, zaručeně — pokud unesete, co to stojí.',
  [roomTitleKey('ship')]: 'Loď',
  [roomDoorHintKey('ship')]: 'Dveře vyměněných prken',
  [roomTeaserKey('ship')]: 'Kousek po kousku jste nahrazován. Kdo odejde ven?',
  [roomTitleKey('casino-pascal')]: 'Pascalovo kasino',
  [roomDoorHintKey('casino-pascal')]: 'Dveře s nekonečnou výhrou',
  [roomTeaserKey('casino-pascal')]: 'Sázka na Boha, u stolu, kde kurzy určuje dům.',
  [roomTitleKey('omelas')]: 'Město Omelas',
  [roomDoorHintKey('omelas')]: 'Třetí dveře, hučící slavnostním světlem',
  [roomTeaserKey('omelas')]: 'Radost města a cena, o které se nahlas nemluví.',
  [roomTitleKey('court-of-usher')]: 'Soud s Uvaděčem',
  [roomDoorHintKey('court-of-usher')]: 'Dveře s přibitým předvoláním',
  [roomTeaserKey('court-of-usher')]: 'Uvaděč stojí před soudem a vy jste soudce.',
  [roomTitleKey('teleporter')]: 'Teleport',
  [roomDoorHintKey('teleporter')]: 'Dveře, které jsou také zdí',
  [roomTeaserKey('teleporter')]: 'Stroj vás zničí a vytiskne kopii. Ta trvá na tom, že prošla.',
  [roomTitleKey('editor')]: 'Editor',
  [roomDoorHintKey('editor')]: 'Dveře červeného pera',
  [roomTeaserKey('editor')]: 'Škrtněte svou nejhorší vzpomínku navždy. Podívejte se, co držela.',
  [roomTitleKey('introduction')]: 'Představení',
  [roomDoorHintKey('introduction')]: 'Malé prosté dveře, zdvořile pootevřené',
  [roomTeaserKey('introduction')]: 'Místnost, která chce jen vědět, kdo skutečně jste.',
  [roomTitleKey('debt-of-dead')]: 'Dluh mrtvých',
  [roomDoorHintKey('debt-of-dead')]: 'Dveře, na které jste přísahal, že nikdy nezaklepete',
  [roomTeaserKey('debt-of-dead')]: 'Někdo, kdo vám ublížil, umírá a prosí o odpuštění.',
  [roomTitleKey('free-will')]: 'Čekárna svobodné vůle',
  [roomDoorHintKey('free-will')]: 'Dveře, které vás čekaly',
  [roomTeaserKey('free-will')]: 'Světla se rozsvítí dřív, než si vyberete. Prohráváte každou sázku, schválně.',
  [roomTitleKey('boulder')]: 'Balvan',
  [roomDoorHintKey('boulder')]: 'Dveře na úpatí kopce',
  [roomTeaserKey('boulder')]: 'Úkol, který se sám ruší. Otázkou je, jak ho ponesete.',
  [roomTitleKey('last-message')]: 'Poslední zpráva',
  [roomDoorHintKey('last-message')]: 'Dveře s poštovní schránkou',
  [roomTeaserKey('last-message')]: 'Jedna věta zpět do bdělého světa. Kdo ji dostane?',
  [roomTitleKey('door-that-asks')]: 'Dveře, které se ptají',
  [roomDoorHintKey('door-that-asks')]: 'Poslední dveře, které čtou váš spis',
  [roomTeaserKey('door-that-asks')]: 'Přečetly celý váš spis. Teď chtějí vědět, jestli si za ním stojíte.',

  [endingTitleKey('return')]: 'Návrat',
  [endingEpitaphKey('return')]: 'Svět byl přesně stejný. To nikdy nebyl slib.',
  [endingTitleKey('open-hand')]: 'Otevřená dlaň',
  [endingEpitaphKey('open-hand')]: 'Rozdal jste se, minci po minci, rád — většinou rád.',
  [endingTitleKey('fortress')]: 'Pevnost',
  [endingEpitaphKey('fortress')]: 'Nic se nedostalo dovnitř. To byl plán. Nic se nedostalo dovnitř.',
  [endingTitleKey('dissolved')]: 'Rozpuštěný',
  [endingEpitaphKey('dissolved')]: 'Moře nikdy neztratilo jedinou věc, na které záleželo.',
  [endingTitleKey('gardener')]: 'Zahradník',
  [endingEpitaphKey('gardener')]: 'Místnosti vždy potřebují strážce. Strážce vždy potřeboval místnosti.',
  [endingTitleKey('punchline')]: 'Pointa',
  [endingEpitaphKey('punchline')]: 'Nikdy tu nebyl nikdo jiný než vy. Dobrý vtip, že?',
});
