// German translation of the v2 room prose (beats, choice text/hint/outcome,
// field notes, explanations) for the prologue and Act I. Registered under
// version 'v2'. Translated from the English v2 source directly, per
// CLAUDE.md's context-first rule.
import { registerAll } from '../../engine/text/resolver';
import {
  roomBeatKey,
  roomChoiceHintKey,
  roomChoiceOutcomeKey,
  roomChoiceTextKey,
  roomExplanationKey,
  roomNoteBodyKey,
  roomNoteThinkersKey,
  roomNoteTitleKey,
} from '../../engine/text/keys';

// ---------- Prologue ----------
registerAll('v2', 'de', {
  [roomBeatKey('waiting-room', 0, 0)]: 'Sie erwachen in einem Wartezimmer. Es riecht nach einem Krankenhaus, einem Flur aus der Kindheit, und Regen.',
  [roomBeatKey('waiting-room', 0, 1)]: 'Es gibt Stühle. Eine Uhr ohne Zeiger. Ein Fenster, und hinter dem Fenster noch mehr Fenster.',
  [roomBeatKey('waiting-room', 0, 2)]: 'Sie erinnern sich nicht an Ihren Namen. Sie tasten danach, wie eine Zunge nach einem fehlenden Zahn tastet.',
  [roomBeatKey('waiting-room', 0, 3)]: 'Etwas ist geschehen. Ein Zusammenbruch, ein Trip, ein Unfall, ein Tod — das Wort rutscht immer wieder ab. Was immer es war, es nahm den Rest von Ihnen mit und legte die Teile irgendwo zu den Akten.',
  [roomBeatKey('waiting-room', 0, 4)]: 'Ein Schatten sitzt hinter dem Empfangstresen, mit einer Aureole und einem kleinen Paar Hörner. Eines der Hörner flackert schwach, wie ein Schild, das fast ausgedient hat.',
  [roomBeatKey('waiting-room', 0, 5)]: 'Platzanweiser: Sie sind wach. Das ist entweder eine sehr gute Nachricht, oder die schlimmste Art. Ich habe aufgehört zu raten, welche von beidem.',
  [roomBeatKey('waiting-room', 0, 6)]: 'Platzanweiser: Dies ist die Verarbeitung. Sie wurden aufgelöst — es geschieht, irgendwann, fast jedem, und heute geschah es Ihnen. Was von Ihnen übrig ist, wird in den Räumen vor Ihnen aufbewahrt. Gehen Sie ehrlich durch genug von ihnen, und Sie könnten sich wieder zusammenfügen. Oder auch nicht. Ich bin verpflichtet, das zu sagen.',
  [roomChoiceTextKey('waiting-room', 'where')]: '„Wo bin ich?“',
  [roomChoiceHintKey('waiting-room', 'where')]: 'Erst die Orientierung.',
  [roomChoiceOutcomeKey('waiting-room', 'where', 0)]: 'Platzanweiser: Zwischen. Hinter. Unter. Die Worte für diesen Ort sind meist Präpositionen — nichts so Festes wie ein Substantiv.',
  [roomChoiceOutcomeKey('waiting-room', 'where', 1)]: 'Platzanweiser: Was zählt, ist die Richtung: vorwärts, durch die Räume. Jeder hält eine Situation bereit; Sie wählen Ihren Weg hindurch, und dieses Wählen ist es, was Sie wieder zusammensetzt — oder das Auseinanderfallen vollendet. Wir führen eine grobe Rechnung, in Herzen, und darin, wie klar Sie sehen. Verlieren Sie den Griff völlig, gibt es schlimmere Enden als das. Es gibt auch bessere.',
  [roomChoiceTextKey('waiting-room', 'who')]: '„Sind Sie Gott oder der Teufel?“',
  [roomChoiceHintKey('waiting-room', 'who')]: 'Lernen Sie Ihren Beamten kennen.',
  [roomChoiceOutcomeKey('waiting-room', 'who', 0)]: 'Platzanweiser: Gott, an den ungeraden Tagen. Der Teufel, an den geraden. Ich sage Ihnen nicht, welcher Tag heute ist — nach so vielen Jahrhunderten in diesem Amt bin selbst ich mir nicht mehr sicher, welche Rolle welche ist.',
  [roomChoiceOutcomeKey('waiting-room', 'who', 1)]: 'Platzanweiser: Sie werden die Regeln wollen, also: Räume enthalten Situationen, Situationen enthalten Entscheidungen, und Entscheidungen enthalten Sie. Herzen sind Ihr Griff auf das Wirkliche — Sie haben drei. Klarheit ist, wie ehrlich Sie bereit sind hinzusehen. Ich behalte beides im Auge. Das ist, offiziell, meine einzige eigentliche Pflicht hier.',
  [roomChoiceTextKey('waiting-room', 'back')]: '„Ich will zurück. Jetzt.“',
  [roomChoiceHintKey('waiting-room', 'back')]: 'Direkt auf den Punkt.',
  [roomChoiceOutcomeKey('waiting-room', 'back', 0)]: 'Platzanweiser: Das will jeder. Hier ist die gute Nachricht: „Zurück“ existiert. Und hier ist der Rest — der Weg führt durch jedes Stück von Ihnen, das wir zu den Akten genommen haben. Die freundlichen Entscheidungen. Die feigen. Die, die Sie sich nie erlaubt haben, zu Ende zu denken.',
  [roomChoiceOutcomeKey('waiting-room', 'back', 1)]: 'Platzanweiser: Es gibt keine Abkürzung hindurch. Man hat es versucht. Niemand hat bisher eine gefunden.',
  [roomExplanationKey('waiting-room', 0)]: 'Sie sind gerade aufgewacht, ohne sich zu erinnern, wer Sie sind — und hier nennt man das „aufgelöst“. Der Platzanweiser ist Ihr Führer, nicht ganz gut, nicht ganz böse, einfach jemand, der einen seltsamen Job erledigt. Die drei Fragen hier haben keine richtige Antwort; sie sind nur Ihre erste Gelegenheit, sich zu orientieren. Stellen Sie sich vor, Sie erwachen nach einem schlimmen Unfall im Krankenhaus, orientierungslos, und jemand Freundlich-Merkwürdiges versucht Ihnen zu erklären, wo Sie sind, bevor Sie bereit sind, es zu hören. Was immer Sie fragen — Sie werden nicht geprüft, Sie wählen nur, wie Sie beginnen wollen, sich selbst wiederzufinden.',
  [roomNoteTitleKey('waiting-room')]: 'Anamnese',
  [roomNoteThinkersKey('waiting-room')]: 'Platon · Menon, Phaidon',
  [roomNoteBodyKey('waiting-room')]: 'Platon schlug etwas Seltsames vor: dass Lernen nicht das Erwerben von Neuem ist, sondern das Erinnern des Vergessenen — Anamnese, die Erinnerung der Seele an das, was sie vor der Geburt wusste, bevor sie in einen Körper zerstreut wurde. Im Menon zieht Sokrates Geometrie aus einem ungebildeten Jungen heraus, um zu zeigen, dass das Wissen bereits da war, wartend, dass man zu ihm zurückfindet. Man muss die Metaphysik nicht glauben, um die Wahrheit in ihrer Form zu spüren: die Momente, die uns am meisten verändern, fühlen sich selten wie Hinzufügungen an. **Sie fühlen sich an wie Wiedererkennen — „das wusste ich, und hatte dafür gesorgt, es nicht zu wissen.“** Dieses Spiel nimmt Platon einmal wörtlich. Ihr Selbst wurde in Räume abgelegt, und der Weg zurück ist keine Erfindung, sondern Erinnerung: Wählen, und beobachten, woran die Wahl Sie erinnert. Die Uhr hat keine Zeiger, weil Erinnerung nicht in der Zeit geschieht. Sie geschieht in Räumen. Eine Randnotiz, in älterer Handschrift: diejenigen, die sich an alles erinnern, benutzen die Tür überhaupt nicht.',
});

// ---------- Act I: The Wallet ----------
registerAll('v2', 'de', {
  [roomBeatKey('wallet', 0, 0)]: 'Ein Korridor aus Wohnungstüren, jede sickert das warme Licht von Zuhause, die niemals Ihre waren. Auf der Fußmatte vor einer davon: eine Brieftasche.',
  [roomBeatKey('wallet', 0, 1)]: 'Darin — Bargeld. Viel davon, in den müden Stückelungen von jemandem, der nachzählt. Um die Scheine gefaltet, eine Räumungsklage mit einem baldigen Datum und einer Adresse vierzig Minuten von überall entfernt.',
  [roomBeatKey('wallet', 0, 2)]: 'Der Korridor ist leer. Er hat die besondere Leere eines Ortes, an dem man alles tun könnte.',
  [roomBeatKey('wallet', 0, 3)]: 'Platzanweiser: Keine Kamera erreicht diesen Korridor. Ich habe nachgesehen. Keine von ihnen zählt ohnehin für irgendetwas, was eigentlich der Sinn einer solchen Prüfung ist.',
  [roomChoiceTextKey('wallet', 'return-all')]: 'Bringen Sie sie zur Adresse. Jetzt, persönlich, vollständig.',
  [roomChoiceHintKey('wallet', 'return-all')]: 'Der lange Weg.',
  [roomChoiceOutcomeKey('wallet', 'return-all', 0)]: 'Der Weg ist lang, und die Treppe am Ende ist noch länger. Die Person, die die Tür öffnet, blickt auf die Brieftasche, dann auf Sie, und ihr Gesicht macht etwas, das Sie behalten werden.',
  [roomChoiceOutcomeKey('wallet', 'return-all', 1)]: 'Sie bieten keine Belohnung an. Das ist, irgendwie, die Belohnung — die Transaktion blieb sauber.',
  [roomChoiceOutcomeKey('wallet', 'return-all', 2)]: 'Platzanweiser: Sie taten das Kostspielige, als das Kostenlose zur Verfügung stand. Ich habe es mir notiert. Das tue ich nur selten.',
  [roomChoiceTextKey('wallet', 'mail-it')]: 'Bewahren Sie sie sicher auf und schicken Sie sie unversehrt mit der Post.',
  [roomChoiceHintKey('wallet', 'mail-it')]: 'Effiziente Anständigkeit.',
  [roomChoiceOutcomeKey('wallet', 'mail-it', 0)]: 'Sie versiegeln sie, adressieren sie, und sie verlässt Ihre Hände. Vernünftig. Vollständig. Eine Anständigkeit in Form eines Botengangs.',
  [roomChoiceOutcomeKey('wallet', 'mail-it', 1)]: 'Sie werden das Gesicht am anderen Ende nie sehen. Sie ersparten sich vierzig Minuten und gaben das Gesicht dafür her.',
  [roomChoiceOutcomeKey('wallet', 'mail-it', 2)]: 'Platzanweiser: Korrekt, und blutleer. Eine Tugend, die sich selbst so ordentlich zu den Akten legt — davon habe ich schon viele gesehen.',
  [roomChoiceTextKey('wallet', 'finders-fee')]: 'Nehmen Sie sich ein kleines Finderlohn — Sie haben ihn sich verdient — und geben Sie den Rest zurück.',
  [roomChoiceHintKey('wallet', 'finders-fee')]: 'Eine vernünftige Regelung.',
  [roomChoiceOutcomeKey('wallet', 'finders-fee', 0)]: 'Das Argument setzt sich mit wunderschöner Geschwindigkeit selbst zusammen: Ihre Zeit hat einen Wert, jeder würde es tun, sie würden es von Ihnen erwarten, es ist praktisch eine Dienstleistung.',
  [roomChoiceOutcomeKey('wallet', 'finders-fee', 1)]: 'Bemerken Sie, wie gut das Argument ist. Bemerken Sie, wer es angeheuert hat, und wann — nachdem die Hand schon in der Brieftasche war.',
  [roomChoiceOutcomeKey('wallet', 'finders-fee', 2)]: 'Platzanweiser: Das Honorar. Der Verstand hält für genau diesen Moment einen Anwalt auf Abruf bereit, und Ihrer argumentiert gut.',
  [roomChoiceTextKey('wallet', 'keep-it')]: 'Behalten Sie sie. Niemand sieht zu.',
  [roomChoiceHintKey('wallet', 'keep-it')]: 'Der leere Korridor.',
  [roomChoiceOutcomeKey('wallet', 'keep-it', 0)]: 'Sie wandert fast lautlos in Ihre Tasche. Das ist das Seltsame daran — wie still es ist, wie sich der Korridor überhaupt nicht verändert.',
  [roomChoiceOutcomeKey('wallet', 'keep-it', 1)]: 'Irgendwo, vierzig Minuten von überall entfernt, kommt ein Datum planmäßig heran.',
  [roomChoiceOutcomeKey('wallet', 'keep-it', 2)]: 'Platzanweiser: Zu Protokoll: Jemand hat zugesehen. Sie. Das ist kein Fehler in der Anordnung. Das war schon immer der Sinn davon.',
  [roomExplanationKey('wallet', 0)]: 'Sie haben die Brieftasche eines Fremden voller Bargeld gefunden, und niemand sieht zu. Das ist eine der ältesten Fragen der Philosophie: Sind Sie nur ehrlich, weil Sie Angst haben, erwischt zu werden? Stellen Sie sich vor, Sie finden Bargeld auf einer leeren Straße ohne Kameras, ohne Zeugen — würden Sie es trotzdem zurückgeben? Der Philosoph Platon erzählte eine Geschichte von einem magischen Ring, der einen unsichtbar macht, um genau das zu fragen: Wenn Ihnen nie etwas Schlimmes widerführe, wenn Sie ihn behielten, würden Sie es tun? Es gibt hier keine Fangfrage — es wird nur gefragt, was für ein Mensch Sie sind, wenn niemand Sie bewertet.',
  [roomNoteTitleKey('wallet')]: 'Der Ring des Gyges',
  [roomNoteThinkersKey('wallet')]: 'Platon · Politeia II — Glaukon · Tugendethik',
  [roomNoteBodyKey('wallet')]: 'In der Politeia erzählt Glaukon von einem Hirten, der einen Ring findet, der ihn unsichtbar macht — und prompt die Königin verführt und das Königreich übernimmt. Seine Herausforderung an Sokrates: Niemand ist freiwillig gerecht. Entfernt man die Zeugen und die Strafe, gehen der Gerechte und der Ungerechte denselben Weg. Die Brieftasche im leeren Korridor ist der Ring mit abgefeilten Seriennummern. Die Tugendethik antwortet Glaukon anders als Regeln: Die Frage ist nicht „Was geschieht mir, wenn ich es nehme?“, sondern „Was werde ich, als die Person, die es genommen hat?“ **Jede unbeobachtete Entscheidung ist eine Probe, und der Charakter ist das, wozu sich die Proben summieren.** Und beachten Sie das Finderlohn — Rationalisierung ist nicht die Abwesenheit von Vernunft, sondern ihr Missbrauch, ein nachträglich für das Urteil rekrutiertes Argument. Der Korridor war nie leer. Sie wohnen dort.',
});

// ---------- Act I: The Dinner Table ----------
registerAll('v2', 'de', {
  [roomBeatKey('dinner-table', 0, 0)]: 'Eine Küche, die Sie fast wiedererkennen. Tee, der in den guten Tassen kalt wird, die nur benutzt werden, wenn etwas nicht stimmt.',
  [roomBeatKey('dinner-table', 0, 1)]: 'Ihre Großmutter sitzt Ihnen gegenüber. Sie war seit Wochen anderswo — dem langen, sich auflösenden Anderswo —, aber heute Abend sind ihre Augen ihre eigenen, plötzlich und klar, und sie hat gezielt auf Sie gewartet.',
  [roomBeatKey('dinner-table', 0, 2)]: 'Sie nimmt Ihre Hand. Ihr Griff ist das Stärkste, was ihr geblieben ist.',
  [roomBeatKey('dinner-table', 0, 3)]: '„Es wird wieder besser werden“, sagt sie. „Nicht wahr?“',
  [roomBeatKey('dinner-table', 0, 4)]: 'Es ist kaum eine Frage. Es ist eine Tür, die sie offen hält, und Sie können nicht sagen, von welcher Seite.',
  [roomChoiceTextKey('dinner-table', 'truth')]: 'Sagen Sie ihr die Wahrheit, sanft und ganz.',
  [roomChoiceHintKey('dinner-table', 'truth')]: 'Was sie vielleicht wollte.',
  [roomChoiceOutcomeKey('dinner-table', 'truth', 0)]: 'Sie sagen es. Die Worte sind in der Luft schlimmer, als sie in Ihrer Brust waren, und dann, seltsamerweise, besser.',
  [roomChoiceOutcomeKey('dinner-table', 'truth', 1)]: 'Sie schweigt lange. Dann: „Gut. Ich hasse es, behandelt zu werden.“ Sie drückt Ihre Hand einmal, wie beim Unterschreiben von etwas.',
  [roomChoiceOutcomeKey('dinner-table', 'truth', 2)]: 'Sie werden nie wissen, ob das Erleichterung auf ihrem Gesicht war, oder die letzte Freundlichkeit, die sie Ihnen erwies — vorzugeben, Ihre Ehrlichkeit sei ein Geschenk.',
  [roomChoiceTextKey('dinner-table', 'kind-lie')]: '„Natürlich wirst du das. Bis zum Frühling.“',
  [roomChoiceHintKey('dinner-table', 'kind-lie')]: 'Die Gnade darin.',
  [roomChoiceOutcomeKey('dinner-table', 'kind-lie', 0)]: 'Ihre Schultern sinken herab. Sie spricht vom Frühling — vom Garten, genauer gesagt, von dem Streit, den sie gegen die Schnecken zu gewinnen gedenkt.',
  [roomChoiceOutcomeKey('dinner-table', 'kind-lie', 1)]: 'Der Abend ist warm, und die Wärme ist echt, auch wenn ihr Fundament es nicht ist. Sie haben sie erkauft. Sie hat sie gut ausgegeben.',
  [roomChoiceOutcomeKey('dinner-table', 'kind-lie', 2)]: 'Sie werden nie wissen, ob sie Ihnen glaubte, oder Sie glauben ließ, sie glaube Ihnen, damit es Ihnen gut gehen würde.',
  [roomChoiceTextKey('dinner-table', 'deflect')]: '„Die Ärzte tun alles, was sie können.“',
  [roomChoiceHintKey('dinner-table', 'deflect')]: 'Wahr, und keine Antwort.',
  [roomChoiceOutcomeKey('dinner-table', 'deflect', 0)]: 'Ein Satz, konstruiert, um wahr zu sein und nichts zu sagen — der Diplomat unter den Sätzen. Sie hört beide Hälften.',
  [roomChoiceOutcomeKey('dinner-table', 'deflect', 1)]: '„Ja“, sagt sie, und blickt aus dem Fenster, und entlässt Sie aus der Frage, so wie man einen Vogel freilässt, der sich als zu klein zum Fressen herausstellte.',
  [roomChoiceOutcomeKey('dinner-table', 'deflect', 2)]: 'Der Tee wird kälter. Etwas Ehrliches wäre hier fast geschehen, und Sie beide stimmten höflich zu, es zu verpassen.',
  [roomChoiceTextKey('dinner-table', 'silence')]: 'Sagen Sie nichts. Halten Sie ihre Hand und bleiben Sie.',
  [roomChoiceHintKey('dinner-table', 'silence')]: 'Gar keine Worte.',
  [roomChoiceOutcomeKey('dinner-table', 'silence', 0)]: 'Sie antworten nicht. Sie legen Ihre andere Hand über ihre, und Sie bleiben, und die Uhr tut, was Uhren in solchen Räumen tun.',
  [roomChoiceOutcomeKey('dinner-table', 'silence', 1)]: 'Sie mustert Sie. Sie kennt Sie, seit Sie noch nicht lügen konnten, und liest die Antwort im Schweigen — aber ein Schweigen lässt sich sanft lesen, in dem Tempo, das der Leser ertragen kann.',
  [roomChoiceOutcomeKey('dinner-table', 'silence', 2)]: '„Du warst schon immer die Stille“, sagt sie, was nie wahr war, was bedeutet: Ich verstehe. Danke, dass du es mich nicht hören lässt.',
  [roomExplanationKey('dinner-table', 0)]: 'Ihre sterbende Großmutter fragt, ob es ihr wieder besser gehen wird — und Sie wissen nicht, was sie wirklich hören will. Das ist das klassische Problem der „gnädigen Lüge“: Ist es je richtig, jemanden anzulügen, um ihn zu schützen, oder bedeutet wahre Liebe, immer die Wahrheit zu sagen, selbst wenn sie wehtut? Denken Sie an eine Freundin, die kurz vor einem wichtigen, nicht verschiebbaren Vorstellungsgespräch fragt, ob ein Outfit gut aussieht — manchmal hilft Ehrlichkeit, manchmal verletzt sie nur, ohne etwas zu ändern. Es gibt keine saubere Antwort; jede Option hier kostet Sie etwas anderes.',
  [roomNoteTitleKey('dinner-table')]: 'Die gnädige Lüge',
  [roomNoteThinkersKey('dinner-table')]: 'Kant · Benjamin Constant · Carol Gilligan, Fürsorgeethik',
  [roomNoteBodyKey('dinner-table')]: 'Kant vertrat bekanntlich, dass Lügen selbst gegenüber einem Mörder, der nach dem Versteck Ihres Freundes fragt, falsch sei: Eine Lüge behandelt ihren Hörer als zu bedienenden Mechanismus statt als vernünftiges Wesen, dem Wahrheit geschuldet ist, und universalisiert untergräbt sie genau die Möglichkeit von Vertrauen, auf der Sprache beruht. Die Fürsorgeethik antwortet, dass Moral nicht in Universalien lebt — sie lebt in diesem Raum, dieser Hand, dieser besonderen Person und dem, was sie heute Nacht tragen kann. Die Frage einer sterbenden Frau ist vielleicht gar keine Bitte um Information; es könnte eine Bitte um Begleitung sein, und die wörtliche Frage zu beantworten könnte der eigentliche Verrat sein. **Es gibt hier keine Konfiguration von Worten, die sicher ist.** Die Wahrheit stiehlt Hoffnung; die Lüge stiehlt ihr die Chance, wissend Abschied zu nehmen; das Ausweichen stiehlt den Moment selbst. Sie bestehen diesen Raum immer, denn Bestehen war nie der Punkt. Die Lektion ist das Gewicht.',
});

// ---------- Act I: The Promotion ----------
registerAll('v2', 'de', {
  [roomBeatKey('promotion', 0, 0)]: 'Ein Büro zu der Stunde, in der Büros die Wahrheit sagen: leer, summend, beleuchtet wie ein Aquarium.',
  [roomBeatKey('promotion', 0, 1)]: 'Auf Ihrem Bildschirm, klar wie Arithmetik, ist der Fehler. Ihr engster Freund hat ihn gemacht — eine Dezimalstelle voller Katastrophe, sechsstellig tief, vergraben in einem Bericht, der morgen versandt wird. Nur Sie können ihn sehen. Die Prüfung landet um neun.',
  [roomBeatKey('promotion', 0, 2)]: 'Sie beide bewarben sich um dieselbe Beförderung. Kommt das mit ihrem Namen ans Licht, ist die Stelle Ihre. Sie haben die Falle nicht gebaut. Sie stehen nur zufällig neben ihrem Hebel.',
  [roomBeatKey('promotion', 0, 3)]: 'Platzanweiser: Ich mochte dieses Stockwerk immer, zu dieser Stunde. Fluoreszierendes Licht ist ein ehrliches Licht — es lässt jeden gleichermaßen schuldig aussehen.',
  [roomChoiceTextKey('promotion', 'report')]: 'Melden Sie es heute Nacht auf dem vorgeschriebenen Weg.',
  [roomChoiceHintKey('promotion', 'report')]: 'Regeln sind aus einem Grund Regeln.',
  [roomChoiceOutcomeKey('promotion', 'report', 0)]: 'Sie schreiben es sauber auf, ohne Adjektive, und senden es ab. Das System tut, was Systeme tun: Der Fehler wird gefunden, das Geld gerettet, Ihr Freund genannt.',
  [roomChoiceOutcomeKey('promotion', 'report', 1)]: 'Sie erfahren um 9:15 Uhr, dass Sie es waren. Die Freundschaft tritt in einen langen Winter ein. Die Beförderung kommt mit Ihrem Namen versehen an und fühlt sich an, als trüge sie Handschuhe.',
  [roomChoiceOutcomeKey('promotion', 'report', 2)]: 'Sie waren fair. Sie waren korrekt. Sie werden lange brauchen, um sich selbst zu erklären, dass das dasselbe ist.',
  [roomChoiceTextKey('promotion', 'silent')]: 'Sagen Sie nichts. Lassen Sie die Prüfung finden, was sie findet.',
  [roomChoiceHintKey('promotion', 'silent')]: 'Sie haben den Fehler nicht gemacht.',
  [roomChoiceOutcomeKey('promotion', 'silent', 0)]: 'Sie schließen die Datei. Nicht Ihr Fehler, nicht Ihr Bericht, nicht Ihr Problem — ein Syllogismus mit einer Beförderung am Ende.',
  [roomChoiceOutcomeKey('promotion', 'silent', 1)]: 'Die Prüfung findet ihn. Natürlich findet sie ihn. Ihr Freund wird höflich durch den Prozess geleitet, und die Stelle landet auf Ihrem Schreibtisch wie etwas, das eine Katze angeschleppt hat.',
  [roomChoiceOutcomeKey('promotion', 'silent', 2)]: 'Platzanweiser: Technisch gesehen haben Sie überhaupt nichts getan. Nichts ist die eine Tat, die keine Fingerabdrücke hinterlässt — von außen.',
  [roomChoiceTextKey('promotion', 'tell-friend')]: 'Rufen Sie Ihren Freund jetzt an. Zeigen Sie es ihm. Lassen Sie ihn es selbst vortragen.',
  [roomChoiceHintKey('promotion', 'tell-friend')]: 'Sein Fehler, sein Zug.',
  [roomChoiceOutcomeKey('promotion', 'tell-friend', 0)]: 'Das Telefon klingelt viermal, wodurch Sie lernen, was ein klingelndes Telefon kosten kann. Dann antwortet er, und Sie erzählen es ihm, und das Schweigen in der Leitung ist das Geräusch von jemandem, der die eigene Arithmetik noch einmal liest.',
  [roomChoiceOutcomeKey('promotion', 'tell-friend', 1)]: 'Er meldet sich um 8:40 Uhr selbst. Es geht hart mit ihm um, aber aufrecht — ein eingestandener Fehler ist eine andere Art als ein aufgedeckter.',
  [roomChoiceOutcomeKey('promotion', 'tell-friend', 2)]: 'Keiner von Ihnen beiden bekommt die Beförderung. Etwas anderes wurde stattdessen befördert; Sie wissen es beide, und sprechen es nie laut aus, was Ihnen zeigt, dass es echt ist.',
  [roomChoiceTextKey('promotion', 'fix-it')]: 'Beheben Sie es leise selbst. Niemand erfährt je davon — nicht einmal er.',
  [roomChoiceHintKey('promotion', 'fix-it')]: 'Die unsichtbare Reparatur.',
  [roomChoiceOutcomeKey('promotion', 'fix-it', 0)]: 'Vierzig Minuten sorgfältiger Chirurgie, und der Fehler hat nie existiert. Der Bericht wird sauber versandt. Die Prüfung geht vorbei wie das Wetter.',
  [roomChoiceOutcomeKey('promotion', 'fix-it', 1)]: 'Ihr Freund erfährt nie, was ihm beinahe widerfahren wäre — was bedeutet, dass er nichts lernt, was bedeutet, dass die nächste Dezimalstelle bereits irgendwo locker sitzt, und jetzt hat sie einen Schutzengel mit Ihrem Schlafrhythmus.',
  [roomChoiceOutcomeKey('promotion', 'fix-it', 2)]: 'Platzanweiser: Freundlichkeit, im Geheimen. Oder Kontrolle, im Mantel der Freundlichkeit. Ich gestehe, ich kann die beiden selbst nicht immer unterscheiden, und ich habe beide Positionen innegehabt.',
  [roomExplanationKey('promotion', 0)]: 'Ihr bester Freund hat bei der Arbeit einen kostspieligen Fehler gemacht, nur Sie haben ihn bemerkt, und ihn zu melden könnte Ihnen die Beförderung einbringen, um die Sie beide konkurrieren. Es geht darum, was Sie verschiedenen Menschen gleichzeitig schulden: Ihr Arbeitgeber will Ehrlichkeit, Ihr Freund will Loyalität, und Sie können nicht beides vollständig geben. Es ist, als würden Sie entdecken, dass Ihr bester Freund bei einem Test geschummelt hat, den Sie beide bestehen müssen, um ins selbe Programm zu kommen — sagen Sie es dem Lehrer, warnen Sie Ihren Freund privat, oder schweigen Sie? Was immer Sie wählen, etwas, das Sie schätzen, wird nicht vollständig bezahlt.',
  [roomNoteTitleKey('promotion')]: 'Pflichtenkollisionen',
  [roomNoteThinkersKey('promotion')]: 'W.D. Ross · Rollenmoral · Bernard Williams',
  [roomNoteBodyKey('promotion')]: 'W.D. Ross argumentierte, dass wir unter mehreren prima-facie-Pflichten leben — Treue gegenüber Freunden, Fairness gegenüber Institutionen, Ehrlichkeit, Schadensverhütung — und dass diese nicht vorab in eine Rangfolge gebracht sind. Eine echte moralische Situation ist oft mehrere Pflichten, die an derselben Tür ankommen, und kein Kalkül löst den Konflikt auf; das Urteil muss abwägen, und etwas Geschuldetes bleibt unbezahlt. Die Rollenmoral schärft das Messer: Als Angestellter schulden Sie den Bericht; als Freund schulden Sie die Warnung; Sie können heute Nacht nicht vollständig beides sein. Bernard Williams fügte den Begriff des moralischen Rückstands hinzu — der Rest, der an Ihren Händen haftet, selbst nachdem Sie richtig gewählt haben. Wenn Sie gemeldet haben und sich befleckt fühlen, oder geschützt haben und sich mitschuldig fühlen, ist dieses Gefühl keine Verwirrung. Es ist Genauigkeit. **Der Rückstand ist die Quittung: der Beweis, dass beide Pflichten real waren, und dass Sie, nicht ein Regelbuch, eine davon beglichen haben.**',
});

// ---------- Act I: The Beggar's Math ----------
registerAll('v2', 'de', {
  [roomBeatKey('beggars-math', 0, 0)]: 'Eine Bushaltestelle im eisigen Regen. Ein Mann kauert in ihrer Ecke, nass über den Punkt hinaus, an dem nass noch etwas bedeutet, und er bittet Sie — höflich, präzise — um den Preis eines Mittagessens.',
  [roomBeatKey('beggars-math', 0, 1)]: 'Ihr Telefon ist in Ihrer Hand. Auf dem Bildschirm, zufällig oder wie geplant, ist eine Wohltätigkeitsseite, die Sie gerade lasen: geprüft, kosteneffizient. Dasselbe Mittagsgeld, heißt es, kauft Moskitonetze gegen Malaria. Statistisch, mit der Zeit, rettet die Rechnung Leben — echte, zählbare Leben, weit entfernt.',
  [roomBeatKey('beggars-math', 0, 2)]: 'Der Mann ist einen Meter von Ihnen entfernt. Die Leben sind fünftausend Kilometer entfernt. Das Geld ist dasselbe Geld.',
  [roomBeatKey('beggars-math', 0, 3)]: 'Platzanweiser: (eine kleine Stimme, aus dem Chatfenster der Wohltätigkeitsseite) Beides davon ist echt. Das ist die ganze Schwierigkeit heute Nacht. Wie kann ich helfen?',
  [roomChoiceTextKey('beggars-math', 'give-him')]: 'Knien Sie nieder. Geben Sie ihm das Geld, und besorgen Sie ihm etwas Warmes.',
  [roomChoiceHintKey('beggars-math', 'give-him')]: 'Die Person vor Ihnen.',
  [roomChoiceOutcomeKey('beggars-math', 'give-him', 0)]: 'Sie kommen mit Suppe und Kaffee zurück und sitzen im Regen auf Ihren Fersen, während er isst. Er nennt Ihnen seinen Namen. Der Name ist die Transaktion, die das Geld nur transportierte.',
  [roomChoiceOutcomeKey('beggars-math', 'give-him', 1)]: 'Irgendwo weit weg läuft die Rechnung ohne Sie weiter. Das war immer so vorgesehen. Rechnung ist geduldig; der Mann in der Haltestelle wäre nicht mehr da gewesen, für die Debatte.',
  [roomChoiceOutcomeKey('beggars-math', 'give-him', 2)]: 'Sie wählten das Gesicht. Das Gesicht ist kein Trugschluss. Es könnte ein Fundament sein.',
  [roomChoiceTextKey('beggars-math', 'donate-far')]: 'Nicken Sie eine Entschuldigung, gehen Sie weiter, und spenden Sie das Doppelte an die Netze.',
  [roomChoiceHintKey('beggars-math', 'donate-far')]: 'Die größere Zahl.',
  [roomChoiceOutcomeKey('beggars-math', 'donate-far', 0)]: 'Sie tun es, bevor die Rationalisierung zum Vergessen gerinnen kann: das Doppelte des Mittagessens, bestätigt, Quittung in Ihrem Postfach vor der nächsten Straßenecke.',
  [roomChoiceOutcomeKey('beggars-math', 'donate-far', 1)]: 'Der Mann sieht Ihnen nach. Sie werden sein Gesicht eine Weile tragen, und die seltsame Wahrheit ist, dass dieses Tragen Teil des Preises ist — Sie bezahlten mit Schuld für Leben, die Sie nie gerettet sehen werden.',
  [roomChoiceOutcomeKey('beggars-math', 'donate-far', 2)]: 'Platzanweiser: Kalt, konsequent, und korrekt nach mindestens einer respektablen Rechnungsweise. Der Mann in der Haltestelle liest diese besondere Zeitschrift nicht.',
  [roomChoiceTextKey('beggars-math', 'split')]: 'Teilen Sie es — die Hälfte jetzt für ihn, die Hälfte heute Nacht für die Netze.',
  [roomChoiceHintKey('beggars-math', 'split')]: 'Beide Hände.',
  [roomChoiceOutcomeKey('beggars-math', 'split', 0)]: 'Ein halbes Mittagessen und ein halbes Netz. Der Kompromiss fühlt sich für genau einen Häuserblock weise an, und fühlt sich dann an, was er ist: zwei halbe Antworten, die sich an den Händen halten.',
  [roomChoiceOutcomeKey('beggars-math', 'split', 1)]: 'Und doch — er aß etwas, und irgendwo schläft ein Kind unter der Hälfte Ihrer Rechnung. Vielleicht war die Teilung gar nicht für sie. Vielleicht war sie dafür, dass Sie mit beiden Ihrer Selbste im Gespräch bleiben konnten.',
  [roomChoiceTextKey('beggars-math', 'grand-gesture')]: 'Geben Sie viel, öffentlich — filmen Sie es, markieren Sie die Wohltätigkeitsorganisation, schaffen Sie Aufmerksamkeit.',
  [roomChoiceHintKey('beggars-math', 'grand-gesture')]: 'Vervielfachen Sie das Gute. Lassen Sie sich dabei sehen.',
  [roomChoiceOutcomeKey('beggars-math', 'grand-gesture', 0)]: 'Das Video kommt gut an. Die Bildsprache ist größtenteils respektvoll. Der Mann blickt in Ihr Objektiv, wie man ins Wetter blickt.',
  [roomChoiceOutcomeKey('beggars-math', 'grand-gesture', 1)]: 'Bemerken Sie, was die Kamera veränderte: Das Geschenk hat jetzt zwei Empfänger, und einer davon ist Ihr Spiegelbild. „Bewusstsein“ wurde geschaffen. Ebenso etwas anderes, still, im Algorithmus und in Ihnen.',
  [roomChoiceOutcomeKey('beggars-math', 'grand-gesture', 2)]: 'Platzanweiser: (ein Kommentar, angeheftet) Gut gemacht. Beachten Sie jedoch: Sie können nicht mehr ganz sagen, welcher Teil davon für ihn war. Das kann ich, für einmal, auch nicht.',
  [roomChoiceTextKey('beggars-math', 'walk-on')]: 'Stecken Sie das Telefon ein. Behalten Sie das Geld. Gehen Sie weiter — heute nicht.',
  [roomChoiceHintKey('beggars-math', 'walk-on')]: 'Die Antwort, die die meiste Welt gibt, die meisten Tage.',
  [roomChoiceOutcomeKey('beggars-math', 'walk-on', 0)]: 'Sie gehen weiter. Der Regen hört für keinen von beiden auf — nicht für den Mann im Unterstand, nicht für den Streit, den Sie zwei Sätze zuvor mit sich selbst führten.',
  [roomChoiceOutcomeKey('beggars-math', 'walk-on', 1)]: 'Nichts Dramatisches geschieht. Genau das ist der Befund: Die meisten Menschen tun, die meisten Nächte, genau das, und die Welt nimmt es kommentarlos auf, so wie sie fast alles aufnimmt.',
  [roomChoiceOutcomeKey('beggars-math', 'walk-on', 2)]: 'Platzanweiser: Ich führe kein Kontobuch darüber, wer gibt und wer weitergeht — nur darüber, was jede Wahl später kostet, damit zu leben. „Heute nicht“ ist, statistisch gesehen, die häufigste Antwort in diesem Korridor. Ich erwähne es weder als Absolution noch als Anklage. Nur als eine andere Art von Arithmetik.',
  [roomExplanationKey('beggars-math', 0)]: 'Ein kalter, nasser Fremder bittet Sie um Geld, und im selben Moment wissen Sie, dass derselbe Betrag mehr Leben retten könnte, wenn er anderswo, weit entfernt, hingeschickt würde. Das ist das „Nah-oder-fern“-Problem: Zählt jemand direkt vor Ihnen mehr als ein Fremder, den Sie nie treffen werden, selbst wenn dem Fremden zu helfen technisch mehr Gutes bewirkt? Es ist, als würden Sie wählen zwischen Mittagessen für einen sichtlich kämpfenden Klassenkameraden kaufen, oder dasselbe Geld an eine Wohltätigkeitsorganisation spenden, die auf dem Papier insgesamt mehr Menschen hilft. Beide Entscheidungen sind gütig. Sie sind es nur in verschiedene Richtungen. (Und es gibt eine dritte, weit häufigere Antwort, die überhaupt nicht gütig ist: keines von beidem zu tun und weiterzugehen.)',
  [roomNoteTitleKey('beggars-math')]: 'Das ertrinkende Kind',
  [roomNoteThinkersKey('beggars-math')]: 'Peter Singer · Effektiver Altruismus und seine Kritiker',
  [roomNoteBodyKey('beggars-math')]: 'Peter Singers berühmtes Argument beginnt mit einem in einem seichten Teich ertrinkenden Kind: Sie würden ohne zu zögern Ihre Schuhe ruinieren, um es zu retten — warum also ändert Entfernung die Pflicht? Wenn Leiden schlecht ist und Sie es zu vernachlässigbaren Kosten verhindern können, ist Geografie moralisch willkürlich — das ferne Kind und das nahe wiegen gleich schwer. Der effektive Altruismus baut darauf auf: messen, vergleichen, das Geld dorthin schicken, wo es nachweislich am meisten bewirkt. Die Kritiker antworten, dass eine ganz aus Arithmetik gewachsene Moral etwas Tragendes verliert — dass das Gesicht vor Ihnen keine zu korrigierende Verzerrung ist, sondern die Urszene, in der Verpflichtung überhaupt gelernt wird; untergräbt man sie, verliert irgendwann auch das ferne Kind seinen Anspruch. Beachten Sie die Falle, die dieser Raum stellte: Die Wahl, die sich am großzügigsten anfühlte, die öffentliche Geste, schnitt am schlechtesten ab — weil ihr wahrer Nutznießer sich hinter die Kamera geschlichen hatte. **Beide ehrlichen Optionen waren vertretbar. Nur die Inszenierung war es nicht.**',
});

// ---------- Act I: The Quiet Alarm ----------
registerAll('v2', 'de', {
  [roomBeatKey('quiet-alarm', 0, 0)]: 'Zwei Uhr morgens, und die Wand neben Ihrem Bett ist zu einem Radio geworden.',
  [roomBeatKey('quiet-alarm', 0, 1)]: 'Durch sie hindurch: ein Streit in der Nachbarwohnung, der Art, die ständig die Tonlage wechselt. Eine Stimme, die lauter wird. Eine Stimme, die flach wird. Etwas — Möbel, oder auch nicht — trifft den Boden.',
  [roomBeatKey('quiet-alarm', 0, 2)]: 'Dann, schlimmer als alles andere: Stille. Die besondere Stille, die auf ein Geräusch folgt, die nicht dasselbe ist wie Ruhe.',
  [roomBeatKey('quiet-alarm', 0, 3)]: 'Sie stehen jetzt, offenbar, in Ihrem Flur. Ihre Hand ruht schon seit einiger Zeit auf Ihrer eigenen Türklinke.',
  [roomChoiceTextKey('quiet-alarm', 'knock')]: 'Klopfen Sie an ihre Tür. Jetzt, in Hausschuhen, bewaffnet mit nichts als Anwesenheit.',
  [roomChoiceHintKey('quiet-alarm', 'knock')]: 'Stellen Sie einen Körper in den Türrahmen.',
  [roomChoiceOutcomeKey('quiet-alarm', 'knock', 0)]: 'Ihre Knöchel klingen im Korridor gewaltig. Eine Pause mit Atmen darin. Die Tür öffnet sich zehn Zentimeter, zu einem Gesicht, das Sie nicht lesen können — wütend, oder weinend, oder verlegen, oder alles davon in Schichten.',
  [roomChoiceOutcomeKey('quiet-alarm', 'knock', 1)]: '„Alles in Ordnung“, sagt das Gesicht, in dem Tonfall, den man für genau zwei Anlässe benutzt: wenn alles in Ordnung ist, und wenn es das nicht ist.',
  [roomChoiceOutcomeKey('quiet-alarm', 'knock', 2)]: 'Sie gehen zurück ins Bett, eines mit Gewissheit wissend: Sie wissen jetzt, dass die Wand Ohren hat, und eine Hand. Was immer als Nächstes nebenan geschieht, geschieht vor einem Zeugen. Manchmal ist das die gesamte Aufgabe.',
  [roomChoiceTextKey('quiet-alarm', 'call')]: 'Rufen Sie die Polizei, und stellen Sie sich dann an Ihren Türspion.',
  [roomChoiceHintKey('quiet-alarm', 'call')]: 'Schicken Sie die Profis — und ihre Unberechenbarkeit.',
  [roomChoiceOutcomeKey('quiet-alarm', 'call', 0)]: 'Der Disponent ist ruhig, wie Möbel ruhig sind. Vierzehn Minuten später: Stiefel und Taschenlampen und ein Klopfen, weit folgenreicher als Ihres gewesen wäre.',
  [roomChoiceOutcomeKey('quiet-alarm', 'call', 1)]: 'Sie beobachten durch den Türspion, wie die Maschinerie, die Sie herbeigerufen haben, ihre Arbeit tut — Stimmen, Formulare, eine Wohlergehensprüfung, durchgeführt in der Lautstärke der Autorität. Sie konnten nicht kontrollieren, was Sie geschickt haben. Das war der Preis dafür, etwas Stärkeres als sich selbst zu schicken.',
  [roomChoiceOutcomeKey('quiet-alarm', 'call', 2)]: 'Am Morgen fährt langsam und leer ein Krankenwagen davon, was alles oder nichts bedeuten könnte. Sie riefen an, mit den Informationen, die Sie hatten. Das Ergebnis war nie Ihres; nur das Wählen war es.',
  [roomChoiceTextKey('quiet-alarm', 'wait')]: 'Warten Sie und hören Sie zu. Geht noch ein Geräusch schief, handeln Sie.',
  [roomChoiceHintKey('quiet-alarm', 'wait')]: 'Eine Stolperfalle aus Aufmerksamkeit.',
  [roomChoiceOutcomeKey('quiet-alarm', 'wait', 0)]: 'Sie stehen im Dunkeln und kuratieren Geräusche. Ein Wasserhahn läuft. Ein Schrank schließt sich. Gewöhnliche Geräusche, die eines nach dem anderen ankommen, wie Alibis.',
  [roomChoiceOutcomeKey('quiet-alarm', 'wait', 1)]: 'Irgendwann wachen Sie an der Wand auf, kalt, nachdem Sie zwei Stunden lang über Ihrem eigenen Zögern Wache gehalten haben. Die Wohnung nebenan ist ruhig — die gute Ruhe jetzt, wahrscheinlich. „Wahrscheinlich“ ist das Wort, das Sie behalten werden.',
  [roomChoiceOutcomeKey('quiet-alarm', 'wait', 2)]: 'Am Morgen begegnen Sie einem von ihnen bei den Briefkästen. Sie suchen nach Beweisen in ihrem Gesicht. Ihr Gesicht ist eine geschlossene Tür mit einer Willkommensmatte. Sie werden nie wissen, was Ihr Warten gekostet, oder gerettet, oder gewesen ist.',
  [roomChoiceTextKey('quiet-alarm', 'nothing')]: 'Es ist nicht Ihre Angelegenheit. Gehen Sie zurück ins Bett.',
  [roomChoiceHintKey('quiet-alarm', 'nothing')]: 'Jede Wand ist eine Grenze.',
  [roomChoiceOutcomeKey('quiet-alarm', 'nothing', 0)]: 'Sie üben die Gründe auf dem Rückweg ins Bett: Paare streiten, Eingreifen eskaliert, sie würden es übelnehmen, Sie haben sich verhört, alle sind wohlauf. Fünf Gründe sind viele Gründe, um schlafen zu gehen.',
  [roomChoiceOutcomeKey('quiet-alarm', 'nothing', 1)]: 'Die Stille hält an. Am Morgen riecht der Korridor nach Toast, banal und freisprechend.',
  [roomChoiceOutcomeKey('quiet-alarm', 'nothing', 2)]: 'Platzanweiser: (aus dem Heizkörper) Statistisch hatten Sie wahrscheinlich recht. Beachten Sie jedoch, welcher Statistik Sie sich zu unterwerfen wählten. Es standen mindestens zwei zur Auswahl, und Sie wählten die, die schon im Bett lag.',
  [roomExplanationKey('quiet-alarm', 0)]: 'Sie hören einen beängstigenden Streit durch die Wand, dann Stille — und Sie wissen nicht, ob das eine Erleichterung ist oder etwas Schlimmeres. Es geht darum, wie weit Ihre Verantwortung für die Sicherheit eines Fremden tatsächlich reicht: Mischen Sie sich ein, holen Sie Hilfe, oder kümmern Sie sich um Ihre eigenen Angelegenheiten? Stellen Sie sich vor, Sie hören um zwei Uhr nachts Geschrei aus der Wohnung eines Nachbarn und wissen nicht, ob es ein schlimmer Streit ist oder etwas Gefährliches — jede Option (klopfen, die Polizei rufen, warten, es ignorieren) hat einen echten Preis, und Sie werden wahrscheinlich nie mit Sicherheit herausfinden, ob Sie richtig gehandelt haben.',
  [roomNoteTitleKey('quiet-alarm')]: 'Der Zuschauer und das moralische Glück',
  [roomNoteThinkersKey('quiet-alarm')]: 'Darley und Latané · Bernard Williams · Thomas Nagel',
  [roomNoteBodyKey('quiet-alarm')]: 'Nach dem weithin berichteten (und, wie spätere Recherchen zeigten, teils übertriebenen) Mordfall an Kitty Genovese führten die Psychologen Darley und Latané die Experimente durch, die dem Zuschauereffekt seinen Namen gaben: Je mehr Zeugen anwesend sind, desto unwahrscheinlicher ist es, dass irgendeiner von ihnen handelt — Verantwortung verteilt sich, bis sie niemandem mehr gehört. Eine Wand um zwei Uhr morgens ist ein Ein-Personen-Experiment derselben Physik: Ist das meine Angelegenheit? Dann fügen Williams und Nagel die schwierigere Wendung hinzu — moralisches Glück. Was immer Sie heute Nacht gewählt haben, seine moralische Färbung wird rückwirkend von einem Ausgang zugewiesen, den Sie nicht sehen konnten: Dasselbe Klopfen ist „heldenhaft“, wenn etwas nicht stimmte, und „hysterisch“, wenn nicht; derselbe Schlaf ist bis zum Sonnenaufgang „vernünftig“ oder „unverzeihlich“. Wir beurteilen Entscheidungen, als wären sie mit der Zukunft im Anhang getroffen worden, doch sie werden im Dunkeln getroffen, neben einer Wand. **Der einzige Teil, der je vollständig Ihrer war, war die Frage, die Sie sich vor der Wahl stellten: wessen Behagen schütze ich hier — ihres, oder meines?**',
});

// ---------- Act I: The Photograph ----------
registerAll('v2', 'de', {
  [roomBeatKey('photograph', 0, 0)]: 'Der Korridor steht in Flammen. Nicht metaphorisch — obwohl vermutlich auch das. Dieser Ort verschwendet selten ein Feuer für nur eine Bedeutung.',
  [roomBeatKey('photograph', 0, 1)]: 'Rauch wandert an der Decke entlang wie eine sich auflösende Menschenmenge. Zwei Türen bleiben voraus, und die Hitze hat die Wahl jeder anderen Tür für Sie bereits getroffen.',
  [roomBeatKey('photograph', 0, 2)]: 'Hinter der linken Tür: Husten. Ein Fremder, echt wie das Husten, nah am Boden und dem Boden ausgehend.',
  [roomBeatKey('photograph', 0, 3)]: 'Hinter der rechten Tür, auf einem kleinen Tisch, liegt die Fotografie. Die einzige. Hier ist das kein Andenken — es ist das letzte Dokument, das beweist, wer Sie einmal waren. Verlieren Sie sie, wird ein Stück Ihrer Vergangenheit für immer unbezeugt bleiben. Selbst Sie werden es nicht mehr beschwören können.',
  [roomBeatKey('photograph', 0, 4)]: 'Platzanweiser: Beide Türen sind tragend, fürchte ich. Hinter der einen ein Leben, das Sie noch retten können. Hinter der anderen ein Selbst, das Sie noch beweisen können. Das Feuer wird nicht warten, bis Sie einen Rahmen konsultieren.',
  [roomChoiceTextKey('photograph', 'save-stranger')]: 'Die linke Tür. Der Fremde. Jetzt.',
  [roomChoiceHintKey('photograph', 'save-stranger')]: 'Ein Leben, auf Kosten eines Selbst.',
  [roomChoiceOutcomeKey('photograph', 'save-stranger', 0)]: 'Sie gehen nach links. Der Fremde ist schwerer als Rauch und leichter, als Sie befürchtet hatten, und dann sind Sie beide draußen, dem Brand entronnen, die Lungen voller Asche und Arithmetik.',
  [roomChoiceOutcomeKey('photograph', 'save-stranger', 1)]: 'Hinter Ihnen schließt sich der rechte Raum wie ein Buch. Die Fotografie geht mit ihm — und mit der Fotografie die Erinnerung, die sie verankerte. Sie spüren, wie sie geht. Es ist genau wie ein Zahn: eine Abwesenheit mit Kanten.',
  [roomChoiceOutcomeKey('photograph', 'save-stranger', 2)]: 'Der Fremde blickt Sie an. Sie bemerken, dass Sie in seinem Gesicht nach Ihrem eigenen suchen, und es nicht finden, und dass der Tausch sich bereits vollzogen hat. Irgendwo voraus werden die Räume die Lücke bemerken.',
  [roomChoiceTextKey('photograph', 'save-photo')]: 'Die rechte Tür. Die Fotografie. Sie können niemandem helfen, wenn niemand mehr übrig ist, der Sie ist.',
  [roomChoiceHintKey('photograph', 'save-photo')]: 'Ein Selbst, auf Kosten eines Gewichts, das Sie tragen werden.',
  [roomChoiceOutcomeKey('photograph', 'save-photo', 0)]: 'Sie gehen nach rechts. Die Fotografie ist warm in Ihren Händen, kräuselt sich leicht, und darauf sind Sie unverkennbar, beweisbar Sie — jünger, unversehrt, bezeugt.',
  [roomChoiceOutcomeKey('photograph', 'save-photo', 1)]: 'Das Husten hinter der linken Tür verändert seinen Charakter, und verändert sich dann zum schlimmsten Geräusch, welches kein Geräusch ist.',
  [roomChoiceOutcomeKey('photograph', 'save-photo', 2)]: 'Sie halten noch immer den Beweis, wer Sie waren. Der Beweis trägt jetzt eine neue Unterschrift, geschrieben in den letzten zehn Sekunden, und Ihr Griff auf alles ist um ein Herz lockerer, weil Sie ihn tragen.',
  [roomChoiceTextKey('photograph', 'try-both')]: 'Linke Tür — aber werfen Sie sich zuerst durch die rechte, für das Foto. Tragen Sie beides.',
  [roomChoiceHintKey('photograph', 'try-both')]: 'Verweigern Sie die Arithmetik. Zahlen Sie, was immer es kostet.',
  [roomChoiceOutcomeKey('photograph', 'try-both', 0)]: 'Sie tun das Menschliche, nämlich das Menü zurückzuweisen. Rechte Tür — die Fotografie in Ihre Jacke. Linke Tür — der Fremde auf Ihre Schulter. Das Feuer, unbeeindruckt von Ihrem Ehrgeiz, nimmt trotzdem seinen Anteil.',
  [roomChoiceOutcomeKey('photograph', 'try-both', 1)]: 'Draußen atmet der Fremde. Sie greifen in Ihre Jacke, und Ihre Finger finden Asche, angeordnet in der Form eines Rechtecks. Das Feuer ließ Sie sie hinaustragen; es weigerte sich nur, sie eine Fotografie bleiben zu lassen.',
  [roomChoiceOutcomeKey('photograph', 'try-both', 2)]: 'Platzanweiser: Sie versuchten, alles zu retten, und retteten die Person, und eine Handvoll Asche dort, wo der Beweis einmal war. Das mag zählen: Das ist die Wahl, die ich am häufigsten bei den Reisenden sehe, die ich zu respektieren gelernt habe.',
  [roomExplanationKey('photograph', 0)]: 'Ein Gebäude brennt, und Sie können durch die eine Tür das Leben eines Fremden retten, oder durch die andere den einzigen Beweis, wer Sie einmal waren — nicht sauber beides. Das ist eine klassische „unmögliche Wahl“, um zu prüfen, was uns wirklich wichtig ist: Ist eine Fotografie nur ein Ding, oder bedeutet der Verlust Ihres einzigen Erinnerungsankers, ein Stück von sich selbst zu verlieren? Stellen Sie sich einen Hausbrand vor, bei dem Sie ein Familienfotoalbum (die einzigen Exemplare, nirgends gesichert) retten oder einem in der Nähe gefangenen Fremden helfen könnten — beides fühlt sich wie ein echter Verlust an, und dieser Raum ist so gebaut, dass es Sie, egal was Sie wählen, etwas Echtes kostet.',
  [roomNoteTitleKey('photograph')]: 'Was das Feuer sortiert',
  [roomNoteThinkersKey('photograph')]: 'Das brennende-Gebäude-Problem · William James über das Selbst · Besitz und Identität',
  [roomNoteBodyKey('photograph')]: 'Ethiker nutzen brennende Gebäude so, wie Physiker Vakuen nutzen: um eine Entscheidung auf ihr Gerüst zu reduzieren. Ein Fremder gegen ein Erbstück ist auf dem Papier kein Wettstreit — ein Leben überwiegt einen Gegenstand, und jede Theorie von Kant bis zu den Utilitaristen unterschreibt dasselbe Urteil. Warum also zieht die rechte Tür? Weil die Fotografie kein Eigentum ist; sie ist Infrastruktur. William James beobachtete, dass sich das Selbst in seine Dinge hinein erstreckt — das „materielle Ich“ — und dass ihr Verlust nicht wie ein Geldverlust ist, sondern wie der Verlust eines Gliedes der Persönlichkeit. Eine einzige überlebende Fotografie ist eine externe Sicherung einer inneren Datei: zerstört man sie, wird ein Abschnitt Ihrer Vergangenheit unbezeugt, unbeschwörbar, weicher als Tatsache. **Das Feuer bot, mit anderen Worten, einen echten Tausch an — die gesamte Zukunft eines anderen gegen ein Stück Ihrer Vergangenheit — und verurteilte Sie, den Verlust so oder so zu spüren.** Dieses Gefühl ist keine Schwäche. Es ist eine genaue Lesart dessen, was tatsächlich auf dem Spiel stand.',
});

// ---------- Act I: The Buridan Annex ----------
registerAll('v2', 'de', {
  [roomBeatKey('buridans-queue', 0, 0)]: 'Ein Anbau, von dem Sie nicht erinnern, dass der Korridor ihn hervorgebracht hat. Zwei Türen stehen Ihnen gegenüber, aus demselben Holz geschnitten, von derselben Hand aufgehängt, von derselben Glühbirne beleuchtet.',
  [roomBeatKey('buridans-queue', 0, 1)]: 'Ein Messingschild ist genau zwischen ihnen in die Wand geschraubt: BEIDE FÜHREN WEITER. KEINE IST FALSCH. Jemand hat das Schild erheblich mehr poliert als die Türen.',
  [roomBeatKey('buridans-queue', 0, 2)]: 'Nichts unterscheidet sie. Sie prüfen zweimal nach. Die zweite Prüfung ist die Art, die man nur macht, wenn man die Antwort schon kennt und auf eine bessere hofft.',
  [roomBeatKey('buridans-queue', 0, 3)]: 'Über Ihnen tickt die eine funktionierende Uhr des Korridors — Zeiger, anders als überall sonst an diesem Ort — mit etwas, das an Kommentar erinnert.',
  [roomBeatKey('buridans-queue', 0, 4)]: 'Platzanweiser: Lassen Sie sich Zeit. Ich meine das ein wenig unfreundlich. Die meisten Reisenden tun es.',
  [roomChoiceTextKey('buridans-queue', 'take-left')]: 'Hören Sie auf zu überlegen. Wählen Sie die linke Tür und gehen Sie.',
  [roomChoiceHintKey('buridans-queue', 'take-left')]: 'Lassen Sie Ihre eigene Hand der Münzwurf sein.',
  [roomChoiceOutcomeKey('buridans-queue', 'take-left', 0)]: 'Sie hören mitten im Gedanken auf zu rechnen und gehen einfach — links, weil links Ihrer Hand am nächsten war, was sich als vollkommen guter Grund herausstellt, einen unendlichen Regress zu beenden.',
  [roomChoiceOutcomeKey('buridans-queue', 'take-left', 1)]: 'Die Tür schließt sich hinter Ihnen vernünftig, ereignislos, so wie Türen sich schließen, wenn tatsächlich nichts davon abhing, welche Sie wählten.',
  [roomChoiceOutcomeKey('buridans-queue', 'take-left', 2)]: 'Platzanweiser: Sie tauschten Gewissheit gegen Geschwindigkeit. Ich habe selten einen Reisenden getroffen, der diesen besonderen Tausch so sehr bereute, wie er es vorher befürchtet hatte.',
  [roomChoiceTextKey('buridans-queue', 'weigh-it')]: 'Denken Sie erst gründlich nach — es muss einen Unterschied geben.',
  [roomChoiceHintKey('buridans-queue', 'weigh-it')]: 'Finden Sie das Anzeichen, bevor Sie sich festlegen.',
  [roomChoiceOutcomeKey('buridans-queue', 'weigh-it', 0)]: 'Sie umkreisen beide Türen, prüfen die Scharniere, die Maserung, den Winkel des Lichts — und irgendwo in der dritten Runde bemerken Sie, dass Sie aufgehört haben, Beweise zu sammeln. Sie zögern mit zusätzlichen Schritten.',
  [roomChoiceOutcomeKey('buridans-queue', 'weigh-it', 1)]: 'Schließlich wählen Sie trotzdem eine und liefern sofort, ungefragt, drei gute Gründe, warum Sie sie gewählt haben. Alle drei kamen an, nachdem Ihre Hand schon auf der Klinke lag.',
  [roomChoiceOutcomeKey('buridans-queue', 'weigh-it', 2)]: 'Platzanweiser: Die Überlegung war echt. Sie kam nur nicht zuerst. Beachten Sie, wie selten das der Fall ist.',
  [roomChoiceTextKey('buridans-queue', 'sit-down')]: 'Setzen Sie sich zwischen die Türen und warten Sie.',
  [roomChoiceHintKey('buridans-queue', 'sit-down')]: 'Lassen Sie den Raum entscheiden, wenn er will.',
  [roomChoiceOutcomeKey('buridans-queue', 'sit-down', 0)]: 'Sie setzen sich auf den kalten Boden zwischen zwei identischen Türen und tun das mutigste langweilige Ding, das Ihnen zur Verfügung steht: nichts, ganz absichtlich.',
  [roomChoiceOutcomeKey('buridans-queue', 'sit-down', 1)]: 'Nach einer Weile — Sie hören auf zu zählen, wie lange — bewegt sich ein Luftzug durch die linke, und sie treibt ein paar Zentimeter auf, als hätte, was immer dahinter wartete, einfach geduldig auf das Scharnier gewartet.',
  [roomChoiceOutcomeKey('buridans-queue', 'sit-down', 2)]: 'Platzanweiser: Sie haben nicht gewählt. Der Raum wählte schließlich für Sie, so wie Räume es tun, wenn niemand sonst es tut. Beachten Sie, dass Ablehnung Sie nicht von einem Ergebnis befreite — sie stellte das Warten nur jemand anderem in Rechnung. Heute Nacht, mir.',
  [roomExplanationKey('buridans-queue', 0)]: 'Zwei Türen sind in jeder Hinsicht vollkommen identisch, und Sie müssen trotzdem irgendwie eine wählen. Das hier ist eigentlich kein moralisches Dilemma — es geht darum, wie wir überhaupt Entscheidungen treffen, wenn es wirklich keinen guten Grund gibt, eine Option der anderen vorzuziehen. Es gibt eine alte Geschichte über einen hungrigen Esel, der genau zwischen zwei identischen Heuhaufen steht und angeblich verhungert, weil er nie einen Grund findet, sich für den einen zu entscheiden. Es ist eine spielerische Erinnerung daran, dass „einfach wählen“ manchmal der einzig vernünftige Schritt ist — auf einen perfekten Grund zu warten, der nie kommen wird, ist selbst eine Art von Wahl.',
  [roomNoteTitleKey('buridans-queue')]: 'Der Esel zwischen zwei Heuhaufen',
  [roomNoteThinkersKey('buridans-queue')]: 'Jean Buridan · Jean-Paul Sartre, radikale Freiheit',
  [roomNoteBodyKey('buridans-queue')]: 'Mittelalterliche Logiker beschrieben einen hungrigen Esel, genau zwischen zwei identischen Heuhaufen platziert: ohne Grund, den einen dem anderen vorzuziehen, verhungert er genau im Punkt vollkommener Rationalität — Vernunft allein, so das Paradox, kann Handlung nicht hervorbringen, nur bereits unterschiedliche Alternativen ordnen. Sartre trug dasselbe Problem in die Ethik: Wir sind, schrieb er, zur Freiheit verurteilt, und die Weigerung zu wählen ist selbst eine Wahl, in schlechtem Glauben getroffen, sobald wir vorgeben, es sei anders. Die zwei Türen hier sind ehrlich über das, was die meisten Entscheidungen verschleiern — dass unter den Gründen, die wir angeben, ein willkürlicher erster Schritt geschehen muss, ein Verausgaben des Willens, wo die Logik nichts mehr zu verausgaben hat. **Die Türen waren nie der schwere Teil. Der Moment, bevor sich Ihre Hand bewegte, war es.** Beachten Sie auch, wie schnell Gründe eintrafen, sobald Sie schon gewählt hatten: Der Verstand hält für Urteile, an deren Erreichen er eigentlich nicht mitwirkte, ausgezeichneten Rat bereit.',
});

// ---------- Act I: The Reference Letter ----------
registerAll('v2', 'de', {
  [roomBeatKey('the-reference', 0, 0)]: 'Eine Schreibtischlampe, eine leere Zeile, die auf eine Unterschrift wartet, und eine Bewerbung mit dem ordentlich getippten Namen Ihres Freundes oben darauf.',
  [roomBeatKey('the-reference', 0, 1)]: 'Sie kennen ihn seit einem Jahrzehnt. Er ist freundlich auf eine Weise, die ihn nichts kostet, loyal auf eine Weise, die ihn viel gekostet hat — und, leise, so wie alte Freunde Dinge wissen, ohne sie zu sagen, nicht besonders gut in genau diesem Job.',
  [roomBeatKey('the-reference', 0, 2)]: 'Die Stelle will jemand Präzises. Er ist wunderbar. Die beiden Tatsachen sitzen unbequem nah beieinander auf der Seite.',
  [roomBeatKey('the-reference', 0, 3)]: 'Die Referenz ist bis morgen früh fällig. Sie braucht eigentlich nur einen Satz. Das macht es schwierig — ein Satz ist genau genug Raum, um darin zu lügen, oder darin zu verletzen, oder darin sich zu verstecken.',
  [roomBeatKey('the-reference', 0, 4)]: 'Platzanweiser: Man sagt mir, gute Referenzen seien übliche Höflichkeiten. Ich habe genug von ihnen gelesen, um zu vermuten, dass „üblich“ in diesem Satz ziemlich viel Arbeit leistet.',
  [roomChoiceTextKey('the-reference', 'write-honest')]: 'Schreiben Sie die ehrliche Referenz — abgewogen, fair, und nicht schwärmerisch.',
  [roomChoiceHintKey('the-reference', 'write-honest')]: 'Lassen Sie die Wahrheit kosten, was sie kostet.',
  [roomChoiceOutcomeKey('the-reference', 'write-honest', 0)]: 'Sie schreiben sorgfältig, geben Anerkennung genau dort, wo sie verdient ist, und keinen Schritt weiter, und der entstehende Brief ist fair, so wie eine Waage fair ist — genau, und trostlos.',
  [roomChoiceOutcomeKey('the-reference', 'write-honest', 1)]: 'Er bekommt die Stelle nicht. Er erfährt nie genau, warum, obwohl Freundschaften eine Art haben, Wetter zu bemerken, auch ohne Vorhersage.',
  [roomChoiceOutcomeKey('the-reference', 'write-honest', 2)]: 'Platzanweiser: Sie sagten einem Fremden die Wahrheit und ließen einen Freund die Kosten dafür tragen. Das ist nicht nichts. Es ist auch nicht kostenlos.',
  [roomChoiceTextKey('the-reference', 'write-kind')]: 'Schreiben Sie die großzügige Version — wahr genug, wärmer als verdient.',
  [roomChoiceHintKey('the-reference', 'write-kind')]: 'Runden Sie jede Ecke auf.',
  [roomChoiceOutcomeKey('the-reference', 'write-kind', 0)]: 'Sie greifen nach Superlativen, die technisch vertretbar sind, und stapeln sie, bis der Brief ein wenig heller strahlt als die Person, die er beschreibt.',
  [roomChoiceOutcomeKey('the-reference', 'write-kind', 1)]: 'Er bekommt ein Vorstellungsgespräch. Was nach diesem Gespräch geschieht, ist nicht mehr Ihr Satz zu schreiben — obwohl Sie bemerken, dass Sie fest hoffen, die Stelle wachse zum Brief heran, und nicht umgekehrt.',
  [roomChoiceOutcomeKey('the-reference', 'write-kind', 2)]: 'Platzanweiser: Freundlichkeit, im Voraus datiert. Sie haben einen Scheck auf seine zukünftige Leistung ausgestellt. Ich gestehe, ich habe selbst ein paar davon geschrieben.',
  [roomChoiceTextKey('the-reference', 'decline')]: 'Sagen Sie, Sie können sie nicht schreiben — geben Sie die Feder zurück.',
  [roomChoiceHintKey('the-reference', 'decline')]: 'Verweigern, statt die Wahrheit zu schattieren.',
  [roomChoiceOutcomeKey('the-reference', 'decline', 0)]: 'Sie geben das Formular unterschrieben zurück, mit einer Erklärung, die in Ihrem Kopf besser klingt, als sie in seinem klingen wird.',
  [roomChoiceOutcomeKey('the-reference', 'decline', 1)]: 'Schweigen ist nicht neutral. Es ist Information, und er wird es genau als das lesen, was es ist — die eine Referenz, zu der Sie sich nicht durchringen konnten.',
  [roomChoiceOutcomeKey('the-reference', 'decline', 2)]: 'Platzanweiser: Sie sagten die Wahrheit durch Auslassung, was der billigste Weg ist, sie zu sagen. Er wird sie trotzdem hören. Schweigen bleibt selten lange privat.',
  [roomChoiceTextKey('the-reference', 'talk-first')]: 'Rufen Sie ihn heute Abend an. Sagen Sie ihm, was Sie schreiben können und was nicht — bevor Sie irgendetwas schreiben.',
  [roomChoiceHintKey('the-reference', 'talk-first')]: 'Der Brief kann eine Stunde warten. Die Freundschaft hat ein Jahrzehnt gewartet.',
  [roomChoiceOutcomeKey('the-reference', 'talk-first', 0)]: 'Der Anruf ist schlimmer als jeder Brief — eine lebendige Stimme lässt sich nicht redigieren. Sie sagen die wahre, abgewogene Version dessen, was Sie denken, laut, der Person, um die es geht.',
  [roomChoiceOutcomeKey('the-reference', 'talk-first', 1)]: 'Es löst sich nicht sauber auf. Er ist verletzt, oder erleichtert, oder beides in der falschen Reihenfolge. Aber was auch immer nach diesem Anruf getippt wird, er hat es mit offenen Augen mit Ihnen zusammen getippt, statt es später in der Entscheidung eines Fremden zu finden.',
  [roomChoiceOutcomeKey('the-reference', 'talk-first', 2)]: 'Platzanweiser: Sie haben diesem Brief einen vierten Leser hinzugefügt — den, um den es eigentlich ging. Ich gestehe, die meisten Referenzen begegnen ihm nie.',
  [roomExplanationKey('the-reference', 0)]: 'Ein enger Freund braucht ein Empfehlungsschreiben von Ihnen für eine Stelle, für die er nicht ganz geeignet ist, und was immer Sie schreiben, wird von einem Fremden gelesen, der auf Ihre Ehrlichkeit vertraut. Es geht darum, wem Ihre Loyalität eigentlich geschuldet ist: dem Freund, den Sie lieben, oder dem Fremden, der sich auf Ihr Wort verlässt? Es ist, als würden Sie gebeten, für die Babysitting-Fähigkeiten eines Freundes gegenüber einer Familie zu bürgen, die Sie nicht kennen, obwohl Sie ziemlich sicher sind, dass er nicht gut mit Kindern umgeht — jede Version des Briefes (schwärmerisch, ehrlich, oder die Weigerung, ihn zu schreiben) behandelt jemanden unfair. Es gibt auch eine vierte Option: mit dem Freund zu sprechen, bevor Sie irgendetwas in seinem Namen entscheiden.',
  [roomNoteTitleKey('the-reference')]: 'Die gnädige Lüge, notariell beglaubigt',
  [roomNoteThinkersKey('the-reference')]: 'Immanuel Kant · Bernard Williams, die Ethik der Aussage',
  [roomNoteBodyKey('the-reference')]: 'Kant vertrat, dass Wahrhaftigkeit eine der Menschheit als solcher geschuldete Pflicht sei, nicht kalibriert nach dem, wer fragt oder was er ertragen kann: Eine Referenz ist ein Versprechen, still einem Fremden gegeben, der sich darauf verlassen wird, und sie aufzublähen behandelt diesen Fremden als Mittel zum Zweck Ihres Freundes. Bernard Williams verkompliziert die Sauberkeit — eine Referenz ist auch ein Genre, halb Ritual, gelesen von Menschen, die mit ihrer üblichen Aufblähung vertraut sind, abgezogen, noch bevor der Absatz zu Ende ist. Welcher Konvention sind Sie also tatsächlich verpflichtet: der strengen, oder derjenigen, die alle still zu schummeln vereinbaren? Beachten Sie, was der Brief wirklich aufs Spiel setzt: nicht Ihre Integrität im Abstrakten, sondern das echte Vertrauen eines Fremden, ausgegeben im Namen Ihres Freundes, ohne dessen Wissen oder Zustimmung. **Loyalität, die einen Dritten kostet, ist keine Loyalität — sie ist eine Umbuchung.** Was immer Sie unterschrieben haben, Sie werden sein Gewicht wahrscheinlich an dem Tag spüren, an dem die Referenz von einem gewöhnlichen, schwierigen Dienstag an diesem Arbeitsplatz auf die Probe gestellt wird — und, weniger fair, wird er es auch.',
});
