// German translations, registered against the text catalog. UI chrome, act
// structure, room titles/hints/teasers, and endings are fully translated;
// long-form room prose (beats, choice outcomes, field notes) is not yet
// translated and gracefully falls back to English v2 (see resolver.ts).
// Milestone 5, Phase R4 — lowest priority, may slip to Milestone 6; this is
// the infrastructure + UI/structural layer, translated from the English v2
// source directly (never via Czech), matching cs.ts's key inventory.
import { registerAll } from '../../engine/text/resolver';
import { uiKey, actNameKey, actIntroKey, usherBarkKey, roomTitleKey, roomDoorHintKey, roomTeaserKey, endingTitleKey, endingEpitaphKey, keepsakeKey, stampKey, understoryNameKey } from '../../engine/text/keys';

registerAll('v2', 'de', {
  [uiKey('abandonToTitle')]: 'Aufgeben und zum Titelbildschirm zurückkehren',
  [uiKey('advanceHintClick')]: 'klicken · Leertaste',
  [uiKey('advanceHintContinue')]: 'weiter',
  [uiKey('rereadBack')]: 'Zurück — den vorherigen Abschnitt noch einmal lesen',
  [uiKey('rereadJumpTo')]: 'Abschnitt {n} noch einmal lesen',
  [uiKey('rereadScene')]: '⟲ die Szene noch einmal lesen',
  [uiKey('heartsAriaLabel')]: 'Griff auf die Wirklichkeit',
  [uiKey('exitGame')]: 'Spiel beenden',
  [uiKey('saveAndExit')]: 'Speichern und zum Titelbildschirm zurückkehren',
  [uiKey('settingsSectionDisplay')]: 'Anzeige',
  [uiKey('settingFullscreen')]: 'Vollbild',
  [uiKey('settingFullscreenDesc')]: 'Füllt den gesamten Bildschirm — lässt sich auch mit der Taste F umschalten.',
  [uiKey('renderScalePerformance')]: 'Rendering-Auflösung: Leistung',
  [uiKey('renderScaleStandard')]: 'Rendering-Auflösung: Standard',
  [uiKey('renderScaleSharp')]: 'Rendering-Auflösung: Scharf',
  [uiKey('settingRenderScale')]: 'Rendering-Auflösung',
  [uiKey('settingRenderScaleDesc')]: 'Niedriger = flüssiger auf schwächeren Grafikkarten, ein etwas weicheres Bild. Scharf nutzt die volle Bildschirmauflösung.',
  [uiKey('fpsCap30')]: 'Bildrate: 30 fps (flüssiger auf schwächeren Grafikkarten)',
  [uiKey('fpsCap60')]: 'Bildrate: 60 fps',
  [uiKey('settingFpsCap')]: 'Bildratenbegrenzung',
  [uiKey('settingFpsCapDesc')]: 'Niedriger spart spürbar Grafikleistung — dies ist ein Nebel-und-Text-Spiel, kein Actiontitel.',
  [uiKey('settingUiZoom')]: 'Oberflächengröße',
  [uiKey('settingUiZoomDesc')]: 'Vergrößert oder verkleinert Menüs und Text nach Belieben — die 3D-Szene bleibt scharf.',
  [uiKey('settingQualityDesc')]: 'Glüh- und Kantenglättungseffekte; erfordert eine stärkere Grafikkarte. Wirkt sich erst beim nächsten Start aus.',
  [uiKey('settingDynamicSceneryDesc')]: 'Räume färben Licht und Nebel dezent nach ihrer Stimmung.',
  [uiKey('settingLightModeDesc')]: 'Dasselbe Hotel im Morgenlicht — dieselben Zimmer, nur sanfter.',
  [uiKey('settingReducedMotionDesc')]: 'Verkürzt Kamerabewegungen und weiche Übergänge auf nahezu sofort — schonender bei Bewegungsempfindlichkeit.',
  [uiKey('settingsSectionAudio')]: 'Ton',
  [uiKey('settingMusicDesc')]: 'Eine leise, sich wandelnde Klangkulisse, die sich mit jedem Akt verändert.',
  [uiKey('settingSfxDesc')]: 'Türgeräusche, Seitenumblättern und die kleinen Klänge des Wählens.',
  [uiKey('settingsSectionText')]: 'Text & Sprache',
  [uiKey('settingLanguageDesc')]: 'Wirkt sich sofort aus, überall im Spiel.',
  [uiKey('settingTextVersionDesc')]: 'v1 ist die ursprüngliche Stimme, als wählbare Sicherung erhalten; v2 ist die aktuelle Überarbeitung.',
  [uiKey('settingTypewriterDesc')]: 'Der Text erscheint Buchstabe für Buchstabe, als würde ihn Ihnen jemand erzählen.',
  [uiKey('settingHighContrastDesc')]: 'Hellere Textfarbe für leichteres Lesen.',
  [uiKey('settingExaminedPath')]: 'Der geprüfte Pfad — zu Beginn jedes neuen Durchlaufs angeboten',
  [uiKey('settingExaminedPathDesc')]: 'Ändert nur die Vorauswahl beim Start eines neuen Durchlaufs — Sie werden stets erneut gefragt, und die Wahl für diesen Durchlauf bleibt unberührt.',
  [uiKey('examinedOfferTitle')]: 'Der Prüfungsanbau',
  [uiKey('examinedOfferIntro')]: 'Der Anbau legt Kommentare an. Er hat keine einzige Meinung — er hat vier.',
  [uiKey('examinedOfferBody')]: 'Ein freiwilliger Stempel in Ihrer Akte: Nach jeder bedeutsamen Entscheidung zeigt Ihnen ein stiller Beamter, wie mehrere benannte ethische Traditionen sie lesen könnten — nebeneinander, absichtlich uneinig. Nichts hier wird benotet oder bepunktet, und keine Lesart ist die „richtige“. Die Räume, Herzen und Enden, die Sie erreichen können, bleiben vollkommen unverändert. Jede Karte schließen Sie mit einem einzigen Klick. Die Vorauswahl für das nächste Mal können Sie jederzeit in den Einstellungen ändern.',
  [uiKey('walkPlainly')]: 'Den einfachen Weg gehen',
  [uiKey('takeExaminedPath')]: 'Den geprüften Pfad wählen',
  [uiKey('annexHeader')]: 'Der Anbau notiert:',
  [uiKey('tradition.consequence')]: 'Konsequenz',
  [uiKey('tradition.duty')]: 'Pflicht',
  [uiKey('tradition.virtue')]: 'Tugend',
  [uiKey('tradition.care')]: 'Fürsorge',
  [uiKey('settingsSectionData')]: 'Daten',
  [uiKey('resetRun')]: 'Aktuellen Durchlauf zurücksetzen',
  [uiKey('confirmAgain')]: 'Zum Bestätigen erneut klicken',
  [uiKey('resetRunDesc')]: 'Bricht Ihre laufende Reise ab. Notizen, Enden und Einstellungen bleiben erhalten.',
  [uiKey('resetRunDone')]: 'Durchlauf zurückgesetzt',
  [uiKey('resetProgress')]: 'Gesamten Fortschritt zurücksetzen',
  [uiKey('resetProgressDesc')]: 'Löscht alles — Notizen, Enden, Einstellungen, Ihren aktuellen Durchlauf — zurück zum allerersten Anfang.',
  [uiKey('recoveryTitle')]: 'Das Gerät flackert',
  [uiKey('recoveryBody')]: 'Irgendetwas im Getriebe hat das Gleichgewicht verloren. Ihre Akte ist sicher — nichts, was Sie hier getan haben, ist verloren.',
  [uiKey('recoveryReturn')]: 'Zurück zum Titelbildschirm',
  [uiKey('restoredFromBackup')]: 'Ihr letzter Speicherstand konnte nicht geladen werden — aus der vorherigen Sicherung wiederhergestellt. Es sollte nichts fehlen.',
  [uiKey('saveFailed')]: 'Ihr Fortschritt konnte nicht gespeichert werden — der Speicherplatz ist möglicherweise voll.',
  [uiKey('exportProfile')]: 'Profil exportieren',
  [uiKey('exportProfileDesc')]: 'Lädt Ihr gesamtes Profil als Datei herunter — eine persönliche Sicherung, oder etwas, das Sie versenden können, falls Sie einmal Hilfe brauchen.',
  [uiKey('exportProfileButton')]: 'Herunterladen',
  [uiKey('importProfile')]: 'Profil importieren',
  [uiKey('importProfileDesc')]: 'Ersetzt Ihr gesamtes Profil durch die eingefügte Datei. Ihr aktueller Fortschritt wird überschrieben — exportieren Sie ihn zuerst, wenn Sie ihn behalten möchten.',
  [uiKey('importProfileButton')]: 'Importieren',
  [uiKey('importProfilePlaceholder')]: 'Fügen Sie hier den Inhalt einer exportierten Profildatei ein',
  [uiKey('importProfileSuccess')]: 'Importiert — wird neu geladen…',
  [uiKey('importProfileError')]: 'Das sieht nicht nach einer gültigen Profildatei aus — es wurde nichts verändert.',
  [uiKey('ledger')]: 'Reisetagebuch',
  [uiKey('hotelRegister')]: 'Das Register',
  [uiKey('registerSub')]: 'die Gestalt dieses Ortes — ob Sie ihn schon durchschritten haben oder nicht',
  [uiKey('readMore')]: 'Weiterlesen →',
  [uiKey('articleKicker')]: 'Weiterführende Lektüre',
  [understoryNameKey()]: 'Das Untergeschoss',
  [uiKey('registerDoorsWalked')]: 'durchschrittene Türen',
  [uiKey('epiphaniesTitle')]: 'Erkenntnisse',
  [uiKey('guestStampsTitle')]: 'Gäste-Stempel',
  [stampKey('full-house')]: 'Volles Haus — jeder Raum aktenkundig',
  [stampKey('clean-bill')]: 'Jedes Mal mit jedem Herzen abgereist',
  [stampKey('frequent-guest')]: 'Ein Stammgast',
  [stampKey('below-the-surface')]: 'Den Weg nach unten gefunden',
  [stampKey('on-the-record')]: 'Den Prüfenden Pfad gegangen',
  [stampKey('student-of-the-place')]: 'Ein Kenner dieses Ortes',
  [uiKey('epiphanyEarned')]: 'heute Abend vermerkt',
  [uiKey('pivotalChoicesHeader')]: 'was Sie gewählt haben',
  [uiKey('doorsNeverOpenedHeader')]: 'Türen, die Sie nie geöffnet haben',
  [uiKey('ledgerRuns')]: 'Abgeschlossene Durchläufe',
  [uiKey('ledgerRooms')]: 'Erblickte Räume',
  [uiKey('ledgerEndings')]: 'Erblickte Enden',
  [uiKey('ledgerHearts')]: 'Verlorene Herzen, insgesamt',
  [uiKey('ledgerMostWalked')]: 'Die meistbegangene Tür',
  [uiKey('ledgerKeepsakes')]: 'Andenken im Regal',
  [uiKey('ledgerDescents')]: 'Abstiege nach unten',
  [uiKey('ledgerExamined')]: 'Geprüfte Durchläufe',
  [uiKey('ledgerLastMessage')]: 'Ihre letzte Nachricht',
  [uiKey('aboutDoors')]: '<b>Türen.</b> Jede Tür am Ende des Korridors ist eine andere Situation, und Sie können in einem einzigen Durchlauf nicht durch alle gehen. Eine Tür zu wählen heißt zu wählen, was Sie diesmal erwartet — und was Sie diesmal auslassen. Ein weiterer Durchlauf zeigt Ihnen den Rest.',
  [uiKey('aboutHearts')]: '<b>Herzen.</b> Drei Herzen sind Ihr Griff auf die Wirklichkeit. Eine Handvoll besonders kostspieliger Entscheidungen — vom Platzanweiser stets vorher angekündigt — kostet unmittelbar eines, ebenso wie eine vollständig erschöpfte Klarheit. Alle drei zu verlieren ist kein Bildschirm des Scheiterns — es ist ein echtes Ende, und so ist es auch geschrieben.',
  [uiKey('aboutTitle')]: 'Bevor Sie beginnen',
  [uiKey('aboutWhy')]: '<b>Warum spielen.</b> Nichts hier wird als richtig oder falsch bewertet. Jede Entscheidung verschiebt still drei verborgene Neigungen — Vernunft gegen Gefühl, das Selbst gegen die anderen, Kontrolle gegen Annahme — und genau diese, nicht eine Punktetafel, bestimmen, welche Türen sich öffnen, wie die Einrichtung aussieht und klingt, und zu welchem von sechs Enden Sie schließlich gelangen. Belohnt wird einzig ehrliches Engagement.',
  [uiKey('back')]: 'Zurück',
  [uiKey('begin')]: 'Beginnen',
  [uiKey('beginAgain')]: 'Erneut beginnen',
  [uiKey('codexSub')]: 'wodurch Sie gegangen sind — das bleibt gegangen',
  [uiKey('collected')]: 'gesammelt',
  [uiKey('continue')]: 'Weiter',
  [uiKey('continueJourney')]: 'Die Reise fortsetzen',
  [uiKey('creditsTitle')]: 'Mitwirkende',
  [uiKey('vestibuleButton')]: 'The Vestibule — Spiel wählen',
  [uiKey('oneDoorButton')]: 'Eine Tür',
  [uiKey('creditsIntro')]: 'Unabhängig geschrieben, entworfen und gebaut.',
  [uiKey('creditsEngine')]: '<b>Rendering & Audio.</b> Jedes Bild ist generierte Geometrie (Three.js), und jeder Klang wird zur Laufzeit erzeugt — keine gekauften oder heruntergeladenen Grafik- oder Audio-Assets.',
  [uiKey('creditsTooling')]: '<b>Erstellt mit.</b> Three.js (MIT-Lizenz) · TypeScript · Vite · Electron (Desktop-Build) · Vitest & Playwright (Tests).',
  [uiKey('creditsFonts')]: '<b>Schriftarten.</b> Inter, Spectral und Vazirmatn, über Fontsource — jeweils lizenziert unter der SIL Open Font License 1.1.',
  [uiKey('creditsNotices')]: 'Vollständige Lizenztexte Dritter finden Sie in THIRD_PARTY_NOTICES.md, das zusammen mit diesem Build verteilt wird.',
  [uiKey('creditsTelemetry')]: 'Nichts an Ihrem Spielverhalten wird verfolgt, irgendwohin gesendet oder mit einem Konto verknüpft — Ihr Spielstand existiert nur in diesem Browser oder dieser Installation.',
  [uiKey('done')]: 'Fertig',
  [uiKey('doorHelp')]: 'wählen Sie einen Weg — klicken Sie eine Tür an, oder drücken Sie ihre Zahl',
  [uiKey('doorHelpSingle')]: 'dies ist der einzige Weg nach vorn — klicken Sie die Tür an, oder drücken Sie 1',
  [uiKey('doorUnseenBadge')]: 'neu',
  [uiKey('doorUnseenBadgeTooltip')]: 'Durch diese Tür sind Sie noch nie gegangen',
  [uiKey('explainButton')]: 'Einfach erklären',
  [uiKey('explainLabel')]: 'In einfachen Worten',
  [uiKey('rememberedTag')]: 'erinnert',
  [uiKey('ending')]: 'Ende',
  [uiKey('endingFieldNoteHeader')]: 'Ende · Notiz',
  [uiKey('endingsWitnessed')]: 'erblickte Enden',
  [uiKey('fieldNoteHeader')]: 'Notiz',
  [uiKey('fieldNotes')]: 'Notizen',
  [uiKey('heartsTooltip')]: 'Ihr Griff auf die Wirklichkeit. Ein paar kostspielige Entscheidungen kosten unmittelbar ein Herz — der Platzanweiser warnt stets vorher —, ebenso wie eine völlig erschöpfte Klarheit. Alle drei Herzen zu verlieren ist ein Ende, kein Scheitern.',
  [uiKey('howToAdvance')]: '<b>Klicken</b> Sie den Text an, oder drücken Sie die <b>Leertaste</b>, um fortzufahren',
  [uiKey('howToClick')]: '<b>Klicken</b> Sie eine Tür an, oder drücken Sie <b>1–3</b>, um Ihren Weg zu wählen',
  [uiKey('howToPause')]: '<b>Esc</b> für Pause · fahren Sie über eine Tür, um ihren Hinweis zu lesen',
  [uiKey('lastMessageBody')]: 'Sie hatten einen Satz, und das war er:',
  [uiKey('lucidityTooltip')]: 'Klarheit — wie ehrlich Sie hingesehen haben.',
  [uiKey('menu')]: 'Menü',
  [uiKey('notYetWalked')]: 'noch nicht begangen',
  [uiKey('of')]: 'von',
  [uiKey('off')]: 'aus',
  [uiKey('on')]: 'ein',
  [uiKey('paused')]: 'Pause',
  [uiKey('pausedSub')]: 'die Räume warten — Zeit ist hier nur Zierde',
  [uiKey('persona.daniel')]: 'Sie messen zweimal. Trotzdem schneiden Sie manchmal falsch.',
  [uiKey('persona.mira')]: 'Ihnen fielen Dinge auf, bevor jemand Sie darum bat.',
  [uiKey('persona.sara')]: 'Sie bleiben bis zum Ende der Dinge. Das taten Sie schon immer.',
  [uiKey('persona.tomas')]: 'Sie verzeihen langsam, aber vollständig, sobald Sie es tun.',
  [uiKey('persona.about1')]: 'Vorsichtig mit anderen. Weniger vorsichtig mit sich selbst.',
  [uiKey('persona.about2')]: 'Schnell zum Lachen, langsam damit, zu sagen, was wirklich geschah.',
  [uiKey('persona.about3')]: 'Immer noch hier. Das ist an den meisten Tagen der Großteil der Antwort.',
  [uiKey('personaAboutLabel')]: 'Über Sie (optional — niemandem gezeigt, nur vom Platzanweiser gespürt)',
  [uiKey('personaFreeTextPlaceholder')]: 'Oder schreiben Sie kurz Ihr eigenes…',
  [uiKey('personaNameLabel')]: 'Name',
  [uiKey('personaNamePlaceholder')]: 'Ihr Name (oder wie man Sie hier nennen soll)',
  [uiKey('personaSkip')]: 'Überspringen — nennt mich Reisende(r)',
  [uiKey('personaSub')]: 'Rein zum Nutzen des Platzanweisers — das ändert nichts an den Räumen, nur daran, wie sie zu Ihnen sprechen.',
  [uiKey('personaTitle')]: 'Wer sind Sie, heute Nacht?',
  [uiKey('recapHeader')]: 'Wodurch Sie gegangen sind',
  [uiKey('resume')]: 'Fortsetzen',
  [uiKey('savedToast')]: 'Gespeichert',
  [uiKey('senderYou')]: 'Absender: Sie',
  [uiKey('settingHighContrast')]: 'Text mit hohem Kontrast',
  [uiKey('settingLanguage')]: 'Sprache',
  [uiKey('settingMusic')]: 'Hintergrundmusik',
  [uiKey('settingQuality')]: 'Hohe visuelle Qualität',
  [uiKey('settingDynamicScenery')]: 'Dynamische Umgebung (experimentell)',
  [uiKey('settingLightMode')]: 'Heller Modus',
  [uiKey('settingMusicVolume')]: 'Musiklautstärke',
  [uiKey('settingSfxVolume')]: 'Effektlautstärke',
  [uiKey('settingNarration')]: 'Vertonung',
  [uiKey('settingNarrationDesc')]: 'Gesprochene Zeilen, wo aufgenommen.',
  [uiKey('settingNarrationVolume')]: 'Vertonungslautstärke',
  [uiKey('hudLanguageTooltip')]: 'Sprache wechseln (wirkt sich ab dem nächsten Moment aus)',
  [uiKey('settingReducedMotion')]: 'Reduzierte Bewegung',
  [uiKey('settingSfx')]: 'Klangeffekte',
  [uiKey('settingTextVersion')]: 'Textversion',
  [uiKey('settingTypewriter')]: 'Schreibmaschinen-Text',
  [uiKey('settings')]: 'Einstellungen',
  [uiKey('settingsFooter')]: 'Qualitätsänderungen wirken sich erst beim nächsten Start aus · alles andere sofort',
  [uiKey('statHearts')]: 'bewahrte Herzen',
  [uiKey('statLucidity')]: 'Klarheit',
  [uiKey('statNewNotes')]: 'neue Notizen',
  [uiKey('title')]: 'Titelbildschirm',
  [uiKey('titleTagline')]: 'eine Reise durch die Räume · jede Tür ist eine Frage · der Weg zurück führt hindurch',
  [uiKey('titleAgeAdvisory')]: '16+ · Reife Themen',
  [uiKey('travelerLabel')]: 'Reisende(r)',
  [uiKey('travellerFallback')]: 'Reisende(r)',
  [uiKey('archiveBlurbFallback')]: 'keine weitere Beschreibung in der Akte',
  [uiKey('shelfTitle')]: 'Das Regal',
  [uiKey('keepsakeChoiceTooltip')]: 'Ein Andenken, still ausgegeben',
  [uiKey('versionV1')]: 'Stimme: v1 (ursprünglich)',
  [uiKey('versionV2')]: 'Stimme: v2 (neu)',
  [uiKey('walkAgain')]: 'Erneut gehen — die Räume ordnen sich für niemanden um, aber Sie haben sich verändert',
  [uiKey('whoAreYou')]: 'Wer sind Sie?',

  [actNameKey(0)]: 'Prolog — Das Wartezimmer',
  [actNameKey(1)]: 'Akt I — Die Untiefen',
  [actNameKey(2)]: 'Akt II — Das Getriebe',
  [actNameKey(3)]: 'Akt III — Der Spiegel',
  [actNameKey(4)]: 'Akt IV — Die Schwelle',

  [actIntroKey(1)]: 'Voraus: ein Korridor aus Wohnungstüren, jede sickert das warme Licht von Zuhause, die niemals Ihre waren. Die gewöhnlichen Räume, werden Sie feststellen, gehen am tiefsten. Eine Warnung, Reisende(r): einige dieser Türen kosten mehr als Zeit — entscheiden Sie sich gegen sich selbst, und ein Herz kann verloren gehen.',
  [actIntroKey(2)]: 'Der Korridor öffnet sich zu einem Getriebe — Zahnräder groß wie Monde, und langsame Bänder, die kleine, gleichgültige Sterne tragen. Hier werden die alten Gedankenexperimente jede Nacht neu aufgeführt, für eine Belegschaft von einer Person. Manche der alten Experimente verlangen noch immer Eintritt. Die Währung hier sind Herzen.',
  [actIntroKey(3)]: 'Der Boden wird zu schwarzem Spiegel. Ihre eigenen Erinnerungen hängen im Dunkeln wie Dioramen, ihre Gesichter über die Erkennbarkeit hinaus geglättet. Die Einrichtung nennt diesen Flügel archivarisch. Das heißt: Ihrer, {name}. Einiges von dem, was Sie hier finden, hat einen Preis, den Sie spüren, nicht nur sehen — und ja, dieser Preis kann ein Herz sein.',
  [actIntroKey(4)]: 'Der Nebel lichtet sich. Dahinter, unverkennbar, Morgen. Drei Türen bleiben, und dann die Schwelle. Alles von hier an zählt doppelt — obwohl der Platzanweiser sagen würde, das sei es immer gewesen. Selbst so nah am Ende kann eine unbedachte Entscheidung noch ein Herz kosten.',

  [usherBarkKey('understory-hint')]: 'Platzanweiser: Diese zweite Tür steht nicht auf meiner Karte. Einst tat sie es. Nehmen Sie sie oder nicht; ein zweites Mal wird sie nicht angeboten.',
  [usherBarkKey('gate-single-door')]: 'Platzanweiser: Für diesen Abschnitt bleibt nur eine Tür. Die anderen liegen schon hinter Ihnen, gewählt oder ausgelassen — was auf seine Weise ebenfalls eine Wahl war. Diese hier ist schlicht der einzige noch offene Weg.',
  [usherBarkKey('first-choice-explainer')]: 'Platzanweiser: Mehrere Türen, und nur manche werden diesmal Ihre sein — der Rest bleibt vorerst verschlossen. Jede verbirgt eine andere Situation, nicht einen anderen Punktestand. Wählen Sie die, deren Frage Sie wirklich bereit sind auszuhalten.',
  [usherBarkKey('second-run')]: 'Platzanweiser: Sie sind zurückgekehrt. Der Hebel steht dort, wo Sie ihn zurückließen; hier ordnen wir nichts um — Beständigkeit ist der einzige Luxus, den sich diese Einrichtung erlaubt.',
  [usherBarkKey('reason-low')]: 'Platzanweiser: Sie wiegen jeden Raum wie ein Hauptbuch. Die Räume haben es bemerkt und ihre Fußnoten entsprechend angepasst.',
  [usherBarkKey('reason-high')]: 'Platzanweiser: Sie fühlen hier alles, ganz offen. Der Korridor ist deswegen wärmer. Das ist keine Redewendung.',
  [usherBarkKey('self-low')]: 'Platzanweiser: Sie haben sich unversehrt gehalten. Ein vernünftiger Instinkt. Fragen Sie sich gelegentlich, wozu dieses Bewahren eigentlich dient.',
  [usherBarkKey('self-high')]: 'Platzanweiser: Sie verschenken immer noch Stücke von sich. Es steht Ihnen — obwohl mit der Zeit weniger zum Verschenken bleibt.',
  [usherBarkKey('control-low')]: 'Platzanweiser: Sie kämpfen gegen jeden Raum. Ich bewundere es. Die Räume lässt es unbewegt.',
  [usherBarkKey('control-high')]: 'Platzanweiser: Sie haben aufgehört, im Wasser zu kämpfen, Reisende(r). Treiben ist auch eine Fertigkeit. Ebenso zu wissen, wo das Ufer geblieben ist.',
  [usherBarkKey('first-heart-loss')]: 'Platzanweiser: Da — ein Herz, ausgegeben. Sie spüren es. Es ist nur ein Gerät, das ein ehrliches Hauptbuch führt, nicht mehr. Ihnen bleiben {hearts}. Es ist kein Countdown bis zur Niederlage; es ist einfach, was diese Entscheidung gekostet hat.',
  [usherBarkKey('one-heart')]: 'Platzanweiser: Ein Herz bleibt. Ich darf mir keine Sorgen machen. Betrachten Sie dies als die nächstmögliche Annäherung daran.',
  [usherBarkKey('high-lucidity')]: 'Platzanweiser: In dieser Tiefe sehen Sie ungewöhnlich klar. Klarheit ist die einzige Währung hier, die das Haus nicht fälschen kann.',
  [usherBarkKey('generic0')]: 'Platzanweiser: Wählen Sie eine Tür. Jede von ihnen ist Ihre — eine Tatsache, die die meisten Reisenden erst lange danach glauben.',
  [usherBarkKey('generic1')]: 'Platzanweiser: Lassen Sie sich Zeit. Die Türen ertragen das besser, als Sie erwarten würden.',
  [usherBarkKey('generic2')]: 'Platzanweiser: Ich würde Ihnen sagen, welche ich wählen würde, aber ich habe sie alle einmal gewählt. Ziehen Sie Ihre eigenen Schlüsse.',
  [usherBarkKey('generic3')]: 'Platzanweiser: Die Hinweise über den Türen sind ehrlich. Wir handeln hier nicht mit falschen Zeichen.',
  [usherBarkKey('generic4')]: 'Platzanweiser: Es gibt keine Eile. Zeit ist an diesem Ort reine Zierde.',
  [usherBarkKey('generic5')]: 'Platzanweiser: Was immer Sie auslassen, bleibt hier, ungeöffnet, für einen anderen Besuch. Das ist kein Verlust. Es ist einfach nicht diese Geschichte.',
  [usherBarkKey('generic6')]: 'Platzanweiser: Lesen Sie den Hinweis, bevor Sie sich entscheiden. Er ist keine Verzierung — er ist die einzige ehrliche Vorschau, die Sie bekommen.',
  [usherBarkKey('generic7')]: 'Platzanweiser: Die Türen kennen Ihren Namen schon, {name}. Was sie neugierig macht, ist der Rest von Ihnen.',
  [usherBarkKey('remembered-room')]: 'An diesen Ort erinnern Sie sich.',
  [usherBarkKey('examined-act1')]: 'Platzanweiser: Würden Sie dasselbe vor Zeugen wählen? Wäre das besser gewesen — oder nur hübscher?',
  [usherBarkKey('examined-act2')]: 'Platzanweiser: Wenn eine Maschine recht hat, spielt es dann eine Rolle, warum?',
  [usherBarkKey('examined-act3')]: 'Platzanweiser: Welche Ihrer heutigen Gründe waren wirklich Ihre eigenen, und welche nur auswendig Gelerntes?',
  [usherBarkKey('examined-act4')]: 'Platzanweiser: Wenn es niemand jemals erfahren könnte, gehen Sie noch einmal durch den Korridor. Würde sich etwas ändern?',

  [roomTitleKey('waiting-room')]: 'Das Wartezimmer',
  [roomDoorHintKey('waiting-room')]: 'Die Tür, durch die Sie schon gehen',
  [roomTeaserKey('waiting-room')]: 'Wo immer Sie sind, hier beginnt es.',
  [roomTitleKey('wallet')]: 'Die Brieftasche',
  [roomDoorHintKey('wallet')]: 'Die Tür der Sache, die niemand sah',
  [roomTeaserKey('wallet')]: 'Eine Prüfung ohne Zeugen — außer dem einen, der zählt.',
  [roomTitleKey('dinner-table')]: 'Der Esstisch',
  [roomDoorHintKey('dinner-table')]: 'Die Tür der Frage, die Sie schon kennen',
  [roomTeaserKey('dinner-table')]: 'Eine Frage ohne sichere Antwort, gestellt von jemandem, den Sie lieben.',
  [roomTitleKey('promotion')]: 'Die Beförderung',
  [roomDoorHintKey('promotion')]: 'Die Tür des Hauptbuchs und des Freundes',
  [roomTeaserKey('promotion')]: 'Loyalität und Vorteil — nur eines von beiden kann gewinnen.',
  [roomTitleKey('beggars-math')]: 'Die Mathematik des Bettlers',
  [roomDoorHintKey('beggars-math')]: 'Die Tür des Nahen und des Fernen',
  [roomTeaserKey('beggars-math')]: 'Der Fremde vor Ihnen, oder das größere Gut, das Sie nicht sehen.',
  [roomTitleKey('quiet-alarm')]: 'Der stille Alarm',
  [roomDoorHintKey('quiet-alarm')]: 'Die Tür des Geräuschs durch die Wand',
  [roomTeaserKey('quiet-alarm')]: 'Eine Wand, Stille, und eine Entscheidung, die sich nicht rückgängig machen lässt.',
  [roomTitleKey('photograph')]: 'Die Fotografie',
  [roomDoorHintKey('photograph')]: 'Die Tür, die bereits warm ist',
  [roomTeaserKey('photograph')]: 'Feuer hinter zwei Türen. So oder so verlieren Sie etwas.',
  [roomTitleKey('buridans-queue')]: 'Buridans Warteschlange',
  [roomDoorHintKey('buridans-queue')]: 'Die Tür der zwei Türen',
  [roomTeaserKey('buridans-queue')]: 'Eine Entscheidung, die nur schwer ist, weil nichts sie leichter macht.',
  [roomTitleKey('the-reference')]: 'Das Empfehlungsschreiben',
  [roomDoorHintKey('the-reference')]: 'Die Tür der geliehenen Feder',
  [roomTeaserKey('the-reference')]: 'Jemand, den Sie lieben, braucht einen Satz von Ihnen, der nicht wahr sein muss.',
  [roomTitleKey('junction')]: 'Die Weiche',
  [roomDoorHintKey('junction')]: 'Die Tür des Hebels und der Waage',
  [roomTeaserKey('junction')]: 'Ein Hebel, eine Brücke, und dieselben fünf Leben, zweimal.',
  [roomTitleKey('experience-machine')]: 'Die Erlebnismaschine',
  [roomDoorHintKey('experience-machine')]: 'Die Tür, hinter der nichts falsch ist',
  [roomTeaserKey('experience-machine')]: 'Ein perfektes Leben, garantiert — wenn Sie tragen können, was es kostet.',
  [roomTitleKey('ship')]: 'Das Schiff',
  [roomDoorHintKey('ship')]: 'Die Tür der ausgetauschten Planken',
  [roomTeaserKey('ship')]: 'Stück für Stück werden Sie ersetzt. Wer geht am Ende hinaus?',
  [roomTitleKey('casino-pascal')]: 'Pascals Kasino',
  [roomDoorHintKey('casino-pascal')]: 'Die Tür mit dem unendlichen Gewinn',
  [roomTeaserKey('casino-pascal')]: 'Eine Wette auf Gott, an einem Tisch, dessen Quoten das Haus bestimmt.',
  [roomTitleKey('omelas')]: 'Die Stadt Omelas',
  [roomDoorHintKey('omelas')]: 'Die dritte Tür, summend im Festlicht',
  [roomTeaserKey('omelas')]: 'Die Freude einer Stadt, und ein Preis, über den nicht laut gesprochen wird.',
  [roomTitleKey('chinese-room')]: 'Das chinesische Zimmer',
  [roomDoorHintKey('chinese-room')]: 'Die Tür der perfekten Antwort',
  [roomTeaserKey('chinese-room')]: 'Es antwortet auf alles, mit Ihren eigenen Worten.',
  [roomTitleKey('newcomb-annex')]: 'Newcombs Anbau',
  [roomDoorHintKey('newcomb-annex')]: 'Die Tür der bereits gefüllten Kiste',
  [roomTeaserKey('newcomb-annex')]: 'Ihre Wahl wurde schon vorhergesagt. Noch ist es nicht zu spät — oder doch?',
  [roomTitleKey('veil-of-ignorance')]: 'Der Schleier des Nichtwissens',
  [roomDoorHintKey('veil-of-ignorance')]: 'Die Tür des gezogenen Loses',
  [roomTeaserKey('veil-of-ignorance')]: 'Sie entwerfen eine kleine Welt, und leben dann in ihr.',
  [roomTitleKey('court-of-usher')]: 'Das Gericht des Platzanweisers',
  [roomDoorHintKey('court-of-usher')]: 'Die Tür mit der angeschlagenen Vorladung',
  [roomTeaserKey('court-of-usher')]: 'Der Platzanweiser steht vor Gericht, und Sie sind der Richter.',
  [roomTitleKey('teleporter')]: 'Der Teleporter',
  [roomDoorHintKey('teleporter')]: 'Die Tür, die auch eine Wand ist',
  [roomTeaserKey('teleporter')]: 'Eine Maschine zerstört Sie und druckt eine Kopie. Diese besteht darauf, hindurchgegangen zu sein.',
  [roomTitleKey('editor')]: 'Der Redakteur',
  [roomDoorHintKey('editor')]: 'Die Tür des roten Stifts',
  [roomTeaserKey('editor')]: 'Streichen Sie Ihre schlimmste Erinnerung für immer. Sehen Sie, was sie festhielt.',
  [roomTitleKey('introduction')]: 'Die Vorstellung',
  [roomDoorHintKey('introduction')]: 'Eine kleine, schlichte Tür, höflich einen Spalt geöffnet',
  [roomTeaserKey('introduction')]: 'Ein Raum, der nur wissen will, wer Sie wirklich sind.',
  [roomTitleKey('debt-of-dead')]: 'Die Schuld der Toten',
  [roomDoorHintKey('debt-of-dead')]: 'Die Tür, an die zu klopfen Sie geschworen haben, es nie zu tun',
  [roomTeaserKey('debt-of-dead')]: 'Jemand, der Ihnen wehgetan hat, liegt im Sterben und bittet um Vergebung.',
  [roomTitleKey('marys-room')]: 'Marys Zimmer',
  [roomDoorHintKey('marys-room')]: 'Die Tür des grauen Arbeitszimmers',
  [roomTeaserKey('marys-room')]: 'Sie weiß absolut alles über eine Farbe, die sie nie gesehen hat.',
  [roomTitleKey('butterfly-dream')]: 'Der Schmetterlingstraum',
  [roomDoorHintKey('butterfly-dream')]: 'Die Tür der Papierwand',
  [roomTeaserKey('butterfly-dream')]: 'Jemand hier träumt von jemandem. Es ist nicht klar, in welche Richtung.',
  [roomTitleKey('swampman')]: 'Der Sumpfmann',
  [roomDoorHintKey('swampman')]: 'Die Tür des zweiten Mantels',
  [roomTeaserKey('swampman')]: 'Jemand da drinnen trägt Ihr Gesicht, und ist dabei sehr höflich.',
  [roomTitleKey('the-cave')]: 'Die Höhle',
  [roomDoorHintKey('the-cave')]: 'Eine niedrige Tür mit Feuerlicht',
  [roomTeaserKey('the-cave')]: 'Schatten, die Sie erkennen, für ein Publikum von einer Person vorgeführt.',
  [roomTitleKey('free-will')]: 'Das Wartezimmer des freien Willens',
  [roomDoorHintKey('free-will')]: 'Die Tür, die auf Sie gewartet hat',
  [roomTeaserKey('free-will')]: 'Die Lichter gehen an, bevor Sie sich entscheiden. Sie verlieren jede Wette, absichtlich.',
  [roomTitleKey('boulder')]: 'Der Felsblock',
  [roomDoorHintKey('boulder')]: 'Die Tür am Fuß des Hügels',
  [roomTeaserKey('boulder')]: 'Eine Aufgabe, die sich selbst aufhebt. Die Frage ist, wie Sie sie tragen.',
  [roomTitleKey('last-message')]: 'Die letzte Nachricht',
  [roomDoorHintKey('last-message')]: 'Die Tür mit dem Briefschlitz',
  [roomTeaserKey('last-message')]: 'Ein Satz zurück in die wache Welt. Wer erhält ihn?',
  [roomTitleKey('door-that-asks')]: 'Die Tür, die fragt',
  [roomDoorHintKey('door-that-asks')]: 'Die letzte Tür, die Ihre Akte liest',
  [roomTeaserKey('door-that-asks')]: 'Sie hat Ihre ganze Akte gelesen. Jetzt will sie wissen, ob Sie dazu stehen.',
  [roomTitleKey('the-archive')]: 'Das Archiv · unten',
  [roomDoorHintKey('the-archive')]: 'Eine Treppe, die nicht auf der Karte war',
  [roomTeaserKey('the-archive')]: 'Irgendwo dort unten ist Ihr letzter Durchlauf schon zu den Akten genommen.',
  [roomTitleKey('the-unchosen')]: 'Die Ungewählten · unten',
  [roomDoorHintKey('the-unchosen')]: 'Ein Korridor der Türen, die Sie nicht geöffnet haben',
  [roomTeaserKey('the-unchosen')]: 'Sie standen die ganze Zeit einen Spalt offen. Eine tut es noch immer.',
  [roomTitleKey('the-echo')]: 'Das Echo · unten',
  [roomDoorHintKey('the-echo')]: 'Ein Raum mit dem zweiten Stuhl',
  [roomTeaserKey('the-echo')]: 'Jemand sitzt schon darauf, und es klingt wie Sie.',

  [endingTitleKey('return')]: 'Die Rückkehr',
  [endingEpitaphKey('return')]: 'Die Welt war genau dieselbe. Das war nie das Versprechen.',
  [endingTitleKey('open-hand')]: 'Die offene Hand',
  [endingEpitaphKey('open-hand')]: 'Sie verschenkten sich, Münze für Münze, gern — meistens gern.',
  [endingTitleKey('fortress')]: 'Die Festung',
  [endingEpitaphKey('fortress')]: 'Nichts kam hinein. Das war der Plan. Nichts kam hinein.',
  [endingTitleKey('dissolved')]: 'Aufgelöst',
  [endingEpitaphKey('dissolved')]: 'Das Meer hat noch nie auch nur eine einzige Sache verloren, die zählte.',
  [endingTitleKey('gardener')]: 'Der Gärtner',
  [endingEpitaphKey('gardener')]: 'Die Räume brauchen immer einen Wächter. Der Wächter brauchte immer die Räume.',
  [endingTitleKey('punchline')]: 'Die Pointe',
  [endingEpitaphKey('punchline')]: 'Es war nie jemand hier außer Ihnen. Guter Witz, nicht wahr?',
  [endingTitleKey('anamnesis')]: 'Anamnese',
  [endingEpitaphKey('anamnesis')]: 'Sie kehrten nicht zurück. Sie erwachten, und das Erwachen enthielt die Räume.',
});

// ---------- Keepsakes (Milestone 5, Phase N) ----------
registerAll('v2', 'de', {
  [keepsakeKey('casino-chip', 'name')]: 'Der unausgegebene Jeton',
  [keepsakeKey('casino-chip', 'origin')]: 'vom Kasino behalten, unausgegeben',
  [keepsakeKey('photo-corner', 'name')]: 'Eine Ecke des Fotos',
  [keepsakeKey('photo-corner', 'origin')]: 'aus dem Feuer gerettet, eine Ecke davon',
  [keepsakeKey('ship-splinter', 'name')]: 'Ein Splitter des Schiffs',
  [keepsakeKey('ship-splinter', 'origin')]: 'aus der Werkstatt behalten, ursprüngliches Holz',
  [keepsakeKey('release-form', 'name')]: 'Der Entlassungsschein der Maschine',
  [keepsakeKey('release-form', 'origin')]: 'auf dem Weg hinaus unterschrieben, nie abgeschickt',
});
