// Farsi translations, registered against the text catalog. UI chrome, act
// structure, room titles/hints/teasers, and endings are fully translated;
// long-form room prose (beats, choice outcomes, field notes) is not yet
// translated and gracefully falls back to English v2 (see resolver.ts).
// RTL layout and the Vazirmatn webfont are applied in ui/locale.ts.
import { registerAll } from '../../engine/text/resolver';
import { uiKey, actNameKey, actIntroKey, usherBarkKey, roomTitleKey, roomDoorHintKey, roomTeaserKey, endingTitleKey, endingEpitaphKey, keepsakeKey } from '../../engine/text/keys';

registerAll('v2', 'fa', {
  [uiKey('abandonToTitle')]: 'رها کردن و بازگشت به صفحه‌ی عنوان',
  [uiKey('advanceHintClick')]: 'کلیک · فاصله',
  [uiKey('advanceHintContinue')]: 'ادامه',
  [uiKey('heartsAriaLabel')]: 'چنگ به واقعیت',
  [uiKey('exitGame')]: 'خروج از بازی',
  [uiKey('saveAndExit')]: 'ذخیره و بازگشت به صفحه‌ی عنوان',
  [uiKey('settingsSectionDisplay')]: 'نمایش',
  [uiKey('settingFullscreen')]: 'تمام‌صفحه',
  [uiKey('settingFullscreenDesc')]: 'تمام صفحه را پر می‌کند — با کلید F هم قابل تغییر است.',
  [uiKey('renderScalePerformance')]: 'وضوح رندر: عملکرد',
  [uiKey('renderScaleStandard')]: 'وضوح رندر: استاندارد',
  [uiKey('renderScaleSharp')]: 'وضوح رندر: واضح',
  [uiKey('settingRenderScale')]: 'وضوح رندر',
  [uiKey('settingRenderScaleDesc')]: 'کمتر = روان‌تر روی کارت‌های گرافیک ضعیف‌تر، تصویری کمی نرم‌تر. حالت واضح از وضوح کامل صفحه‌ی شما استفاده می‌کند.',
  [uiKey('fpsCap30')]: 'نرخ فریم: ۳۰ فریم بر ثانیه (روان‌تر روی کارت‌های گرافیک ضعیف‌تر)',
  [uiKey('fpsCap60')]: 'نرخ فریم: ۶۰ فریم بر ثانیه',
  [uiKey('settingFpsCap')]: 'محدودیت نرخ فریم',
  [uiKey('settingFpsCapDesc')]: 'مقدار کمتر به‌طور محسوسی توان گرافیکی کمتری مصرف می‌کند — این بازی مه و متن است، نه یک بازی اکشن.',
  [uiKey('settingUiZoom')]: 'اندازه‌ی رابط کاربری',
  [uiKey('settingUiZoomDesc')]: 'منوها و متن را به دلخواه شما بزرگ یا کوچک می‌کند — صحنه‌ی سه‌بعدی همچنان واضح می‌ماند.',
  [uiKey('settingQualityDesc')]: 'جلوه‌های درخشش و صاف‌سازی؛ به کارت گرافیک قوی‌تری نیاز دارد. با بارگذاری بعدی اعمال می‌شود.',
  [uiKey('settingDynamicSceneryDesc')]: 'اتاق‌ها نور و مه را به‌آرامی متناسب با حال‌وهوایشان رنگ می‌کنند.',
  [uiKey('settingLightModeDesc')]: 'همان هتل در نور صبح — همان اتاق‌ها، با رنگ‌مایه‌ای ملایم‌تر.',
  [uiKey('settingReducedMotionDesc')]: 'حرکت دوربین و انیمیشن‌های نرم را تقریباً آنی می‌کند — برای حساسیت به حرکت مناسب‌تر است.',
  [uiKey('settingsSectionAudio')]: 'صدا',
  [uiKey('settingMusicDesc')]: 'فضایی آرام و درحال‌تغییر که با هر پرده عوض می‌شود.',
  [uiKey('settingSfxDesc')]: 'صدای درها، ورق‌خوردن صفحه، و صداهای کوچک انتخاب.',
  [uiKey('settingsSectionText')]: 'متن و زبان',
  [uiKey('settingLanguageDesc')]: 'بلافاصله، در همه‌جای بازی اعمال می‌شود.',
  [uiKey('settingTextVersionDesc')]: 'نسخه‌ی ۱ لحن اصلی است که به‌عنوان نسخه‌ی پشتیبان نگه داشته شده؛ نسخه‌ی ۲ بازنویسی کنونی است.',
  [uiKey('settingTypewriterDesc')]: 'متن حرف‌به‌حرف ظاهر می‌شود، مثل روایت‌شدن یک داستان.',
  [uiKey('settingHighContrastDesc')]: 'رنگ روشن‌تر متن برای خواندن آسان‌تر.',
  [uiKey('settingExaminedPath')]: 'مسیر بررسی‌شده — در آغاز هر بازی تازه پیشنهاد می‌شود',
  [uiKey('settingExaminedPathDesc')]: 'فقط چیزی را تغییر می‌دهد که در آغاز یک بازی تازه از پیش انتخاب شده — همیشه دوباره از شما پرسیده می‌شود و انتخاب این بازی دست‌نخورده می‌ماند.',
  [uiKey('examinedOfferTitle')]: 'ضمیمه‌ی بررسی',
  [uiKey('examinedOfferIntro')]: 'ضمیمه تفسیر بایگانی می‌کند. نظری ندارد — چهار نظر دارد.',
  [uiKey('examinedOfferBody')]: 'مهری اختیاری روی پرونده‌ی ورودی شما: پس از هر انتخاب مهم، یک کارمند آرام نشان می‌دهد چند سنت اخلاقیِ نام‌برده ممکن است آن را چگونه بخوانند — کنار هم، عمداً ناهم‌رأی. اینجا هیچ‌چیز نمره یا امتیاز نمی‌گیرد و هیچ خوانشی «درست» نیست. اتاق‌ها، قلب‌ها، و پایان‌هایی که می‌توانید به آن‌ها برسید کاملاً بدون تغییرند. هر کارت با یک کلیک بسته می‌شود. می‌توانید بعداً در تنظیمات، پیش‌فرض دفعه‌ی بعد را تغییر دهید.',
  [uiKey('walkPlainly')]: 'راه رفتن ساده',
  [uiKey('takeExaminedPath')]: 'انتخاب مسیر بررسی‌شده',
  [uiKey('annexHeader')]: 'ضمیمه ثبت می‌کند:',
  [uiKey('tradition.consequence')]: 'پیامد',
  [uiKey('tradition.duty')]: 'وظیفه',
  [uiKey('tradition.virtue')]: 'فضیلت',
  [uiKey('tradition.care')]: 'مراقبت',
  [uiKey('settingsSectionData')]: 'داده‌ها',
  [uiKey('resetRun')]: 'بازنشانی بازی جاری',
  [uiKey('confirmAgain')]: 'برای تأیید دوباره کلیک کنید',
  [uiKey('resetRunDesc')]: 'سفر نیمه‌کاره‌ی شما را رها می‌کند. یادداشت‌ها، پایان‌ها و تنظیمات حفظ می‌شوند.',
  [uiKey('resetRunDone')]: 'بازی بازنشانی شد',
  [uiKey('resetProgress')]: 'بازنشانی کامل پیشرفت',
  [uiKey('resetProgressDesc')]: 'همه‌چیز را پاک می‌کند — یادداشت‌ها، پایان‌ها، تنظیمات، بازی جاری شما — و به نقطه‌ی آغاز بازمی‌گردد.',
  [uiKey('recoveryTitle')]: 'مرکز سوسو می‌زند',
  [uiKey('recoveryBody')]: 'چیزی در چرخ‌دنده‌ها تعادلش را از دست داد. پرونده‌ی شما امن است — هیچ‌چیز از آنچه اینجا انجام داده‌اید از دست نرفته.',
  [uiKey('recoveryReturn')]: 'بازگشت به صفحه‌ی عنوان',
  [uiKey('restoredFromBackup')]: 'بارگذاریِ آخرین ذخیره با مشکل مواجه شد — از نسخه‌ی پیشین بازیابی شد. چیزی نباید از دست رفته باشد.',
  [uiKey('saveFailed')]: 'پیشرفت شما ذخیره نشد — ممکن است فضای ذخیره‌سازی پر باشد.',
  [uiKey('exportProfile')]: 'برون‌بردنِ پروفایل',
  [uiKey('exportProfileDesc')]: 'کل پروفایل شما را به‌عنوان یک فایل دانلود می‌کند — نسخه‌ی پشتیبانِ شخصی، یا چیزی برای ارسال در صورت نیاز به کمک.',
  [uiKey('exportProfileButton')]: 'دانلود',
  [uiKey('importProfile')]: 'درون‌ریزیِ پروفایل',
  [uiKey('importProfileDesc')]: 'کل پروفایل شما را با فایلِ چسبانده‌شده جایگزین می‌کند. پیشرفتِ فعلیِ شما بازنویسی می‌شود — اگر می‌خواهید نگهش دارید، اول آن را برون‌ببرید.',
  [uiKey('importProfileButton')]: 'درون‌ریزی',
  [uiKey('importProfilePlaceholder')]: 'محتوای فایلِ برون‌بردهِ پروفایل را اینجا بچسبانید',
  [uiKey('importProfileSuccess')]: 'درون‌ریزی شد — در حال بارگذاریِ دوباره…',
  [uiKey('importProfileError')]: 'این شبیه فایلِ پروفایلِ معتبر نیست — چیزی تغییر نکرد.',
  [uiKey('ledger')]: 'دفترِ مسافر',
  [uiKey('epiphaniesTitle')]: 'بصیرت‌ها',
  [uiKey('epiphanyEarned')]: 'امشب ثبت شد',
  [uiKey('ledgerRuns')]: 'سفرهای کامل‌شده',
  [uiKey('ledgerRooms')]: 'اتاق‌های دیده‌شده',
  [uiKey('ledgerEndings')]: 'پایان‌های دیده‌شده',
  [uiKey('ledgerHearts')]: 'قلب‌های ازدست‌رفته، در کل',
  [uiKey('ledgerMostWalked')]: 'پرتردَدترین در',
  [uiKey('ledgerKeepsakes')]: 'یادگارهای روی قفسه',
  [uiKey('ledgerDescents')]: 'نزول‌ها به پایین',
  [uiKey('ledgerExamined')]: 'سفرهای بررسی‌شده',
  [uiKey('ledgerLastMessage')]: 'آخرین پیامِ شما',
  [uiKey('aboutDoors')]: '<b>درها.</b> هر در پشت راهرو یک موقعیت متفاوت است و نمی‌توانید در یک بازی از همه‌ی آن‌ها عبور کنید. انتخاب یک در یعنی انتخاب اینکه با چه چیزی روبه‌رو می‌شوید — و این‌بار از چه چیزی می‌گذرید. بازیِ دوباره، بقیه را نشان می‌دهد.',
  [uiKey('aboutHearts')]: '<b>قلب‌ها.</b> سه قلب، میزان چنگ شما به واقعیت است. دسته‌ای از انتخاب‌های بسیار پرهزینه — که نگهبان همیشه پیشاپیش هشدار می‌دهد — مستقیماً یک قلب می‌گیرند، همان‌طور که تمام‌شدنِ کاملِ هوشیاری هم همین‌طور است. از دست دادن هر سه قلب، صفحه‌ی شکست نیست — یک پایان واقعی است، و همین‌طور نوشته شده است.',
  [uiKey('aboutTitle')]: 'پیش از آغاز',
  [uiKey('aboutWhy')]: '<b>چرا بازی کنید.</b> هیچ‌چیز اینجا درست یا غلط ارزیابی نمی‌شود. هر انتخاب، بی‌صدا، سه گرایش پنهان را جابه‌جا می‌کند — عقل در برابر احساس، خود در برابر دیگران، کنترل در برابر پذیرش — و همین‌ها، نه یک جدول امتیاز، تعیین می‌کنند کدام درها باز می‌شوند، این مکان چگونه به‌نظر می‌رسد و چه صدایی دارد، و سرانجام به کدام‌یک از شش پایان می‌رسید. تنها چیزی که پاداش می‌گیرد، درگیرشدنِ صادقانه است.',
  [uiKey('back')]: 'بازگشت',
  [uiKey('begin')]: 'آغاز',
  [uiKey('beginAgain')]: 'دوباره آغاز کنید',
  [uiKey('codexSub')]: 'آنچه از آن گذشته‌اید — گذشته باقی می‌ماند',
  [uiKey('collected')]: 'جمع‌آوری‌شده',
  [uiKey('continue')]: 'ادامه',
  [uiKey('continueJourney')]: 'ادامه‌ی سفر',
  [uiKey('creditsTitle')]: 'دست‌اندرکاران',
  [uiKey('creditsIntro')]: 'نوشته‌شده، طراحی‌شده و ساخته‌شده به‌طور مستقل.',
  [uiKey('creditsEngine')]: '<b>رندر و صدا.</b> هر عنصر تصویری هندسه‌ای تولیدشده است (Three.js) و هر صدا در زمان اجرا تولید می‌شود — بدون هیچ دارایی هنری یا صوتی خریداری‌شده یا دانلودشده.',
  [uiKey('creditsTooling')]: '<b>ساخته‌شده با.</b> Three.js (مجوز MIT) · TypeScript · Vite · Electron (نسخه‌ی دسکتاپ) · Vitest و Playwright (آزمایش).',
  [uiKey('creditsFonts')]: '<b>قلم‌ها.</b> Inter، Spectral و Vazirmatn، از طریق Fontsource — هرکدام تحت مجوز SIL Open Font License 1.1.',
  [uiKey('creditsNotices')]: 'متن کامل مجوزهای شخص‌ثالث در فایل THIRD_PARTY_NOTICES.md، همراه با این نسخه توزیع شده است.',
  [uiKey('creditsTelemetry')]: 'هیچ‌چیز از نحوه‌ی بازی شما ردیابی، ارسال، یا به حسابی متصل نمی‌شود — ذخیره‌ی شما فقط در همین مرورگر یا همین نصب وجود دارد.',
  [uiKey('done')]: 'انجام شد',
  [uiKey('doorHelp')]: 'مسیری را انتخاب کنید — روی دری کلیک کنید، یا شماره‌اش را بزنید',
  [uiKey('doorHelpSingle')]: 'این تنها راه پیش رو است — روی در کلیک کنید، یا عدد ۱ را بزنید',
  [uiKey('doorUnseenBadge')]: 'جدید',
  [uiKey('doorUnseenBadgeTooltip')]: 'هرگز از این در نگذشته‌اید',
  [uiKey('explainButton')]: 'به‌زبان ساده توضیح بده',
  [uiKey('explainLabel')]: 'به‌زبان ساده',
  [uiKey('rememberedTag')]: 'به‌یادمانده',
  [uiKey('ending')]: 'پایان',
  [uiKey('endingFieldNoteHeader')]: 'پایان · یادداشت',
  [uiKey('endingsWitnessed')]: 'پایان‌های دیده‌شده',
  [uiKey('fieldNoteHeader')]: 'یادداشت',
  [uiKey('fieldNotes')]: 'یادداشت‌ها',
  [uiKey('heartsTooltip')]: 'چنگ شما به واقعیت. چند انتخاب پرهزینه مستقیماً یک قلب می‌گیرند — نگهبان همیشه پیشاپیش هشدار می‌دهد — همان‌طور که تمام‌شدنِ کاملِ هوشیاری هم همین‌طور است. از دست دادن هر سه قلب یک پایان است، نه شکست.',
  [uiKey('howToAdvance')]: '<b>کلیک</b> روی متن، یا فشردن <b>فاصله</b>، برای ادامه',
  [uiKey('howToClick')]: '<b>کلیک</b> روی دری، یا فشردن <b>۱ تا ۳</b>، برای انتخاب مسیر',
  [uiKey('howToPause')]: '<b>Esc</b> برای توقف · با نگه‌داشتن نشانگر روی در، راهنمای آن را بخوانید',
  [uiKey('lastMessageBody')]: 'یک جمله داشتید، و این همان بود:',
  [uiKey('lucidityTooltip')]: 'هوشیاری — اینکه چقدر صادقانه نگاه کرده‌اید.',
  [uiKey('menu')]: 'منو',
  [uiKey('notYetWalked')]: 'هنوز طی‌نشده',
  [uiKey('of')]: 'از',
  [uiKey('off')]: 'خاموش',
  [uiKey('on')]: 'روشن',
  [uiKey('paused')]: 'توقف',
  [uiKey('pausedSub')]: 'اتاق‌ها منتظر می‌مانند — زمان اینجا فقط تزئین است',
  [uiKey('persona.daniel')]: 'دوبار اندازه می‌گیرید. باز هم گاهی اشتباه می‌برید.',
  [uiKey('persona.mira')]: 'پیش از آنکه کسی از شما بخواهد، متوجه‌ی چیزها می‌شدید.',
  [uiKey('persona.sara')]: 'تا پایانِ هر چیزی می‌مانید. همیشه همین‌طور بوده‌اید.',
  [uiKey('persona.tomas')]: 'دیر می‌بخشید، اما وقتی می‌بخشید، کامل می‌بخشید.',
  [uiKey('persona.about1')]: 'با دیگران محتاط. با خودتان کمتر.',
  [uiKey('persona.about2')]: 'زود می‌خندید، دیر می‌گویید واقعاً چه اتفاقی افتاده.',
  [uiKey('persona.about3')]: 'هنوز اینجایید. بیشترِ روزها، همین بیشترِ پاسخ است.',
  [uiKey('personaAboutLabel')]: 'درباره‌ی شما (اختیاری — به هیچ‌کس نشان داده نمی‌شود، فقط نگهبان آن را حس می‌کند)',
  [uiKey('personaFreeTextPlaceholder')]: 'یا خودتان بنویسید، کوتاه…',
  [uiKey('personaNameLabel')]: 'نام',
  [uiKey('personaNamePlaceholder')]: 'نام شما (یا آنچه اینجا با آن صدایتان می‌زنند)',
  [uiKey('personaSkip')]: 'رد شدن — مرا مسافر صدا کنید',
  [uiKey('personaSub')]: 'صرفاً برای خود نگهبان — چیزی در اتاق‌ها تغییر نمی‌کند، فقط نحوه‌ی صحبتشان با شما.',
  [uiKey('personaTitle')]: 'امشب، شما کیستید؟',
  [uiKey('recapHeader')]: 'آنچه از آن گذشتید',
  [uiKey('resume')]: 'ادامه',
  [uiKey('savedToast')]: 'ذخیره شد',
  [uiKey('senderYou')]: 'فرستنده: شما',
  [uiKey('settingHighContrast')]: 'کنتراست بالای متن',
  [uiKey('settingLanguage')]: 'زبان',
  [uiKey('settingMusic')]: 'موسیقی پس‌زمینه',
  [uiKey('settingQuality')]: 'کیفیت تصویری بالا',
  [uiKey('settingDynamicScenery')]: 'محیط پویا (آزمایشی)',
  [uiKey('settingLightMode')]: 'حالت روشن',
  [uiKey('settingMusicVolume')]: 'میزان صدای موسیقی',
  [uiKey('settingSfxVolume')]: 'میزان صدای جلوه‌ها',
  [uiKey('hudLanguageTooltip')]: 'تغییر زبان (از لحظه‌ی بعدی اعمال می‌شود)',
  [uiKey('settingReducedMotion')]: 'کاهش حرکت',
  [uiKey('settingSfx')]: 'جلوه‌های صوتی',
  [uiKey('settingTextVersion')]: 'نسخه‌ی متن',
  [uiKey('settingTypewriter')]: 'نمایش تدریجی متن',
  [uiKey('settings')]: 'تنظیمات',
  [uiKey('settingsFooter')]: 'تغییر کیفیت در بارگذاری بعدی اعمال می‌شود · زبان و نسخه‌ی متن بلافاصله اعمال می‌شوند',
  [uiKey('statHearts')]: 'قلب‌های باقی‌مانده',
  [uiKey('statLucidity')]: 'هوشیاری',
  [uiKey('statNewNotes')]: 'یادداشت‌های جدید',
  [uiKey('title')]: 'صفحه‌ی عنوان',
  [uiKey('titleTagline')]: 'سفری میان اتاق‌ها · هر در یک پرسش است · راه بازگشت از میان آن‌هاست',
  [uiKey('titleAgeAdvisory')]: '16+ · مضامین بزرگسالان',
  [uiKey('travelerLabel')]: 'مسافر',
  [uiKey('travellerFallback')]: 'مسافر',
  [uiKey('archiveBlurbFallback')]: 'در پرونده توضیح بیشتری ثبت نشده',
  [uiKey('shelfTitle')]: 'قفسه',
  [uiKey('keepsakeChoiceTooltip')]: 'یادگاری، آرام خرج‌شده',
  [uiKey('versionV1')]: 'لحن: نسخه‌ی ۱ (اصلی)',
  [uiKey('versionV2')]: 'لحن: نسخه‌ی ۲ (جدید)',
  [uiKey('walkAgain')]: 'دوباره طی کنید — اتاق‌ها برای هیچ‌کس دوباره نمی‌چینند، اما شما تغییر کرده‌اید',
  [uiKey('whoAreYou')]: 'شما کیستید؟',

  [actNameKey(0)]: 'پیش‌درآمد — اتاق انتظار',
  [actNameKey(1)]: 'پرده‌ی یکم — کم‌عمق‌ها',
  [actNameKey(2)]: 'پرده‌ی دوم — کارخانه',
  [actNameKey(3)]: 'پرده‌ی سوم — آینه',
  [actNameKey(4)]: 'پرده‌ی چهارم — آستانه',

  [actIntroKey(1)]: 'پیش رو: راهرویی از درهای آپارتمان‌ها، هرکدام نشت‌کننده‌ی نور گرمِ خانه‌هایی که هرگز از آن شما نبودند. اتاق‌های معمولی، خواهید دید، از همه عمیق‌تر می‌روند. هشداری، مسافر: چند تا از این درها بیشتر از زمان هزینه دارند — علیه خودتان انتخاب کنید، و ممکن است قلبی از دست برود.',
  [actIntroKey(2)]: 'راهرو به کارخانه‌ای می‌رسد — چرخ‌دنده‌هایی به بزرگی ماه، و نوارهایی که به‌آرامی ستاره‌های کوچک و بی‌تفاوت را حمل می‌کنند. اینجا آزمایش‌های فکریِ کهن، هر شب، برای یک خدمه‌ی تک‌نفره، بار دیگر اجرا می‌شوند. برخی از آزمایش‌های قدیمی هنوز هزینه‌ی ورود می‌گیرند. واحد پول اینجا، قلب است.',
  [actIntroKey(3)]: 'کف به آینه‌ای سیاه بدل می‌شود. خاطرات خودتان مانند دیوراما در تاریکی آویزانند، چهره‌ها تا مرز ناشناختگی نرم شده‌اند. این مرکز، این بخش را آرشیوی می‌نامد. یعنی: مال شما، {name}. بخشی از آنچه اینجا می‌یابید، بهایی دارد که حسش می‌کنید، نه فقط می‌بینید — و بله، این بها می‌تواند یک قلب باشد.',
  [actIntroKey(4)]: 'مه رقیق می‌شود. آن‌سوتر، بی‌هیچ تردیدی، صبح است. سه در باقی مانده، و سپس آستانه. هرچه از این پس رخ دهد دوچندان به‌حساب می‌آید — هرچند نگهبان می‌گفت همیشه همین‌طور بوده. حتی این‌قدر نزدیک به پایان، یک انتخاب بی‌دقت هنوز می‌تواند یک قلب هزینه داشته باشد.',

  [usherBarkKey('understory-hint')]: 'نگهبان: آن در دوم روی نقشه‌ی من نیست. زمانی بود. بردارید یا نبردارید؛ دوباره پیشنهاد نخواهد شد.',
  [usherBarkKey('gate-single-door')]: 'نگهبان: برای این بخش تنها یک در باقی مانده. بقیه از پیش پشت سر شما هستند، انتخاب‌شده یا ردشده — که خود نوعی انتخاب بود. این یکی صرفاً تنها راهی است که هنوز باز مانده.',
  [usherBarkKey('first-choice-explainer')]: 'نگهبان: چند در، و فقط برخی این‌بار از آنِ شما خواهند بود — بقیه فعلاً بسته می‌مانند. هرکدام موقعیتی متفاوت را پنهان می‌کنند، نه امتیازی متفاوت را. آن دری را انتخاب کنید که پرسشش را واقعاً حاضرید با آن بنشینید.',
  [usherBarkKey('second-run')]: 'نگهبان: بازگشته‌اید. اهرم همان‌جاست که رهایش کردید؛ اینجا چیزی را دوباره نمی‌چینیم — ثبات، تنها تجملی است که این مکان به خود اجازه می‌دهد.',
  [usherBarkKey('reason-low')]: 'نگهبان: هر اتاق را مثل یک دفتر حساب می‌سنجید. اتاق‌ها متوجه شده‌اند، و پانوشت‌هایشان را بر همین اساس تنظیم کرده‌اند.',
  [usherBarkKey('reason-high')]: 'نگهبان: همه‌چیز را اینجا، آشکارا، حس می‌کنید. راهرو به همین دلیل گرم‌تر شده. این استعاره نیست.',
  [usherBarkKey('self-low')]: 'نگهبان: خودتان را یک‌پارچه نگه داشته‌اید. غریزه‌ای معقول. گاهی بپرسید این نگه‌داشتن برای چیست.',
  [usherBarkKey('self-high')]: 'نگهبان: هنوز تکه‌هایی از خود را می‌بخشید. به شما می‌آید — هرچند با گذر زمان، چیز کمتری برای بخشیدن می‌ماند.',
  [usherBarkKey('control-low')]: 'نگهبان: با هر اتاقی می‌جنگید. تحسینش می‌کنم. اتاق‌ها بی‌تفاوت‌اند.',
  [usherBarkKey('control-high')]: 'نگهبان: در آب، دیگر مقاومت نمی‌کنید، مسافر. شناور ماندن هم مهارتی است. دانستنِ اینکه ساحل کجا ماند هم همین‌طور.',
  [usherBarkKey('first-heart-loss')]: 'نگهبان: بفرمایید — قلبی، خرج شد. حسش کنید. این فقط دستگاهی است که دفتر حساب صادقانه‌ای نگه می‌دارد، نه بیشتر. {hearts} قلب برایتان مانده. این شمارش معکوس تا شکست نیست؛ فقط همان چیزی است که آن انتخاب هزینه داشت.',
  [usherBarkKey('one-heart')]: 'نگهبان: یک قلب باقی مانده. اجازه ندارم نگران باشم. این را نزدیک‌ترین حالت به نگرانیِ من بدانید.',
  [usherBarkKey('high-lucidity')]: 'نگهبان: در این عمق، غیرعادی روشن می‌بینید. روشنی تنها ارزی است که این خانه نمی‌تواند تقلبی بسازد.',
  [usherBarkKey('generic0')]: 'نگهبان: دری را انتخاب کنید. همه‌شان از آنِ شمایند — چیزی که بیشتر مسافران تا مدت‌ها بعد باور نمی‌کنند.',
  [usherBarkKey('generic1')]: 'نگهبان: عجله نکنید. درها بهتر از آنچه فکر می‌کنید تحمل می‌کنند.',
  [usherBarkKey('generic2')]: 'نگهبان: می‌گفتم کدام را انتخاب می‌کردم، اما زمانی همه‌شان را انتخاب کرده‌ام. خودتان نتیجه بگیرید.',
  [usherBarkKey('generic3')]: 'نگهبان: راهنماهای بالای درها درست‌اند. اینجا نشانه‌ی دروغین به کار نمی‌بریم.',
  [usherBarkKey('generic4')]: 'نگهبان: عجله‌ای نیست. زمان اینجا فقط تزئین است.',
  [usherBarkKey('generic5')]: 'نگهبان: هرچه را رد کنید همین‌جا می‌ماند، بازنشده، برای دیدارِ دیگری. این یک از دست دادن نیست. فقط این داستان نیست.',
  [usherBarkKey('generic6')]: 'نگهبان: پیش از تصمیم، راهنما را بخوانید. تزئین نیست — تنها پیش‌نمایشِ صادقانه‌ای است که دریافت می‌کنید.',
  [usherBarkKey('generic7')]: 'نگهبان: درها از پیش نام شما را می‌دانند، {name}. آنچه کنجکاوشان می‌کند، باقیِ شماست.',
  [usherBarkKey('remembered-room')]: 'این مکان را به یاد دارید.',
  [usherBarkKey('examined-act1')]: 'نگهبان: آیا جلوی شاهدان هم همین انتخاب را می‌کردید؟ آیا آن بهتر می‌بود — یا فقط دلپذیرتر؟',
  [usherBarkKey('examined-act2')]: 'نگهبان: وقتی دستگاه درست می‌گوید، آیا اهمیتی دارد که چرا؟',
  [usherBarkKey('examined-act3')]: 'نگهبان: کدام‌یک از دلایل امشب شما واقعاً از آنِ خودتان بود، و کدام فقط تمرین بود؟',
  [usherBarkKey('examined-act4')]: 'نگهبان: اگر هیچ‌کس هرگز نمی‌توانست بفهمد، دوباره از راهرو عبور کنید. چیزی تغییر می‌کند؟',

  [roomTitleKey('waiting-room')]: 'اتاق انتظار',
  [roomDoorHintKey('waiting-room')]: 'دری که از پیش از آن گذشته‌اید',
  [roomTeaserKey('waiting-room')]: 'هرجا که باشید، همین‌جا آغاز می‌شود.',
  [roomTitleKey('wallet')]: 'کیف پول',
  [roomDoorHintKey('wallet')]: 'در آن چیزی که کسی ندید',
  [roomTeaserKey('wallet')]: 'آزمونی بی‌شاهد — جز همان یکی که اهمیت دارد.',
  [roomTitleKey('dinner-table')]: 'میز شام',
  [roomDoorHintKey('dinner-table')]: 'در پرسشی که از پیش می‌دانید',
  [roomTeaserKey('dinner-table')]: 'پرسشی بی‌پاسخ امن، از سوی کسی که دوستش دارید.',
  [roomTitleKey('promotion')]: 'ترفیع',
  [roomDoorHintKey('promotion')]: 'در دفتر حساب و دوست',
  [roomTeaserKey('promotion')]: 'وفاداری و منفعت — فقط یکی می‌تواند برنده شود.',
  [roomTitleKey('beggars-math')]: 'حساب گدا',
  [roomDoorHintKey('beggars-math')]: 'در نزدیک و دور',
  [roomTeaserKey('beggars-math')]: 'غریبه‌ی روبه‌رویتان، یا خیرِ بزرگ‌تری که نمی‌بینید.',
  [roomTitleKey('quiet-alarm')]: 'زنگ خطر خاموش',
  [roomDoorHintKey('quiet-alarm')]: 'در صدایی از میان دیوار',
  [roomTeaserKey('quiet-alarm')]: 'دیواری، سکوتی، و تصمیمی که بازگشت‌ناپذیر است.',
  [roomTitleKey('photograph')]: 'عکس',
  [roomDoorHintKey('photograph')]: 'دری که از پیش گرم است',
  [roomTeaserKey('photograph')]: 'آتش پشت دو در. در هر صورت چیزی را از دست می‌دهید.',
  [roomTitleKey('buridans-queue')]: 'ضمیمه‌ی بوریدان',
  [roomDoorHintKey('buridans-queue')]: 'درِ دو در',
  [roomTeaserKey('buridans-queue')]: 'انتخابی که تنها به این دلیل دشوار است که هیچ‌چیز آن را آسان نمی‌کند.',
  [roomTitleKey('the-reference')]: 'نامه‌ی معرفی',
  [roomDoorHintKey('the-reference')]: 'درِ قلمِ به‌عاریت‌گرفته',
  [roomTeaserKey('the-reference')]: 'کسی که دوستش دارید به جمله‌ای از شما نیاز دارد که شاید درست نباشد.',
  [roomTitleKey('junction')]: 'تقاطع',
  [roomDoorHintKey('junction')]: 'در اهرم و وزن',
  [roomTeaserKey('junction')]: 'اهرمی، پلی، و همان پنج جان، دوباره.',
  [roomTitleKey('experience-machine')]: 'دستگاه تجربه',
  [roomDoorHintKey('experience-machine')]: 'دری که پشتش هیچ‌چیز اشتباه نیست',
  [roomTeaserKey('experience-machine')]: 'زندگی‌ای کامل، تضمین‌شده — اگر بتوانید هزینه‌اش را تحمل کنید.',
  [roomTitleKey('ship')]: 'کشتی',
  [roomDoorHintKey('ship')]: 'در تخته‌های تعویض‌شده',
  [roomTeaserKey('ship')]: 'ذره‌ذره جایگزین می‌شوید. چه کسی بیرون می‌رود؟',
  [roomTitleKey('casino-pascal')]: 'کازینوی پاسکال',
  [roomDoorHintKey('casino-pascal')]: 'دری با جایزه‌ی بی‌کران',
  [roomTeaserKey('casino-pascal')]: 'شرطی بر سر خدا، سر میزی که شرایطش را خانه تعیین می‌کند.',
  [roomTitleKey('omelas')]: 'شهر اومیلاس',
  [roomDoorHintKey('omelas')]: 'دری سوم، درخشان از نور جشن',
  [roomTeaserKey('omelas')]: 'شادیِ یک شهر، و بهایی که هرگز به زبان نمی‌آید.',
  [roomTitleKey('chinese-room')]: 'اتاق چینی',
  [roomDoorHintKey('chinese-room')]: 'درِ پاسخ کامل',
  [roomTeaserKey('chinese-room')]: 'به هر چیزی پاسخ می‌دهد، با کلمات خودتان.',
  [roomTitleKey('newcomb-annex')]: 'ضمیمه‌ی نیوکامب',
  [roomDoorHintKey('newcomb-annex')]: 'درِ جعبه‌ی از پیش پرشده',
  [roomTeaserKey('newcomb-annex')]: 'انتخاب شما از پیش پیش‌بینی شده. هنوز دیر نشده — یا شده؟',
  [roomTitleKey('veil-of-ignorance')]: 'حجاب جهل',
  [roomDoorHintKey('veil-of-ignorance')]: 'درِ قرعه‌ی کشیده‌شده',
  [roomTeaserKey('veil-of-ignorance')]: 'دنیایی کوچک طراحی خواهید کرد، و سپس در آن زندگی خواهید کرد.',
  [roomTitleKey('court-of-usher')]: 'دادگاه نگهبان',
  [roomDoorHintKey('court-of-usher')]: 'دری با احضاریه‌ای بر آن میخکوب',
  [roomTeaserKey('court-of-usher')]: 'نگهبان محاکمه می‌شود، و شما قاضی‌اید.',
  [roomTitleKey('teleporter')]: 'دروازه‌ی انتقال',
  [roomDoorHintKey('teleporter')]: 'دری که دیوار هم هست',
  [roomTeaserKey('teleporter')]: 'دستگاهی شما را نابود می‌کند و کپی چاپ می‌کند. کپی اصرار دارد که خودش عبور کرده.',
  [roomTitleKey('editor')]: 'ویراستار',
  [roomDoorHintKey('editor')]: 'در قلم قرمز',
  [roomTeaserKey('editor')]: 'بدترین خاطره‌تان را برای همیشه خط بزنید. ببینید چه چیزی را نگه داشته بود.',
  [roomTitleKey('introduction')]: 'معرفی',
  [roomDoorHintKey('introduction')]: 'دری کوچک و ساده، مؤدبانه نیمه‌باز',
  [roomTeaserKey('introduction')]: 'اتاقی که فقط می‌خواهد بداند واقعاً کیستید.',
  [roomTitleKey('debt-of-dead')]: 'دین مردگان',
  [roomDoorHintKey('debt-of-dead')]: 'دری که قسم خوردید هرگز نکوبید',
  [roomTeaserKey('debt-of-dead')]: 'کسی که به شما بد کرد، در حال مرگ، طلب بخشش می‌کند.',
  [roomTitleKey('marys-room')]: 'اتاق مری',
  [roomDoorHintKey('marys-room')]: 'در اتاق مطالعه‌ی خاکستری',
  [roomTeaserKey('marys-room')]: 'او همه‌چیز را درباره‌ی رنگی که هرگز ندیده می‌داند.',
  [roomTitleKey('butterfly-dream')]: 'خواب پروانه',
  [roomDoorHintKey('butterfly-dream')]: 'در دیوار کاغذی',
  [roomTeaserKey('butterfly-dream')]: 'کسی اینجا در خواب کسی دیگر است. جهتش روشن نیست.',
  [roomTitleKey('swampman')]: 'مرد مرداب',
  [roomDoorHintKey('swampman')]: 'در کت دوم',
  [roomTeaserKey('swampman')]: 'کسی آن‌تو چهره‌ی شما را دارد، و بابتش بسیار مؤدب است.',
  [roomTitleKey('the-cave')]: 'غار',
  [roomDoorHintKey('the-cave')]: 'در کوتاه با نور آتش',
  [roomTeaserKey('the-cave')]: 'سایه‌هایی که می‌شناسید، برای تماشاگری واحد به نمایش درآمده.',
  [roomTitleKey('free-will')]: 'اتاق انتظار اراده‌ی آزاد',
  [roomDoorHintKey('free-will')]: 'دری که پیش از شما را دیده بود',
  [roomTeaserKey('free-will')]: 'چراغ‌ها پیش از انتخاب شما روشن می‌شوند. عمداً هر شرط را می‌بازید.',
  [roomTitleKey('boulder')]: 'تخته‌سنگ',
  [roomDoorHintKey('boulder')]: 'دری در دامنه‌ی تپه',
  [roomTeaserKey('boulder')]: 'کاری که خودش را باطل می‌کند. پرسش این است که چگونه حملش می‌کنید.',
  [roomTitleKey('last-message')]: 'آخرین پیام',
  [roomDoorHintKey('last-message')]: 'دری با شکاف نامه',
  [roomTeaserKey('last-message')]: 'یک جمله به دنیای بیداری بازمی‌گردد. به چه کسی می‌رسد؟',
  [roomTitleKey('door-that-asks')]: 'دری که می‌پرسد',
  [roomDoorHintKey('door-that-asks')]: 'آخرین در، که پرونده‌تان را می‌خواند',
  [roomTeaserKey('door-that-asks')]: 'کل پرونده‌تان را خوانده. حالا می‌خواهد بداند آیا پای آن ایستاده‌اید.',
  [roomTitleKey('the-archive')]: 'بایگانی · پایین',
  [roomDoorHintKey('the-archive')]: 'پله‌ای که روی نقشه نبود',
  [roomTeaserKey('the-archive')]: 'جایی آن پایین، آخرین دورِ شما از پیش بایگانی شده.',
  [roomTitleKey('the-unchosen')]: 'ناگزیده‌ها · پایین',
  [roomDoorHintKey('the-unchosen')]: 'راهروی درهایی که باز نکردید',
  [roomTeaserKey('the-unchosen')]: 'تمام این مدت نیمه‌باز مانده بودند. یکی‌شان هنوز همین‌طور است.',
  [roomTitleKey('the-echo')]: 'پژواک · پایین',
  [roomDoorHintKey('the-echo')]: 'اتاقی با صندلی دوم',
  [roomTeaserKey('the-echo')]: 'کسی از قبل روی آن نشسته، و صدایش شبیه شماست.',

  [endingTitleKey('return')]: 'بازگشت',
  [endingEpitaphKey('return')]: 'دنیا دقیقاً همان بود. این هرگز وعده نبود.',
  [endingTitleKey('open-hand')]: 'دست گشوده',
  [endingEpitaphKey('open-hand')]: 'خودتان را سکه به سکه بخشیدید، با میل — بیشتر اوقات با میل.',
  [endingTitleKey('fortress')]: 'دژ',
  [endingEpitaphKey('fortress')]: 'هیچ‌چیز داخل نشد. نقشه همین بود. هیچ‌چیز داخل نشد.',
  [endingTitleKey('dissolved')]: 'محو شده',
  [endingEpitaphKey('dissolved')]: 'دریا هرگز چیزی را که اهمیت داشت از دست نداده است.',
  [endingTitleKey('gardener')]: 'باغبان',
  [endingEpitaphKey('gardener')]: 'اتاق‌ها همیشه به یک نگهبان نیاز دارند. نگهبان همیشه به اتاق‌ها نیاز داشت.',
  [endingTitleKey('punchline')]: 'نکته‌ی پایانی',
  [endingEpitaphKey('punchline')]: 'هیچ‌کس اینجا جز شما نبود. جوک خوبی است، نه؟',
});

// ---------- Keepsakes (Milestone 5, Phase N) ----------
registerAll('v2', 'fa', {
  [keepsakeKey('casino-chip', 'name')]: 'ژتون خرج‌نشده',
  [keepsakeKey('casino-chip', 'origin')]: 'از کازینو نگه‌داشته‌شده، خرج‌نشده',
  [keepsakeKey('photo-corner', 'name')]: 'گوشه‌ای از عکس',
  [keepsakeKey('photo-corner', 'origin')]: 'از آتش نجات‌یافته، یک گوشه از آن',
  [keepsakeKey('ship-splinter', 'name')]: 'تراشه‌ای از کشتی',
  [keepsakeKey('ship-splinter', 'origin')]: 'از کارگاه نگه‌داشته‌شده، چوب اصلی',
  [keepsakeKey('release-form', 'name')]: 'فرم ترخیص دستگاه',
  [keepsakeKey('release-form', 'origin')]: 'در راه خروج امضا شده، هرگز پست نشده',
});
