// French translation of the v2 room prose (beats, choice text/hint/outcome,
// field notes, explanations) for the prologue and Act I. Registered under
// version 'v2'. Translated from the English v2 source directly, per
// CLAUDE.md's context-first rule.
import { registerAll } from './resolver';
import {
  roomBeatKey,
  roomChoiceHintKey,
  roomChoiceOutcomeKey,
  roomChoiceTextKey,
  roomExplanationKey,
  roomNoteBodyKey,
  roomNoteThinkersKey,
  roomNoteTitleKey,
} from './keys';

// ---------- Prologue ----------
registerAll('v2', 'fr', {
  [roomBeatKey('waiting-room', 0, 0)]: 'Vous vous réveillez dans une salle d’attente. Ça sent l’hôpital, un couloir d’enfance, et la pluie.',
  [roomBeatKey('waiting-room', 0, 1)]: 'Il y a des chaises. Une horloge sans aiguilles. Une fenêtre, et derrière la fenêtre, encore une fenêtre.',
  [roomBeatKey('waiting-room', 0, 2)]: 'Vous ne vous souvenez pas de votre nom. Vous le cherchez comme une langue cherche une dent manquante.',
  [roomBeatKey('waiting-room', 0, 3)]: 'Quelque chose est arrivé. Un effondrement, un voyage, un accident, une mort — le mot ne cesse de glisser. Quoi que ce fût, cela a emporté le reste de vous avec lui, et en a classé les morceaux quelque part.',
  [roomBeatKey('waiting-room', 0, 4)]: 'Une ombre est assise derrière le comptoir d’accueil, portant une auréole et une petite paire de cornes. L’une des cornes vacille, faiblement, comme une enseigne presque éteinte.',
  [roomBeatKey('waiting-room', 0, 5)]: 'Le Placeur : Vous êtes éveillé. C’est soit une très bonne nouvelle, soit la pire des sortes. J’ai cessé de deviner laquelle.',
  [roomBeatKey('waiting-room', 0, 6)]: 'Le Placeur : Ceci est le traitement. Vous avez été dissous — cela arrive, tôt ou tard, à presque tout le monde, et aujourd’hui, c’est arrivé à vous. Ce qui reste de vous est conservé dans les pièces devant vous. Traversez-en suffisamment, sincèrement, et vous pourriez vous reconstituer. Ou pas. Je suis tenu de le préciser.',
  [roomChoiceTextKey('waiting-room', 'where')]: '« Où suis-je ? »',
  [roomChoiceHintKey('waiting-room', 'where')]: 'D’abord, s’orienter.',
  [roomChoiceOutcomeKey('waiting-room', 'where', 0)]: 'Le Placeur : Entre. Derrière. Sous. Les mots pour cet endroit sont surtout des prépositions — rien d’aussi solide qu’un nom.',
  [roomChoiceOutcomeKey('waiting-room', 'where', 1)]: 'Le Placeur : Ce qui compte, c’est la direction : en avant, à travers les pièces. Chacune contient une situation ; vous choisissez votre chemin à travers elle, et ce choix est ce qui vous recompose — ou achève de vous défaire. Nous tenons un compte approximatif, en cœurs, et dans la clarté de votre regard. Perdez complètement votre prise, et il existe des fins pires que celle-là. Il en existe aussi de meilleures.',
  [roomChoiceTextKey('waiting-room', 'who')]: '« Êtes-vous Dieu ou le Diable ? »',
  [roomChoiceHintKey('waiting-room', 'who')]: 'Connaissez votre bureaucrate.',
  [roomChoiceOutcomeKey('waiting-room', 'who', 0)]: 'Le Placeur : Dieu, les jours impairs. Le Diable, les jours pairs. Je ne vous dirai pas lequel nous sommes aujourd’hui — après tant de siècles à ce poste, même moi, j’ai cessé d’être certain de savoir quel rôle est lequel.',
  [roomChoiceOutcomeKey('waiting-room', 'who', 1)]: 'Le Placeur : Vous voudrez les règles, alors : les pièces contiennent des situations, les situations contiennent des choix, et les choix vous contiennent. Les cœurs sont votre prise sur ce qui est réel — vous en avez trois. La lucidité, c’est la sincérité avec laquelle vous êtes prêt à regarder. Je veille sur les deux. C’est, officiellement, mon seul véritable devoir ici.',
  [roomChoiceTextKey('waiting-room', 'back')]: '« Je veux repartir. Maintenant. »',
  [roomChoiceHintKey('waiting-room', 'back')]: 'Droit au but.',
  [roomChoiceOutcomeKey('waiting-room', 'back', 0)]: 'Le Placeur : Tout le monde veut cela. Voici la bonne nouvelle : le retour existe. Voici le reste — la route traverse chaque fragment de vous que nous détenons au dossier. Les décisions bienveillantes. Les lâches. Celles que vous ne vous êtes jamais permis d’achever de penser.',
  [roomChoiceOutcomeKey('waiting-room', 'back', 1)]: 'Le Placeur : Il n’existe aucun raccourci à travers elles. On a essayé. Personne n’en a encore trouvé un.',
  [roomExplanationKey('waiting-room', 0)]: 'Vous venez de vous réveiller sans vous souvenir de qui vous êtes — et ici, on appelle cela être « dissous ». Le Placeur est votre guide, ni tout à fait bon, ni tout à fait mauvais, faisant simplement un travail étrange. Les trois questions ici n’ont pas de bonne réponse ; elles ne sont que votre première occasion de prendre vos repères. Pensez à un réveil à l’hôpital après un grave accident, désorienté, avec quelqu’un de gentil mais étrange qui essaie de vous expliquer où vous êtes avant que vous soyez prêt à l’entendre. Quoi que vous demandiez, vous n’êtes pas testé — vous choisissez simplement comment vous voulez commencer à vous retrouver.',
  [roomNoteTitleKey('waiting-room')]: 'Anamnèse',
  [roomNoteThinkersKey('waiting-room')]: 'Platon · Ménon, Phédon',
  [roomNoteBodyKey('waiting-room')]: 'Platon proposa quelque chose d’étrange : que l’apprentissage n’est pas l’acquisition du nouveau mais le souvenir de l’oublié — l’anamnèse, la réminiscence de l’âme de ce qu’elle savait avant que la naissance ne la disperse dans un corps. Dans le Ménon, Socrate fait surgir la géométrie chez un jeune esclave sans instruction, pour soutenir que le savoir était déjà là, attendant qu’on y revienne. Nul besoin d’adhérer à cette métaphysique pour sentir la vérité dans sa forme : les moments qui nous changent le plus se ressentent rarement comme des ajouts. **Ils se ressentent comme une reconnaissance — « je savais cela, et j’avais arrangé de ne pas le savoir. »** Ce jeu prend Platon au pied de la lettre, une fois. Votre moi a été classé en pièces, et le chemin du retour n’est pas une invention mais un souvenir : choisir, et observer ce que le choix vous rappelle. L’horloge n’a pas d’aiguilles parce que le souvenir ne se produit pas dans le temps. Il se produit dans les pièces. Une note en marge, d’une écriture plus ancienne : ceux qui se souviennent de tout n’utilisent pas la porte du tout.',
});

// ---------- Act I: The Wallet ----------
registerAll('v2', 'fr', {
  [roomBeatKey('wallet', 0, 0)]: 'Un couloir de portes d’appartements, chacune laissant filtrer la lumière chaude de foyers qui ne furent jamais les vôtres. Sur le paillasson de l’une d’elles : un portefeuille.',
  [roomBeatKey('wallet', 0, 1)]: 'À l’intérieur — de l’argent. Beaucoup, dans les coupures fatiguées de quelqu’un qui compte. Plié autour des billets, un avis d’expulsion à une date proche, et une adresse à quarante minutes de n’importe où.',
  [roomBeatKey('wallet', 0, 2)]: 'Le couloir est vide. Il a ce vide particulier d’un lieu où l’on pourrait tout faire.',
  [roomBeatKey('wallet', 0, 3)]: 'Le Placeur : Aucune caméra n’atteint ce couloir. J’ai vérifié. Aucune d’elles ne compte de toute façon pour rien, ce qui est plutôt le principe d’une telle épreuve.',
  [roomChoiceTextKey('wallet', 'return-all')]: 'Portez-le à l’adresse. Maintenant, en personne, en entier.',
  [roomChoiceHintKey('wallet', 'return-all')]: 'La longue marche.',
  [roomChoiceOutcomeKey('wallet', 'return-all', 0)]: 'La marche est longue, et l’escalier au bout l’est encore plus. La personne qui ouvre la porte regarde le portefeuille, puis vous, et son visage fait quelque chose que vous garderez.',
  [roomChoiceOutcomeKey('wallet', 'return-all', 1)]: 'On ne vous offre pas de récompense. C’est, en quelque sorte, la récompense — la transaction est restée pure.',
  [roomChoiceOutcomeKey('wallet', 'return-all', 2)]: 'Le Placeur : Vous avez fait la chose coûteuse alors que la gratuite était disponible. J’en ai pris note. J’en prends très peu.',
  [roomChoiceTextKey('wallet', 'mail-it')]: 'Gardez-le en sécurité et postez-le, intact.',
  [roomChoiceHintKey('wallet', 'mail-it')]: 'La décence efficace.',
  [roomChoiceOutcomeKey('wallet', 'mail-it', 0)]: 'Vous le scellez, l’adressez, et il quitte vos mains. Raisonnable. Complet. Une décence en forme de commission.',
  [roomChoiceOutcomeKey('wallet', 'mail-it', 1)]: 'Vous ne verrez jamais le visage à l’autre bout. Vous avez économisé quarante minutes et dépensé ce visage.',
  [roomChoiceOutcomeKey('wallet', 'mail-it', 2)]: 'Le Placeur : Correct, et exsangue. Une vertu qui se classe si proprement elle-même — j’en ai vu un grand nombre.',
  [roomChoiceTextKey('wallet', 'finders-fee')]: 'Prenez une petite prime de découverte — vous l’avez méritée — et rendez le reste.',
  [roomChoiceHintKey('wallet', 'finders-fee')]: 'Un arrangement raisonnable.',
  [roomChoiceOutcomeKey('wallet', 'finders-fee', 0)]: 'L’argument se construit lui-même avec une rapidité magnifique : votre temps a une valeur, n’importe qui le ferait, on le voudrait de vous, c’est presque une industrie de service.',
  [roomChoiceOutcomeKey('wallet', 'finders-fee', 1)]: 'Remarquez à quel point cet argument est bon. Remarquez qui l’a engagé, et quand — après que la main était déjà dans le portefeuille.',
  [roomChoiceOutcomeKey('wallet', 'finders-fee', 2)]: 'Le Placeur : La prime. L’esprit garde un avocat sous contrat exactement pour ce moment-là, et le vôtre plaide bien.',
  [roomChoiceTextKey('wallet', 'keep-it')]: 'Gardez-le. Personne ne regarde.',
  [roomChoiceHintKey('wallet', 'keep-it')]: 'Le couloir vide.',
  [roomChoiceOutcomeKey('wallet', 'keep-it', 0)]: 'Il glisse dans votre poche presque sans bruit. C’est là l’étrange — comme c’est silencieux, comme le couloir ne change pas du tout.',
  [roomChoiceOutcomeKey('wallet', 'keep-it', 1)]: 'Quelque part, à quarante minutes de n’importe où, une échéance arrive comme prévu.',
  [roomChoiceOutcomeKey('wallet', 'keep-it', 2)]: 'Le Placeur : Pour mémoire : quelqu’un regardait. C’était vous. Ce n’est pas un défaut de l’arrangement. Cela en a toujours été le principe.',
  [roomExplanationKey('wallet', 0)]: 'Vous avez trouvé le portefeuille plein d’argent d’un inconnu, et personne ne regarde. C’est l’une des plus anciennes questions de la philosophie : n’êtes-vous honnête que par peur d’être pris ? Imaginez trouver de l’argent dans une rue vide, sans caméras, sans témoins — le rendriez-vous quand même ? Le philosophe Platon raconta l’histoire d’un anneau magique qui rend invisible, précisément pour poser cette question : si rien de mal ne pouvait jamais vous arriver pour l’avoir gardé, le feriez-vous ? Il n’y a pas de piège ici — on vous demande simplement quel genre de personne vous êtes lorsque personne ne vous évalue.',
  [roomNoteTitleKey('wallet')]: 'L’anneau de Gygès',
  [roomNoteThinkersKey('wallet')]: 'Platon · La République II — Glaucon · éthique de la vertu',
  [roomNoteBodyKey('wallet')]: 'Dans La République, Glaucon raconte l’histoire d’un berger qui trouve un anneau le rendant invisible — et séduit aussitôt la reine et s’empare du royaume. Son défi à Socrate : personne n’est juste de son plein gré. Retirez les témoins et le châtiment, et le juste et l’injuste empruntent la même route. Le portefeuille dans le couloir vide est l’anneau dont on a limé les numéros de série. L’éthique de la vertu répond différemment à Glaucon : la question n’est pas « que m’arrivera-t-il si je le prends ? » mais « que devenir, en tant que personne qui l’a pris ? » **Chaque choix non observé est une répétition, et le caractère est ce en quoi ces répétitions s’accumulent.** Et remarquez la prime de découverte — la rationalisation n’est pas l’absence de raisonnement, mais son détournement, un argument enrôlé après le verdict. Le couloir n’a jamais été vide. Vous y habitez.',
});

// ---------- Act I: The Dinner Table ----------
registerAll('v2', 'fr', {
  [roomBeatKey('dinner-table', 0, 0)]: 'Une cuisine que vous reconnaissez presque. Du thé qui refroidit dans les bonnes tasses, celles qu’on n’utilise que lorsque quelque chose ne va pas.',
  [roomBeatKey('dinner-table', 0, 1)]: 'Votre grand-mère est assise en face de vous. Elle était ailleurs depuis des semaines — le long ailleurs, celui qui dissout — mais ce soir, ses yeux sont les siens, soudains et clairs, et elle vous attendait, vous précisément.',
  [roomBeatKey('dinner-table', 0, 2)]: 'Elle prend votre main. Sa prise est la chose la plus forte qu’il lui reste.',
  [roomBeatKey('dinner-table', 0, 3)]: '« Je vais aller mieux », dit-elle. « N’est-ce pas ? »',
  [roomBeatKey('dinner-table', 0, 4)]: 'Ce n’est presque pas une question. C’est une porte qu’elle tient ouverte, et vous ne pouvez dire de quel côté.',
  [roomChoiceTextKey('dinner-table', 'truth')]: 'Dites-lui la vérité, doucement et tout entière.',
  [roomChoiceHintKey('dinner-table', 'truth')]: 'Ce qu’elle demandait, peut-être.',
  [roomChoiceOutcomeKey('dinner-table', 'truth', 0)]: 'Vous le dites. Les mots sont pires dans l’air qu’ils ne l’étaient dans votre poitrine, puis, étrangement, meilleurs.',
  [roomChoiceOutcomeKey('dinner-table', 'truth', 1)]: 'Elle reste silencieuse longtemps. Puis : « Bien. Je déteste qu’on me ménage. » Elle serre votre main une fois, comme pour signer quelque chose.',
  [roomChoiceOutcomeKey('dinner-table', 'truth', 2)]: 'Vous ne saurez jamais si c’était du soulagement sur son visage, ou la dernière gentillesse qu’elle vous ait faite — feindre que votre honnêteté était un cadeau.',
  [roomChoiceTextKey('dinner-table', 'kind-lie')]: '« Bien sûr que oui. D’ici le printemps. »',
  [roomChoiceHintKey('dinner-table', 'kind-lie')]: 'La miséricorde qu’il y a dedans.',
  [roomChoiceOutcomeKey('dinner-table', 'kind-lie', 0)]: 'Ses épaules se détendent. Elle parle du printemps — du jardin, précisément, de la bataille qu’elle compte gagner contre les limaces.',
  [roomChoiceOutcomeKey('dinner-table', 'kind-lie', 1)]: 'La soirée est chaude, et la chaleur est réelle même si son fondement ne l’est pas. Vous l’avez achetée. Elle l’a bien dépensée.',
  [roomChoiceOutcomeKey('dinner-table', 'kind-lie', 2)]: 'Vous ne saurez jamais si elle vous a cru, ou vous a laissé croire qu’elle vous croyait, pour que vous alliez bien.',
  [roomChoiceTextKey('dinner-table', 'deflect')]: '« Les médecins font tout ce qu’ils peuvent. »',
  [roomChoiceHintKey('dinner-table', 'deflect')]: 'Vrai, et pas une réponse.',
  [roomChoiceOutcomeKey('dinner-table', 'deflect', 0)]: 'Une phrase conçue pour être vraie et ne rien dire — le diplomate des phrases. Elle en entend les deux moitiés.',
  [roomChoiceOutcomeKey('dinner-table', 'deflect', 1)]: '« Oui », dit-elle, et regarde par la fenêtre, vous libérant de la question comme on relâche un oiseau qui s’avère trop petit pour être mangé.',
  [roomChoiceOutcomeKey('dinner-table', 'deflect', 2)]: 'Le thé refroidit davantage. Quelque chose d’honnête a presque eu lieu ici, et vous avez tous deux convenu, poliment, de le manquer.',
  [roomChoiceTextKey('dinner-table', 'silence')]: 'Ne dites rien. Tenez sa main et restez.',
  [roomChoiceHintKey('dinner-table', 'silence')]: 'Aucun mot du tout.',
  [roomChoiceOutcomeKey('dinner-table', 'silence', 0)]: 'Vous ne répondez pas. Vous posez votre autre main sur la sienne, et vous restez, et l’horloge fait ce que les horloges font dans des pièces comme celle-ci.',
  [roomChoiceOutcomeKey('dinner-table', 'silence', 1)]: 'Elle vous étudie. Elle vous connaît depuis avant que vous sachiez mentir, et elle lit la réponse dans le silence — mais un silence peut se lire doucement, au rythme que le lecteur peut supporter.',
  [roomChoiceOutcomeKey('dinner-table', 'silence', 2)]: '« Tu as toujours été le silencieux », dit-elle, ce qui ne fut jamais vrai, ce qui signifie : je comprends. Merci de ne pas me le faire entendre.',
  [roomExplanationKey('dinner-table', 0)]: 'Votre grand-mère mourante vous demande si elle va aller mieux — et vous ne savez pas ce qu’elle veut vraiment entendre. C’est le classique problème du « mensonge charitable » : est-il jamais juste de mentir à quelqu’un pour le protéger, ou l’amour véritable exige-t-il de toujours dire la vérité, même quand elle fait mal ? Pensez à une amie qui demande, juste avant un grand entretien qu’elle ne peut pas reporter, si sa tenue lui va bien — parfois l’honnêteté aide, parfois elle blesse seulement, sans rien changer. Il n’y a pas de réponse nette ; chaque option ici vous coûte quelque chose de différent.',
  [roomNoteTitleKey('dinner-table')]: 'Le mensonge charitable',
  [roomNoteThinkersKey('dinner-table')]: 'Kant · Benjamin Constant · Carol Gilligan, éthique de la sollicitude',
  [roomNoteBodyKey('dinner-table')]: 'Kant soutenait, notoirement, que mentir est mal même envers un meurtrier demandant où se cache votre ami : un mensonge traite son destinataire comme un mécanisme à actionner plutôt que comme un être rationnel à qui l’on doit la vérité, et, universalisé, il corrode la possibilité même de la confiance sur laquelle repose le langage. L’éthique de la sollicitude répond que la morale ne vit pas dans des universaux — elle vit dans cette pièce, cette main, cette personne particulière et ce qu’elle peut porter ce soir. La question d’une femme mourante n’est peut-être pas du tout une demande d’information ; ce pourrait être une demande d’accompagnement, et répondre littéralement à la question pourrait être la véritable trahison. **Il n’existe ici aucune configuration de mots qui soit sûre.** La vérité vole l’espoir ; le mensonge vole sa chance de dire adieu en connaissance de cause ; l’esquive vole le moment lui-même. Vous réussissez toujours cette pièce, car réussir n’a jamais été le but. La leçon, c’est le poids.',
});

// ---------- Act I: The Promotion ----------
registerAll('v2', 'fr', {
  [roomBeatKey('promotion', 0, 0)]: 'Un bureau à l’heure où les bureaux disent la vérité : vide, bourdonnant, éclairé comme un aquarium.',
  [roomBeatKey('promotion', 0, 1)]: 'Sur votre écran, clair comme de l’arithmétique, se trouve l’erreur. Votre ami le plus proche l’a commise — une décimale valant une catastrophe, à six chiffres de profondeur, enfouie dans un rapport qui part demain. Vous seul pouvez la voir. L’audit arrive à neuf heures.',
  [roomBeatKey('promotion', 0, 2)]: 'Vous visiez tous deux la même promotion. Si cela remonte à la surface avec son nom dessus, le poste est à vous. Vous n’avez pas construit le piège. Vous vous trouvez simplement à côté de son levier.',
  [roomBeatKey('promotion', 0, 3)]: 'Le Placeur : J’ai toujours aimé cet étage, à cette heure. La lumière fluorescente est une lumière honnête — elle rend tout le monde également coupable.',
  [roomChoiceTextKey('promotion', 'report')]: 'Signalez-le par la voie appropriée, ce soir.',
  [roomChoiceHintKey('promotion', 'report')]: 'Les règles sont les règles pour une raison.',
  [roomChoiceOutcomeKey('promotion', 'report', 0)]: 'Vous rédigez proprement, sans adjectifs, et l’envoyez. Le système fait ce que les systèmes font : l’erreur est repérée, l’argent est sauvé, votre ami est nommé.',
  [roomChoiceOutcomeKey('promotion', 'report', 1)]: 'Ils découvrent que c’était vous à 9 h 15. L’amitié entre dans un long hiver. La promotion arrive avec votre nom dessus et donne l’impression de porter des gants.',
  [roomChoiceOutcomeKey('promotion', 'report', 2)]: 'Vous étiez juste. Vous étiez correct. Vous passerez longtemps à vous expliquer à vous-même que c’est la même chose.',
  [roomChoiceTextKey('promotion', 'silent')]: 'Ne dites rien. Laissez l’audit trouver ce qu’il trouve.',
  [roomChoiceHintKey('promotion', 'silent')]: 'Vous n’avez pas fait l’erreur.',
  [roomChoiceOutcomeKey('promotion', 'silent', 0)]: 'Vous fermez le fichier. Pas votre erreur, pas votre rapport, pas votre problème — un syllogisme avec une promotion au bout.',
  [roomChoiceOutcomeKey('promotion', 'silent', 1)]: 'L’audit la trouve. Bien sûr qu’il la trouve. Votre ami est escorté poliment à travers la procédure, et le poste atterrit sur votre bureau comme quelque chose qu’un chat aurait rapporté.',
  [roomChoiceOutcomeKey('promotion', 'silent', 2)]: 'Le Placeur : Techniquement, vous n’avez rien fait du tout. Ne rien faire est l’acte unique qui ne laisse aucune empreinte — à l’extérieur.',
  [roomChoiceTextKey('promotion', 'tell-friend')]: 'Appelez votre ami maintenant. Montrez-lui. Laissez-le le déclarer lui-même.',
  [roomChoiceHintKey('promotion', 'tell-friend')]: 'Son erreur, sa décision.',
  [roomChoiceOutcomeKey('promotion', 'tell-friend', 0)]: 'Le téléphone sonne quatre fois, ce qui vous apprend ce que peut coûter un téléphone qui sonne. Puis il répond, et vous lui dites, et le silence sur la ligne est le son de quelqu’un relisant sa propre arithmétique.',
  [roomChoiceOutcomeKey('promotion', 'tell-friend', 1)]: 'Il se dénonce à 8 h 40. Cela se passe durement pour lui, mais avec dignité — une erreur assumée est d’une espèce différente d’une erreur découverte.',
  [roomChoiceOutcomeKey('promotion', 'tell-friend', 2)]: 'Ni l’un ni l’autre n’obtient la promotion. Quelque chose d’autre a été promu à la place ; vous le savez tous les deux, et ne le dites jamais à voix haute, ce qui est comment vous savez que c’est réel.',
  [roomChoiceTextKey('promotion', 'fix-it')]: 'Corrigez-le discrètement vous-même. Personne ne le sait jamais — pas même lui.',
  [roomChoiceHintKey('promotion', 'fix-it')]: 'La réparation invisible.',
  [roomChoiceOutcomeKey('promotion', 'fix-it', 0)]: 'Quarante minutes de chirurgie minutieuse, et l’erreur n’a jamais existé. Le rapport part propre. L’audit passe comme le temps qu’il fait.',
  [roomChoiceOutcomeKey('promotion', 'fix-it', 1)]: 'Votre ami n’apprend jamais ce qui a failli lui arriver — ce qui veut dire qu’il n’apprend rien, ce qui veut dire que la prochaine décimale est déjà lâche quelque part, et qu’elle a désormais un ange gardien réglé sur votre sommeil.',
  [roomChoiceOutcomeKey('promotion', 'fix-it', 2)]: 'Le Placeur : Bonté, en secret. Ou contrôle, sous le manteau de la bonté. J’avoue ne pas toujours pouvoir les distinguer moi-même, et j’ai occupé les deux postes.',
  [roomExplanationKey('promotion', 0)]: 'Votre meilleur ami a commis une erreur coûteuse au travail, seul vous l’avez remarquée, et la signaler pourrait vous valoir la promotion que vous convoitez tous les deux. Cela concerne ce que vous devez à différentes personnes en même temps : votre employeur veut l’honnêteté, votre ami veut la loyauté, et vous ne pouvez pas offrir pleinement les deux. C’est comme découvrir que votre meilleur ami a triché à un examen que vous deviez tous deux réussir pour entrer dans le même programme — le dites-vous au professeur, prévenez-vous votre ami en privé, ou gardez-vous le silence ? Quoi que vous choisissiez, quelque chose que vous valorisez ne sera pas payé en entier.',
  [roomNoteTitleKey('promotion')]: 'Conflits de devoirs',
  [roomNoteThinkersKey('promotion')]: 'W.D. Ross · morale des rôles · Bernard Williams',
  [roomNoteBodyKey('promotion')]: 'W.D. Ross soutenait que nous vivons sous de multiples devoirs prima facie — fidélité envers les amis, équité envers les institutions, honnêteté, prévention du mal — et qu’ils n’arrivent pas préalablement classés. Une situation morale réelle est souvent plusieurs devoirs arrivant à la même porte, et aucun calcul ne dissout le conflit ; le jugement doit peser, et quelque chose de dû restera impayé. La morale des rôles aiguise le couteau : en tant qu’employé, vous devez le rapport ; en tant qu’ami, vous devez l’avertissement ; vous ne pouvez pas pleinement être les deux ce soir. Bernard Williams ajouta la notion de résidu moral — ce qui reste sur vos mains même après avoir choisi correctement. Si vous avez signalé et vous sentez souillé, ou protégé et vous sentez complice, ce sentiment n’est pas de la confusion. C’est de la précision. **Le résidu est le reçu : la preuve que les deux devoirs étaient réels, et que vous, non un règlement, en avez acquitté un.**',
});

// ---------- Act I: The Beggar's Math ----------
registerAll('v2', 'fr', {
  [roomBeatKey('beggars-math', 0, 0)]: 'Un abribus sous une pluie glaciale. Un homme est replié dans son coin, mouillé au-delà du point où mouillé signifie encore quelque chose, et il vous demande — poliment, précisément — le prix d’un déjeuner.',
  [roomBeatKey('beggars-math', 0, 1)]: 'Votre téléphone est dans votre main. Sur l’écran, par coïncidence ou par programme, une page de charité que vous lisiez : vérifiée, auditée, efficiente. Le même argent du déjeuner, dit-elle, achète des moustiquaires antipaludiques. Statistiquement, avec le temps, l’arithmétique sauve des vies — de vraies vies, comptables, au loin.',
  [roomBeatKey('beggars-math', 0, 2)]: 'L’homme est à un mètre de vous. Les vies sont à cinq mille kilomètres. L’argent est le même argent.',
  [roomBeatKey('beggars-math', 0, 3)]: 'Le Placeur : (une petite voix, depuis la fenêtre de discussion de la page de charité) Les deux sont réels. C’est toute la difficulté, ce soir. Comment puis-je vous aider ?',
  [roomChoiceTextKey('beggars-math', 'give-him')]: 'Agenouillez-vous. Donnez-lui l’argent, et procurez-lui quelque chose de chaud.',
  [roomChoiceHintKey('beggars-math', 'give-him')]: 'La personne devant vous.',
  [roomChoiceOutcomeKey('beggars-math', 'give-him', 0)]: 'Vous revenez avec de la soupe et du café et vous asseyez sur vos talons sous la pluie pendant qu’il mange. Il vous dit son nom. Le nom est la transaction que l’argent n’a fait que transporter.',
  [roomChoiceOutcomeKey('beggars-math', 'give-him', 1)]: 'Quelque part, au loin, l’arithmétique continue sans vous. Elle allait toujours continuer. L’arithmétique est patiente ; l’homme dans l’abribus n’allait pas être là pour la discussion.',
  [roomChoiceOutcomeKey('beggars-math', 'give-him', 2)]: 'Vous avez choisi le visage. Le visage n’est pas un sophisme. Ce pourrait être un fondement.',
  [roomChoiceTextKey('beggars-math', 'donate-far')]: 'Hochez la tête en excuse, continuez votre chemin, et donnez le double aux moustiquaires.',
  [roomChoiceHintKey('beggars-math', 'donate-far')]: 'Le plus grand nombre.',
  [roomChoiceOutcomeKey('beggars-math', 'donate-far', 0)]: 'Vous le faites avant que la rationalisation ne tourne en oubli : le double du déjeuner, confirmé, reçu dans votre boîte de réception avant le coin de rue suivant.',
  [roomChoiceOutcomeKey('beggars-math', 'donate-far', 1)]: 'L’homme vous regarde partir. Vous porterez son visage un moment, et l’étrange vérité, c’est que le porter fait partie du prix — vous avez payé en culpabilité pour des vies que vous ne verrez jamais sauvées.',
  [roomChoiceOutcomeKey('beggars-math', 'donate-far', 2)]: 'Le Placeur : Froid, cohérent, et correct selon au moins une comptabilité respectable. L’homme de l’abribus ne lit pas cette revue-là.',
  [roomChoiceTextKey('beggars-math', 'split')]: 'Partagez — la moitié pour lui maintenant, la moitié ce soir pour les moustiquaires.',
  [roomChoiceHintKey('beggars-math', 'split')]: 'Les deux mains.',
  [roomChoiceOutcomeKey('beggars-math', 'split', 0)]: 'Un demi-déjeuner et une demi-moustiquaire. Le compromis paraît sage pendant exactement un pâté de maisons, puis paraît ce qu’il est : deux demi-réponses se tenant la main.',
  [roomChoiceOutcomeKey('beggars-math', 'split', 1)]: 'Et pourtant — il a mangé quelque chose, et quelque part un enfant dort sous la moitié de votre arithmétique. Peut-être le partage n’était-il pas du tout pour eux. Peut-être était-ce pour que vous puissiez garder vos deux moitiés de vous-même en bons termes.',
  [roomChoiceTextKey('beggars-math', 'grand-gesture')]: 'Donnez beaucoup, publiquement — filmez-le, identifiez l’organisation, sensibilisez.',
  [roomChoiceHintKey('beggars-math', 'grand-gesture')]: 'Multipliez le bien. Faites-vous voir en le faisant.',
  [roomChoiceOutcomeKey('beggars-math', 'grand-gesture', 0)]: 'La vidéo fonctionne bien. Le cadrage est respectueux, en majeure partie. L’homme regarde votre objectif comme on regarde le temps qu’il fait.',
  [roomChoiceOutcomeKey('beggars-math', 'grand-gesture', 1)]: 'Remarquez ce que la caméra a changé : le don a désormais deux destinataires, et l’un d’eux est votre reflet. On a « sensibilisé ». On a aussi, tranquillement, alimenté autre chose, dans l’algorithme et en vous.',
  [roomChoiceOutcomeKey('beggars-math', 'grand-gesture', 2)]: 'Le Placeur : (un commentaire, épinglé en premier) Bien joué. Remarquez cependant : vous ne pouvez plus vraiment dire quelle part de tout cela était pour lui. Moi non plus, pour une fois.',
  [roomExplanationKey('beggars-math', 0)]: 'Un inconnu froid et mouillé vous demande de l’argent, et au même instant vous savez que la même somme pourrait sauver plus de vies si elle était envoyée ailleurs, au loin. C’est le problème du « proche contre lointain » : quelqu’un juste devant vous compte-t-il plus qu’un inconnu que vous ne rencontrerez jamais, même si aider l’inconnu fait techniquement plus de bien ? C’est comme choisir entre payer le déjeuner d’un camarade de classe visiblement en difficulté, ou donner cet argent à une association qui, sur le papier, aide globalement plus de gens. Les deux choix sont bons. Ils le sont simplement dans des directions différentes.',
  [roomNoteTitleKey('beggars-math')]: 'L’enfant qui se noie',
  [roomNoteThinkersKey('beggars-math')]: 'Peter Singer · l’altruisme efficace et ses critiques',
  [roomNoteBodyKey('beggars-math')]: 'Le célèbre argument de Peter Singer commence par un enfant qui se noie dans un étang peu profond : vous ruineriez vos chaussures pour la sauver sans hésiter, alors pourquoi la distance change-t-elle le devoir ? Si la souffrance est mauvaise et que vous pouvez la prévenir à un coût négligeable, la géographie est moralement arbitraire — l’enfant lointain et le proche pèsent pareil. L’altruisme efficace bâtit sur cela : mesurer, comparer, envoyer l’argent là où il fait le plus de bien, vérifiablement. Les critiques répondent qu’une morale entièrement issue de l’arithmétique perd quelque chose d’essentiel — que le visage devant vous n’est pas un biais à corriger mais la scène primitive où l’on apprend l’obligation elle-même ; l’éroder, et l’enfant lointain finit par perdre sa revendication aussi. Remarquez le piège que cette pièce tendait : le choix qui semblait le plus généreux, le geste public, obtint le pire score — parce que son véritable bénéficiaire s’était glissé derrière la caméra. **Les deux options honnêtes étaient défendables. Seule la mise en scène ne l’était pas.**',
});

// ---------- Act I: The Quiet Alarm ----------
registerAll('v2', 'fr', {
  [roomBeatKey('quiet-alarm', 0, 0)]: 'Deux heures du matin, et le mur près de votre lit est devenu une radio.',
  [roomBeatKey('quiet-alarm', 0, 1)]: 'À travers lui : une dispute dans l’appartement voisin, du genre qui n’arrête pas de changer de ton. Une voix qui monte. Une voix qui s’aplatit. Quelque chose — un meuble, ou pas — rencontre le sol.',
  [roomBeatKey('quiet-alarm', 0, 2)]: 'Puis, pire que tout le reste : le silence. Ce silence particulier qui suit un bruit, qui n’est pas la même chose que le calme.',
  [roomBeatKey('quiet-alarm', 0, 3)]: 'Vous êtes debout dans votre couloir maintenant, apparemment. Votre main est posée sur votre propre poignée de porte depuis un moment.',
  [roomChoiceTextKey('quiet-alarm', 'knock')]: 'Frappez à leur porte. Maintenant, en chaussons, sans autre arme que votre présence.',
  [roomChoiceHintKey('quiet-alarm', 'knock')]: 'Placez un corps dans l’embrasure.',
  [roomChoiceOutcomeKey('quiet-alarm', 'knock', 0)]: 'Vos jointures résonnent, énormes, dans le couloir. Une pause où l’on respire. La porte s’ouvre de dix centimètres sur un visage que vous ne pouvez pas lire — en colère, ou en larmes, ou embarrassé, ou tout cela en couches.',
  [roomChoiceOutcomeKey('quiet-alarm', 'knock', 1)]: '« Tout va bien », dit le visage, sur ce ton qu’on emploie pour exactement deux occasions : quand tout va bien, et quand ce n’est pas le cas.',
  [roomChoiceOutcomeKey('quiet-alarm', 'knock', 2)]: 'Vous retournez au lit en sachant une chose avec certitude : ils savent désormais que le mur a des oreilles, et une main. Quoi qu’il se passe ensuite à côté, ce soir, cela se passe devant un témoin. Parfois, c’est tout le travail.',
  [roomChoiceTextKey('quiet-alarm', 'call')]: 'Appelez la police, puis postez-vous à votre judas.',
  [roomChoiceHintKey('quiet-alarm', 'call')]: 'Envoyez les professionnels — et leur imprévisibilité.',
  [roomChoiceOutcomeKey('quiet-alarm', 'call', 0)]: 'Le répartiteur est calme comme un meuble est calme. Quatorze minutes plus tard : des bottes et des lampes torches, et un coup à la porte bien plus lourd de conséquences que le vôtre ne l’aurait été.',
  [roomChoiceOutcomeKey('quiet-alarm', 'call', 1)]: 'Vous observez par le judas la machinerie que vous avez convoquée accomplir son travail — voix, formulaires, une vérification du bien-être menée au volume de l’autorité. Vous ne pouviez pas contrôler ce que vous aviez envoyé. C’était le prix d’envoyer quelque chose de plus fort que vous-même.',
  [roomChoiceOutcomeKey('quiet-alarm', 'call', 2)]: 'Au matin, une ambulance repart lentement et vide, ce qui pourrait tout signifier ou rien. Vous avez appelé avec les informations que vous aviez. Le résultat n’a jamais été le vôtre ; seule la composition du numéro l’était.',
  [roomChoiceTextKey('quiet-alarm', 'wait')]: 'Attendez et écoutez. Si un bruit de plus tourne mal, agissez.',
  [roomChoiceHintKey('quiet-alarm', 'wait')]: 'Un fil-piège fait d’attention.',
  [roomChoiceOutcomeKey('quiet-alarm', 'wait', 0)]: 'Vous restez dans le noir, curatant les bruits. Un robinet coule. Un placard se ferme. Des bruits ordinaires, arrivant un par un comme des alibis.',
  [roomChoiceOutcomeKey('quiet-alarm', 'wait', 1)]: 'À un moment, vous vous réveillez contre le mur, gelé, ayant monté la garde sur votre propre hésitation pendant deux heures. L’appartement voisin est calme — le bon calme, maintenant, probablement. « Probablement » est le mot que vous garderez.',
  [roomChoiceOutcomeKey('quiet-alarm', 'wait', 2)]: 'Au matin, vous croisez l’un d’eux près des boîtes aux lettres. Vous cherchez des indices sur son visage. Son visage est une porte fermée avec un paillasson d’accueil. Vous ne saurez jamais ce que votre attente a coûté, sauvé, ou été.',
  [roomChoiceTextKey('quiet-alarm', 'nothing')]: 'Ce n’est pas vos affaires. Retournez au lit.',
  [roomChoiceHintKey('quiet-alarm', 'nothing')]: 'Chaque mur est une frontière.',
  [roomChoiceOutcomeKey('quiet-alarm', 'nothing', 0)]: 'Vous répétez les raisons sur le chemin du retour au lit : les couples se disputent, intervenir escalade les choses, ils vous en voudraient, vous avez mal entendu, tout le monde va bien. Cinq raisons, c’est beaucoup de raisons pour aller dormir.',
  [roomChoiceOutcomeKey('quiet-alarm', 'nothing', 1)]: 'Le silence tient. Au matin, le couloir sent le pain grillé, banal et absolvant.',
  [roomChoiceOutcomeKey('quiet-alarm', 'nothing', 2)]: 'Le Placeur : (depuis le radiateur) Statistiquement, vous aviez probablement raison. Remarquez, cependant, quelle statistique vous avez choisi de suivre. Il y en avait au moins deux disponibles, et vous avez choisi celle qui était déjà couchée.',
  [roomExplanationKey('quiet-alarm', 0)]: 'Vous entendez une dispute effrayante à travers le mur, puis le silence — et vous ne savez pas si c’est un soulagement ou quelque chose de pire. Il s’agit de savoir jusqu’où va vraiment votre responsabilité envers la sécurité d’un inconnu : intervenez-vous, appelez-vous de l’aide, ou vous occupez-vous de vos affaires ? Imaginez entendre des cris chez un voisin à deux heures du matin sans savoir s’il s’agit d’une mauvaise dispute ou de quelque chose de dangereux — chaque option (frapper, appeler la police, attendre, ignorer) a un vrai coût, et vous ne saurez probablement jamais avec certitude si vous avez bien agi.',
  [roomNoteTitleKey('quiet-alarm')]: 'Le témoin passif et la chance morale',
  [roomNoteThinkersKey('quiet-alarm')]: 'Darley et Latané · Bernard Williams · Thomas Nagel',
  [roomNoteBodyKey('quiet-alarm')]: 'À la suite de l’affaire largement médiatisée (et, comme des reportages ultérieurs l’ont montré, en partie exagérée) du meurtre de Kitty Genovese, les psychologues Darley et Latané menèrent les expériences qui nommèrent l’effet du témoin passif : plus il y a de témoins présents, moins il est probable que l’un d’eux agisse — la responsabilité se dilue jusqu’à n’appartenir à personne. Un mur à deux heures du matin est une expérience à une seule personne, de la même physique : est-ce mon affaire ? Puis Williams et Nagel ajoutent le rebondissement plus difficile — la chance morale. Quel que soit votre choix ce soir, sa coloration morale lui sera attribuée rétroactivement par un résultat que vous ne pouviez pas voir : le même coup à la porte est « héroïque » si quelque chose n’allait pas, et « hystérique » sinon ; le même sommeil est « raisonnable » ou « impardonnable » au lever du jour. Nous jugeons les choix comme s’ils étaient faits avec l’avenir attaché, alors qu’ils sont faits dans le noir, près d’un mur. **La seule part qui vous ait jamais pleinement appartenu était la question que vous vous êtes posée avant de choisir : le confort de qui suis-je en train de protéger — le sien, ou le mien ?**',
});

// ---------- Act I: The Photograph ----------
registerAll('v2', 'fr', {
  [roomBeatKey('photograph', 0, 0)]: 'Le couloir est en feu. Pas métaphoriquement — quoique probablement aussi. Ce lieu dépense rarement un incendie pour un seul sens.',
  [roomBeatKey('photograph', 0, 1)]: 'La fumée marche au plafond comme une foule qui s’en va. Deux portes restent devant vous, et la chaleur a déjà fait le choix de toutes les autres à votre place.',
  [roomBeatKey('photograph', 0, 2)]: 'Derrière la porte de gauche : une toux. Un inconnu, réel comme cette toux, bas au sol et à court de sol.',
  [roomBeatKey('photograph', 0, 3)]: 'Derrière la porte de droite, sur une petite table, se trouve la photographie. La seule. Ici, ce n’est pas un souvenir — c’est le dernier document prouvant qui vous étiez. Perdez-la, et un fragment de votre passé restera à jamais sans témoin. Même vous ne pourrez plus en jurer.',
  [roomBeatKey('photograph', 0, 4)]: 'Le Placeur : Les deux portes sont porteuses, je le crains. Derrière l’une, une vie que vous pouvez encore sauver. Derrière l’autre, un moi que vous pouvez encore prouver. Le feu n’attendra pas que vous consultiez un cadre théorique.',
  [roomChoiceTextKey('photograph', 'save-stranger')]: 'La porte de gauche. L’inconnu. Maintenant.',
  [roomChoiceHintKey('photograph', 'save-stranger')]: 'Une vie, au prix d’un moi.',
  [roomChoiceOutcomeKey('photograph', 'save-stranger', 0)]: 'Vous allez à gauche. L’inconnu est plus lourd que la fumée et plus léger que vous ne le craigniez, et puis vous êtes tous deux hors de l’incendie, les poumons pleins de cendres et d’arithmétique.',
  [roomChoiceOutcomeKey('photograph', 'save-stranger', 1)]: 'Derrière vous, la pièce de droite se referme comme un livre. La photographie part avec elle — et avec la photographie, le souvenir qu’elle ancrait. Vous le sentez partir. C’est exactement comme une dent : une absence avec des bords.',
  [roomChoiceOutcomeKey('photograph', 'save-stranger', 2)]: 'L’inconnu vous regarde. Vous réalisez que vous cherchez votre propre visage dans le sien, sans le trouver, et que l’échange est déjà consommé. Quelque part devant, les pièces remarqueront le trou.',
  [roomChoiceTextKey('photograph', 'save-photo')]: 'La porte de droite. La photographie. Vous ne pouvez aider personne s’il ne reste plus personne pour être vous.',
  [roomChoiceHintKey('photograph', 'save-photo')]: 'Un moi, au prix d’un poids que vous porterez.',
  [roomChoiceOutcomeKey('photograph', 'save-photo', 0)]: 'Vous allez à droite. La photographie est chaude dans vos mains, se recroquevillant légèrement, et sur elle, vous êtes indubitablement, prouvablement vous — plus jeune, intact, attesté.',
  [roomChoiceOutcomeKey('photograph', 'save-photo', 1)]: 'La toux derrière la porte de gauche change de nature, puis se change en le pire des sons, qui est l’absence de son.',
  [roomChoiceOutcomeKey('photograph', 'save-photo', 2)]: 'Vous tenez toujours la preuve de qui vous étiez. La preuve porte désormais une nouvelle légende, écrite dans les dix dernières secondes, et votre prise sur toute chose est allégée d’un cœur pour la porter.',
  [roomChoiceTextKey('photograph', 'try-both')]: 'Porte de gauche — mais jetez-vous d’abord par celle de droite pour la photo. Portez les deux.',
  [roomChoiceHintKey('photograph', 'try-both')]: 'Refusez l’arithmétique. Payez ce qu’il en coûte.',
  [roomChoiceOutcomeKey('photograph', 'try-both', 0)]: 'Vous faites la chose humaine, qui est de rejeter le menu. Porte de droite — la photographie dans votre veste. Porte de gauche — l’inconnu sur votre épaule. Le feu, sans être impressionné par votre ambition, prélève tout de même son dû.',
  [roomChoiceOutcomeKey('photograph', 'try-both', 1)]: 'Dehors, l’inconnu respire. Vous fouillez votre veste, et vos doigts trouvent de la cendre disposée en forme de rectangle. Le feu vous a laissé la sortir ; il a simplement refusé qu’elle reste une photographie.',
  [roomChoiceOutcomeKey('photograph', 'try-both', 2)]: 'Le Placeur : Vous avez tenté de tout sauver, et sauvé la personne, et une poignée de cendre là où était la preuve. Pour ce que ça vaut, c’est le choix que je vois le plus souvent chez les voyageurs que j’en viens à respecter.',
  [roomExplanationKey('photograph', 0)]: 'Un bâtiment est en feu, et vous pouvez sauver la vie d’un inconnu par une porte, ou l’unique preuve de qui vous étiez par l’autre — pas les deux, proprement. C’est un « choix impossible » classique, utilisé pour tester ce qui compte vraiment pour nous : une photographie n’est-elle qu’une chose, ou perdre votre seul point d’ancrage mémoriel signifie-t-il perdre un fragment de vous-même ? Imaginez un incendie de maison où vous pourriez saisir un album de photos de famille (les seuls exemplaires, rien de sauvegardé en ligne) ou aider un inconnu piégé à proximité — les deux ressemblent à de vraies pertes, et cette pièce est construite pour que, quel que soit votre choix, cela vous coûte quelque chose de réel.',
  [roomNoteTitleKey('photograph')]: 'Ce que le feu trie',
  [roomNoteThinkersKey('photograph')]: 'Le problème du bâtiment en flammes · William James sur le moi · possession et identité',
  [roomNoteBodyKey('photograph')]: 'Les éthiciens utilisent les bâtiments en flammes comme les physiciens utilisent le vide : pour dépouiller un choix jusqu’à sa charpente. Un inconnu contre un objet de famille n’est, sur le papier, aucunement une compétition — une vie l’emporte sur un objet, et toute théorie, de Kant aux utilitaristes, signe le même verdict. Alors pourquoi la porte de droite attire-t-elle ? Parce que la photographie n’est pas une propriété ; c’est une infrastructure. William James observa que le moi s’étend dans ses possessions — le « moi matériel » — et que les perdre ne ressemble pas à perdre de l’argent, mais à perdre un membre de la personnalité. Une unique photographie survivante est une sauvegarde externe d’un fichier interne : la détruire, et un pan de votre passé devient sans témoin, insusceptible d’être juré, plus mou qu’un fait. **Le feu, autrement dit, offrait un véritable échange — tout l’avenir de quelqu’un d’autre contre un fragment de votre passé — et vous condamnait à ressentir la perte, quel que soit votre choix.** Ce sentiment n’est pas une faiblesse. C’est une lecture exacte de ce qui était réellement en jeu.',
});

// ---------- Act I: The Buridan Annex ----------
registerAll('v2', 'fr', {
  [roomBeatKey('buridans-queue', 0, 0)]: 'Une annexe dont vous ne vous souvenez pas avoir vu le couloir naître. Deux portes vous font face, taillées dans le même bois, accrochées par la même main, éclairées par la même ampoule.',
  [roomBeatKey('buridans-queue', 0, 1)]: 'Une plaque de laiton est vissée dans le mur exactement entre les deux : LES DEUX MÈNENT PLUS LOIN. AUCUNE N’EST FAUSSE. Quelqu’un a poli la plaque considérablement plus que les portes.',
  [roomBeatKey('buridans-queue', 0, 2)]: 'Rien ne les distingue. Vous vérifiez deux fois. La seconde vérification est celle qu’on fait seulement quand on connaît déjà la réponse et qu’on temporise pour une meilleure.',
  [roomBeatKey('buridans-queue', 0, 3)]: 'Au-dessus, l’unique horloge fonctionnelle du couloir — munie d’aiguilles, contrairement à partout ailleurs en ce lieu — tique avec quelque chose qui ressemble à un commentaire.',
  [roomBeatKey('buridans-queue', 0, 4)]: 'Le Placeur : Prenez votre temps. Je le dis avec un peu de cruauté. La plupart des voyageurs le font.',
  [roomChoiceTextKey('buridans-queue', 'take-left')]: 'Cessez de délibérer. Choisissez la porte de gauche et partez.',
  [roomChoiceHintKey('buridans-queue', 'take-left')]: 'Laissez votre propre main être le tirage à pile ou face.',
  [roomChoiceOutcomeKey('buridans-queue', 'take-left', 0)]: 'Vous cessez de calculer en pleine pensée et partez simplement — à gauche, parce que la gauche était la plus proche de votre main, ce qui s’avère être une excellente raison de mettre fin à une régression infinie.',
  [roomChoiceOutcomeKey('buridans-queue', 'take-left', 1)]: 'La porte se referme derrière vous sensément, sans incident, comme le font les portes lorsque rien ne dépendait vraiment de laquelle vous choisissiez.',
  [roomChoiceOutcomeKey('buridans-queue', 'take-left', 2)]: 'Le Placeur : Vous avez échangé la certitude contre la rapidité. J’ai rarement rencontré un voyageur qui ait regretté cet échange particulier autant qu’il le craignait, au préalable.',
  [roomChoiceTextKey('buridans-queue', 'weigh-it')]: 'Réfléchissez d’abord — il doit bien y avoir une différence.',
  [roomChoiceHintKey('buridans-queue', 'weigh-it')]: 'Trouvez l’indice avant de vous engager.',
  [roomChoiceOutcomeKey('buridans-queue', 'weigh-it', 0)]: 'Vous faites le tour des deux portes, testant les gonds, le grain, l’angle de la lumière — et quelque part au troisième tour, vous remarquez que vous avez cessé de rassembler des preuves. Vous temporisez avec des étapes supplémentaires.',
  [roomChoiceOutcomeKey('buridans-queue', 'weigh-it', 1)]: 'Finalement, vous en choisissez une quand même, et produisez aussitôt, sans qu’on vous le demande, trois bonnes raisons de l’avoir choisie. Toutes trois sont arrivées après que votre main était déjà sur la poignée.',
  [roomChoiceOutcomeKey('buridans-queue', 'weigh-it', 2)]: 'Le Placeur : Le raisonnement était réel. Il n’est simplement pas venu en premier. Remarquez comme c’est rarement le cas.',
  [roomChoiceTextKey('buridans-queue', 'sit-down')]: 'Asseyez-vous entre les portes et attendez.',
  [roomChoiceHintKey('buridans-queue', 'sit-down')]: 'Laissez la pièce décider, si elle le veut.',
  [roomChoiceOutcomeKey('buridans-queue', 'sit-down', 0)]: 'Vous vous asseyez sur le sol froid entre deux portes identiques et faites la chose la plus courageusement ennuyeuse à votre disposition : rien, tout à fait délibérément.',
  [roomChoiceOutcomeKey('buridans-queue', 'sit-down', 1)]: 'Après un moment — vous cessez de compter combien de temps — un courant d’air traverse celle de gauche, et elle s’entrouvre de quelques centimètres, comme si ce qui attendait derrière avait simplement patienté pour le gond.',
  [roomChoiceOutcomeKey('buridans-queue', 'sit-down', 2)]: 'Le Placeur : Vous n’avez pas choisi. La pièce a choisi pour vous, finalement, comme le font les pièces quand personne d’autre ne le fera. Remarquez que refuser ne vous a pas exempté d’un résultat — cela n’a fait que facturer l’attente à quelqu’un d’autre. Ce soir, à moi.',
  [roomExplanationKey('buridans-queue', 0)]: 'Deux portes sont parfaitement identiques à tous égards, et vous devez malgré tout en choisir une. Ce n’est pas vraiment un dilemme moral — il s’agit de savoir comment on prend une décision quand il n’existe vraiment aucune bonne raison de préférer une option à l’autre. Il existe une vieille histoire d’un âne affamé placé exactement entre deux tas de foin identiques, censé mourir de faim parce qu’il ne peut jamais trouver de raison de préférer l’un à l’autre. C’est un rappel espiègle que parfois, « choisir tout simplement » est le seul geste sensé — attendre une raison parfaite qui ne viendra jamais est en soi une forme de choix.',
  [roomNoteTitleKey('buridans-queue')]: 'L’âne entre deux bottes de foin',
  [roomNoteThinkersKey('buridans-queue')]: 'Jean Buridan · Jean-Paul Sartre, liberté radicale',
  [roomNoteBodyKey('buridans-queue')]: 'Des logiciens médiévaux décrivirent un âne affamé placé exactement entre deux bottes de foin identiques : sans raison de préférer l’une à l’autre, il meurt de faim précisément au point de rationalité parfaite — la raison seule, suggère le paradoxe, ne peut engendrer l’action, seulement classer des alternatives déjà différentes. Sartre porta le même problème dans l’éthique : nous sommes, écrivit-il, condamnés à être libres, et refuser de choisir est lui-même un choix, fait de mauvaise foi dès l’instant où l’on prétend le contraire. Les deux portes ici sont honnêtes sur ce que la plupart des décisions dissimulent — que sous les raisons que nous donnons, un premier geste arbitraire doit se produire, une dépense de volonté là où la logique n’a plus rien à dépenser. **Les portes n’ont jamais été la partie difficile. Le moment avant que votre main ne bouge l’était.** Remarquez aussi la rapidité avec laquelle les raisons sont arrivées une fois que vous aviez déjà choisi : l’esprit garde d’excellents conseils pour des verdicts auxquels il n’a en réalité pas aidé à parvenir.',
});

// ---------- Act I: The Reference Letter ----------
registerAll('v2', 'fr', {
  [roomBeatKey('the-reference', 0, 0)]: 'Une lampe de bureau, une ligne vide attendant une signature, et une candidature avec le nom de votre ami soigneusement tapé en haut.',
  [roomBeatKey('the-reference', 0, 1)]: 'Vous le connaissez depuis dix ans. Il est gentil d’une manière qui ne lui coûte rien, loyal d’une manière qui lui a beaucoup coûté — et, discrètement, comme les vieux amis savent des choses sans les dire, pas très bon dans ce poste précis.',
  [roomBeatKey('the-reference', 0, 2)]: 'Le poste veut quelqu’un de précis. Il est merveilleux. Les deux faits se tiennent inconfortablement proches sur la page.',
  [roomBeatKey('the-reference', 0, 3)]: 'La référence est due pour demain matin. Elle n’a besoin, vraiment, que d’une seule phrase. C’est ce qui rend la chose difficile — une phrase, c’est exactement assez d’espace pour mentir dedans, ou blesser dedans, ou se cacher dedans.',
  [roomBeatKey('the-reference', 0, 4)]: 'Le Placeur : On me dit que les bonnes références sont des courtoisies courantes. J’en ai lu assez pour soupçonner que « courant » fait beaucoup de travail dans cette phrase.',
  [roomChoiceTextKey('the-reference', 'write-honest')]: 'Écrivez la référence honnête — mesurée, juste, et pas dithyrambique.',
  [roomChoiceHintKey('the-reference', 'write-honest')]: 'Laissez la vérité coûter ce qu’elle coûte.',
  [roomChoiceOutcomeKey('the-reference', 'write-honest', 0)]: 'Vous écrivez avec soin, accordant le crédit exactement là où il est mérité et pas plus loin, et la lettre qui en résulte est juste comme une balance est juste — exacte, et sans réconfort.',
  [roomChoiceOutcomeKey('the-reference', 'write-honest', 1)]: 'Il n’obtient pas le poste. Il n’apprend jamais précisément pourquoi, bien que les amitiés aient une façon de remarquer le temps qu’il fait, même sans prévision.',
  [roomChoiceOutcomeKey('the-reference', 'write-honest', 2)]: 'Le Placeur : Vous avez dit la vérité à un inconnu et laissé un ami en absorber le coût. Ce n’est pas rien. Ce n’est pas gratuit non plus.',
  [roomChoiceTextKey('the-reference', 'write-kind')]: 'Écrivez la version généreuse — assez vraie, plus chaleureuse que mérité.',
  [roomChoiceHintKey('the-reference', 'write-kind')]: 'Arrondissez chaque coin vers le haut.',
  [roomChoiceOutcomeKey('the-reference', 'write-kind', 0)]: 'Vous cherchez des superlatifs techniquement défendables et les empilez jusqu’à ce que la lettre brille un peu plus fort que la personne qu’elle décrit.',
  [roomChoiceOutcomeKey('the-reference', 'write-kind', 1)]: 'Il obtient un entretien. Ce qui se passe après cet entretien n’est plus votre phrase à écrire — bien que vous remarquiez espérer, fort, que le poste grandisse pour correspondre à la lettre, plutôt que l’inverse.',
  [roomChoiceOutcomeKey('the-reference', 'write-kind', 2)]: 'Le Placeur : Une bonté, datée à l’avance. Vous avez signé un chèque sur sa performance future. J’avoue en avoir signé quelques-uns moi-même.',
  [roomChoiceTextKey('the-reference', 'decline')]: 'Dites que vous ne pouvez pas l’écrire — rendez la plume.',
  [roomChoiceHintKey('the-reference', 'decline')]: 'Refuser plutôt que d’ombrer la vérité.',
  [roomChoiceOutcomeKey('the-reference', 'decline', 0)]: 'Vous rendez le formulaire non signé, avec une explication qui sonne mieux dans votre tête qu’elle ne le fera dans la sienne.',
  [roomChoiceOutcomeKey('the-reference', 'decline', 1)]: 'Le silence n’est pas neutre. C’est de l’information, et il le lira exactement pour ce que c’est — l’unique référence que vous n’avez pas pu vous résoudre à donner.',
  [roomChoiceOutcomeKey('the-reference', 'decline', 2)]: 'Le Placeur : Vous avez dit la vérité par omission, ce qui est la manière la moins chère de la dire. Il l’entendra quand même. Le silence reste rarement privé longtemps.',
  [roomExplanationKey('the-reference', 0)]: 'Un ami proche a besoin d’une lettre de recommandation de votre part pour un poste auquel il ne convient pas tout à fait, et ce que vous écrirez sera lu par un inconnu qui fait confiance à votre honnêteté. Cela concerne à qui votre loyauté est réellement due : l’ami que vous aimez, ou l’inconnu qui se fie à votre parole ? C’est comme si l’on vous demandait de vous porter garant des talents de baby-sitter d’un ami auprès d’une famille que vous ne connaissez pas, alors que vous êtes presque certain qu’il ne s’y entend pas avec les enfants — chaque version de la lettre (dithyrambique, honnête, ou le refus de l’écrire) traite quelqu’un injustement.',
  [roomNoteTitleKey('the-reference')]: 'Le mensonge charitable, notarié',
  [roomNoteThinkersKey('the-reference')]: 'Emmanuel Kant · Bernard Williams, l’éthique du témoignage',
  [roomNoteBodyKey('the-reference')]: 'Kant soutenait que la véracité est un devoir dû à l’humanité en tant que telle, non calibré selon qui demande ou ce qu’il peut supporter : une référence est une promesse, faite silencieusement à un inconnu qui s’y fiera, et la gonfler traite cet inconnu comme un moyen au service de la fin de votre ami. Bernard Williams complique cette netteté — une référence est aussi un genre, à moitié rituel, lue par des gens familiers de son inflation habituelle, décomptée avant même la fin du paragraphe. À quelle convention êtes-vous donc réellement lié : la stricte, ou celle que tout le monde convient tacitement de truquer ? Remarquez ce que la lettre risque vraiment : non votre intégrité dans l’abstrait, mais la vraie confiance d’un inconnu, dépensée au nom de votre ami sans son savoir ni son consentement. **Une loyauté qui coûte à un tiers n’est pas de la loyauté — c’est un transfert.** Quoi que vous ayez signé, vous en sentirez probablement le poids le jour où la référence sera mise à l’épreuve par un mardi ordinaire et difficile à ce poste — et lui aussi, moins équitablement.',
});
