// French translations, registered against the text catalog. UI chrome, act
// structure, room titles/hints/teasers, and endings are fully translated;
// long-form room prose (beats, choice outcomes, field notes) is not yet
// translated and gracefully falls back to English v2 (see resolver.ts).
// Milestone 5, Phase R4 — lowest priority, may slip to Milestone 6; this is
// the infrastructure + UI/structural layer, translated from the English v2
// source directly (never via Czech), matching cs.ts's key inventory.
import { registerAll } from '../../engine/text/resolver';
import { uiKey, actNameKey, actIntroKey, usherBarkKey, roomTitleKey, roomDoorHintKey, roomTeaserKey, endingTitleKey, endingEpitaphKey, keepsakeKey, stampKey, understoryNameKey } from '../../engine/text/keys';

registerAll('v2', 'fr', {
  [uiKey('abandonToTitle')]: 'Abandonner et revenir à l’écran-titre',
  [uiKey('advanceHintClick')]: 'cliquer · espace',
  [uiKey('advanceHintContinue')]: 'continuer',
  [uiKey('rereadBack')]: 'Retour — relire le passage précédent',
  [uiKey('rereadJumpTo')]: 'Relire le passage {n}',
  [uiKey('rereadScene')]: '⟲ relire la scène',
  [uiKey('heartsAriaLabel')]: 'prise sur la réalité',
  [uiKey('exitGame')]: 'Quitter le jeu',
  [uiKey('saveAndExit')]: 'Enregistrer et revenir à l’écran-titre',
  [uiKey('settingsSectionDisplay')]: 'Affichage',
  [uiKey('settingFullscreen')]: 'Plein écran',
  [uiKey('settingFullscreenDesc')]: 'Remplit tout l’écran — se bascule aussi avec la touche F.',
  [uiKey('renderScalePerformance')]: 'Résolution de rendu : Performance',
  [uiKey('renderScaleStandard')]: 'Résolution de rendu : Standard',
  [uiKey('renderScaleSharp')]: 'Résolution de rendu : Nette',
  [uiKey('settingRenderScale')]: 'Résolution de rendu',
  [uiKey('settingRenderScaleDesc')]: 'Plus bas = plus fluide sur les cartes graphiques modestes, une image un peu plus douce. Nette utilise la pleine résolution de votre écran.',
  [uiKey('fpsCap30')]: 'Fréquence d’images : 30 im/s (plus fluide sur les cartes graphiques modestes)',
  [uiKey('fpsCap60')]: 'Fréquence d’images : 60 im/s',
  [uiKey('settingFpsCap')]: 'Limite de fréquence d’images',
  [uiKey('settingFpsCapDesc')]: 'Une valeur plus basse économise nettement la puissance graphique — ce jeu est fait de brume et de texte, pas d’action.',
  [uiKey('settingUiZoom')]: 'Taille de l’interface',
  [uiKey('settingUiZoomDesc')]: 'Agrandit ou réduit les menus et le texte à votre convenance — la scène 3D reste nette.',
  [uiKey('settingQualityDesc')]: 'Effets de lueur et de lissage ; nécessite une carte graphique plus puissante. S’applique au prochain lancement.',
  [uiKey('settingDynamicSceneryDesc')]: 'Les pièces teintent subtilement la lumière et la brume selon leur humeur.',
  [uiKey('settingLightModeDesc')]: 'Le même hôtel au petit matin — les mêmes chambres, une lumière plus douce.',
  [uiKey('settingReducedMotionDesc')]: 'Réduit les mouvements de caméra et les transitions à un instantané quasi immédiat — plus doux pour la sensibilité au mouvement.',
  [uiKey('settingsSectionAudio')]: 'Son',
  [uiKey('settingMusicDesc')]: 'Une ambiance calme et changeante, qui évolue à chaque acte.',
  [uiKey('settingSfxDesc')]: 'Bruits de portes, de pages qu’on tourne, et les petits sons du choix.',
  [uiKey('settingsSectionText')]: 'Texte et langue',
  [uiKey('settingLanguageDesc')]: 'S’applique immédiatement, partout dans le jeu.',
  [uiKey('settingTextVersionDesc')]: 'v1 est la voix d’origine, conservée comme sauvegarde optionnelle ; v2 est la réécriture actuelle.',
  [uiKey('settingTypewriterDesc')]: 'Le texte apparaît lettre par lettre, comme si on vous racontait une histoire.',
  [uiKey('settingHighContrastDesc')]: 'Couleur de texte plus claire pour une lecture plus facile.',
  [uiKey('settingExaminedPath')]: 'Le chemin examiné — proposé au début de chaque nouvelle partie',
  [uiKey('settingExaminedPathDesc')]: 'Ne change que la présélection au début d’une nouvelle partie — on vous le demandera toujours à nouveau, et le choix de cette partie reste inchangé.',
  [uiKey('examinedOfferTitle')]: 'L’Annexe d’examen',
  [uiKey('examinedOfferIntro')]: 'L’annexe consigne des commentaires. Elle n’a pas un seul avis — elle en a quatre.',
  [uiKey('examinedOfferBody')]: 'Un tampon facultatif sur votre dossier : après chaque choix important, un greffier silencieux vous montre comment plusieurs traditions éthiques nommées pourraient le lire — côte à côte, délibérément en désaccord. Rien ici n’est noté ni évalué, et aucune lecture n’est la « bonne ». Les pièces, les cœurs et les fins que vous pouvez atteindre restent parfaitement identiques. Chaque carte se referme d’un seul clic. Vous pouvez changer à tout moment, dans les réglages, la présélection pour la prochaine fois.',
  [uiKey('walkPlainly')]: 'Suivre le chemin ordinaire',
  [uiKey('takeExaminedPath')]: 'Prendre le chemin examiné',
  [uiKey('annexHeader')]: 'L’annexe consigne :',
  [uiKey('tradition.consequence')]: 'Conséquence',
  [uiKey('tradition.duty')]: 'Devoir',
  [uiKey('tradition.virtue')]: 'Vertu',
  [uiKey('tradition.care')]: 'Sollicitude',
  [uiKey('settingsSectionData')]: 'Données',
  [uiKey('resetRun')]: 'Réinitialiser la partie en cours',
  [uiKey('confirmAgain')]: 'Cliquez à nouveau pour confirmer',
  [uiKey('resetRunDesc')]: 'Abandonne votre voyage en cours. Les notes, les fins et les réglages sont conservés.',
  [uiKey('resetRunDone')]: 'Partie réinitialisée',
  [uiKey('resetProgress')]: 'Réinitialiser toute la progression',
  [uiKey('resetProgressDesc')]: 'Efface tout — notes, fins, réglages, votre partie en cours — retour au tout début.',
  [uiKey('recoveryTitle')]: 'L’installation a vacillé',
  [uiKey('recoveryBody')]: 'Quelque chose dans les rouages a perdu l’équilibre. Votre dossier est en sécurité — rien de ce que vous avez fait ici n’est perdu.',
  [uiKey('recoveryReturn')]: 'Retour à l’écran-titre',
  [uiKey('restoredFromBackup')]: 'Votre dernière sauvegarde n’a pas pu être chargée — restaurée depuis la sauvegarde précédente. Rien ne devrait manquer.',
  [uiKey('saveFailed')]: 'Votre progression n’a pas pu être enregistrée — l’espace de stockage est peut-être plein.',
  [uiKey('exportProfile')]: 'Exporter le profil',
  [uiKey('exportProfileDesc')]: 'Télécharge tout votre profil sous forme de fichier — une sauvegarde personnelle, ou de quoi envoyer si vous avez un jour besoin d’aide.',
  [uiKey('exportProfileButton')]: 'Télécharger',
  [uiKey('importProfile')]: 'Importer un profil',
  [uiKey('importProfileDesc')]: 'Remplace tout votre profil par le fichier collé. Votre progression actuelle sera écrasée — exportez-la d’abord si vous voulez la garder.',
  [uiKey('importProfileButton')]: 'Importer',
  [uiKey('importProfilePlaceholder')]: 'Collez ici le contenu d’un fichier de profil exporté',
  [uiKey('importProfileSuccess')]: 'Importé — rechargement en cours…',
  [uiKey('importProfileError')]: 'Cela ne ressemble pas à un fichier de profil valide — rien n’a changé.',
  [uiKey('ledger')]: 'Le carnet du voyageur',
  [uiKey('hotelRegister')]: 'Le registre',
  [uiKey('registerSub')]: 'la forme de ce lieu, que vous l’ayez déjà parcouru ou non',
  [uiKey('readMore')]: 'Lire la suite →',
  [uiKey('articleKicker')]: 'Pour aller plus loin',
  [understoryNameKey()]: 'Le sous-sol',
  [uiKey('registerDoorsWalked')]: 'portes franchies',
  [uiKey('epiphaniesTitle')]: 'Révélations',
  [uiKey('guestStampsTitle')]: 'Tampons du registre',
  [stampKey('full-house')]: 'Complet — chaque chambre au dossier',
  [stampKey('clean-bill')]: 'Reparti avec chaque cœur, à chaque fois',
  [stampKey('frequent-guest')]: 'Un habitué',
  [stampKey('below-the-surface')]: 'A trouvé le chemin vers le bas',
  [stampKey('on-the-record')]: 'A suivi le Chemin de l’examen',
  [stampKey('student-of-the-place')]: 'Un connaisseur des lieux',
  [uiKey('epiphanyEarned')]: 'consignée ce soir',
  [uiKey('pivotalChoicesHeader')]: 'ce que vous avez choisi',
  [uiKey('doorsNeverOpenedHeader')]: 'les portes que vous n’avez jamais ouvertes',
  [uiKey('ledgerRuns')]: 'Voyages accomplis',
  [uiKey('ledgerRooms')]: 'Pièces contemplées',
  [uiKey('ledgerEndings')]: 'Fins contemplées',
  [uiKey('ledgerHearts')]: 'Cœurs perdus, au total',
  [uiKey('ledgerMostWalked')]: 'La porte la plus empruntée',
  [uiKey('ledgerKeepsakes')]: 'Souvenirs sur l’étagère',
  [uiKey('ledgerDescents')]: 'Descentes en contrebas',
  [uiKey('ledgerExamined')]: 'Parties examinées',
  [uiKey('ledgerLastMessage')]: 'Votre dernier message',
  [uiKey('aboutDoors')]: '<b>Les portes.</b> Chaque porte au fond du couloir est une situation différente, et vous ne pouvez pas toutes les franchir en une seule partie. Choisir une porte, c’est choisir ce que vous affronterez — et ce que vous laisserez de côté — cette fois-ci. Une autre partie vous montrera le reste.',
  [uiKey('aboutHearts')]: '<b>Les cœurs.</b> Trois cœurs sont votre prise sur la réalité. Une poignée de choix particulièrement coûteux — toujours annoncés à l’avance par le Placeur — en coûtent un directement, tout comme laisser votre lucidité s’épuiser complètement. Perdre les trois n’est pas un écran d’échec — c’est une véritable fin, et elle est écrite comme telle.',
  [uiKey('aboutTitle')]: 'Avant de commencer',
  [uiKey('aboutWhy')]: '<b>Pourquoi jouer.</b> Rien ici n’est jugé bon ou mauvais. Chaque choix déplace silencieusement trois penchants cachés — la raison contre le sentiment, soi contre autrui, le contrôle contre l’acceptation — et ce sont eux, non un tableau de scores, qui déterminent quelles portes s’ouvrent, à quoi ressemble et ressemble l’établissement, et laquelle des six fins vous atteindrez finalement. Seul un engagement sincère est récompensé.',
  [uiKey('back')]: 'Retour',
  [uiKey('begin')]: 'Commencer',
  [uiKey('beginAgain')]: 'Recommencer',
  [uiKey('codexSub')]: 'ce que vous avez traversé — cela reste traversé',
  [uiKey('collected')]: 'recueillies',
  [uiKey('continue')]: 'Continuer',
  [uiKey('continueJourney')]: 'Poursuivre le voyage',
  [uiKey('creditsTitle')]: 'Crédits',
  [uiKey('vestibuleButton')]: 'The Vestibule — choisir un jeu',
  [uiKey('oneDoorButton')]: 'Une porte',
  [uiKey('creditsIntro')]: 'Écrit, conçu et construit de manière indépendante.',
  [uiKey('creditsEngine')]: '<b>Rendu et audio.</b> Chaque visuel est une géométrie générée (Three.js), et chaque son est généré en temps réel — aucun élément graphique ou sonore acheté ou téléchargé.',
  [uiKey('creditsTooling')]: '<b>Construit avec.</b> Three.js (licence MIT) · TypeScript · Vite · Electron (version bureau) · Vitest et Playwright (tests).',
  [uiKey('creditsFonts')]: '<b>Polices.</b> Inter, Spectral et Vazirmatn, via Fontsource — chacune sous licence SIL Open Font License 1.1.',
  [uiKey('creditsNotices')]: 'Les textes complets des licences tierces se trouvent dans THIRD_PARTY_NOTICES.md, distribué avec cette version.',
  [uiKey('creditsTelemetry')]: 'Rien de votre façon de jouer n’est suivi, envoyé où que ce soit, ni lié à un compte — votre sauvegarde n’existe que dans ce navigateur ou cette installation.',
  [uiKey('done')]: 'Terminé',
  [uiKey('doorHelp')]: 'choisissez un chemin — cliquez une porte, ou appuyez sur son chiffre',
  [uiKey('doorHelpSingle')]: 'c’est l’unique chemin possible — cliquez la porte, ou appuyez sur 1',
  [uiKey('doorUnseenBadge')]: 'nouveau',
  [uiKey('doorUnseenBadgeTooltip')]: 'Vous n’avez jamais franchi cette porte',
  [uiKey('explainButton')]: 'Expliquer simplement',
  [uiKey('explainLabel')]: 'En mots simples',
  [uiKey('rememberedTag')]: 'souvenir',
  [uiKey('ending')]: 'Fin',
  [uiKey('endingFieldNoteHeader')]: 'Fin · Note',
  [uiKey('endingsWitnessed')]: 'fins contemplées',
  [uiKey('fieldNoteHeader')]: 'Note',
  [uiKey('fieldNotes')]: 'Notes',
  [uiKey('heartsTooltip')]: 'Votre prise sur la réalité. Quelques choix coûteux coûtent directement un cœur — le Placeur prévient toujours à l’avance —, tout comme une lucidité entièrement épuisée. Perdre les trois cœurs est une fin, pas un échec.',
  [uiKey('howToAdvance')]: '<b>Cliquez</b> sur le texte, ou appuyez sur <b>Espace</b>, pour continuer',
  [uiKey('howToClick')]: '<b>Cliquez</b> sur une porte, ou appuyez sur <b>1–3</b>, pour choisir votre chemin',
  [uiKey('howToPause')]: '<b>Échap</b> pour mettre en pause · survolez une porte pour lire son indice',
  [uiKey('lastMessageBody')]: 'Vous aviez une phrase, et la voici :',
  [uiKey('lucidityTooltip')]: 'Lucidité — la sincérité de votre regard.',
  [uiKey('menu')]: 'Menu',
  [uiKey('notYetWalked')]: 'pas encore franchie',
  [uiKey('of')]: 'sur',
  [uiKey('off')]: 'désactivé',
  [uiKey('on')]: 'activé',
  [uiKey('paused')]: 'Pause',
  [uiKey('pausedSub')]: 'les pièces attendront — ici, le temps n’est qu’un décor',
  [uiKey('persona.daniel')]: 'Vous mesurez deux fois. Il vous arrive encore de mal couper.',
  [uiKey('persona.mira')]: 'Vous remarquiez les choses avant même qu’on vous le demande.',
  [uiKey('persona.sara')]: 'Vous restez jusqu’à la fin des choses. Cela a toujours été ainsi.',
  [uiKey('persona.tomas')]: 'Vous pardonnez lentement, mais complètement, une fois que vous le faites.',
  [uiKey('persona.about1')]: 'Attentif aux autres. Moins attentif à soi-même.',
  [uiKey('persona.about2')]: 'Prompt à rire, lent à dire ce qui s’est vraiment passé.',
  [uiKey('persona.about3')]: 'Encore là. La plupart du temps, c’est là l’essentiel de la réponse.',
  [uiKey('personaAboutLabel')]: 'À propos de vous (facultatif — montré à personne, seulement ressenti par le Placeur)',
  [uiKey('personaFreeTextPlaceholder')]: 'Ou écrivez le vôtre, brièvement…',
  [uiKey('personaNameLabel')]: 'Nom',
  [uiKey('personaNamePlaceholder')]: 'Votre nom (ou comment on vous appelle ici)',
  [uiKey('personaSkip')]: 'Passer — appelez-moi voyageur',
  [uiKey('personaSub')]: 'Uniquement à l’usage du Placeur — cela ne change rien aux pièces, seulement la façon dont elles vous parlent.',
  [uiKey('personaTitle')]: 'Qui êtes-vous, ce soir ?',
  [uiKey('recapHeader')]: 'Ce que vous avez traversé',
  [uiKey('resume')]: 'Reprendre',
  [uiKey('savedToast')]: 'Enregistré',
  [uiKey('senderYou')]: 'expéditeur : vous',
  [uiKey('settingHighContrast')]: 'Texte à contraste élevé',
  [uiKey('settingLanguage')]: 'Langue',
  [uiKey('settingMusic')]: 'Musique de fond',
  [uiKey('settingQuality')]: 'Qualité visuelle élevée',
  [uiKey('settingDynamicScenery')]: 'Décor dynamique (expérimental)',
  [uiKey('settingLightMode')]: 'Mode clair',
  [uiKey('settingMusicVolume')]: 'Volume de la musique',
  [uiKey('settingSfxVolume')]: 'Volume des effets',
  [uiKey('settingNarration')]: 'Narration',
  [uiKey('settingNarrationDesc')]: 'Répliques parlées, là où elles ont été enregistrées.',
  [uiKey('settingNarrationVolume')]: 'Volume de la narration',
  [uiKey('hudLanguageTooltip')]: 'Changer de langue (s’applique dès le prochain instant)',
  [uiKey('settingReducedMotion')]: 'Mouvement réduit',
  [uiKey('settingSfx')]: 'Effets sonores',
  [uiKey('settingTextVersion')]: 'Version du texte',
  [uiKey('settingTypewriter')]: 'Texte façon machine à écrire',
  [uiKey('settings')]: 'Réglages',
  [uiKey('settingsFooter')]: 'les changements de qualité s’appliquent au prochain lancement · le reste, immédiatement',
  [uiKey('statHearts')]: 'cœurs préservés',
  [uiKey('statLucidity')]: 'lucidité',
  [uiKey('statNewNotes')]: 'nouvelles notes',
  [uiKey('title')]: 'Écran-titre',
  [uiKey('titleTagline')]: 'un voyage à travers les pièces · chaque porte est une question · le chemin du retour passe par elles',
  [uiKey('titleAgeAdvisory')]: '16+ · Thèmes matures',
  [uiKey('travelerLabel')]: 'Voyageur',
  [uiKey('travellerFallback')]: 'voyageur',
  [uiKey('archiveBlurbFallback')]: 'aucune autre description au dossier',
  [uiKey('shelfTitle')]: 'L’étagère',
  [uiKey('keepsakeChoiceTooltip')]: 'Un souvenir, discrètement dépensé',
  [uiKey('versionV1')]: 'Voix : v1 (originale)',
  [uiKey('versionV2')]: 'Voix : v2 (nouvelle)',
  [uiKey('walkAgain')]: 'Refaire le chemin — les pièces ne se réarrangent pour personne, mais vous avez changé',
  [uiKey('whoAreYou')]: 'Qui êtes-vous ?',

  [actNameKey(0)]: 'Prologue — La salle d’attente',
  [actNameKey(1)]: 'Acte I — Les bas-fonds',
  [actNameKey(2)]: 'Acte II — La machinerie',
  [actNameKey(3)]: 'Acte III — Le miroir',
  [actNameKey(4)]: 'Acte IV — Le seuil',

  [actIntroKey(1)]: 'Devant vous : un couloir de portes d’appartements, chacune laissant filtrer la lumière chaude de foyers qui ne furent jamais les vôtres. Les pièces ordinaires, vous le constaterez, vont le plus profond. Un avertissement, voyageur : certaines de ces portes coûtent plus que du temps — choisissez contre vous-même, et un cœur pourrait s’en aller.',
  [actIntroKey(2)]: 'Le couloir s’ouvre sur une machinerie — des engrenages gros comme des lunes, et de lentes courroies portant de petites étoiles indifférentes. Ici, les vieilles expériences de pensée sont rejouées chaque nuit, pour un équipage d’une seule personne. Certaines des anciennes expériences réclament encore un droit d’entrée. La monnaie, ici, ce sont les cœurs.',
  [actIntroKey(3)]: 'Le sol devient miroir noir. Vos propres souvenirs pendent dans l’obscurité comme des dioramas, leurs visages adoucis au-delà de toute reconnaissance. L’établissement appelle cette aile l’archive. Cela veut dire : la vôtre, {name}. Une partie de ce que vous trouverez ici a un prix que vous sentirez, pas seulement que vous verrez — et oui, ce prix peut être un cœur.',
  [actIntroKey(4)]: 'La brume se dissipe. Au-delà, sans équivoque, le matin. Trois portes restent, puis le seuil. Tout, à partir d’ici, compte double — bien que le Placeur dirait que cela a toujours été le cas. Même si près de la fin, un choix inattentif peut encore coûter un cœur.',

  [usherBarkKey('understory-hint')]: 'Le Placeur : Cette deuxième porte ne figure pas sur ma carte. Autrefois, si. Prenez-la ou non ; elle ne se proposera pas deux fois.',
  [usherBarkKey('first-door')]: 'Le Placeur : Une seule porte, pour commencer. Vous n’avez rien laissé de côté — il n’y avait nulle part ailleurs où être, pas encore.',
  [usherBarkKey('gate-single-door')]: 'Le Placeur : Pour ce passage, une seule porte demeure. Les autres sont déjà derrière vous, choisies ou laissées de côté — ce qui, à sa façon, fut aussi un choix. Celle-ci est simplement le seul chemin encore ouvert.',
  [usherBarkKey('first-choice-explainer')]: 'Le Placeur : Plusieurs portes, et seules certaines seront les vôtres cette fois — le reste demeure fermé, pour l’instant. Chacune dissimule une situation différente, non un score différent. Choisissez celle dont vous êtes vraiment prêt à endurer la question.',
  [usherBarkKey('second-run')]: 'Le Placeur : Vous êtes revenu. Le levier est là où vous l’avez laissé ; ici, nous ne réarrangeons rien — la permanence est le seul luxe que s’accorde cet établissement.',
  [usherBarkKey('reason-low')]: 'Le Placeur : Vous pesez chaque pièce comme un grand livre comptable. Les pièces l’ont remarqué, et ont ajusté leurs notes de bas de page en conséquence.',
  [usherBarkKey('reason-high')]: 'Le Placeur : Vous sentez tout, ici, ouvertement. Le couloir en est plus chaud. Ce n’est pas une figure de style.',
  [usherBarkKey('self-low')]: 'Le Placeur : Vous vous êtes gardé intact. Un instinct raisonnable. Demandez-vous, de temps en temps, à quoi sert cette préservation.',
  [usherBarkKey('self-high')]: 'Le Placeur : Vous continuez à vous donner par morceaux. Cela vous va bien — même s’il en restera moins à donner, avec le temps.',
  [usherBarkKey('control-low')]: 'Le Placeur : Vous luttez contre chaque pièce. Je l’admire. Les pièces en restent inébranlées.',
  [usherBarkKey('control-high')]: 'Le Placeur : Vous avez cessé de lutter dans l’eau, voyageur. Flotter est aussi une compétence. Tout comme savoir où se trouvait le rivage.',
  [usherBarkKey('first-heart-loss')]: 'Le Placeur : Voilà — un cœur, dépensé. Vous le sentez. Ce n’est qu’un dispositif qui tient un grand livre honnête, rien de plus. Il vous en reste {hearts}. Ce n’est pas un compte à rebours vers la défaite ; c’est simplement ce que ce choix a coûté.',
  [usherBarkKey('one-heart')]: 'Le Placeur : Un cœur demeure. Il ne m’est pas permis de m’inquiéter. Considérez ceci comme ce qui s’en rapproche le plus.',
  [usherBarkKey('high-lucidity')]: 'Le Placeur : À cette profondeur, vous voyez avec une clarté inhabituelle. La clarté est la seule monnaie ici que la maison ne peut contrefaire.',
  [usherBarkKey('generic0')]: 'Le Placeur : Choisissez une porte. Chacune d’elles est vôtre — un fait que la plupart des voyageurs ne croient que bien plus tard.',
  [usherBarkKey('generic1')]: 'Le Placeur : Prenez votre temps. Les portes le supportent mieux que vous ne le pensez.',
  [usherBarkKey('generic2')]: 'Le Placeur : Je vous dirais bien laquelle je choisirais, mais je les ai toutes choisies, une fois. Tirez vos propres conclusions.',
  [usherBarkKey('generic3')]: 'Le Placeur : Les indices au-dessus des portes sont sincères. Nous ne traitons pas ici en fausses enseignes.',
  [usherBarkKey('generic4')]: 'Le Placeur : Rien ne presse. Le temps, en ce lieu, n’est qu’un ornement.',
  [usherBarkKey('generic5')]: 'Le Placeur : Ce que vous laissez de côté reste ici, non ouvert, pour une autre visite. Ce n’est pas une perte. Ce n’est simplement pas cette histoire-ci.',
  [usherBarkKey('generic6')]: 'Le Placeur : Lisez l’indice avant de décider. Ce n’est pas un ornement — c’est le seul aperçu honnête que vous obtiendrez.',
  [usherBarkKey('generic7')]: 'Le Placeur : Les portes connaissent déjà votre nom, {name}. Ce qui les intrigue, c’est le reste de vous.',
  [usherBarkKey('remembered-room')]: 'Vous vous souvenez de ce lieu.',
  [usherBarkKey('examined-act1')]: 'Le Placeur : Feriez-vous le même choix devant témoins ? Cela aurait-il été meilleur — ou simplement plus joli ?',
  [usherBarkKey('examined-act2')]: 'Le Placeur : Quand une machine a raison, la raison pour laquelle elle a raison compte-t-elle ?',
  [usherBarkKey('examined-act3')]: 'Le Placeur : Lesquelles de vos raisons, ce soir, étaient vraiment les vôtres, et lesquelles n’étaient que des leçons récitées ?',
  [usherBarkKey('examined-act4')]: 'Le Placeur : Si personne ne pouvait jamais le savoir, traversez encore une fois le couloir. Quelque chose changerait-il ?',

  [roomTitleKey('waiting-room')]: 'La salle d’attente',
  [roomDoorHintKey('waiting-room')]: 'La porte que vous franchissez déjà',
  [roomTeaserKey('waiting-room')]: 'Où que vous soyez, cela commence ici.',
  [roomTitleKey('wallet')]: 'Le portefeuille',
  [roomDoorHintKey('wallet')]: 'La porte de la chose que personne n’a vue',
  [roomTeaserKey('wallet')]: 'Une épreuve sans témoin — sauf celui, unique, qui compte.',
  [roomTitleKey('dinner-table')]: 'La table du dîner',
  [roomDoorHintKey('dinner-table')]: 'La porte de la question que vous connaissez déjà',
  [roomTeaserKey('dinner-table')]: 'Une question sans réponse sûre, posée par quelqu’un que vous aimez.',
  [roomTitleKey('promotion')]: 'La promotion',
  [roomDoorHintKey('promotion')]: 'La porte du grand livre et de l’ami',
  [roomTeaserKey('promotion')]: 'Loyauté et avantage — un seul des deux peut l’emporter.',
  [roomTitleKey('beggars-math')]: 'L’arithmétique du mendiant',
  [roomDoorHintKey('beggars-math')]: 'La porte du proche et du lointain',
  [roomTeaserKey('beggars-math')]: 'L’étranger devant vous, ou le plus grand bien que vous ne voyez pas.',
  [roomTitleKey('quiet-alarm')]: 'L’alarme silencieuse',
  [roomDoorHintKey('quiet-alarm')]: 'La porte du son à travers le mur',
  [roomTeaserKey('quiet-alarm')]: 'Un mur, un silence, et une décision qu’on ne peut reprendre.',
  [roomTitleKey('photograph')]: 'La photographie',
  [roomDoorHintKey('photograph')]: 'La porte déjà tiède',
  [roomTeaserKey('photograph')]: 'Un incendie derrière deux portes. De toute façon, vous perdrez quelque chose.',
  [roomTitleKey('buridans-queue')]: 'La file de Buridan',
  [roomDoorHintKey('buridans-queue')]: 'La porte des deux portes',
  [roomTeaserKey('buridans-queue')]: 'Un choix difficile pour la seule raison que rien ne le facilite.',
  [roomTitleKey('the-reference')]: 'La lettre de recommandation',
  [roomDoorHintKey('the-reference')]: 'La porte de la plume empruntée',
  [roomTeaserKey('the-reference')]: 'Quelqu’un que vous aimez a besoin d’une phrase de vous qui n’a pas à être vraie.',
  [roomTitleKey('junction')]: 'L’aiguillage',
  [roomDoorHintKey('junction')]: 'La porte du levier et de la balance',
  [roomTeaserKey('junction')]: 'Un levier, un pont, et les cinq mêmes vies, deux fois.',
  [roomTitleKey('experience-machine')]: 'La machine à expériences',
  [roomDoorHintKey('experience-machine')]: 'La porte derrière laquelle rien ne va mal',
  [roomTeaserKey('experience-machine')]: 'Une vie parfaite, garantie — si vous pouvez en supporter le prix.',
  [roomTitleKey('ship')]: 'Le navire',
  [roomDoorHintKey('ship')]: 'La porte des planches remplacées',
  [roomTeaserKey('ship')]: 'Morceau par morceau, on vous remplace. Qui en ressort ?',
  [roomTitleKey('casino-pascal')]: 'Le casino de Pascal',
  [roomDoorHintKey('casino-pascal')]: 'La porte au gain infini',
  [roomTeaserKey('casino-pascal')]: 'Un pari sur Dieu, à une table dont la maison fixe les cotes.',
  [roomTitleKey('omelas')]: 'La ville d’Omelas',
  [roomDoorHintKey('omelas')]: 'La troisième porte, bourdonnante d’une lumière de fête',
  [roomTeaserKey('omelas')]: 'La joie d’une ville, et un prix dont on ne parle pas à voix haute.',
  [roomTitleKey('chinese-room')]: 'La chambre chinoise',
  [roomDoorHintKey('chinese-room')]: 'La porte de la réponse parfaite',
  [roomTeaserKey('chinese-room')]: 'Elle répond à tout, avec vos propres mots.',
  [roomTitleKey('newcomb-annex')]: 'L’annexe de Newcomb',
  [roomDoorHintKey('newcomb-annex')]: 'La porte de la boîte déjà remplie',
  [roomTeaserKey('newcomb-annex')]: 'Votre choix a déjà été prédit. Il n’est pas encore trop tard — ou l’est-il ?',
  [roomTitleKey('veil-of-ignorance')]: 'Le voile d’ignorance',
  [roomDoorHintKey('veil-of-ignorance')]: 'La porte du tirage au sort',
  [roomTeaserKey('veil-of-ignorance')]: 'Vous concevrez un petit monde, puis y vivrez.',
  [roomTitleKey('court-of-usher')]: 'Le tribunal du Placeur',
  [roomDoorHintKey('court-of-usher')]: 'La porte à l’assignation clouée',
  [roomTeaserKey('court-of-usher')]: 'Le Placeur comparaît en jugement, et vous êtes le juge.',
  [roomTitleKey('teleporter')]: 'Le téléporteur',
  [roomDoorHintKey('teleporter')]: 'La porte qui est aussi un mur',
  [roomTeaserKey('teleporter')]: 'Une machine vous détruit et imprime une copie. Celle-ci insiste avoir traversé elle-même.',
  [roomTitleKey('editor')]: 'Le rédacteur',
  [roomDoorHintKey('editor')]: 'La porte du stylo rouge',
  [roomTeaserKey('editor')]: 'Biffez pour toujours votre pire souvenir. Voyez ce qu’il retenait.',
  [roomTitleKey('introduction')]: 'La présentation',
  [roomDoorHintKey('introduction')]: 'Une petite porte simple, poliment entrouverte',
  [roomTeaserKey('introduction')]: 'Une pièce qui veut seulement savoir qui vous êtes vraiment.',
  [roomTitleKey('debt-of-dead')]: 'La dette des morts',
  [roomDoorHintKey('debt-of-dead')]: 'La porte à laquelle vous aviez juré de ne jamais frapper',
  [roomTeaserKey('debt-of-dead')]: 'Quelqu’un qui vous a fait du mal se meurt et implore le pardon.',
  [roomTitleKey('marys-room')]: 'La chambre de Mary',
  [roomDoorHintKey('marys-room')]: 'La porte du bureau gris',
  [roomTeaserKey('marys-room')]: 'Elle sait absolument tout d’une couleur qu’elle n’a jamais vue.',
  [roomTitleKey('butterfly-dream')]: 'Le rêve du papillon',
  [roomDoorHintKey('butterfly-dream')]: 'La porte du mur de papier',
  [roomTeaserKey('butterfly-dream')]: 'Quelqu’un ici rêve de quelqu’un. On ne sait pas dans quel sens.',
  [roomTitleKey('swampman')]: 'L’homme du marécage',
  [roomDoorHintKey('swampman')]: 'La porte du second manteau',
  [roomTeaserKey('swampman')]: 'Quelqu’un là-dedans porte votre visage, et s’en montre très courtois.',
  [roomTitleKey('the-cave')]: 'La caverne',
  [roomDoorHintKey('the-cave')]: 'Une porte basse à la lueur du feu',
  [roomTeaserKey('the-cave')]: 'Des ombres que vous reconnaissez, projetées pour un public d’une seule personne.',
  [roomTitleKey('free-will')]: 'La salle d’attente du libre arbitre',
  [roomDoorHintKey('free-will')]: 'La porte qui vous attendait',
  [roomTeaserKey('free-will')]: 'Les lumières s’allument avant que vous ne choisissiez. Vous perdez chaque pari, exprès.',
  [roomTitleKey('boulder')]: 'Le rocher',
  [roomDoorHintKey('boulder')]: 'La porte au pied de la colline',
  [roomTeaserKey('boulder')]: 'Une tâche qui s’annule elle-même. La question est de savoir comment vous la portez.',
  [roomTitleKey('last-message')]: 'Le dernier message',
  [roomDoorHintKey('last-message')]: 'La porte à la fente pour le courrier',
  [roomTeaserKey('last-message')]: 'Une phrase de retour vers le monde éveillé. Qui la reçoit ?',
  [roomTitleKey('door-that-asks')]: 'La porte qui interroge',
  [roomDoorHintKey('door-that-asks')]: 'La dernière porte, qui lit votre dossier',
  [roomTeaserKey('door-that-asks')]: 'Elle a lu tout votre dossier. Maintenant, elle veut savoir si vous l’assumez.',
  [roomTitleKey('the-archive')]: 'Les archives · en contrebas',
  [roomDoorHintKey('the-archive')]: 'Un escalier qui ne figurait pas sur la carte',
  [roomTeaserKey('the-archive')]: 'Quelque part là-dessous, votre dernier voyage est déjà classé au dossier.',
  [roomTitleKey('the-unchosen')]: 'Les non-choisies · en contrebas',
  [roomDoorHintKey('the-unchosen')]: 'Un couloir de portes que vous n’avez pas ouvertes',
  [roomTeaserKey('the-unchosen')]: 'Elles sont restées entrouvertes tout ce temps. L’une d’elles l’est encore.',
  [roomTitleKey('the-echo')]: 'L’écho · en contrebas',
  [roomDoorHintKey('the-echo')]: 'Une pièce avec la seconde chaise',
  [roomTeaserKey('the-echo')]: 'Quelqu’un y est déjà assis, et cela sonne comme vous.',

  [endingTitleKey('return')]: 'Le retour',
  [endingEpitaphKey('return')]: 'Le monde était exactement le même. Cela n’avait jamais été la promesse.',
  [endingTitleKey('open-hand')]: 'La main ouverte',
  [endingEpitaphKey('open-hand')]: 'Vous vous êtes donné, pièce après pièce, de bon cœur — la plupart du temps de bon cœur.',
  [endingTitleKey('fortress')]: 'La forteresse',
  [endingEpitaphKey('fortress')]: 'Rien n’est entré. C’était le plan. Rien n’est entré.',
  [endingTitleKey('dissolved')]: 'Dissous',
  [endingEpitaphKey('dissolved')]: 'La mer n’a jamais perdu une seule chose qui comptait.',
  [endingTitleKey('gardener')]: 'Le jardinier',
  [endingEpitaphKey('gardener')]: 'Les pièces ont toujours besoin d’un gardien. Le gardien a toujours eu besoin des pièces.',
  [endingTitleKey('punchline')]: 'La chute',
  [endingEpitaphKey('punchline')]: 'Il n’y a jamais eu personne ici, à part vous. Bonne blague, non ?',
  [endingTitleKey('anamnesis')]: 'Anamnèse',
  [endingEpitaphKey('anamnesis')]: 'Ils ne sont pas retournés. Ils se sont réveillés, et le réveil contenait les pièces.',
});

// ---------- Keepsakes (Milestone 5, Phase N) ----------
registerAll('v2', 'fr', {
  [keepsakeKey('casino-chip', 'name')]: 'Le jeton non dépensé',
  [keepsakeKey('casino-chip', 'origin')]: 'gardé du casino, non dépensé',
  [keepsakeKey('photo-corner', 'name')]: 'Un coin de la photographie',
  [keepsakeKey('photo-corner', 'origin')]: 'sauvé du feu, un coin de celle-ci',
  [keepsakeKey('ship-splinter', 'name')]: 'Une esquille du navire',
  [keepsakeKey('ship-splinter', 'origin')]: 'gardée de l’atelier, bois d’origine',
  [keepsakeKey('release-form', 'name')]: 'Le formulaire de sortie de la machine',
  [keepsakeKey('release-form', 'origin')]: 'signé en sortant, jamais posté',
});
