// Bootstraps the text catalog: importing these registers every translation/
// alternate-version entry (side effect) before the app renders anything.
import './v1-en';
import './v1-en-dynamic';
import './v1-en-usher';
import './cs';
import './fa';
import './de';
import './fr';
import './cs-rooms';
import './fa-rooms';
import './de-rooms';
import './fr-rooms';
import './de-rooms-act2';
import './fr-rooms-act2';
import './de-rooms-act3';
import './fr-rooms-act3';
import './de-rooms-act4';
import './fr-rooms-act4';
import './de-rooms-understory';
import './fr-rooms-understory';
import './de-endings';
import './fr-endings';
import './de-dynamic';
import './fr-dynamic';
import './cs-rooms-act2';
import './fa-rooms-act2';
import './cs-rooms-act3';
import './fa-rooms-act3';
import './cs-rooms-act4';
import './fa-rooms-act4';
import './cs-rooms-understory';
import './fa-rooms-understory';
import './cs-endings';
import './fa-endings';
import './cs-dynamic';
import './fa-dynamic';
import './cs-reflections-act1';
import './fa-reflections-act1';
import './cs-reflections-act2';
import './fa-reflections-act2';
import './cs-reflections-act3';
import './fa-reflections-act3';
import './cs-reflections-act4';
import './fa-reflections-act4';
import './cs-epiphanies';
import './fa-epiphanies';
import './de-epiphanies';
import './fr-epiphanies';
import './cs-explanations';
import './fa-explanations';

export * from './resolver';
export * from './keys';
